CppNoddy: Tests/BVP/BVPKarman.cpp File Reference
BVPKarman.cpp File Reference
#include <BVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::Karman_equations
Define the Karman equations.
class CppNoddy::Example::Karman_left_BC
Define the boundary conditions.
class CppNoddy::Example::Karman_right_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum {
U, Ud, V, W,
Wd
}
Functions
int main ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
U
Ud
V
W
Wd
Definition at line 20 of file BVPKarman.cpp.
 {U, Ud, V, W, Wd};
Function Documentation
main()
int main ()
Definition at line 86 of file BVPKarman.cpp.
 {
   cout << "\n";
   cout << "=== BVP: finite-difference soln of Karman eqns ======\n";
   cout << "\n";
   Example::Karman_equations problem;
   Example::Karman_left_BC BC_left;
   Example::Karman_right_BC BC_right;
   // Boundary layer is from 0 to 20
   double left = 0.0;
   double right = 20.0;
   // number of nodal points
   int N = 801;
   DenseVector<double> nodes = Utility::uniform_node_vector( left, right, N );
   ODE_BVP<double> ode( &problem, nodes, &BC_left, &BC_right );
   // (re)set the solution to the initial guess
   for ( int i = 0; i < N; ++i )
   {
     double y = ode.solution().coord( i );
     ode.solution()( i, U ) = 0.0;
     ode.solution()( i, Ud ) = 0.0;
     ode.solution()( i, V ) = 0.0;
     ode.solution()( i, W ) = exp( -y );
     ode.solution()( i, Wd ) = -exp( -y );
   }
   try
   {
     ode.solve2();
   }
   catch (const std::runtime_error &error )
   {
     cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
     return 1;
   }
   // check the BL transpiration vs the known solution
   double tol( 1.e-4 );
   if ( abs( ode.solution()( N - 1, V ) + 0.88447 ) > tol )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << " Difference = " << abs( ode.solution()( N - 1, V ) + 0.88447 ) << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::ODE_BVP< _Type, _Xtype >::solution(), CppNoddy::ODE_BVP< _Type, _Xtype >::solve2(), U, Ud, CppNoddy::Utility::uniform_node_vector(), V, W, and Wd.
© 2012
R.E. Hewitt