CppNoddy: CppNoddy::Timer Class Reference
CppNoddy::Timer Class Reference
A simple CPU-clock-tick timer for timing metods.
#include <Timer.h>
Public Member Functions
Timer ()
Timer (std::string name)
double get_wall_time ()
void start ()
Start the timer & reset stored time to zero.
void stop ()
Stop the clock & add the current time interval to the previously stored values ready for printing.
void reset ()
Pause the clock & add the time interval to the stored cumulative time.
void print () const
Write a string to cout stating the time taken.
int & counter ()
Increment an internal discrete counter.
double time_per_count () const
double get_time () const
Return the time.
Detailed Description
A simple CPU-clock-tick timer for timing metods.
Definition at line 19 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
CppNoddy::Timer::Timer () inline
Definition at line 23 of file Timer.h.
             : STOPPED(true), COUNTER(0),
           T_START(clock()), DELTA_T_STORE(0), m_deltaWall(0.0) {
       HEADER = "";
       m_wallStart = get_wall_time();
     }
References get_wall_time().
Timer() [2/2]
CppNoddy::Timer::Timer (std::string name) inline
Definition at line 29 of file Timer.h.
                           : STOPPED(true), COUNTER(0),
                   T_START(clock()), DELTA_T_STORE(0), m_deltaWall(0.0) {
       HEADER = name;
       m_wallStart = get_wall_time();
     }
References get_wall_time().
Member Function Documentation
counter()
int & CppNoddy::Timer::counter ()
Increment an internal discrete counter.
Definition at line 44 of file Timer.cpp.
                       {
     return COUNTER;
   }
Referenced by main().
get_time()
double CppNoddy::Timer::get_time () const
Return the time.
Returns
The time (in ms).
Definition at line 34 of file Timer.cpp.
{
     if(STOPPED) {
       // if stopped or paused return stored intervals
       return 1.e3 * double(DELTA_T_STORE) / CLOCKS_PER_SEC;
     } else {
       // running clock
       return 1.e3 * (double(DELTA_T_STORE) + double(clock()) - double(T_START)) / CLOCKS_PER_SEC;
     }
   }
Referenced by main().
get_wall_time()
double CppNoddy::Timer::get_wall_time () inline
Definition at line 36 of file Timer.h.
{
       struct timeval time;
       if (gettimeofday(&time,NULL)){
         //  Handle error
         return 0;
       }
       return (double)time.tv_sec + (double)time.tv_usec * .000001;
     }
Referenced by stop(), and Timer().
print()
void CppNoddy::Timer::print () const
Write a string to cout stating the time taken.
Definition at line 59 of file Timer.cpp.
{
     std::cout.precision(4);
     std::cout << "  " << HEADER << "\n";
     const double elapsed_time_in_ms(1.e3 * double(DELTA_T_STORE) / CLOCKS_PER_SEC);
     if(elapsed_time_in_ms > 1000) {
       std::cout << "  TOTAL CPU time taken  = " << elapsed_time_in_ms / 1000. << " s\n";
       std::cout << "  TOTAL wall time taken = " << m_deltaWall << " s\n";
     } else {
       std::cout << "  TOTAL CPU time taken = " << elapsed_time_in_ms << " ms\n";
     }
     if(COUNTER != 0) {
       std::cout << "  Number of loops during this time = " << COUNTER << "\n";
       std::cout << "  Throughput = " << 1.e3 * COUNTER / elapsed_time_in_ms << " runs/s \n";
     }
   }
Referenced by main().
reset()
void CppNoddy::Timer::reset ()
Pause the clock & add the time interval to the stored cumulative time.
Definition at line 26 of file Timer.cpp.
                     {
     stop();
     COUNTER = 0;
     STOPPED = true;
     DELTA_T_STORE = 0;
     m_deltaWall = 0.0;
   }
References stop().
Referenced by main().
start()
void CppNoddy::Timer::start ()
Start the timer & reset stored time to zero.
Definition at line 12 of file Timer.cpp.
                     {
     T_START = clock();
     STOPPED = false;
   }
Referenced by main().
stop()
void CppNoddy::Timer::stop ()
Stop the clock & add the current time interval to the previously stored values ready for printing.
Definition at line 17 of file Timer.cpp.
                    {
     if(!STOPPED) {
       // we add current time interval to that stored
       DELTA_T_STORE += clock() - T_START;
       STOPPED = true;
       m_deltaWall = get_wall_time() - m_wallStart;
     }
   }
References get_wall_time().
Referenced by main(), and reset().
time_per_count()
double CppNoddy::Timer::time_per_count () const
Returns
The average time taken per increment of the internal discrete counter.
Definition at line 48 of file Timer.cpp.
{
     if(STOPPED) {
       return 1.e3 * double(DELTA_T_STORE) / CLOCKS_PER_SEC / COUNTER;
     } else {
       std::string problem = HEADER;
       problem += "\n The Timer object can only return time_per_count after being stopped.\n";
       throw ExceptionRuntime(problem);
     }
     return 0; // dummy
   }
The documentation for this class was generated from the following files:
include/Timer.h
src/Timer.cpp
© 2012
R.E. Hewitt