CppNoddy: CppNoddy::SparseMatrix< _Type > Class Template Reference
CppNoddy::SparseMatrix< _Type > Class Template Reference
A matrix class that constructs a SPARSE matrix as a row major std::vector of SparseVectors.
#include <SparseMatrix.h>
Public Member Functions
SparseMatrix (const std::size_t &rows, const std::size_t &cols)
Construct with a set number of rows.
SparseMatrix (const SparseMatrix< _Type > &source, const std::vector< std::size_t > &source_rows)
Construct from a row permutation of another sparse matrix.
SparseMatrix (const SparseMatrix &source)
Copy constructor.
SparseMatrix & operator= (const SparseMatrix &source)
Assignment operator.
~SparseMatrix ()
Default d-tor.
void blank ()
Blank the contents of this matrix.
const _Type & operator() (const std::size_t &row, const std::size_t &col) const
Access operator.
_Type & operator() (const std::size_t &row, const std::size_t &col)
Access operator.
const _Type & get (const std::size_t &row, const std::size_t &col) const
Access operator.
_Type & set (const std::size_t &row, const std::size_t &col)
Access operator.
SparseVector< _Type > get_row (const std::size_t &row) const
Get a row of the matrix.
void set_row (const std::size_t &row, const SparseVector< _Type > &row_vector)
Set a row of the matrix.
std::size_t nrows () const
Get the number of rows in the matrix.
std::size_t ncols () const
Get the number of columns in the matrix.
std::size_t nelts () const
Get the number of (non-zero) elements in the matrix.
void scale (const _Type &mult)
Scale the matrix by a scalar.
double one_norm () const
Transpose the matrix in place.
double two_norm () const
double inf_norm () const
double frob_norm () const
DenseVector< _Type > multiply (const DenseVector< _Type > &X) const
Right-multiply by a DENSE vector.
void dump () const
Output the contents of the matrix to std::cout.
void dump (std::string filename, int precision=10) const
A simple method for dumping the matrix to a file.
SparseVector< _Type > & operator[] (const std::size_t &row)
Operator overloading for ROW access.
const SparseVector< _Type > & operator[] (const std::size_t &row) const
Operator overloading for ROW access.
std::size_t nelts_in_row (int row)
The number of non-zero elements in a specified row.
std::size_t max_in_col (const std::size_t &col, const std::size_t &row_min, const std::size_t &row_max) const
Find the maximum entry in a column – used in the native solver.
void row_swap (const std::size_t &row1, const std::size_t &row2)
Swap two rows in the matrix – used in the native solver.
Public Member Functions inherited from CppNoddy::Sequential_Matrix_base< _Type >
Sequential_Matrix_base ()
An empty constructor.
virtual ~Sequential_Matrix_base ()
Friends
template<typename _SystemType >
class SparseLinearSystem
Detailed Description
template<typename _Type>
class CppNoddy::SparseMatrix< _Type >
A matrix class that constructs a SPARSE matrix as a row major std::vector of SparseVectors.
Definition at line 31 of file SparseMatrix.h.
Constructor & Destructor Documentation
SparseMatrix() [1/3]
template<typename _Type > CppNoddy::SparseMatrix< _Type >::SparseMatrix (const std::size_t & rows, const std::size_t & cols)
Construct with a set number of rows.
Parameters
rows The number of rows in the matrix
cols The number of columns in the matrix
Definition at line 15 of file SparseMatrix.cpp.
     : m_nr(rows), m_nc(cols) {
     m_matrix.reserve(m_nr);
     SparseVector<_Type> sparse_row(m_nc);
     for(std::size_t i = 0; i < m_nr; ++i) {
       m_matrix.push_back(sparse_row);
     }
   }
SparseMatrix() [2/3]
template<typename _Type > CppNoddy::SparseMatrix< _Type >::SparseMatrix (const SparseMatrix< _Type > & source, const std::vector< std::size_t > & source_rows)
Construct from a row permutation of another sparse matrix.
Parameters
source_rows Defines the permutation, row i of this matrix is row source_rows[i] of the source
Definition at line 25 of file SparseMatrix.cpp.
                                                                                                               :
     m_nr(source.nrows()), m_nc(source.ncols()) {
     m_matrix.reserve(m_nr);
     for(std::size_t i = 0; i < m_nr; ++i) {
       m_matrix.push_back(source.get_row(source_rows[i]));
     }
   }
References CppNoddy::Example::source().
SparseMatrix() [3/3]
template<typename _Type > CppNoddy::SparseMatrix< _Type >::SparseMatrix (const SparseMatrix< _Type > & source)
Copy constructor.
Parameters
source The source object to be copied
Definition at line 34 of file SparseMatrix.cpp.
{
     *this = source;
   }
References CppNoddy::Example::source().
~SparseMatrix()
template<typename _Type > CppNoddy::SparseMatrix< _Type >::~SparseMatrix () inline
Default d-tor.
Definition at line 57 of file SparseMatrix.h.
 {}
Member Function Documentation
blank()
template<typename _Type > void CppNoddy::SparseMatrix< _Type >::blank () inline
Blank the contents of this matrix.
Definition at line 60 of file SparseMatrix.h.
                  {
       m_matrix.clear();
       m_matrix.reserve(m_nr);
       SparseVector<_Type> sparse_row(m_nc);
       for(std::size_t i = 0; i < m_nr; ++i) {
         m_matrix.push_back(sparse_row);
       }
     }
dump() [1/2]
template<typename _Type > void CppNoddy::SparseMatrix< _Type >::dump virtual
Output the contents of the matrix to std::cout.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 197 of file SparseMatrix.cpp.
{
     std::cout << "SPARSE mtx size = " << m_nr << " x  sparse \n";
     std::cout.precision(4);
     std::cout << "- start matrix \n";
     for(std::size_t row = 0; row < m_nr; ++row) {
       std::cout << " row " << row << " :  ";
       m_matrix[ row ].dump();
       std::cout << " \n";
     }
     std::cout << "- end matrix \n";
   }
Referenced by CppNoddy::SparseMatrix< _Type >::dump().
dump() [2/2]
template<typename _Type > void CppNoddy::SparseMatrix< _Type >::dump (std::string filename, int precision = 10) const inline
A simple method for dumping the matrix to a file.
Parameters
filename The filename to write the data to (will overwrite)
precision Precision of the output strings
Definition at line 137 of file SparseMatrix.h.
{
       std::ofstream dump;
       dump.open(filename.c_str());
       dump.precision(precision);
       dump.setf(std::ios::showpoint);
       dump.setf(std::ios::showpos);
       dump.setf(std::ios::scientific);
       for(std::size_t row = 0; row < m_nr; ++row) {
         for(citer pos = m_matrix[row].begin(); pos != m_matrix[row].end(); ++pos) {
           dump << row << " " << pos -> first << " " << pos -> second << "\n";
         }
       }
       dump << "\n";
       dump.close();
     }
References CppNoddy::SparseMatrix< _Type >::dump().
frob_norm()
template<typename _Type > double CppNoddy::SparseMatrix< _Type >::frob_norm
Returns
The sum of the two_norm of all rows
Definition at line 112 of file SparseMatrix.cpp.
{
     double sum(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       sum += m_matrix[ row ].two_norm();
     }
     return sum;
   }
get()
template<typename _Type > const _Type & CppNoddy::SparseMatrix< _Type >::get (const std::size_t & row, const std::size_t & col) const inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 239 of file SparseMatrix.h.
{
     return this -> operator()(row, col);
   }
get_row()
template<typename _Type > SparseVector<_Type> CppNoddy::SparseMatrix< _Type >::get_row (const std::size_t & row) const inline
Get a row of the matrix.
Parameters
row The index of the row to be get
Returns
A sparse vector of values in the row
Definition at line 83 of file SparseMatrix.h.
{
       return m_matrix[row];
     }
inf_norm()
template<typename _Type > double CppNoddy::SparseMatrix< _Type >::inf_norm
Returns
The maximum inf_norm of all rows
Definition at line 103 of file SparseMatrix.cpp.
{
     double max(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       max = std::max(max, m_matrix[ row ].inf_norm());
     }
     return max;
   }
max_in_col()
template<typename _Type > std::size_t CppNoddy::SparseMatrix< _Type >::max_in_col (const std::size_t & col, const std::size_t & row_min, const std::size_t & row_max) const
Find the maximum entry in a column – used in the native solver.
Parameters
col The column to search through
row_min The start row for the search
row_max The end row for the search (NOT INCLUSIVE)
Definition at line 58 of file SparseMatrix.cpp.
{
     double maxelt(0.0);
     // return outside of the array as default
     std::size_t index = nrows();
     for(std::size_t row = row_min; row < row_max ; ++row) {
       // only bother looking up entries of rows with a first
       // element in a column less than the one we're looking at
       if(m_matrix[ row ].begin() -> first <= col) {
         const double elt(std::abs(m_matrix[ row ].get(col)));
         if(elt >= maxelt) {
           maxelt = elt;
           index = row;
         }
       }
     }
     return index;
   }
multiply()
template<typename _Type > DenseVector<_Type> CppNoddy::SparseMatrix< _Type >::multiply (const DenseVector< _Type > & X) const
Right-multiply by a DENSE vector.
Parameters
X The DENSE vector to be multiplied by
Returns
A DENSE vector of the result of the multiplication
ncols()
template<typename _Type > std::size_t CppNoddy::SparseMatrix< _Type >::ncols inline virtual
Get the number of columns in the matrix.
Returns
The number of columns
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 277 of file SparseMatrix.h.
{
     return m_nc;
   }
nelts()
template<typename _Type > std::size_t CppNoddy::SparseMatrix< _Type >::nelts virtual
Get the number of (non-zero) elements in the matrix.
Returns
The number of (non-zero) elements
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 49 of file SparseMatrix.cpp.
{
     std::size_t num_of_elts(0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       num_of_elts += m_matrix[ row ].nelts();
     }
     return num_of_elts;
   }
nelts_in_row()
template<typename _Type > std::size_t CppNoddy::SparseMatrix< _Type >::nelts_in_row (int row) inline
The number of non-zero elements in a specified row.
Parameters
row The row index to return the number of non-zero elts for
Definition at line 194 of file SparseMatrix.h.
{
       return m_matrix[row].nelts();
     }
nrows()
template<typename _Type > std::size_t CppNoddy::SparseMatrix< _Type >::nrows inline virtual
Get the number of rows in the matrix.
Returns
The number of rows
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 272 of file SparseMatrix.h.
{
     return m_nr;
   }
one_norm()
template<typename _Type > double CppNoddy::SparseMatrix< _Type >::one_norm
Transpose the matrix in place.
Returns
The maximum one_norm of all rows
Definition at line 85 of file SparseMatrix.cpp.
{
     double max(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       max = std::max(max, m_matrix[ row ].one_norm());
     }
     return max;
   }
operator()() [1/2]
template<typename _Type > _Type & CppNoddy::SparseMatrix< _Type >::operator() (const std::size_t & row, const std::size_t & col) inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 234 of file SparseMatrix.h.
{
     return m_matrix[ row ][ col ];
   }
operator()() [2/2]
template<typename _Type > const _Type & CppNoddy::SparseMatrix< _Type >::operator() (const std::size_t & row, const std::size_t & col) const inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 229 of file SparseMatrix.h.
{
     return m_matrix[ row ].get(col);
   }
operator=()
template<typename _Type > SparseMatrix< _Type > & CppNoddy::SparseMatrix< _Type >::operator= (const SparseMatrix< _Type > & source) inline
Assignment operator.
Parameters
source The source object for the assignment
Returns
The newly assigned object
Definition at line 39 of file SparseMatrix.cpp.
{
     if(this == &source)
       return * this;
     m_matrix = source.m_matrix;
     m_nr = source.m_nr;
     m_nc = source.m_nc;
     return *this;
   }
References CppNoddy::Example::source().
operator[]() [1/2]
template<typename _Type > SparseVector< _Type > & CppNoddy::SparseMatrix< _Type >::operator[] (const std::size_t & row) inline
Operator overloading for ROW access.
Parameters
row The row to access
Returns
The DENSE vector of the row data
Definition at line 249 of file SparseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The SparseMatrix.get_row has a range error.\n");
       throw ExceptionRange(problem, m_nr, row);
     }
 #endif
     return m_matrix[ row ];
   }
operator[]() [2/2]
template<typename _Type > const SparseVector< _Type > & CppNoddy::SparseMatrix< _Type >::operator[] (const std::size_t & row) const inline
Operator overloading for ROW access.
Parameters
row The row to access
Returns
The DENSE vector of the row data
Definition at line 261 of file SparseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The SparseMatrix.get_row has a range error.\n");
       throw ExceptionRange(problem, m_nr, row);
     }
 #endif
     return m_matrix[ row ];
   }
row_swap()
template<typename _Type > void CppNoddy::SparseMatrix< _Type >::row_swap (const std::size_t & row1, const std::size_t & row2) inline
Swap two rows in the matrix – used in the native solver.
Parameters
row1 The first row to be exchanged
row2 The second row to be exchanged
Definition at line 282 of file SparseMatrix.h.
{
     // actually do the swap, rather than keep a row permutation vector.
     // std::swap<SparseVector<_Type> > ( matrix[ row1 ], matrix[ row2 ] );
     m_matrix[ row1 ].swap(m_matrix[ row2 ]);
   }
scale()
template<typename _Type > void CppNoddy::SparseMatrix< _Type >::scale (const _Type & mult) virtual
Scale the matrix by a scalar.
Parameters
mult The scalar multiplier
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 78 of file SparseMatrix.cpp.
{
     for(std::size_t row = 0; row < m_nr; ++row) {
       m_matrix[ row ] *= mult;
     }
   }
Referenced by main().
set()
template<typename _Type > _Type & CppNoddy::SparseMatrix< _Type >::set (const std::size_t & row, const std::size_t & col) inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 244 of file SparseMatrix.h.
{
     return this -> operator()(row, col);
   }
set_row()
template<typename _Type > void CppNoddy::SparseMatrix< _Type >::set_row (const std::size_t & row, const SparseVector< _Type > & row_vector) inline
Set a row of the matrix.
Parameters
row The index of the row to be set
A sparse vector of values to go into the row
Definition at line 90 of file SparseMatrix.h.
{
       m_matrix[row] = row_vector;
     }
two_norm()
template<typename _Type > double CppNoddy::SparseMatrix< _Type >::two_norm
Returns
The maximum two_norm of all rows
Definition at line 94 of file SparseMatrix.cpp.
{
     double max(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       max = std::max(max, m_matrix[ row ].two_norm());
     }
     return max;
   }
Friends And Related Function Documentation
SparseLinearSystem
template<typename _Type > template<typename _SystemType > friend class SparseLinearSystem friend
Definition at line 220 of file SparseMatrix.h.
The documentation for this class was generated from the following files:
include/SparseMatrix.h
src/SparseMatrix.cpp
© 2012
R.E. Hewitt