CppNoddy: CppNoddy::DenseMatrix< _Type > Class Template Reference
CppNoddy::DenseMatrix< _Type > Class Template Reference
A matrix class that constructs a DENSE matrix as a row major std::vector of DenseVectors.
#include <DenseMatrix.h>
Public Types
typedef std::vector< DenseVector< _Type > >::iterator row_iter
Typedef iterator types.
typedef std::vector< DenseVector< _Type > >::const_iterator row_citer
typedef std::vector< DenseVector< _Type > >::reverse_iterator row_riter
typedef std::vector< DenseVector< _Type > >::const_reverse_iterator row_criter
typedef DenseVector< _Type >::elt_iter elt_iter
typedef DenseVector< _Type >::elt_citer elt_citer
typedef DenseVector< _Type >::elt_riter elt_riter
typedef DenseVector< _Type >::elt_criter elt_criter
Public Member Functions
DenseMatrix ()
Allow empty construction.
DenseMatrix (const std::size_t &rows, const std::size_t &cols, const _Type &fill)
Noddy Matrix constructor with a specified fill data.
DenseMatrix (const std::size_t &rows, const std::size_t &cols, const _Type *p)
Construct a Noddy Matrix from a contiguous set of data.
DenseMatrix (const BandedMatrix< _Type > &source)
Construct a dense matrix from its banded counterpart.
DenseMatrix (const DenseMatrix &source)
Copy constructor.
DenseMatrix & operator= (const DenseMatrix &source)
Assignment operator.
~DenseMatrix ()
const _Type & operator() (const std::size_t &row, const std::size_t &col) const
Access operator.
_Type & operator() (const std::size_t &row, const std::size_t &col)
Access operator.
const _Type & get (const std::size_t &row, const std::size_t &col) const
Access operator.
_Type & set (const std::size_t &row, const std::size_t &col)
Access operator.
DenseMatrix< _Type > operator* (const double &m) const
SIMD operator sugar.
DenseMatrix< _Type > operator+ (const DenseMatrix< _Type > &A) const
DenseMatrix< _Type > operator- (const DenseMatrix< _Type > &A) const
std::size_t nrows () const
std::size_t ncols () const
std::size_t nelts () const
void scale (const _Type &mult)
Scale all matrix elements by a scalar.
void transpose ()
Transpose the matrix.
double one_norm () const
Return the maximum one_norm of all rows.
double two_norm () const
Rreturn the maximum two_norm of all rows.
double inf_norm () const
Return the maximum inf_norm of all rows.
double frob_norm () const
Return the sum of the two_norm of all rows.
DenseVector< _Type > multiply (const DenseVector< _Type > &x) const
Right multiply the matrix by a DENSE vector.
void dump () const
Output the matrix to std::cout.
void assign (_Type elt)
Assign a value to the matrix but keep the same geometry.
row_iter begin ()
Pass through of iterator calls.
row_iter end ()
Pass through of iterator calls.
row_riter rbegin ()
Pass through of iterator calls.
row_riter rend ()
Pass through of iterator calls.
row_citer begin () const
Pass through of iterator calls.
row_citer end () const
Pass through of iterator calls.
row_criter rbegin () const
Pass through of iterator calls.
row_criter rend () const
Pass through of iterator calls.
DenseVector< _Type > & operator[] (const std::size_t &row)
Operator overloading for ROW access.
const DenseVector< _Type > & operator[] (const std::size_t &row) const
Operator overloading for ROW access.
void add (const DenseMatrix< _Type > &b)
Add a DENSE matrix to this object.
void sub (const DenseMatrix< _Type > &b)
Subtract a DENSE matrix from this object.
DenseMatrix< _Type > multiply (const DenseMatrix< _Type > &b) const
Right-multiply by a DENSE matrix and return the result.
void set_col (const std::size_t &col, const DenseVector< _Type > &x)
Set a column of the matrix.
DenseVector< _Type > get_col (const std::size_t &col) const
Get a column of the matrix.
DenseVector< double > matrix_to_vector (const std::size_t &padding=0) const
Conversion to contiguous data in row major format Inefficient ...
void matrix_to_vector (DenseVector< double > &p, const std::size_t &padding=0) const
Conversion to contiguous data in row major format.
row_iter max_in_col (const std::size_t &col, row_iter row_min, row_iter row_max) const
Find the maximum abs value in a column.
void matrix_to_vector (DenseVector< double > &p, const std::size_t &padding) const
void matrix_to_vector (DenseVector< double > &p, const std::size_t &padding) const
DenseVector< double > matrix_to_vector (const std::size_t &padding) const
DenseVector< double > matrix_to_vector (const std::size_t &padding) const
Public Member Functions inherited from CppNoddy::Sequential_Matrix_base< _Type >
Sequential_Matrix_base ()
An empty constructor.
virtual ~Sequential_Matrix_base ()
Detailed Description
template<typename _Type>
class CppNoddy::DenseMatrix< _Type >
A matrix class that constructs a DENSE matrix as a row major std::vector of DenseVectors.
This is generally a nice way to implement the matrix, but the data elements [i][j] are not necessarily in contiguous row_major format in memory because there is a system dependent padding at the end of each row vector. Thus, in general, &[i][j+1] - &[i][j] != &[i][0] - &[i-1][Nc] .. ie. the step may be larger from the end of row i-1 to the start of row i. Typically, the data must be copied into contiguous memory for use in external libraries that take base pointers & assume uniform steps between elements.
Definition at line 25 of file DenseMatrix.h.
Member Typedef Documentation
elt_citer
template<typename _Type > typedef DenseVector<_Type>::elt_citer CppNoddy::DenseMatrix< _Type >::elt_citer
Definition at line 37 of file DenseMatrix.h.
elt_criter
template<typename _Type > typedef DenseVector<_Type>::elt_criter CppNoddy::DenseMatrix< _Type >::elt_criter
Definition at line 39 of file DenseMatrix.h.
elt_iter
template<typename _Type > typedef DenseVector<_Type>::elt_iter CppNoddy::DenseMatrix< _Type >::elt_iter
Definition at line 36 of file DenseMatrix.h.
elt_riter
template<typename _Type > typedef DenseVector<_Type>::elt_riter CppNoddy::DenseMatrix< _Type >::elt_riter
Definition at line 38 of file DenseMatrix.h.
row_citer
template<typename _Type > typedef std::vector<DenseVector<_Type> >::const_iterator CppNoddy::DenseMatrix< _Type >::row_citer
Definition at line 31 of file DenseMatrix.h.
row_criter
template<typename _Type > typedef std::vector<DenseVector<_Type> >::const_reverse_iterator CppNoddy::DenseMatrix< _Type >::row_criter
Definition at line 35 of file DenseMatrix.h.
row_iter
template<typename _Type > typedef std::vector<DenseVector<_Type> >::iterator CppNoddy::DenseMatrix< _Type >::row_iter
Typedef iterator types.
Definition at line 29 of file DenseMatrix.h.
row_riter
template<typename _Type > typedef std::vector<DenseVector<_Type> >::reverse_iterator CppNoddy::DenseMatrix< _Type >::row_riter
Definition at line 33 of file DenseMatrix.h.
Constructor & Destructor Documentation
DenseMatrix() [1/5]
template<typename _Type > CppNoddy::DenseMatrix< _Type >::DenseMatrix
Allow empty construction.
Definition at line 17 of file DenseMatrix.cpp.
                                   : m_nr(0), m_nc(0)
   {}
DenseMatrix() [2/5]
template<typename _Type > CppNoddy::DenseMatrix< _Type >::DenseMatrix (const std::size_t & rows, const std::size_t & cols, const _Type & fill)
Noddy Matrix constructor with a specified fill data.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
fill The entry to be placed in all elements.
Definition at line 21 of file DenseMatrix.cpp.
                                                      :
     Sequential_Matrix_base<_Type>(),
     m_nr(rows),
     m_nc(cols) {
     // make a row
     const DenseVector<_Type> row(cols, fill);
     // reserve the space
     m_matrix.reserve(rows);
     for(std::size_t i = 0; i < rows; ++i) {
       // push require number of rows into the 'matrix'
       m_matrix.push_back(row);
     }
   }
DenseMatrix() [3/5]
template<typename _Type > CppNoddy::DenseMatrix< _Type >::DenseMatrix (const std::size_t & rows, const std::size_t & cols, const _Type * p)
Construct a Noddy Matrix from a contiguous set of data.
This will be nasty if you pass the wrong pointer, but is useful in interfacing with external libraries. This assumes the contiguous data is in row_major format.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
p A pointer to the start of the data.
Definition at line 38 of file DenseMatrix.cpp.
                                                   :
     Sequential_Matrix_base<_Type>(),
     m_nr(rows),
     m_nc(cols) {
     m_matrix.reserve(rows);
     for(std::size_t i = 0; i < rows; ++i) {
       m_matrix.push_back(DenseVector<_Type>(cols, &p[ i * cols ]));
     }
   }
DenseMatrix() [4/5]
template<typename _Type > CppNoddy::DenseMatrix< _Type >::DenseMatrix (const BandedMatrix< _Type > & source) inline
Construct a dense matrix from its banded counterpart.
Parameters
source The banded matrix to be used in the construction.
Definition at line 65 of file DenseMatrix.h.
{
       // get the number of off diagonal elts
       int l = source.noffdiag();
       // banded matrix class is always square
       int n = source.nrows();
       for(int row = 0; row < n; ++row) {
         DenseVector<_Type> vecrow(n, 0.0);
         for(int col = std::max(row - l, 0);
             col < std::min(n, row + l + 1);
             ++col) {
           vecrow[ col ] = source(row, col);
         }
         m_matrix.push_back(vecrow);
       }
       m_nr = m_nc = n;
     }
DenseMatrix() [5/5]
template<typename _Type > CppNoddy::DenseMatrix< _Type >::DenseMatrix (const DenseMatrix< _Type > & source)
Copy constructor.
Parameters
source The source object to be copied
Definition at line 51 of file DenseMatrix.cpp.
                                                                   :
     Sequential_Matrix_base<_Type>() {
     *this = source;
   }
~DenseMatrix()
template<typename _Type > CppNoddy::DenseMatrix< _Type >::~DenseMatrix
Definition at line 57 of file DenseMatrix.cpp.
   {}
Member Function Documentation
add()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::add (const DenseMatrix< _Type > & b)
Add a DENSE matrix to this object.
Parameters
b The DENSE matrix to add to 'this'
Definition at line 76 of file DenseMatrix.cpp.
{
 #ifdef PARANOID
     // check number of columns at least match
     if((B.nrows() != m_nr) || (B.ncols() != m_nc)) {
       std::string problem("The DenseMatrix.add has a geometry error.\n");
       throw ExceptionGeom(problem, m_nr, m_nc, B.nrows(), B.ncols());
     }
 #endif
     std::transform(m_matrix.begin(), m_matrix.end(), B.m_matrix.begin(), m_matrix.begin(), std::plus< DenseVector<_Type> >());
   }
Referenced by main().
assign()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::assign (_Type elt) inline
Assign a value to the matrix but keep the same geometry.
Parameters
elt The value to be assigned to all entries
Definition at line 170 of file DenseMatrix.h.
{
       m_matrix.assign(m_matrix.size(), DenseVector<_Type>(m_nc, elt));
     }
begin() [1/2]
template<typename _Type > row_iter CppNoddy::DenseMatrix< _Type >::begin () inline
Pass through of iterator calls.
Returns
Iterator to the begin row
Definition at line 176 of file DenseMatrix.h.
                      {
       return m_matrix.begin();
     }
begin() [2/2]
template<typename _Type > row_citer CppNoddy::DenseMatrix< _Type >::begin () const inline
Pass through of iterator calls.
Returns
Const iterator to the begin row
Definition at line 200 of file DenseMatrix.h.
{
       return m_matrix.begin();
     }
dump()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::dump virtual
Output the matrix to std::cout.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 223 of file DenseMatrix.cpp.
{
     std::cout << "DENSE mtx size = " << nrows() << " x " << ncols() << "; \n";
     std::cout.precision(3);
     std::cout << std::fixed;
     std::cout.setf(std::ios::showpoint);
     std::cout.setf(std::ios::showpos);
     //std::cout.setf( std::ios::scientific );
     std::cout << "- start matrix \n";
     for(std::size_t i = 0; i < nrows(); ++i) {
       std::cout << " row " << i << " =  ";
       for(std::size_t j = 0; j < ncols(); ++j) {
         std::cout << m_matrix[ i ][ j ] << ", ";
       }
       std::cout << "\n";
     }
     std::cout << "- end matrix \n";
   }
end() [1/2]
template<typename _Type > row_iter CppNoddy::DenseMatrix< _Type >::end () inline
Pass through of iterator calls.
Returns
Iterator to the end row
Definition at line 182 of file DenseMatrix.h.
                    {
       return m_matrix.end();
     }
end() [2/2]
template<typename _Type > row_citer CppNoddy::DenseMatrix< _Type >::end () const inline
Pass through of iterator calls.
Returns
Const iterator to the end row
Definition at line 206 of file DenseMatrix.h.
{
       return m_matrix.end();
     }
frob_norm()
template<typename _Type > double CppNoddy::DenseMatrix< _Type >::frob_norm
Return the sum of the two_norm of all rows.
Definition at line 213 of file DenseMatrix.cpp.
{
     double sum(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       sum += m_matrix[ row ].two_norm();
     }
     return sum;
   }
get()
template<typename _Type > const _Type & CppNoddy::DenseMatrix< _Type >::get (const std::size_t & row, const std::size_t & col) const inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 323 of file DenseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The DenseMatrix.get has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
     if((col > m_nc) || (col < 0)) {
       std::string problem("The DenseMatrix.get has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
 #endif
     return m_matrix[ row ][ col ];
   }
get_col()
template<typename _Type > DenseVector< _Type > CppNoddy::DenseMatrix< _Type >::get_col (const std::size_t & col) const
Get a column of the matrix.
Parameters
col The column to get
Returns
A DENSE vector of the column of data
Definition at line 249 of file DenseMatrix.cpp.
{
     DenseVector<_Type> X(m_nr, 0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       X[ row ] = m_matrix[ row ][ col ];
     }
     return X;
   }
Referenced by CppNoddy::DenseMatrix< D_complex >::multiply().
inf_norm()
template<typename _Type > double CppNoddy::DenseMatrix< _Type >::inf_norm
Return the maximum inf_norm of all rows.
Definition at line 204 of file DenseMatrix.cpp.
{
     double max(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       max = std::max(max, m_matrix[ row ].inf_norm());
     }
     return max;
   }
Referenced by main().
matrix_to_vector() [1/6]
DenseVector< double > CppNoddy::DenseMatrix< double >::matrix_to_vector (const std::size_t & padding) const
Definition at line 287 of file DenseMatrix.cpp.
{
     DenseVector<double> V;
     V.reserve(m_nr * m_nc);
     for(std::size_t row = 0; row < m_nr; ++row) {
       for(std::size_t col = 0; col < m_nc; ++col) {
         V.push_back(m_matrix[ row ][ col ]);
       }
       for(std::size_t col = 0; col < padding; ++col) {
         V.push_back(0.0);
       }
     }
     return V;
   }
matrix_to_vector() [2/6]
DenseVector< double > CppNoddy::DenseMatrix< std::complex< double > >::matrix_to_vector (const std::size_t & padding) const
Definition at line 302 of file DenseMatrix.cpp.
{
     DenseVector<double> V;
     V.reserve(2 * m_nr * m_nc);
     for(std::size_t row = 0; row < m_nr; ++row) {
       for(std::size_t col = 0; col < m_nc; ++col) {
         V.push_back(m_matrix[ row ][ col ].real());
         V.push_back(m_matrix[ row ][ col ].imag());
       }
       for(std::size_t col = 0; col < padding; ++col) {
         V.push_back(0.0);
         V.push_back(0.0);
       }
     }
     return V;
   }
matrix_to_vector() [3/6]
template<typename _Type > DenseVector<double> CppNoddy::DenseMatrix< _Type >::matrix_to_vector (const std::size_t & padding = 0) const
Conversion to contiguous data in row major format Inefficient ...
the void method is preferred
Parameters
padding An integer padding hack
Returns
A DENSE vector containing the matrix
Referenced by CppNoddy::FortranData::FortranData().
matrix_to_vector() [4/6]
void CppNoddy::DenseMatrix< std::complex< double > >::matrix_to_vector (DenseVector< double > & p, const std::size_t & padding) const
Definition at line 258 of file DenseMatrix.cpp.
{
     p.reserve(2 * m_nr * m_nc);
     for(std::size_t row = 0; row < m_nr; ++row) {
       for(std::size_t col = 0; col < m_nc; ++col) {
         p.push_back(m_matrix[ row ][ col ].real());
         p.push_back(m_matrix[ row ][ col ].imag());
       }
       for(std::size_t col = 0; col < padding; ++col) {
         p.push_back(0.0);
         p.push_back(0.0);
       }
     }
   }
matrix_to_vector() [5/6]
void CppNoddy::DenseMatrix< double >::matrix_to_vector (DenseVector< double > & p, const std::size_t & padding) const
Definition at line 274 of file DenseMatrix.cpp.
{
     p.reserve(m_nr * m_nc);
     for(std::size_t row = 0; row < m_nr; ++row) {
       for(std::size_t col = 0; col < m_nc; ++col) {
         p.push_back(m_matrix[ row ][ col ]);
       }
       for(std::size_t col = 0; col < padding; ++col) {
         p.push_back(0.0);
       }
     }
   }
matrix_to_vector() [6/6]
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::matrix_to_vector (DenseVector< double > & p, const std::size_t & padding = 0) const
Conversion to contiguous data in row major format.
Parameters
padding An integer padding hack
p A DENSE vector containing the matrix
max_in_col()
template<typename _Type > std::vector< DenseVector< _Type > >::iterator CppNoddy::DenseMatrix< _Type >::max_in_col (const std::size_t & col, row_iter row_min, row_iter row_max) const
Find the maximum abs value in a column.
Parameters
col The column offset to search through
row_min Iterator to the begin row
row_max Iterator to final row (NOT INCLUSIVE)
Returns
An iterator to the row that contains the maximum value
Definition at line 171 of file DenseMatrix.cpp.
{
     row_iter index(row_min);
     double maxelt(std::abs(*(row_min -> begin())));
     for(row_iter row = row_min + 1; row != row_max ; ++row) {
       const double elt(std::abs(*(row -> begin() + col)));
       if(elt >= maxelt) {
         maxelt = elt;
         index = row;
       }
     }
     return index;
   }
multiply() [1/2]
template<typename _Type > DenseMatrix< _Type > CppNoddy::DenseMatrix< _Type >::multiply (const DenseMatrix< _Type > & b) const
Right-multiply by a DENSE matrix and return the result.
Parameters
b The matrix to right-multiply by
Returns
The matrix result of the multiplication
Definition at line 149 of file DenseMatrix.cpp.
{
 #ifdef PARANOID
     // check number of columns at least match
     if(B.nrows() != m_nc) {
       std::string problem("The DenseMatrix.multiply has a geometry error.\n");
       throw ExceptionGeom(problem, m_nr, m_nc, B.nrows(), B.ncols());
     }
 #endif
     // temporary object for the result
     DenseMatrix<_Type> C(nrows(), B.ncols(), 0.0);
     // loops thru the columns in the B matrix
     for(std::size_t col_in_B = 0; col_in_B < B.ncols(); ++col_in_B) {
       // set the column in the result to be the matrix-vector
       // product of (*this).multiply( column in B )
       C.set_col(col_in_B, multiply(B.get_col(col_in_B)));
     }
     return C;
   }
multiply() [2/2]
template<typename _Type > DenseVector< _Type > CppNoddy::DenseMatrix< _Type >::multiply (const DenseVector< _Type > & x) const
Right multiply the matrix by a DENSE vector.
Parameters
x The DENSE vector to be multiplied
Returns
The DENSE vector of the multiplication
Definition at line 132 of file DenseMatrix.cpp.
{
 #ifdef PARANOID
     // check number of columns at least match
     if(X.size() != m_nc) {
       std::string problem("The DenseMatrix.multiply has a geometry error.\n");
       throw ExceptionGeom(problem, m_nr, m_nc, X.size(), 1);
     }
 #endif
     DenseVector<_Type> temp;
     temp.reserve(m_nr);
     for(std::size_t row = 0; row < m_nr; ++row) {
       temp.push_back(Utility::dot(m_matrix[ row ], X));
     }
     return temp;
   }
Referenced by CppNoddy::OneD_TVDLF_Elt::contributed_flux_in_left(), CppNoddy::OneD_TVDLF_Elt::contributed_flux_out_right(), CppNoddy::TwoD_TVDLF_Elt::get_Q_Taylor_series(), and main().
ncols()
template<typename _Type > std::size_t CppNoddy::DenseMatrix< _Type >::ncols inline virtual
Returns
The number of columns
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 383 of file DenseMatrix.h.
{
     return m_nc;
   }
Referenced by CppNoddy::DenseMatrix< D_complex >::add(), CppNoddy::Utility::multiply(), CppNoddy::DenseMatrix< D_complex >::multiply(), and CppNoddy::DenseMatrix< D_complex >::sub().
nelts()
template<typename _Type > std::size_t CppNoddy::DenseMatrix< _Type >::nelts virtual
Returns
The number of elements
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 71 of file DenseMatrix.cpp.
{
     return m_nr * m_nc;
   }
nrows()
template<typename _Type > std::size_t CppNoddy::DenseMatrix< _Type >::nrows inline virtual
Returns
The number of rows
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 378 of file DenseMatrix.h.
{
     return m_nr;
   }
Referenced by CppNoddy::DenseMatrix< D_complex >::add(), CppNoddy::Utility::multiply(), CppNoddy::DenseMatrix< D_complex >::multiply(), and CppNoddy::DenseMatrix< D_complex >::sub().
one_norm()
template<typename _Type > double CppNoddy::DenseMatrix< _Type >::one_norm
Return the maximum one_norm of all rows.
Definition at line 186 of file DenseMatrix.cpp.
{
     double max(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       max = std::max(max, m_matrix[ row ].one_norm());
     }
     return max;
   }
operator()() [1/2]
template<typename _Type > _Type & CppNoddy::DenseMatrix< _Type >::operator() (const std::size_t & row, const std::size_t & col) inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 306 of file DenseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The DenseMatrix.() has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
     if((col > m_nc) || (col < 0)) {
       std::string problem("The DenseMatrix.() has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
 #endif
     return m_matrix[ row ][ col ];
   }
operator()() [2/2]
template<typename _Type > const _Type & CppNoddy::DenseMatrix< _Type >::operator() (const std::size_t & row, const std::size_t & col) const inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 290 of file DenseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The DenseMatrix.() has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
     if((col > m_nc) || (col < 0)) {
       std::string problem("The DenseMatrix.() has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
 #endif
     return m_matrix[ row ][ col ];
   }
operator*()
template<typename _Type > DenseMatrix<_Type> CppNoddy::DenseMatrix< _Type >::operator* (const double & m) const inline
SIMD operator sugar.
Definition at line 104 of file DenseMatrix.h.
{
       DenseMatrix<_Type> temp(*this);
       temp.scale(m);
       return temp;
     }
operator+()
template<typename _Type > DenseMatrix<_Type> CppNoddy::DenseMatrix< _Type >::operator+ (const DenseMatrix< _Type > & A) const inline
Definition at line 109 of file DenseMatrix.h.
{
       DenseMatrix<_Type> temp(*this);
       for(std::size_t row = 0; row < m_nr; ++row) {
         for(std::size_t col = 0; col < m_nc; ++col) {
           temp(row, col) += A(row, col);
         }
       }
       return temp;
     }
operator-()
template<typename _Type > DenseMatrix<_Type> CppNoddy::DenseMatrix< _Type >::operator- (const DenseMatrix< _Type > & A) const inline
Definition at line 118 of file DenseMatrix.h.
{
       DenseMatrix<_Type> temp(*this);
       for(std::size_t row = 0; row < m_nr; ++row) {
         for(std::size_t col = 0; col < m_nc; ++col) {
           temp(row, col) -= A(row, col);
         }
       }
       return temp;
     }
operator=()
template<typename _Type > DenseMatrix< _Type > & CppNoddy::DenseMatrix< _Type >::operator= (const DenseMatrix< _Type > & source) inline
Assignment operator.
Parameters
source The source object for the assignment
Returns
The newly assigned object
Definition at line 61 of file DenseMatrix.cpp.
{
     if(this == &source)
       return * this;
     m_matrix = source.m_matrix;
     m_nr = source.m_nr;
     m_nc = source.m_nc;
     return *this;
   }
operator[]() [1/2]
template<typename _Type > DenseVector< _Type > & CppNoddy::DenseMatrix< _Type >::operator[] (const std::size_t & row) inline
Operator overloading for ROW access.
Parameters
row The row to access
Returns
The DENSE vector of the row data
Definition at line 356 of file DenseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The DenseMatrix.get_row has a range error.\n");
       throw ExceptionRange(problem, m_nr, row);
     }
 #endif
     return m_matrix[ row ];
   }
operator[]() [2/2]
template<typename _Type > const DenseVector< _Type > & CppNoddy::DenseMatrix< _Type >::operator[] (const std::size_t & row) const inline
Operator overloading for ROW access.
Parameters
row The row to access
Returns
The DENSE vector of the row data
Definition at line 367 of file DenseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The DenseMatrix.get_row has a range error.\n");
       throw ExceptionRange(problem, m_nr, row);
     }
 #endif
     return m_matrix[ row ];
   }
rbegin() [1/2]
template<typename _Type > row_riter CppNoddy::DenseMatrix< _Type >::rbegin () inline
Pass through of iterator calls.
Returns
Reverse iterator to the begin row
Definition at line 188 of file DenseMatrix.h.
{
       return m_matrix.rbegin();
     }
rbegin() [2/2]
template<typename _Type > row_criter CppNoddy::DenseMatrix< _Type >::rbegin () const inline
Pass through of iterator calls.
Returns
Const reverse iterator to the begin row
Definition at line 212 of file DenseMatrix.h.
{
       return m_matrix.rbegin();
     }
rend() [1/2]
template<typename _Type > row_riter CppNoddy::DenseMatrix< _Type >::rend () inline
Pass through of iterator calls.
Returns
Reverse iterator to the end row
Definition at line 194 of file DenseMatrix.h.
                      {
       return m_matrix.rend();
     }
rend() [2/2]
template<typename _Type > row_criter CppNoddy::DenseMatrix< _Type >::rend () const inline
Pass through of iterator calls.
Returns
Const reverse iterator to the end row
Definition at line 218 of file DenseMatrix.h.
{
       return m_matrix.rend();
     }
scale()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::scale (const _Type & mult) virtual
Scale all matrix elements by a scalar.
Parameters
mult The scalar multiplier
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 100 of file DenseMatrix.cpp.
{
     std::transform(m_matrix.begin(), m_matrix.end(), m_matrix.begin(), scale_functor< DenseVector<_Type>, _Type >(mult));
   }
Referenced by CppNoddy::Equation_1matrix< D_complex >::get_jacobian_of_matrix0_mult_vector(), CppNoddy::Equation_2matrix< D_complex >::get_jacobian_of_matrix1_mult_vector(), CppNoddy::Equation_3matrix< _Type >::get_jacobian_of_matrix2_mult_vector(), main(), and CppNoddy::DenseMatrix< D_complex >::operator*().
set()
template<typename _Type > _Type & CppNoddy::DenseMatrix< _Type >::set (const std::size_t & row, const std::size_t & col) inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 340 of file DenseMatrix.h.
{
 #ifdef PARANOID
     if((row > m_nr) || (row < 0)) {
       std::string problem("The DenseMatrix.set has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
     if((col > m_nc) || (col < 0)) {
       std::string problem("The DenseMatrix.set has a range error.\n");
       throw ExceptionRange(problem, m_nr, row, m_nc, col);
     }
 #endif
     return m_matrix[ row ][ col ];
   }
set_col()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::set_col (const std::size_t & col, const DenseVector< _Type > & x)
Set a column of the matrix.
Parameters
col The column to be set
x The DENSE vector of column information
Definition at line 242 of file DenseMatrix.cpp.
{
     for(std::size_t row = 0; row < m_nr; ++row) {
       m_matrix[ row ][ col ] = X[ row ];
     }
   }
Referenced by CppNoddy::OneD_Hyperbolic_System::Jac_flux_fn(), CppNoddy::TwoD_Hyperbolic_System::Jac_flux_fn_x(), CppNoddy::TwoD_Hyperbolic_System::Jac_flux_fn_y(), CppNoddy::Residual< D_complex >::jacobian(), and CppNoddy::DenseMatrix< D_complex >::multiply().
sub()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::sub (const DenseMatrix< _Type > & b)
Subtract a DENSE matrix from this object.
Parameters
b The DENSE matrix to subtract from 'this'
Definition at line 88 of file DenseMatrix.cpp.
{
 #ifdef PARANOID
     // check number of columns at least match
     if((B.nrows() != m_nr) || (B.ncols() != m_nc)) {
       std::string problem("The DenseMatrix.sub has a geometry error.\n");
       throw ExceptionGeom(problem, m_nr, m_nc, B.nrows(), B.ncols());
     }
 #endif
     std::transform(m_matrix.begin(), m_matrix.end(), B.m_matrix.begin(), m_matrix.begin(), std::minus< DenseVector<_Type> >());
   }
Referenced by CppNoddy::Equation_1matrix< D_complex >::get_jacobian_of_matrix0_mult_vector(), CppNoddy::Equation_2matrix< D_complex >::get_jacobian_of_matrix1_mult_vector(), CppNoddy::Equation_3matrix< _Type >::get_jacobian_of_matrix2_mult_vector(), and main().
transpose()
template<typename _Type > void CppNoddy::DenseMatrix< _Type >::transpose
Transpose the matrix.
Definition at line 105 of file DenseMatrix.cpp.
{
     if(nrows() == ncols()) {
       // square matrix needs no temp object
       // loop through upper half diagonal of the matrix
       for(std::size_t i = 0; i < nrows(); ++i) {
         for(std::size_t j = i + 1; j < ncols(); ++j) {
           // swap elements
           std::swap(m_matrix[ i ][ j ], m_matrix[ j ][ i ]);
         }
       }
     } else {
       std::vector< DenseVector<_Type> > temp;
       temp.resize(m_nc);
       for(std::size_t row = 0; row < m_nc; ++row) {
         temp[ row ].resize(m_nr);
       }
       for(std::size_t i = 0; i < nrows(); ++i) {
         for(std::size_t j = 0; j < ncols(); ++j) {
           temp[ j ][ i ] = m_matrix[ i ][ j ];
         }
       }
       m_matrix = temp;
       std::swap(m_nr, m_nc);
     }
   }
Referenced by CppNoddy::FortranData::FortranData().
two_norm()
template<typename _Type > double CppNoddy::DenseMatrix< _Type >::two_norm
Rreturn the maximum two_norm of all rows.
Definition at line 195 of file DenseMatrix.cpp.
{
     double max(0.0);
     for(std::size_t row = 0; row < m_nr; ++row) {
       max = std::max(max, m_matrix[ row ].two_norm());
     }
     return max;
   }
The documentation for this class was generated from the following files:
include/DenseMatrix.h
src/DenseMatrix.cpp
© 2012
R.E. Hewitt