CppNoddy: CppNoddy::HST::Rayleigh< _Type > Class Template Reference
CppNoddy::HST::Rayleigh< _Type > Class Template Reference
#include <HST.h>
Public Member Functions
Rayleigh (OneD_Node_Mesh< _Type, _Type > &base_flow_solution, double &alpha, const std::string &right_bc_type="BL")
ctor – either for a complex solution in the complex plane, or a double solution along the real line.
void global_evp ()
Solve the global eigenvalue problem for the Rayleigh equation by employing a second-order finite-difference matrix.
void local_evp (std::size_t i_ev)
Solve the EVP locally as a nonlinear BVP for just one mode.
void remesh1 (const OneD_Node_Mesh< _Type, _Type > &new_baseflow)
Refine the EIGENVECTORS mesh for a new baseflow.
OneD_Node_Mesh< std::complex< double >, _Type > & eigenvectors ()
A handle to the eigenvectors mesh.
OneD_Node_Mesh< std::complex< double > > eigenvector (unsigned i_ev)
void iterate_to_neutral (std::size_t i_ev)
Iterate on the wavenumber ALPHA, using the local_evp routine, to drive a selected eigenvalue to be neutral (ie.
DenseVector< std::complex< double > > & eigenvalues ()
A handle to the eigenvalues vector.
double & alpha ()
A handle to the wavenumber.
void iterate_to_neutral (std::size_t i_ev)
void iterate_to_neutral (std::size_t i_ev)
void global_evp ()
void global_evp ()
Protected Attributes
std::string RIGHT_BC_TYPE
double ALPHA
OneD_Node_Mesh< _Type, _Type > BASEFLOW
OneD_Node_Mesh< std::complex< double >, _Type > EIGENVECTORS
DenseVector< std::complex< double > > EIGENVALUES
Detailed Description
template<typename _Type>
class CppNoddy::HST::Rayleigh< _Type >
Definition at line 18 of file HST.h.
Constructor & Destructor Documentation
Rayleigh()
template<typename _Type > CppNoddy::HST::Rayleigh< _Type >::Rayleigh (OneD_Node_Mesh< _Type, _Type > & base_flow_solution, double & alpha, const std::string & right_bc_type = "BL")
ctor – either for a complex solution in the complex plane, or a double solution along the real line.
Parameters
base_flow_solution The base flow velocity profile and its curvature.
alpha The wavenumber of the perturbation.
right_bc_type Determines the choice of boundary condition. "BL" is a derivative condition, whilst "CHANNEL" is a Dirichlet impermeability condition
Definition at line 332 of file HST.h.
{
       // protected data storage
       RIGHT_BC_TYPE = right_bc_type;
       ALPHA = alpha;
       BASEFLOW = base_flow_solution;
       EIGENVALUES = DenseVector<std::complex<double> >(BASEFLOW.get_nnodes(), 0.0);
       EIGENVECTORS = OneD_Node_Mesh<std::complex<double>, _Type>(BASEFLOW.nodes(), 1);
     }
References CppNoddy::Example::alpha.
Member Function Documentation
alpha()
template<typename _Type > double& CppNoddy::HST::Rayleigh< _Type >::alpha () inline
A handle to the wavenumber.
Returns
The wavenumber
Definition at line 140 of file HST.h.
                       {
         return ALPHA;
       }
References CppNoddy::HST::Rayleigh< _Type >::ALPHA.
Referenced by main().
eigenvalues()
template<typename _Type > DenseVector<std::complex<double> >& CppNoddy::HST::Rayleigh< _Type >::eigenvalues () inline
A handle to the eigenvalues vector.
Returns
A vector of eigenvalues
Definition at line 134 of file HST.h.
{
         return EIGENVALUES;
       }
References CppNoddy::HST::Rayleigh< _Type >::EIGENVALUES.
Referenced by main().
eigenvector()
template<typename _Type > OneD_Node_Mesh<std::complex<double> > CppNoddy::HST::Rayleigh< _Type >::eigenvector (unsigned i_ev) inline
Definition at line 118 of file HST.h.
{
         unsigned n(BASEFLOW.get_nnodes());
         OneD_Node_Mesh<std::complex<double> > temp(BASEFLOW.nodes(), 1);
         for(unsigned i = 0; i < n; ++i) {
           temp(i, 0) = EIGENVECTORS(i, i_ev);
         }
         return temp;
       }
References CppNoddy::HST::Rayleigh< _Type >::BASEFLOW, CppNoddy::HST::Rayleigh< _Type >::EIGENVECTORS, CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_nnodes(), and CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::nodes().
eigenvectors()
template<typename _Type > OneD_Node_Mesh<std::complex<double>, _Type>& CppNoddy::HST::Rayleigh< _Type >::eigenvectors () inline
A handle to the eigenvectors mesh.
Returns
A mesh containing the eigenvectors, with the i-th variable corresponding to the i-th eigenvalue.
Definition at line 114 of file HST.h.
{
         return EIGENVECTORS;
       }
References CppNoddy::HST::Rayleigh< _Type >::EIGENVECTORS.
global_evp() [1/3]
template<typename _Type > void CppNoddy::HST::Rayleigh< _Type >::global_evp ()
Solve the global eigenvalue problem for the Rayleigh equation by employing a second-order finite-difference matrix.
The scheme allows for a non-uniform distribution of nodal points.
Referenced by main().
global_evp() [2/3]
void CppNoddy::HST::Rayleigh< double >::global_evp ()
Definition at line 428 of file HST.h.
{
       unsigned N(BASEFLOW.get_nnodes());
       // Rayleigh EVP -- we'll keep it complex even though its extra work
       DenseMatrix<std::complex<double> > A(N, N, 0.0);
       DenseMatrix<std::complex<double> > B(N, N, 0.0);
       // f_0 = 0
       A(0, 0) = 1.0;
       B(0, 0) = 0.0;
       // step through the interior nodes
       for(std::size_t i = 1; i < N - 1; ++i) {
 #ifdef PARANOID
         const double h1 = BASEFLOW.coord(1) - BASEFLOW.coord(0);
         if(std::abs(BASEFLOW.coord(i) - BASEFLOW.coord(i - 1) - h1) > 1.e-12) {
           std::string problem;
           problem = " Warning: The Rayleigh.global_evp method is only first order \n";
           problem += " on a non-uniform mesh.\n";
           throw ExceptionRuntime(problem);
         }
 #endif
         double h(BASEFLOW.coord(i) - BASEFLOW.coord(i - 1));
         double k(BASEFLOW.coord(i + 1) - BASEFLOW.coord(i));
         double sigma(k / h);   // sigma = 1 => uniform mesh
         double y = BASEFLOW.coord(i);
         double U = BASEFLOW.get_interpolated_vars(y)[ 0 ];
         double Udd = BASEFLOW.get_interpolated_vars(y)[ 1 ];
         double h2 = 0.5 * h * h * sigma * (sigma + 1.0);
         A(i, i) = U * (-(sigma + 1.0) / h2 - ALPHA * ALPHA) - Udd;
         A(i, i - 1) = sigma * U / h2;
         A(i, i + 1) = U / h2;
         //
         B(i, i) = - (sigma + 1.0) / h2 - ALPHA * ALPHA;
         B(i, i - 1) = sigma / h2;
         B(i, i + 1) = 1. / h2;
       }
       // 3 point backward difference the far-field in BL, but pin in channel
       if(RIGHT_BC_TYPE == "BL") {
         double h = BASEFLOW.coord(N - 2) - BASEFLOW.coord(N - 3);
         double k = BASEFLOW.coord(N - 1) - BASEFLOW.coord(N - 2);
         //A( N - 1, N - 1 ) = -3.0 / ( 2 * h )- alpha;
         //A( N - 1, N - 2 ) = 4.0 / ( 2 * h );
         //A( N - 1, N - 3 ) = -1.0 / ( 2 * h );
         A(N - 1, N - 1) = h * (h + k) / k * (- 1. / (h * h) + 1. / ((h + k) * (h + k))) - ALPHA;
         A(N - 1, N - 2) = h * (h + k) / k * (1. / (h * h));
         A(N - 1, N - 3) = h * (h + k) / k * (1. / ((h + k) * (h + k)));
         B(N - 1, N - 1) = 0.0;
       } else if(RIGHT_BC_TYPE == "CHANNEL") {
         A(N - 1, N - 1) = 1.0;
         B(N - 1, N - 1) = 0.0;
       } else {
         std::string problem;
         problem = " The Rayleigh.global_evp_uniform class has been called with an unknown string \n";
         problem += " that defines the far-field boundary condition.";
         throw ExceptionRuntime(problem);
       }
       double U_max(BASEFLOW(0, 0));
       double U_min(BASEFLOW(0, 0));
       for(unsigned i = 1; i < N; ++i) {
         U_max = std::max(U_max, BASEFLOW(i, 0));
         U_min = std::min(U_min, BASEFLOW(i, 0));
       }
       DenseLinearEigenSystem<std::complex<double> > rayleigh_evp(&A, &B);
       rayleigh_evp.eigensolve();
       // return based on Howard's circle theorem
       rayleigh_evp.set_shift(std::complex<double> (0.5 * (U_max + U_min), 0.0));
       rayleigh_evp.tag_eigenvalues_disc(+1, 0.5 * (U_max - U_min));
       EIGENVALUES = rayleigh_evp.get_tagged_eigenvalues();
       DenseMatrix<std::complex<double> > eigenvecs_mtx = rayleigh_evp.get_tagged_eigenvectors();
       // get eigenvectors
       EIGENVECTORS = OneD_Node_Mesh<std::complex<double>, double>(BASEFLOW.nodes(), N);
       for(unsigned evec = 0; evec < EIGENVALUES.size(); ++evec) {
         for(unsigned node = 0; node < N; ++node) {
           EIGENVECTORS(node, evec) = eigenvecs_mtx(evec, node);
         }
       }
     }
References CppNoddy::Example::A(), CppNoddy::DenseLinearEigenSystem< _Type >::eigensolve(), CppNoddy::DenseLinearEigenSystem< _Type >::get_tagged_eigenvalues(), CppNoddy::DenseLinearEigenSystem< _Type >::get_tagged_eigenvectors(), h, CppNoddy::LinearEigenSystem_base::set_shift(), CppNoddy::Example::sigma(), CppNoddy::DenseLinearEigenSystem< _Type >::tag_eigenvalues_disc(), U, and CppNoddy::Example::Udd().
global_evp() [3/3]
void CppNoddy::HST::Rayleigh< std::complex< double > >::global_evp ()
Definition at line 508 of file HST.h.
{
       unsigned N(BASEFLOW.get_nnodes());
       // Rayleigh EVP
       DenseMatrix<std::complex<double> > A(N, N, 0.0);
       DenseMatrix<std::complex<double> > B(N, N, 0.0);
       // f_0 = 0
       A(0, 0) = 1.0;
       B(0, 0) = 0.0;
       //const std::complex<double>  h1 = BASEFLOW.coord( 1 ) - BASEFLOW.coord( 0 );
       // step through the interior nodes
       for(std::size_t i = 1; i < N - 1; ++i) {
 #ifdef PARANOID
         const double h1 = abs(BASEFLOW.coord(1) - BASEFLOW.coord(0));
         if(std::abs(BASEFLOW.coord(i) - BASEFLOW.coord(i - 1) - h1) > 1.e-12) {
           std::string problem;
           problem = " Warning: The Rayleigh.global_evp method is only first order \n";
           problem += " on a non-uniform mesh.\n";
           //throw ExceptionRuntime( problem );
         }
 #endif
         std::complex<double>  h(BASEFLOW.coord(i) - BASEFLOW.coord(i - 1));
         std::complex<double>  k(BASEFLOW.coord(i + 1) - BASEFLOW.coord(i));
         std::complex<double>  sigma(k / h);   // sigma = 1 => uniform mesh
         std::complex<double>  y = BASEFLOW.coord(i);
         std::complex<double>  U = BASEFLOW.get_interpolated_vars(y)[ 0 ];
         std::complex<double>  Udd = BASEFLOW.get_interpolated_vars(y)[ 1 ];
         std::complex<double>  h2 = 0.5 * h * h * sigma * (sigma + 1.0);
         A(i, i) = U * (-(sigma + 1.0) / h2 - ALPHA * ALPHA) - Udd;
         A(i, i - 1) = sigma * U / h2;
         A(i, i + 1) = U / h2;
         //
         B(i, i) = - (sigma + 1.0) / h2 - ALPHA * ALPHA;
         B(i, i - 1) = sigma / h2;
         B(i, i + 1) = 1. / h2;
       }
       // 3 point backward difference the far-field in BL, but pin in channel
       if(RIGHT_BC_TYPE == "BL") {
         std::complex<double>  h = BASEFLOW.coord(N - 2) - BASEFLOW.coord(N - 3);
         std::complex<double>  k = BASEFLOW.coord(N - 1) - BASEFLOW.coord(N - 2);
         //A( N - 1, N - 1 ) = -3.0 / ( 2 * h )- alpha;
         //A( N - 1, N - 2 ) = 4.0 / ( 2 * h );
         //A( N - 1, N - 3 ) = -1.0 / ( 2 * h );
         A(N - 1, N - 1) = h * (h + k) / k * (- 1. / (h * h) + 1. / ((h + k) * (h + k))) - ALPHA;
         A(N - 1, N - 2) = h * (h + k) / k * (1. / (h * h));
         A(N - 1, N - 3) = h * (h + k) / k * (1. / ((h + k) * (h + k)));
         B(N - 1, N - 1) = 0.0;
       } else if(RIGHT_BC_TYPE == "CHANNEL") {
         A(N - 1, N - 1) = 1.0;
         B(N - 1, N - 1) = 0.0;
       } else {
         std::string problem;
         problem = " The Rayleigh.global_evp_uniform class has been called with an unknown string \n";
         problem += " that defines the far-field boundary condition.";
         throw ExceptionRuntime(problem);
       }
       double U_max(BASEFLOW(0, 0).real());
       double U_min(BASEFLOW(0, 0).real());
       for(unsigned i = 1; i < N; ++i) {
         U_max = std::max(U_max, BASEFLOW(i, 0).real());
         U_min = std::min(U_min, BASEFLOW(i, 0).real());
       }
       DenseLinearEigenSystem<std::complex<double> > rayleigh_evp(&A, &B);
       rayleigh_evp.eigensolve();
       // return based on Howard's circle theorem
       rayleigh_evp.set_shift(std::complex<double> (0.5 * (U_max + U_min), 0.0));
       rayleigh_evp.tag_eigenvalues_disc(+1, 0.5 * (U_max - U_min));
       EIGENVALUES = rayleigh_evp.get_tagged_eigenvalues();
       DenseMatrix<std::complex<double> > eigenvecs_mtx = rayleigh_evp.get_tagged_eigenvectors();
       // get eigenvectors
       EIGENVECTORS = OneD_Node_Mesh<std::complex<double>, std::complex<double> >(BASEFLOW.nodes(), N);
       for(unsigned evec = 0; evec < EIGENVALUES.size(); ++evec) {
         for(unsigned node = 0; node < N; ++node) {
           EIGENVECTORS(node, evec) = eigenvecs_mtx(evec, node);
         }
       }
     }
References CppNoddy::Example::A(), CppNoddy::DenseLinearEigenSystem< _Type >::eigensolve(), CppNoddy::DenseLinearEigenSystem< _Type >::get_tagged_eigenvalues(), CppNoddy::DenseLinearEigenSystem< _Type >::get_tagged_eigenvectors(), h, CppNoddy::Utility::real(), CppNoddy::LinearEigenSystem_base::set_shift(), CppNoddy::Example::sigma(), CppNoddy::DenseLinearEigenSystem< _Type >::tag_eigenvalues_disc(), U, and CppNoddy::Example::Udd().
iterate_to_neutral() [1/3]
template<typename _Type > void CppNoddy::HST::Rayleigh< _Type >::iterate_to_neutral (std::size_t i_ev)
Iterate on the wavenumber ALPHA, using the local_evp routine, to drive a selected eigenvalue to be neutral (ie.
imaginary part is zero)
Parameters
i_ev The index of the eigenvalue to iterate on
Referenced by main().
iterate_to_neutral() [2/3]
void CppNoddy::HST::Rayleigh< double >::iterate_to_neutral (std::size_t i_ev)
Definition at line 351 of file HST.h.
 {}
iterate_to_neutral() [3/3]
void CppNoddy::HST::Rayleigh< std::complex< double > >::iterate_to_neutral (std::size_t i_ev)
Definition at line 354 of file HST.h.
{
       double delta(1.e-8);
       do {
         std::cout << "ALPHA = " << ALPHA << "\n";
         local_evp(i_ev);
         std::complex<double> copy_of_ev(EIGENVALUES[ i_ev ]);
         ALPHA += delta;
         local_evp(i_ev);
         ALPHA -= delta;
         double d_ev = (std::imag(EIGENVALUES[ i_ev ]) - std::imag(copy_of_ev)) / delta;
         ALPHA -= std::imag(copy_of_ev) / d_ev;
         std::cout << "ITERATING: " << ALPHA << " " << EIGENVALUES[ i_ev ] << " " << d_ev << "\n";
       } while(std::abs(std::imag(EIGENVALUES[ i_ev ])) > 1.e-6);
     }
References CppNoddy::Utility::imag().
local_evp()
template<typename _Type > void CppNoddy::HST::Rayleigh< _Type >::local_evp (std::size_t i_ev)
Solve the EVP locally as a nonlinear BVP for just one mode.
Again we employ a second-order accurate finite-difference scheme which allows for non-uniform distribution of nodal points.
Parameters
i_ev The index of the eigenvalue to solve for, based on the return from the global_evp method.
Definition at line 371 of file HST.h.
{
       // number of nodes in the mesh
       std::size_t N = BASEFLOW.get_nnodes();
       // formulate the Rayleigh equation as a BVP
       Rayleigh_equation Rayleigh_problem;
       // boundary conditions
       Rayleigh_left_BC Rayleigh_left;
       Rayleigh_right_BC_deriv Rayleigh_right_deriv;
       Rayleigh_right_BC_Dirichlet Rayleigh_right_Dirichlet;
       // set the private member data in the objects
       Rayleigh_problem.p_BASEFLOW = &BASEFLOW;
       Rayleigh_problem.p_ALPHA = &ALPHA;
       Rayleigh_right_deriv.p_ALPHA = &ALPHA;
       // pointer to the equation
       ODE_BVP<std::complex<double>, _Type>* p_Rayleigh;
       if(RIGHT_BC_TYPE == "BL") {
         p_Rayleigh = new ODE_BVP<std::complex<double>, _Type>(&Rayleigh_problem, BASEFLOW.nodes(), &Rayleigh_left, &Rayleigh_right_deriv);
       } else if(RIGHT_BC_TYPE == "CHANNEL") {
         p_Rayleigh = new ODE_BVP<std::complex<double>, _Type>(&Rayleigh_problem, BASEFLOW.nodes(), &Rayleigh_left, &Rayleigh_right_Dirichlet);
       } else {
         std::string problem;
         problem = " The Rayleigh.global_evp_uniform class has been called with an unknown string \n";
         problem += " that defines the far-field boundary condition.";
         throw ExceptionRuntime(problem);
       }
       p_Rayleigh -> max_itns() = 30;
       // set the initial guess using the global_evp solve data
       p_Rayleigh -> solution()(0, 0) = EIGENVECTORS(0, i_ev);
       p_Rayleigh -> solution()(0, 1) = (EIGENVECTORS(1, i_ev) - EIGENVECTORS(0, i_ev)) / (BASEFLOW.coord(1) - BASEFLOW.coord(0));
       p_Rayleigh -> solution()(0, 2) = EIGENVALUES[ i_ev ];
       // set the (arbitrary) amplitude from the global_evp solve data
       Rayleigh_left.AMPLITUDE = p_Rayleigh -> solution()(0, 1);
       for(unsigned i = 1; i < N - 1; ++i) {
         p_Rayleigh -> solution()(i, 0) = EIGENVECTORS(i, i_ev);
         p_Rayleigh -> solution()(i, 1) = (EIGENVECTORS(i + 1, i_ev) - EIGENVECTORS(i - 1, i_ev)) / (BASEFLOW.coord(i + 1) - BASEFLOW.coord(i - 1));
         p_Rayleigh -> solution()(i, 2) = EIGENVALUES[ i_ev ];
       }
       p_Rayleigh -> solution()(N - 1, 0) = EIGENVECTORS(N - 1, i_ev);
       p_Rayleigh -> solution()(N - 1, 1) = (EIGENVECTORS(N - 1, i_ev) - EIGENVECTORS(N - 2, i_ev)) / (BASEFLOW.coord(N - 1) - BASEFLOW.coord(N - 2));
       p_Rayleigh -> solution()(N - 1, 2) = EIGENVALUES[ i_ev ];
       // do a local solve
       p_Rayleigh -> solve2();
       // write the eigenvalue and eigenvector back to private member data store
       EIGENVALUES[ i_ev ] = p_Rayleigh -> solution()(0, 2);
       for(unsigned i = 0; i < N; ++i) {
         EIGENVECTORS(i, i_ev) = p_Rayleigh -> solution()(i, 0);
       }
       // delete the equation object
       delete p_Rayleigh;
     }
remesh1()
template<typename _Type > void CppNoddy::HST::Rayleigh< _Type >::remesh1 (const OneD_Node_Mesh< _Type, _Type > & new_baseflow)
Refine the EIGENVECTORS mesh for a new baseflow.
Useful following a global_evp solve and prior to a local_evp solve.
Parameters
new_baseflow A new mesh containing the base flow, we'll linearly interpolate to this mesh
Definition at line 343 of file HST.h.
{
       // reset the baseflow mesh
       BASEFLOW = new_baseflow;
       // first order interpolation of the eigenvectors
       EIGENVECTORS.remesh1(BASEFLOW.nodes());
     }
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::remesh1().
Member Data Documentation
ALPHA
template<typename _Type > double CppNoddy::HST::Rayleigh< _Type >::ALPHA protected
Definition at line 147 of file HST.h.
Referenced by CppNoddy::HST::Rayleigh< _Type >::alpha().
BASEFLOW
template<typename _Type > OneD_Node_Mesh<_Type, _Type> CppNoddy::HST::Rayleigh< _Type >::BASEFLOW protected
Definition at line 148 of file HST.h.
Referenced by CppNoddy::HST::Rayleigh< _Type >::eigenvector().
EIGENVALUES
template<typename _Type > DenseVector<std::complex<double> > CppNoddy::HST::Rayleigh< _Type >::EIGENVALUES protected
Definition at line 150 of file HST.h.
Referenced by CppNoddy::HST::Rayleigh< _Type >::eigenvalues().
EIGENVECTORS
template<typename _Type > OneD_Node_Mesh<std::complex<double>, _Type> CppNoddy::HST::Rayleigh< _Type >::EIGENVECTORS protected
Definition at line 149 of file HST.h.
Referenced by CppNoddy::HST::Rayleigh< _Type >::eigenvector(), and CppNoddy::HST::Rayleigh< _Type >::eigenvectors().
RIGHT_BC_TYPE
template<typename _Type > std::string CppNoddy::HST::Rayleigh< _Type >::RIGHT_BC_TYPE protected
Definition at line 146 of file HST.h.
The documentation for this class was generated from the following file:
include/HST.h
© 2012
R.E. Hewitt