CppNoddy: CppNoddy::Example::Acoustic_1d Class Reference
CppNoddy::Example::Acoustic_1d Class Reference
Define the system.
Public Member Functions
Acoustic_1d ()
One dimemsional constant coefft acoustic problem.
void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
Define the vector flux.
double max_charac_speed (const DenseVector< double > &q) const
Bound the shock speed.
Public Member Functions inherited from CppNoddy::OneD_Hyperbolic_System
OneD_Hyperbolic_System (const unsigned &order)
virtual ~OneD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void Jac_flux_fn (const double &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the flux function.
virtual bool_vec edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t=0.0) const
Define the edge boundary conditions.
virtual void source_fn (const double &x, const DenseVector< double > &q, const DenseVector< double > &slope, DenseVector< double > &r) const
unsigned get_order ()
Additional Inherited Members
Protected Attributes inherited from CppNoddy::OneD_Hyperbolic_System
const std::size_t ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
Define the system.
Definition at line 43 of file HYPAcousticImpedance.cpp.
Constructor & Destructor Documentation
Acoustic_1d()
CppNoddy::Example::Acoustic_1d::Acoustic_1d () inline
One dimemsional constant coefft acoustic problem.
Definition at line 49 of file HYPAcousticImpedance.cpp.
                     : OneD_Hyperbolic_System( 2 )
       {}
Member Function Documentation
flux_fn()
void CppNoddy::Example::Acoustic_1d::flux_fn (const double & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
Define the vector flux.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 53 of file HYPAcousticImpedance.cpp.
       {
         f[ p ] = K * q[ u ];
         f[ u ] = q[ p ] / rho( x );
       }
References f, CppNoddy::Example::K(), p, CppNoddy::Example::rho(), and u.
max_charac_speed()
double CppNoddy::Example::Acoustic_1d::max_charac_speed (const DenseVector< double > & q) const inline virtual
Bound the shock speed.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 60 of file HYPAcousticImpedance.cpp.
       {
         // sound speeds
         double c = sqrt( K / rho_small );
         // maximum shock speed
         return c;
       }
References CppNoddy::Example::K(), and CppNoddy::Example::rho_small().
The documentation for this class was generated from the following file:
Tests/HYP_1D/HYPAcousticImpedance.cpp
© 2012
R.E. Hewitt