CppNoddy: CppNoddy::TrackerFile Class Reference
CppNoddy::TrackerFile Class Reference
#include <TrackerFile.h>
Public Member Functions
TrackerFile (int prec=12)
TrackerFile (std::string filename, int prec=12)
~TrackerFile ()
void precision (unsigned prec)
void push_ptr (double *scalar, std::string desc="")
void push_ptr (D_complex *scalar, std::string desc="")
void push_ptr (DenseVector< double > *ptr_to_vector, std::string desc="")
void push_ptr (DenseVector< D_complex > *ptr_to_vector, std::string desc="")
void push_ptr (OneD_Node_Mesh< double > *ptr_to_mesh, std::string desc="")
void push_ptr (OneD_Node_Mesh< D_complex > *ptr_to_mesh, std::string desc="")
void push_ptr (OneD_Node_Mesh< D_complex, D_complex > *ptr_to_mesh, std::string desc="")
void newline ()
void set_filename (std::string filename)
void header ()
void update ()
Protected Attributes
std::ofstream m_dumpFile
Detailed Description
Definition at line 17 of file TrackerFile.h.
Constructor & Destructor Documentation
TrackerFile() [1/2]
CppNoddy::TrackerFile::TrackerFile (int prec = 12)
Definition at line 12 of file TrackerFile.cpp.
{
     this -> m_precision = prec;
   }
TrackerFile() [2/2]
CppNoddy::TrackerFile::TrackerFile (std::string filename, int prec = 12)
Definition at line 16 of file TrackerFile.cpp.
{
     m_dumpFile.open(filename.c_str());
     this -> m_precision = prec;
     m_dumpFile.precision(prec);
     m_dumpFile << std::scientific;
   }
References m_dumpFile.
~TrackerFile()
CppNoddy::TrackerFile::~TrackerFile ()
Definition at line 23 of file TrackerFile.cpp.
{
     m_dumpFile.close();
   }
References m_dumpFile.
Member Function Documentation
header()
void CppNoddy::TrackerFile::header ()
Definition at line 81 of file TrackerFile.cpp.
{
     // write the header
     m_dumpFile << " # Header : \n # ";
     for(std::size_t i = 0; i < m_doubleDesc.size(); ++i) {
       m_dumpFile << m_doubleDesc[ i ] << " | ";
     }
     for(std::size_t i = 0; i < m_doubleVectorDesc.size(); ++i) {
       m_dumpFile << m_doubleVectorDesc[ i ] << " | ";
     }
     for(std::size_t i = 0; i < m_complexVectorDesc.size(); ++i) {
       m_dumpFile << m_complexVectorDesc[ i ] + " (Real)" << " | ";
       m_dumpFile << m_complexVectorDesc[ i ] + " (Imag)" << " | ";
     }
     for(std::size_t i = 0; i < m_doubleMeshDesc.size(); ++i) {
       m_dumpFile << m_doubleMeshDesc[ i ] + " (nodes)" << " | ";
       for(unsigned var = 0; var < (*p_doubleMesh[ i ]).get_nvars(); ++var) {
         m_dumpFile << m_doubleMeshDesc[ i ] + " var#" + Utility::stringify(var) + " | ";
       }
     }
     for(std::size_t i = 0; i < m_complexMeshDesc.size(); ++i) {
       m_dumpFile << m_complexMeshDesc[ i ] + "(nodes)" << " | ";
       for(unsigned var = 0; var < (*p_complexMesh[ i ]).get_nvars(); ++var) {
         m_dumpFile << m_complexMeshDesc[ i ] + " var#" + Utility::stringify(var) + " (Real) | ";
         m_dumpFile << m_complexMeshDesc[ i ] + " var#" + Utility::stringify(var) + " (Imag) | ";
       }
     }
     for(std::size_t i = 0; i < m_complexComplexMeshDesc.size(); ++i) {
       m_dumpFile << m_complexComplexMeshDesc[ i ] + "(nodes)_real" << " | ";
       m_dumpFile << m_complexComplexMeshDesc[ i ] + "(nodes)_imag" << " | ";
       for(unsigned var = 0; var < (*p_complexComplexMesh[ i ]).get_nvars(); ++var) {
         m_dumpFile << m_complexComplexMeshDesc[ i ] + " var#" + Utility::stringify(var) + " (Real) | ";
         m_dumpFile << m_complexComplexMeshDesc[ i ] + " var#" + Utility::stringify(var) + " (Imag) | ";
       }
     }
     m_dumpFile << "\n";
   }
References m_dumpFile, and CppNoddy::Utility::stringify().
Referenced by main().
newline()
void CppNoddy::TrackerFile::newline ()
Definition at line 66 of file TrackerFile.cpp.
{
     m_dumpFile << "\n";
   }
References m_dumpFile.
Referenced by main().
precision()
void CppNoddy::TrackerFile::precision (unsigned prec)
Definition at line 76 of file TrackerFile.cpp.
{
     this -> m_precision = prec;
     m_dumpFile.precision(prec);
   }
References m_dumpFile.
Referenced by main().
push_ptr() [1/7]
void CppNoddy::TrackerFile::push_ptr (D_complex * scalar, std::string desc = "")
Definition at line 32 of file TrackerFile.cpp.
{
     //p_Doubles.push_back( &( scalar -> real() ) );
     //p_Doubles.push_back( &( scalar -> imag() ) );
     // above is no longer valid for g++-7.2
     p_doubles.push_back(&reinterpret_cast<double(&)[2]>(*scalar)[0]);
     p_doubles.push_back(&reinterpret_cast<double(&)[2]>(*scalar)[1]);
     m_doubleDesc.push_back(desc + " (real)");
     m_doubleDesc.push_back(desc + " (imag)");
   }
push_ptr() [2/7]
void CppNoddy::TrackerFile::push_ptr (DenseVector< D_complex > * ptr_to_vector, std::string desc = "")
Definition at line 47 of file TrackerFile.cpp.
{
     p_complexVectors.push_back(ptr_to_vector);
     m_complexVectorDesc.push_back(desc);
   }
push_ptr() [3/7]
void CppNoddy::TrackerFile::push_ptr (DenseVector< double > * ptr_to_vector, std::string desc = "")
Definition at line 42 of file TrackerFile.cpp.
{
     p_doubleVectors.push_back(ptr_to_vector);
     m_doubleVectorDesc.push_back(desc);
   }
push_ptr() [4/7]
void CppNoddy::TrackerFile::push_ptr (double * scalar, std::string desc = "")
Definition at line 27 of file TrackerFile.cpp.
{
     p_doubles.push_back(scalar);
     m_doubleDesc.push_back(desc);
   }
Referenced by main().
push_ptr() [5/7]
void CppNoddy::TrackerFile::push_ptr (OneD_Node_Mesh< D_complex > * ptr_to_mesh, std::string desc = "")
Definition at line 57 of file TrackerFile.cpp.
{
     p_complexMesh.push_back(ptr_to_mesh);
     m_complexMeshDesc.push_back(desc);
   }
push_ptr() [6/7]
void CppNoddy::TrackerFile::push_ptr (OneD_Node_Mesh< D_complex, D_complex > * ptr_to_mesh, std::string desc = "")
Definition at line 62 of file TrackerFile.cpp.
{
     p_complexComplexMesh.push_back(ptr_to_mesh);
     m_complexMeshDesc.push_back(desc);
   }
push_ptr() [7/7]
void CppNoddy::TrackerFile::push_ptr (OneD_Node_Mesh< double > * ptr_to_mesh, std::string desc = "")
Definition at line 52 of file TrackerFile.cpp.
{
     p_doubleMesh.push_back(ptr_to_mesh);
     m_doubleMeshDesc.push_back(desc);
   }
set_filename()
void CppNoddy::TrackerFile::set_filename (std::string filename)
Definition at line 70 of file TrackerFile.cpp.
{
     m_dumpFile.close();
     m_dumpFile.open(filename.c_str());
     m_dumpFile.precision(m_precision);
   }
References m_dumpFile.
Referenced by main().
update()
void CppNoddy::TrackerFile::update ()
Definition at line 118 of file TrackerFile.cpp.
{
     unsigned block_size(1);
     if(!p_doubleVectors.empty()) {
       block_size = p_doubleVectors[ 0 ] -> size();
     }
     if(!p_complexVectors.empty()) {
       block_size = p_complexVectors[ 0 ] -> size();
     }
     if(!p_doubleMesh.empty()) {
       block_size = p_doubleMesh[ 0 ] -> get_nnodes();
     }
     if(!p_complexMesh.empty()) {
       block_size = p_complexMesh[ 0 ] -> get_nnodes();
     }
     if(!p_complexComplexMesh.empty()) {
       block_size = p_complexComplexMesh[ 0 ] -> get_nnodes();
     }
     for(unsigned line = 0; line < block_size; ++line) {
       dump_scalar_data();
       if(!p_doubleVectors.empty()) {
         // for each vector ptr
         for(std::size_t i = 0; i < p_doubleVectors.size(); ++i) {
           m_dumpFile << (*p_doubleVectors[ i ]) [ line ] << " ";
         }
       }
       if(!p_complexVectors.empty()) {
         // for each vector ptr
         for(std::size_t i = 0; i < p_complexVectors.size(); ++i) {
           m_dumpFile << (*p_complexVectors[ i ]) [ line ].real() << " ";
           m_dumpFile << (*p_complexVectors[ i ]) [ line ].imag() << " ";
         }
       }
       if(!p_doubleMesh.empty()) {
         // for each mesh ptr
         for(std::size_t i = 0; i < p_doubleMesh.size(); ++i) {
           m_dumpFile << (*p_doubleMesh[ i ]).coord(line) << " ";
           for(unsigned var = 0; var < p_doubleMesh[ i ] -> get_nvars(); ++var) {
             m_dumpFile << (*p_doubleMesh[ i ])(line, var) << " ";
           }
         }
       }
       if(!p_complexMesh.empty()) {
         // for each mesh ptr
         for(std::size_t i = 0; i < p_complexMesh.size(); ++i) {
           m_dumpFile << (*p_complexMesh[ i ]).coord(line) << " ";
           for(unsigned var = 0; var < p_complexMesh[ i ] -> get_nvars(); ++var) {
             m_dumpFile << (*p_complexMesh[ i ])(line, var).real() << " ";
             m_dumpFile << (*p_complexMesh[ i ])(line, var).imag() << " ";
           }
         }
       }
       if(!p_complexComplexMesh.empty()) {
         // for each mesh ptr
         for(std::size_t i = 0; i < p_complexComplexMesh.size(); ++i) {
           m_dumpFile << (*p_complexComplexMesh[ i ]).coord(line).real() << " ";
           m_dumpFile << (*p_complexComplexMesh[ i ]).coord(line).imag() << " ";
           for(unsigned var = 0; var < p_complexComplexMesh[ i ] -> get_nvars(); ++var) {
             m_dumpFile << (*p_complexComplexMesh[ i ])(line, var).real() << " ";
             m_dumpFile << (*p_complexComplexMesh[ i ])(line, var).imag() << " ";
           }
         }
       }
       m_dumpFile << "\n";
     }
     // flush the buffer
     m_dumpFile.flush();
   }
References CppNoddy::Utility::imag(), m_dumpFile, and CppNoddy::Utility::real().
Referenced by main().
Member Data Documentation
m_dumpFile
std::ofstream CppNoddy::TrackerFile::m_dumpFile mutable protected
Definition at line 52 of file TrackerFile.h.
Referenced by header(), newline(), precision(), set_filename(), TrackerFile(), update(), and ~TrackerFile().
The documentation for this class was generated from the following files:
include/TrackerFile.h
src/TrackerFile.cpp
© 2012
R.E. Hewitt