CppNoddy: CppNoddy::FnQuadrature Class Reference
CppNoddy::FnQuadrature Class Reference
A quadrature class that takes a function pointer.
#include <FnQuadrature.h>
Public Types
typedef void(* fn_ptr) (const double &, double &)
The function pointer associated with this instance.
Public Member Functions
FnQuadrature (fn_ptr ptr_to_fn, const double &x1, const double &x2, const unsigned &num_of_regions)
Constructor.
FnQuadrature (fn_ptr ptr_to_fn, const double &x1, const double &x2, const DenseVector< double > &nodes)
Constructor.
void set_subintervals (const unsigned &n)
A set method to define a UNIFORM number of sub intervals.
double Gauss (const int &n)
n-point Gauss rule inefficiently written!
double sub_Gauss (const int &n)
Evaluate the integral by applying an n-point Gauss rule on each of N sub-intervals.
double trapezium ()
Quick trapezium summation again for sanity checking.
Detailed Description
A quadrature class that takes a function pointer.
Definition at line 15 of file FnQuadrature.h.
Member Typedef Documentation
fn_ptr
typedef void(* CppNoddy::FnQuadrature::fn_ptr) (const double &, double &)
The function pointer associated with this instance.
Definition at line 20 of file FnQuadrature.h.
Constructor & Destructor Documentation
FnQuadrature() [1/2]
CppNoddy::FnQuadrature::FnQuadrature (fn_ptr ptr_to_fn, const double & x1, const double & x2, const unsigned & num_of_regions)
Constructor.
Parameters
ptr_to_fn the function that defines the integrand.
x1 left hand boundary of the domain.
x2 right hand boundary of the domain.
num_of_regions initial number of sub-regions to divide the domain into.
Definition at line 15 of file FnQuadrature.cpp.
                                                              :
     A(x1),
     B(x2),
     p_FN(ptr_to_fn) {
     NODES = Utility::uniform_node_vector(x1, x2, num_of_regions);
   }
References CppNoddy::Utility::uniform_node_vector().
FnQuadrature() [2/2]
CppNoddy::FnQuadrature::FnQuadrature (fn_ptr ptr_to_fn, const double & x1, const double & x2, const DenseVector< double > & nodes)
Constructor.
Parameters
ptr_to_fn the function that defines the integrand.
x1 left hand boundary of the domain.
x2 right hand boundary of the domain.
nodes A vector of nodal positions.
Definition at line 26 of file FnQuadrature.cpp.
                                                                :
     A(x1),
     B(x2),
     p_FN(ptr_to_fn) {
     NODES = nodes;
   }
Member Function Documentation
Gauss()
double CppNoddy::FnQuadrature::Gauss (const int & n)
n-point Gauss rule inefficiently written!
Parameters
n The number of points.
Returns
Approximation to the integral
Definition at line 40 of file FnQuadrature.cpp.
{
     DenseVector<double> t;    // evaluation points in [-1,1]
     DenseVector<double> w;    // respective weight values
     switch(n) {
     case 1:
       t.push_back(0.0);
       w.push_back(2.0);
       break;
     case 2:
       t.push_back(-1. / sqrt(3.));
       w.push_back(1.0);
       t.push_back(1. / sqrt(3.));
       w.push_back(1.0);
       break;
     case 3:
       t.push_back(0.0);
       w.push_back(8. / 9.);
       t.push_back(-0.774596669241483);
       w.push_back(5. / 9.);
       t.push_back(0.774596669241483);
       w.push_back(5. / 9.);
       break;
     default:
       std::string problem;
       problem = " The Quadrature.Gauss method is trying to apply \n";
       problem += " a Gauss rule with more points than 3. \n";
       problem += " Currenlty only n=1,2,3 are supported! \n";
       throw ExceptionRuntime(problem);
     }
     double sum = 0.0;
     double c = 0.5 * (B + A);
     double m = 0.5 * (B - A);
     double f, x;
     t.scale(m);
     for(unsigned i = 0; i < t.size(); ++i) {
       x = c + t[ i ];
       p_FN(x, f);
       sum += w[ i ] * f;
     }
     sum = sum * m;
     return sum;
   }
References f, m, CppNoddy::DenseVector< _Type >::push_back(), CppNoddy::DenseVector< _Type >::scale(), and CppNoddy::DenseVector< _Type >::size().
Referenced by sub_Gauss().
set_subintervals()
void CppNoddy::FnQuadrature::set_subintervals (const unsigned & n)
A set method to define a UNIFORM number of sub intervals.
Parameters
n Number of sub intervals
Definition at line 36 of file FnQuadrature.cpp.
{
     NODES = Utility::uniform_node_vector(A, B, n);
   }
References CppNoddy::Utility::uniform_node_vector().
Referenced by main().
sub_Gauss()
double CppNoddy::FnQuadrature::sub_Gauss (const int & n)
Evaluate the integral by applying an n-point Gauss rule on each of N sub-intervals.
This is inefficient in terms of class instantiation for each sub-interval, but not currently an issue.
Parameters
n The order of the Gauss rule.
Returns
Approximation to the integral.
Definition at line 88 of file FnQuadrature.cpp.
{
     double x_left, x_right;
     double sum = 0.0;
     unsigned num = NODES.size();
     //    double h = ( B - A ) / num;
     for(unsigned i = 0; i < num - 1; ++i) {
       //x_left = A + i * h;
       x_left = NODES[ i ];
       //x_right = x_left + h;
       x_right = NODES[ i + 1 ];
       FnQuadrature I(p_FN, x_left, x_right, num);
       sum += I.Gauss(n);
     }
     return sum;
   }
References Gauss(), and CppNoddy::DenseVector< _Type >::size().
Referenced by main().
trapezium()
double CppNoddy::FnQuadrature::trapezium ()
Quick trapezium summation again for sanity checking.
Should be essentially equivalent to the 1-point Gauss rule.
Returns
An approximation to the integral.
Definition at line 106 of file FnQuadrature.cpp.
{
     double sum = 0.0;
     unsigned num = NODES.size();
     double h = (B - A) / num;
     double x_left, x_right;
     double f_left, f_right;
     x_left = A;
     p_FN(x_left, f_left);
     for(unsigned i = 0; i < num; ++i) {
       x_right = A + (i + 1) * h;
       p_FN(x_right, f_right);
       sum += (f_left + f_right);
       f_left = f_right;
     }
     sum *= h / 2.;
     return sum;
   }
References h, and CppNoddy::DenseVector< _Type >::size().
Referenced by main().
The documentation for this class was generated from the following files:
include/FnQuadrature.h
src/FnQuadrature.cpp
© 2012
R.E. Hewitt