CppNoddy: CppNoddy::Example::Euler_1d Class Reference
CppNoddy::Example::Euler_1d Class Reference
Define the system.
Public Member Functions
Euler_1d ()
One dimemsional Euler problem, so 3rd order.
void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
Define the vector flux.
double max_charac_speed (const DenseVector< double > &q) const
Bound the shock speed.
Public Member Functions inherited from CppNoddy::OneD_Hyperbolic_System
OneD_Hyperbolic_System (const unsigned &order)
virtual ~OneD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void Jac_flux_fn (const double &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the flux function.
virtual bool_vec edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t=0.0) const
Define the edge boundary conditions.
virtual void source_fn (const double &x, const DenseVector< double > &q, const DenseVector< double > &slope, DenseVector< double > &r) const
unsigned get_order ()
Additional Inherited Members
Protected Attributes inherited from CppNoddy::OneD_Hyperbolic_System
const std::size_t ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
Define the system.
Definition at line 28 of file HYPSodsShocktube.cpp.
Constructor & Destructor Documentation
Euler_1d()
CppNoddy::Example::Euler_1d::Euler_1d () inline
One dimemsional Euler problem, so 3rd order.
Definition at line 34 of file HYPSodsShocktube.cpp.
                  : OneD_Hyperbolic_System( 3 )
       {}
Member Function Documentation
flux_fn()
void CppNoddy::Example::Euler_1d::flux_fn (const double & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
Define the vector flux.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 38 of file HYPSodsShocktube.cpp.
       {
         double u = q[ m ] / q[ rho ];
         double p = ( gamma - 1. ) * ( q[ E ] - 0.5 * q[ rho ] * u * u );
         f[ rho ] = q[ m ];
         f[ m ]   = q[ rho ] * u * u + p;
         f[ E ]   = u * ( q[ E ] + p );
       }
References E, f, CppNoddy::Example::gamma(), m, p, CppNoddy::Example::rho(), and u.
max_charac_speed()
double CppNoddy::Example::Euler_1d::max_charac_speed (const DenseVector< double > & q) const inline virtual
Bound the shock speed.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 48 of file HYPSodsShocktube.cpp.
       {
         // sound speeds
         double u = q[ m ] / q[ rho ];
         double p = ( gamma - 1. ) * ( q[ E ] - 0.5 * q[ rho ] * u * u );
         double c = sqrt( gamma *  p / q[ rho ] );
         // maximum shock speed
         return std::max(  u + c, u - c );
       }
References E, CppNoddy::Example::gamma(), m, p, CppNoddy::Example::rho(), and u.
The documentation for this class was generated from the following file:
Tests/HYP_1D/HYPSodsShocktube.cpp
© 2012
R.E. Hewitt