CppNoddy: CppNoddy::Example::harmonic_equation Class Reference
CppNoddy::Example::harmonic_equation Class Reference
Define the harmonic equation by inheriting the Equation base class.
Public Member Functions
harmonic_equation ()
The harmonic equation is a 2nd order real ODE.
void residual_fn (const DenseVector< double > &z, DenseVector< double > &g) const
The harmonic equation.
void matrix0 (const DenseVector< double > &z, DenseMatrix< double > &m) const
matrix to multiply the BVP coordinate
void matrix1 (const DenseVector< double > &z, DenseMatrix< double > &m) const
Define the eigenvalue terms by providing the mass matrix This defines the term lambda * z[ f ] ;.
Public Member Functions inherited from CppNoddy::Equation_2matrix< double >
Equation_2matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_2matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix1 () const
Return a handle to the matrix member data.
virtual void get_jacobian_of_matrix1_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Equation_1matrix< double, double >
Equation_1matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_1matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix0 () const
Return a handle to the matrix.
virtual void get_jacobian_of_matrix0_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Residual_with_coords< double, double >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
double & coord (const unsigned &i)
General handle access to the coordinates.
const double & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< double >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Residual object for the current set of state variables.
const DenseVector< double > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< double > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
double & delta ()
const double & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
Additional Inherited Members
Protected Member Functions inherited from CppNoddy::Residual< double >
virtual void jacobian (const DenseVector< double > &state, DenseMatrix< double > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual_with_coords< double, double >
std::vector< double > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< double >
DenseMatrix< double > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< double > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< double > LAST_STATE
The last state vector.
double DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Define the harmonic equation by inheriting the Equation base class.
Definition at line 25 of file EVPHarmonicEasy_lapack.cpp.
Constructor & Destructor Documentation
harmonic_equation()
CppNoddy::Example::harmonic_equation::harmonic_equation () inline
The harmonic equation is a 2nd order real ODE.
Definition at line 29 of file EVPHarmonicEasy_lapack.cpp.
 : Equation_2matrix<double>( 2 ) {}
Member Function Documentation
matrix0()
void CppNoddy::Example::harmonic_equation::matrix0 (const DenseVector< double > & z, DenseMatrix< double > & m) const inline virtual
matrix to multiply the BVP coordinate
Reimplemented from CppNoddy::Equation_1matrix< double, double >.
Definition at line 39 of file EVPHarmonicEasy_lapack.cpp.
       {
         Utils_Fill::fill_identity(m);
       }
References Utils_Fill::fill_identity(), and m.
matrix1()
void CppNoddy::Example::harmonic_equation::matrix1 (const DenseVector< double > & z, DenseMatrix< double > & m) const inline virtual
Define the eigenvalue terms by providing the mass matrix This defines the term lambda * z[ f ] ;.
Reimplemented from CppNoddy::Equation_2matrix< double >.
Definition at line 46 of file EVPHarmonicEasy_lapack.cpp.
       {
         // eigenvalue multiplies unknown 0 in equation 1
         m( 1, 0 ) = 1.0;
       }
References m.
residual_fn()
void CppNoddy::Example::harmonic_equation::residual_fn (const DenseVector< double > & z, DenseVector< double > & g) const inline virtual
The harmonic equation.
Reimplemented from CppNoddy::Residual< double >.
Definition at line 32 of file EVPHarmonicEasy_lapack.cpp.
       {
         g[ f ] = z[ fd ];
         g[ fd ] = 0.0;
       }
References f, fd, CppNoddy::Example::g(), and CppNoddy::Example::z().
The documentation for this class was generated from the following file:
Tests/EVP/EVPHarmonicEasy_lapack.cpp
© 2012
R.E. Hewitt