CppNoddy: Tests/EVP/EVPOrrSommerfeldNeutralCurve_lapack.cpp File Reference
EVPOrrSommerfeldNeutralCurve_lapack.cpp File Reference
#include <cassert>
#include <EVP_bundle.h>
#include <BVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::OS_evp_equation
Define the OS equation for the global QZ EVP.
class CppNoddy::Example::OS_bvp_equation
Define the OSE for the local refinement procedure.
class CppNoddy::Example::OS_evp_both_BC
class CppNoddy::Example::OS_bvp_left_BC
class CppNoddy::Example::OS_bvp_right_BC
class CppNoddy::Example::Neutral_residual
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum {
phi, phid, psi, psid,
eval
}
Functions
double CppNoddy::Example::U (double y)
Globally define the base flow.
double CppNoddy::Example::Udd (double y)
Globally define the base flow curvature.
int CppNoddy::Example::MAX_REFINE (3)
int main ()
Variables
double CppNoddy::Example::wave_speed
The phase speed of the instability.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
phi
phid
psi
psid
eval
Definition at line 24 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
 { phi, phid, psi, psid, eval };
Function Documentation
main()
int main ()
Definition at line 244 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
 {
   cout << "\n";
   cout << "=== EVP: Temporal OSE via the equation interface ====\n";
   cout << "===  followed by local refinement of the eigenvalue  \n";
   cout << "===  and arclength continuation of the neutral curve.\n";
   cout << "\n";
   double tol = 1.e-8;
   unsigned initial_QZ_mesh = 121;
   DenseVector<double> Re( 1, 5750.0 );
   Example::alpha = 1.0;
   Example::Re = Re[0];
   Example::Neutral_residual residual_problem( initial_QZ_mesh );
   Newton<double> newton( &residual_problem, 20, tol );
   newton.set_monitor_det( false );
   newton.rescale_theta() = true;
   newton.theta() = 0.00001;
   newton.init_arc( Re, &Example::alpha, 0.001, 0.01 );
   // set up the output file
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   TrackerFile my_file( "DATA/neutral.dat" );
   my_file.precision( 8 );
   my_file.push_ptr( &Re, "Reynolds number" );
   my_file.push_ptr( &Example::alpha, "Wavenumber" );
   my_file.push_ptr( &Example::wave_speed, "Phase speed" );
   my_file.header();
   double min_Re( Re[ 0 ] );
   do
   {
     try {
       newton.arclength_solve( Re );
     } catch ( const ExceptionBifurcation &bifn ) {
     }
     my_file.update();
     min_Re = std::min( Re[ 0 ], min_Re );
   }
   while ( Re[ 0 ] < 5820.0 );
   std::cout << " Minimum Reynolds number (for this spatial resolution ) = " << min_Re << "\n";
   // the known minimum critical Re is approx 5772 at alpha =1.02
   // increase MAX_REFINE to get a closer value to 5772.
   if ( std::abs( min_Re - 5772. ) < 30.0 )
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
   cout << "\033[1;31;48m  * FAILED \033[0m\n";
   return 1;
 }
References CppNoddy::Example::alpha, CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::TrackerFile::header(), CppNoddy::ArcLength_base< _Type >::init_arc(), CppNoddy::TrackerFile::precision(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::Example::Re, CppNoddy::ArcLength_base< _Type >::rescale_theta(), CppNoddy::Newton< _Type >::set_monitor_det(), CppNoddy::ArcLength_base< _Type >::theta(), CppNoddy::TrackerFile::update(), and CppNoddy::Example::wave_speed.
© 2012
R.E. Hewitt