CppNoddy: Tests/HYP_2D/HYP2DShallowSource.cpp File Reference
HYP2DShallowSource.cpp File Reference
Tests
#include <TwoD_HYP_bundle.h>
Classes
class CppNoddy::Example::Shallow_2d_source
Define the system.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { h, hu, hv }
Functions
double CppNoddy::Example::g (9.81)
gravitational acceleration
double CppNoddy::Example::A (0.2)
hump amplitude
double CppNoddy::Example::z (const double &x, const double &y)
Topography shape.
void CppNoddy::Example::Q_init (const double &x, const double &y, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Detailed Description
Two dimensional shallow water equations over topography. In this case, although the computation is 2D the topography is independent of the transverse coordinate and the result is checked against the 1D code.
Definition in file HYP2DShallowSource.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
h
hu
hv
Definition at line 11 of file HYP2DShallowSource.cpp.
 { h, hu, hv };
Function Documentation
main()
int main ()
Definition at line 135 of file HYP2DShallowSource.cpp.
 {
   cout << "\n";
   cout << "=== Hyperbolic: 2D shallow water over topography ====\n";
   cout << "\n";
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   std::string filename_stub( "./DATA/HYP_2D_shallow_source" );
   // define the domain/mesh
   const double west =  0;
   const double east = 25;
   const double south = -3;
   const double north = 3;
   const unsigned Nx = 401;
   const unsigned Ny = 3;
   DenseVector<double> faces_x = Utility::power_node_vector( west, east, Nx, 1.0 );
   DenseVector<double> faces_y = Utility::power_node_vector( south, north, Ny, 1.0 );
   Example::Shallow_2d_source conservative_problem;
   TwoD_TVDLF_Mesh Shallow_2d_mesh( faces_x, faces_y, &conservative_problem, Example::Q_init );
   Shallow_2d_mesh.set_limiter( 1 );
   int file_counter( 0 );
   int loop_counter( 0 );
   const double t_end = 5;
   do
   {
     if ( loop_counter % 10 == 0 )
     {
       Shallow_2d_mesh.dump_gnu( filename_stub + Utility::stringify( file_counter ) + ".dat" );
       file_counter += 1;
     }
     Shallow_2d_mesh.update( 0.49, std::abs( Shallow_2d_mesh.get_time() - t_end ) );
     loop_counter += 1;
   }
   while ( Shallow_2d_mesh.get_time() < t_end );
   DenseVector<double> x( 2, 0.0 );
   x[ 0 ] = 10;
   x[ 1 ] = 0;
   double h_10( Shallow_2d_mesh.get_point_values( x )[0] );
   // compare this value to the 1D code's result for this resolution and CFL
   double E( abs( h_10 - 0.116773 ) );
   if ( E > 1.e-5 )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << E << " \n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::TwoD_TVDLF_Mesh::dump_gnu(), E, CppNoddy::TwoD_TVDLF_Mesh::get_point_values(), CppNoddy::TwoD_TVDLF_Mesh::get_time(), CppNoddy::Utility::power_node_vector(), CppNoddy::Example::Q_init(), CppNoddy::TwoD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), and CppNoddy::TwoD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt