CppNoddy: Tests/HYP_1D/HYPAcousticImpedance.cpp File Reference
HYPAcousticImpedance.cpp File Reference
Tests
#include <OneD_HYP_bundle.h>
Classes
class CppNoddy::Example::Acoustic_1d
Define the system.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { p, u }
Functions
double CppNoddy::Example::K (4.0)
bulk modulus
double CppNoddy::Example::rho_big (4.0)
higher density
double CppNoddy::Example::rho_small (1.0)
lower density
double CppNoddy::Example::rho (const double &x)
Density function for the medium.
void CppNoddy::Example::Q_init (const double &x, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Detailed Description
Solve the constant coefficient linear sound wave problem
for a right-propagating square pressure pulse in a medium with constant bulk modulus and density if and elsewhere. The (first) reflected wave's velocity amplitude is
where and are the bulk modulus and wave speed before and after the density interface, with .
Definition in file HYPAcousticImpedance.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
p
u
Definition at line 17 of file HYPAcousticImpedance.cpp.
 { p, u };
Function Documentation
main()
int main ()
Definition at line 91 of file HYPAcousticImpedance.cpp.
 {
   cout << "\n";
   cout << "=== Hyperbolic: 1D acoustic wave, impedance problem =\n";
   cout << "\n";
   // define the domain/mesh
   const double left =  -7.0;
   const double right = 7.0;
   const unsigned N = 800;
   DenseVector<double> faces_x = Utility::uniform_node_vector( left, right, N );
   // time
   double t = 0.0;
   double t_end = 5.0;
   // hyperbolic problem
   Example::Acoustic_1d conservative_problem;
   OneD_TVDLF_Mesh Acoustic_mesh( faces_x, &conservative_problem, Example::Q_init );
   Acoustic_mesh.set_limiter( 1 );
   // mesh & test info
   double I1 = Acoustic_mesh.integrate()[0];
   int loop_counter( 4 );
   int file_counter( 1 );
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   std::string filename_stub;
   filename_stub = "./DATA/HYP_acoustic_imp";
   TrackerFile my_file( 5 );
   OneD_Node_Mesh<double> soln = Acoustic_mesh.get_soln();
   my_file.push_ptr( &soln, "mesh" );
   do
   {
     t += Acoustic_mesh.update( 0.499, t_end - t );
     if ( loop_counter % 2 == 0 )
     {
       my_file.set_filename( filename_stub + Utility::stringify( file_counter ) + ".dat" );
       soln = Acoustic_mesh.get_soln();
       my_file.update();
       file_counter += 1;
     }
     ++loop_counter;
   }
   while ( ( t < t_end ) && ( loop_counter < 1500 ) );
   soln = Acoustic_mesh.get_soln();
   double I2 = Acoustic_mesh.integrate()[0];
   // the first reflected and first transmitted pulses can be determined explicitly.
   // they have amplitude ratios of 1/3 and 8/9ths of the input amplitude for the pressure.
   soln = Acoustic_mesh.get_soln();
   double E1 = std::abs( soln.get_interpolated_vars( -5.0 )[0] - 1. / 3. );
   double E2 = std::abs( soln.get_interpolated_vars(  4.0 )[0] - 8. / 9. );
   if ( ( E1 > 1.e-4 ) || ( E2 > 1.e-4 ) || ( std::abs( I1 - I2 ) > 1.e-8 ) || ( loop_counter >= 1500 ) )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 } // end of main()
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_interpolated_vars(), CppNoddy::OneD_TVDLF_Mesh::get_soln(), CppNoddy::OneD_TVDLF_Mesh::integrate(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::Example::Q_init(), CppNoddy::TrackerFile::set_filename(), CppNoddy::OneD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), CppNoddy::Utility::uniform_node_vector(), CppNoddy::TrackerFile::update(), and CppNoddy::OneD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt