CppNoddy: CppNoddy::Utility Namespace Reference
CppNoddy::Utility Namespace Reference
Some utility methods associated with CppNoddy containers.
Functions
DenseVector< double > uniform_node_vector (const double &lower, const double &upper, const std::size_t &N)
Return a DENSE vector with the nodal points of a uniform mesh distributed between the upper/lower bounds as specified.
DenseVector< double > power_node_vector (const double &lower, const double &upper, const std::size_t &N, const double &power)
Return a DENSE vector with the nodal points of a non-uniform mesh distributed between the upper/lower bounds as specified with more nodes clustered near lower or upper depending upon the differencee of the power from unity.
DenseVector< double > two_uniform_node_vector (const double &lower, const double &mid, const double &upper, const std::size_t &N1, const std::size_t &N2)
Return a dense vector with two uniform distributions in two separate regions.
DenseVector< double > three_uniform_node_vector (const double &lower, const double &mid1, const double &mid2, const double &upper, const std::size_t &N1, const std::size_t &N2, const std::size_t &N3)
Return a dense vector with two uniform distributions in two separate regions.
DenseVector< double > mid_weighted_node_vector (const double &lower, const double &upper, const std::size_t &N, const double &power)
Return a dense vector of nodal positions with more nodes concentrated at the mid point of the range.
template<typename _Type >
void vels_from_streamfn_Cartesian (const TwoD_Node_Mesh< _Type > &source, TwoD_Node_Mesh< _Type > &uv)
template<typename _Type >
void vels_from_streamfn_Cartesian (const TwoD_Mapped_Node_Mesh< _Type > &source, TwoD_Mapped_Node_Mesh< _Type > &uv)
DenseMatrix< double > multiply (DenseMatrix< double > &A, DenseMatrix< double > &B)
BLAS wrapper to do DOUBLE DENSE A_{MxK} * B_{KxN} = C_{MxN} Since this is a Fortran library, it assumes a column_major format, but CppNoddy uses row_major.
template<typename _Type >
_Type dot (const DenseVector< _Type > &X, const DenseVector< _Type > &Y)
Templated dot product.
template<typename _Type >
int sgn (const _Type &a)
DenseVector< double > real (const DenseVector< D_complex > &X)
Return a double DENSE vector containing the real part of a complex DENSE vector.
DenseVector< double > imag (const DenseVector< D_complex > &X)
Return a double DENSE vector containing the imaginary part of a complex DENSE vector.
std::string stringify (const int &val)
Return an integer value as a string - useful for file naming.
std::string stringify (const double &val, int p)
Return a double value as a string - useful for file naming.
double max_abs_location (OneD_Node_Mesh< double > &mesh, unsigned var)
double max_abs_location_range (OneD_Node_Mesh< double > &mesh, unsigned var, double left, double right)
Detailed Description
Some utility methods associated with CppNoddy containers.
Function Documentation
dot()
template<typename _Type > _Type CppNoddy::Utility::dot (const DenseVector< _Type > & X, const DenseVector< _Type > & Y)
Templated dot product.
Parameters
X First dense vector
Y Second dense vector
Returns
The dot product
Definition at line 314 of file Utility.h.
{
       if(X.size() != Y.size()) {
         std::string problem;
         problem = "The Utilities::dot method has been called \n";
         problem += "with two unequal length vectors.";
         throw ExceptionGeom(problem, X.size(), Y.size());
       }
       return inner_product(X.begin(), X.end(), Y.begin(), _Type(0.0));
     }
References CppNoddy::DenseVector< _Type >::begin(), CppNoddy::DenseVector< _Type >::end(), and CppNoddy::DenseVector< _Type >::size().
Referenced by CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::ODE_BVP< D_complex >::arclength_solve(), CppNoddy::PDE_IBVP< _Type >::assemble_matrix_problem(), CppNoddy::Equation_1matrix< D_complex >::get_jacobian_of_matrix0_mult_vector(), CppNoddy::Equation_2matrix< D_complex >::get_jacobian_of_matrix1_mult_vector(), CppNoddy::Equation_3matrix< _Type >::get_jacobian_of_matrix2_mult_vector(), main(), and CppNoddy::DenseMatrix< D_complex >::multiply().
imag()
DenseVector< double > CppNoddy::Utility::imag (const DenseVector< D_complex > & X)
Return a double DENSE vector containing the imaginary part of a complex DENSE vector.
Parameters
X The complex vector to take the imaginary part of
Definition at line 185 of file Utility.cpp.
{
       DenseVector<double> temp(X.size(), 0.0);
       for(std::size_t i = 0; i < X.size(); ++i) {
         temp[ i ] = X[ i ].imag();
       }
       return temp;
     }
References CppNoddy::DenseVector< _Type >::size().
Referenced by CppNoddy::TwoD_Mapped_Node_Mesh< _Type >::dump_gnu(), CppNoddy::TwoD_Node_Mesh< _Type >::dump_gnu(), CppNoddy::OneD_Node_Mesh< D_complex >::dump_gnu(), CppNoddy::HST::Rayleigh< _Type >::iterate_to_neutral(), main(), CppNoddy::DenseMatrix< D_complex >::matrix_to_vector(), CppNoddy::Example::Neutral_residual::residual_fn(), CppNoddy::DenseLinearEigenSystem< _Type >::tag_eigenvalues_lower(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_lower(), CppNoddy::DenseLinearEigenSystem< _Type >::tag_eigenvalues_upper(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_upper(), and CppNoddy::TrackerFile::update().
max_abs_location()
double CppNoddy::Utility::max_abs_location (OneD_Node_Mesh< double > & mesh, unsigned var)
Definition at line 54 of file Utility.cpp.
{
       double max(0.0);
       std::size_t maxIndex(0);
       // step through the nodes
       for ( std::size_t node = 0; node < mesh.get_nnodes(); ++node ) {
         //std::cout << "m_X[node]=" << m_X[node] << " left=" << left << " right=" << right << "\n";
         if ( std::abs(mesh(node,var)) > max ) {
           maxIndex = node;
           max = std::abs( mesh(node,var) );
         }
       }
       if ( ( maxIndex == 0 ) || ( maxIndex == mesh.get_nnodes()-1 ) ) {
         std::cout << "[WARNING] MaxAbsLocationRange: maximumum absolute nodal value is first/last node. \n";
         return mesh.coord( maxIndex );
       }
       double f1,f2,f3;
       double x1,x2,x3;
       f1 = std::abs(mesh(maxIndex-1,var));
       f2 = std::abs(mesh(maxIndex,var));
       f3 = std::abs(mesh(maxIndex+1,var));
       x1 = mesh.coord(maxIndex-1);
       x2 = mesh.coord(maxIndex);
       x3 = mesh.coord(maxIndex+1);
       return ( f1*(x2+x3)/((x1-x2)*(x1-x3)) + f2*(x1+x3)/((x2-x1)*(x2-x3)) + f3*(x1+x2)/((x3-x1)*(x3-x2)) )
         / ( 2.*f1/((x1-x2)*(x1-x3)) + 2.*f2/((x2-x1)*(x2-x3)) + 2.*f3/((x3-x1)*(x3-x2)) );
     }
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::coord(), and CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_nnodes().
max_abs_location_range()
double CppNoddy::Utility::max_abs_location_range (OneD_Node_Mesh< double > & mesh, unsigned var, double left, double right)
Definition at line 82 of file Utility.cpp.
{
       double max(0.0);
       std::size_t maxIndex(0);
       // step through the nodes
       for ( std::size_t node = 0; node < mesh.get_nnodes(); ++node ) {
         //std::cout << "m_X[node]=" << m_X[node] << " left=" << left << " right=" << right << "\n";
         if ( ( mesh.coord(node) >= left ) && ( mesh.coord(node) <= right ) ) {
           if ( std::abs(mesh(node,var)) > max ) {
             maxIndex = node;
             max = std::abs( mesh(node,var) );
           }
         }
       }
       if ( ( maxIndex == 0 ) || ( maxIndex == mesh.get_nnodes()-1 ) ) {
         std::cout << "[WARNING] MaxAbsLocationRange: maximumum absolute nodal value is first/last node. \n";
         return mesh.coord( maxIndex );
       }
       double f1,f2,f3;
       double x1,x2,x3;
       f1 = std::abs(mesh(maxIndex-1,var));
       f2 = std::abs(mesh(maxIndex,var));
       f3 = std::abs(mesh(maxIndex+1,var));
       x1 = mesh.coord(maxIndex-1);
       x2 = mesh.coord(maxIndex);
       x3 = mesh.coord(maxIndex+1);
       return ( f1*(x2+x3)/((x1-x2)*(x1-x3)) + f2*(x1+x3)/((x2-x1)*(x2-x3)) + f3*(x1+x2)/((x3-x1)*(x3-x2)) )
         / ( 2.*f1/((x1-x2)*(x1-x3)) + 2.*f2/((x2-x1)*(x2-x3)) + 2.*f3/((x3-x1)*(x3-x2)) );
     }
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::coord(), and CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_nnodes().
mid_weighted_node_vector()
DenseVector< double > CppNoddy::Utility::mid_weighted_node_vector (const double & lower, const double & upper, const std::size_t & N, const double & power)
Return a dense vector of nodal positions with more nodes concentrated at the mid point of the range.
Parameters
lower The first nodal position.
upper The final nodal position.
N The number of nodes required.
power A measure of the non-uniformity, power = 1 => uniform distribution
Definition at line 155 of file Utility.cpp.
{
       DenseVector<double> node_vector(N, 0.0);
       // make a center weighted distribution over -1 to 1
       for(std::size_t i = 0; i < N; ++i) {
         double s(-1.0 + 2.0 * i / (N - 1));
         node_vector[ i ] = (weight * std::pow(s, 3) + s) / (weight + 1);
       }
       // map the -1 to 1 range to lower to upper
       for(std::size_t i = 0; i < N; ++i) {
         // move the range to 0->2
         node_vector[ i ] += 1.0;
         // move the range tp 0->1
         node_vector[ i ] /= 2.0;
         // move the range to lower -> upper
         node_vector[ i ] *= (upper - lower);
         node_vector[ i ] += lower;
       }
       return node_vector;
     }
References CppNoddy::Example::s.
multiply()
DenseMatrix< double > CppNoddy::Utility::multiply (DenseMatrix< double > & A, DenseMatrix< double > & B)
BLAS wrapper to do DOUBLE DENSE A_{MxK} * B_{KxN} = C_{MxN} Since this is a Fortran library, it assumes a column_major format, but CppNoddy uses row_major.
To be consistent we'll simply do (B^T)_{NxK} * (A^T)_{KxM} = (C^T)_{NxM} instead. Note that inversion of the transpose of the result C^T is handled implicitly via the construction of C.
Parameters
A First dense double matrix to be multiplied
B Second dense double matrix to be multiplied
Returns
The result of the multiplication C=A*B
Definition at line 225 of file Utility.cpp.
{
 #ifndef LAPACK
       std::string problem;
       problem = "The Utilities::multiply method has been called\n";
       problem += "but the compiler option -DLAPACK was not provided when\n";
       problem += "the library was built. This non-member function requires BLAS.";
       throw ExceptionExternal(problem);
 #else
       // set the matrix geometries
       std::size_t M = A.nrows();
       std::size_t N = B.ncols();
       std::size_t K = A.ncols();
       // No need to transpose first, because we will in fact do B^T * A^T = C^T
       // New the memory for the result
       FortranData Af(A, false);
       FortranData Bf(B, false);
       FortranData Cf(M * N);
 #ifdef PARANOID
       if(K != B.nrows()) {
         std::string problem(" The LAPACK::multiply method has detected a failure \n");
         throw ExceptionGeom(problem, A.nrows(), A.ncols(), B.nrows(), B.ncols());
       }
 #endif
       // call Fortran BLAS
       // call Fortran BLAS
       BLAS_DGEMM((char*) "N", (char*) "N", N, M, K, 1.0, Bf.base(), N, Af.base(), K, 0.0, Cf.base(), N);
       // Return a DenseMatrix<double> from the results -- since Cf is in column_major
       // format, this will actually transpose the Cf data to provide C as required
       return (Cf.to_dense_matrix(M, N));
 #endif
     }
References CppNoddy::Example::A(), CppNoddy::FortranData::base(), BLAS_DGEMM, CppNoddy::Example::K(), CppNoddy::DenseMatrix< _Type >::ncols(), CppNoddy::DenseMatrix< _Type >::nrows(), and CppNoddy::FortranData::to_dense_matrix().
Referenced by main(), and CppNoddy::DenseMatrix< D_complex >::multiply().
power_node_vector()
DenseVector< double > CppNoddy::Utility::power_node_vector (const double & lower, const double & upper, const std::size_t & N, const double & power)
Return a DENSE vector with the nodal points of a non-uniform mesh distributed between the upper/lower bounds as specified with more nodes clustered near lower or upper depending upon the differencee of the power from unity.
When power=1 this should provide a uniform mesh.
Parameters
lower The lower bound of the uniform nodal distribution
upper The upper bound of the uniform nodal distribution
N The number of nodal points
power A measure of the non-uniformity
Returns
A vector of nodal positions with a power law distribution
Definition at line 123 of file Utility.cpp.
{
       DenseVector<double> V(N, 0.0);
       for(std::size_t i = 0; i < N; ++i) {
         V[ i ] = lower + (upper - lower) * std::pow((double)i / (N - 1), power);
       }
       return V;
     }
References V.
Referenced by main().
real()
DenseVector< double > CppNoddy::Utility::real (const DenseVector< D_complex > & X)
Return a double DENSE vector containing the real part of a complex DENSE vector.
Parameters
X The complex vector to take the real part of
Definition at line 177 of file Utility.cpp.
{
       DenseVector<double> temp(X.size(), 0.0);
       for(std::size_t i = 0; i < X.size(); ++i) {
         temp[ i ] = X[ i ].real();
       }
       return temp;
     }
References CppNoddy::DenseVector< _Type >::size().
Referenced by CppNoddy::TwoD_Mapped_Node_Mesh< _Type >::dump_gnu(), CppNoddy::TwoD_Node_Mesh< _Type >::dump_gnu(), CppNoddy::OneD_Node_Mesh< D_complex >::dump_gnu(), CppNoddy::OneD_Node_Mesh< D_complex >::get_interpolated_vars(), CppNoddy::HST::Rayleigh< _Type >::global_evp(), main(), CppNoddy::DenseMatrix< D_complex >::matrix_to_vector(), CppNoddy::TwoD_Node_Mesh< _Type >::max_abs_real_part(), CppNoddy::Example::Neutral_residual::residual_fn(), CppNoddy::DenseLinearEigenSystem< _Type >::tag_eigenvalues_left(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_left(), CppNoddy::DenseLinearEigenSystem< _Type >::tag_eigenvalues_right(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_right(), and CppNoddy::TrackerFile::update().
sgn()
template<typename _Type > int CppNoddy::Utility::sgn (const _Type & a)
Definition at line 325 of file Utility.h.
{
       if(a > (_Type)0) {
         return 1;
       } else if(a < (_Type)0) {
         return -1;
       } else {
         return 0;
       }
     }
stringify() [1/2]
std::string CppNoddy::Utility::stringify (const double & val, int p)
Return a double value as a string - useful for file naming.
Parameters
val The double value to be stringified
p Precision to be used in the output
Definition at line 199 of file Utility.cpp.
{
       std::stringstream temp;
       temp.precision(p);
       temp << val;
       return temp.str();
     }
References p.
stringify() [2/2]
std::string CppNoddy::Utility::stringify (const int & val)
Return an integer value as a string - useful for file naming.
Parameters
val The integer value to be stringified.
Definition at line 193 of file Utility.cpp.
{
       std::stringstream temp;
       temp << val;
       return temp.str();
     }
Referenced by CppNoddy::TrackerFile::header(), main(), and CppNoddy::TwoD_Node_Mesh< _Type >::remesh1().
three_uniform_node_vector()
DenseVector< double > CppNoddy::Utility::three_uniform_node_vector (const double & lower, const double & mid1, const double & mid2, const double & upper, const std::size_t & N1, const std::size_t & N2, const std::size_t & N3)
Return a dense vector with two uniform distributions in two separate regions.
Parameters
lower The first node
mid1 The node that defines the first interior boundary
mid2 The node that defines the second interior boundary
upper The final node
N1 The number of nodes in the first region
N2 The number of nodes in the second region
N3 The number of nodes in the third region
Returns
A combined vector of nodes of length N1+N2+N3
Definition at line 141 of file Utility.cpp.
{
       DenseVector<double> first = uniform_node_vector(lower, mid1, N1);
       DenseVector<double> second = uniform_node_vector(mid1, mid2, N2+1);
       DenseVector<double> third = uniform_node_vector(mid2, upper, N3+1);
       // skip the common elt by starting at 1 not 0
       for(std::size_t i = 1; i < N2+1; ++i) {
         first.push_back(second[ i ]);
       }
       for(std::size_t i = 1; i < N3+1; ++i) {
         first.push_back(third[ i ]);
       }
       return first;
     }
References CppNoddy::DenseVector< _Type >::push_back(), and uniform_node_vector().
two_uniform_node_vector()
DenseVector< double > CppNoddy::Utility::two_uniform_node_vector (const double & lower, const double & mid, const double & upper, const std::size_t & N1, const std::size_t & N2)
Return a dense vector with two uniform distributions in two separate regions.
Parameters
lower The first node
mid The node that defines the boundary between the uniform meshes
upper The final node
N1 The number of nodes in the first region
N2 The number of nodes in the second region
Returns
A combined vector of nodes of length N1+N2
Definition at line 131 of file Utility.cpp.
{
       DenseVector<double> first = uniform_node_vector(lower, mid, N1);
       DenseVector<double> second = uniform_node_vector(mid, upper, N2 + 1);
       // skip the common elt by starting at 1 not 0
       for(std::size_t i = 1; i < N2+1; ++i) {
         first.push_back(second[ i ]);
       }
       return first;
     }
References CppNoddy::DenseVector< _Type >::push_back(), and uniform_node_vector().
uniform_node_vector()
DenseVector< double > CppNoddy::Utility::uniform_node_vector (const double & lower, const double & upper, const std::size_t & N)
Return a DENSE vector with the nodal points of a uniform mesh distributed between the upper/lower bounds as specified.
Parameters
lower The lower bound of the uniform nodal distribution
upper The upper bound of the uniform nodal distribution
N The number of nodal points
Definition at line 113 of file Utility.cpp.
{
       DenseVector<double> V;
       V.reserve(N);
       const double delta = (upper - lower) / (N - 1);
       for(std::size_t i = 0; i < N; ++i) {
         V.push_back(lower + delta * i);
       }
       return V;
     }
References V.
Referenced by CppNoddy::FnQuadrature::FnQuadrature(), CppNoddy::TwoD_Mapped_Node_Mesh< _Type >::init_mapping(), main(), CppNoddy::Example::Neutral_residual::Neutral_residual(), CppNoddy::FnQuadrature::set_subintervals(), three_uniform_node_vector(), and two_uniform_node_vector().
vels_from_streamfn_Cartesian() [1/2]
template<typename _Type > void CppNoddy::Utility::vels_from_streamfn_Cartesian (const TwoD_Mapped_Node_Mesh< _Type > & source, TwoD_Mapped_Node_Mesh< _Type > & uv)
Definition at line 166 of file Utility.h.
{
       std::cout << "MAPPED MESH version\n";
       std::size_t Nx(source.get_nnodes().first);
       std::size_t Ny(source.get_nnodes().second);
       double dX( source.get_comp_step_sizes().first );
       double dY( source.get_comp_step_sizes().second );
       // differentiate the streamfunction to get the velocity field
       {
         // west internal nodes
         std::size_t i(0);
         for(std::size_t j = 1; j < Ny - 1; ++j) {
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (source(i, j + 1, 0) - source(i, j - 1, 0)) * Yd / (2 * dY);
           uv(i, j, 1) = -(-source(i + 2, j, 0) + 4. * source(i + 1, j, 0) - 3. * source(i, j, 0)) * Xd / (2 * dX);
         }
       }
       {
         // east internal nodes
         std::size_t i(Nx - 1);
         for(std::size_t j = 1; j < Ny - 1; ++j) {
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (source(i, j + 1, 0) - source(i, j - 1, 0)) * Yd / (2 * dY);
           uv(i, j, 1) = -(source(i - 2, j, 0) - 4. * source(i - 1, j, 0) + 3. * source(i, j, 0)) * Xd / (2 * dX);
         }
       }
       {
         // south internal nodes
         std::size_t j(0);
         for(std::size_t i = 1; i < Nx - 1; ++i) {
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (-source(i, j + 2, 0) + 4. *  source(i, j + 1, 0) - 3. * source(i, j, 0))* Yd / (2 * dY);
           uv(i, j, 1) = -(source(i + 1, j, 0) - source(i - 1, j, 0)) * Xd / (2 * dX);
         }
       }
       {
         // north internal nodes
         std::size_t j(Ny - 1);
         for(std::size_t i = 1; i < Nx - 1; ++i) {
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (source(i, j - 2, 0) - 4. *  source(i, j - 1, 0) + 3. * source(i, j, 0)) * Yd / (2 * dY);
           uv(i, j, 1) = -(source(i + 1, j, 0) - source(i - 1, j, 0)) * Xd / (2 * dX);
         }
       }
       {
         // corner nodes
         {
           // sw
           std::size_t i(0);
           std::size_t j(0);
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (-source(i, j + 2, 0) + 4. *  source(i, j + 1, 0) - 3. * source(i, j, 0))* Xd / (2 * dY);
           uv(i, j, 1) = -(-source(i + 2, j, 0) + 4. * source(i + 1, j, 0) - 3. * source(i, j, 0))* Yd / (2 * dY);
         }
         {
           // nw
           std::size_t i(0);
           std::size_t j(Ny - 1);
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (source(i, j - 2, 0) - 4. *  source(i, j - 1, 0) + 3. * source(i, j, 0)) * Yd / (2 * dY);
           uv(i, j, 1) = -(-source(i + 2, j, 0) + 4. * source(i + 1, j, 0) - 3. * source(i, j, 0))* Xd / (2 * dX);
         }
         {
           // ne
           std::size_t i(Nx - 1);
           std::size_t j(Ny - 1);
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (source(i, j - 2, 0) - 4. *  source(i, j - 1, 0) + 3. * source(i, j, 0)) * Yd / (2 * dY);
           uv(i, j, 1) = -(source(i - 2, j, 0) - 4. * source(i - 1, j, 0) + 3. * source(i, j, 0)) * Xd/ (2 * dX);
         }
         {
           // se
           std::size_t i(Nx - 1);
           std::size_t j(0);
       double x = source.coord(i,j).first;
       double Xd = source.FnComp_Xd(x);
       double y = source.coord(i,j).second;
       double Yd = source.FnComp_Yd(y);
           uv(i, j, 0) = (-source(i, j + 2, 0) + 4. *  source(i, j + 1, 0) - 3. * source(i, j, 0))* Yd / (2 * dY);
           uv(i, j, 1) = -(source(i - 2, j, 0) - 4. * source(i - 1, j, 0) + 3. * source(i, j, 0)) * Xd / (2 * dX);
         }
       }
       {
         // interior nodes
         for(std::size_t i = 1; i < Nx - 1; ++i) {
           for(std::size_t j = 1; j < Ny - 1; ++j) {
         double x = source.coord(i,j).first;
         double Xd = source.FnComp_Xd(x);
         double y = source.coord(i,j).second;
         double Yd = source.FnComp_Yd(y);
             uv(i, j, 0) = (source(i, j + 1, 0) - source(i, j - 1, 0)) * Yd / (2 * dY);
             uv(i, j, 1) = -(source(i + 1, j, 0) - source(i - 1, j, 0)) * Xd / (2 * dX);
           }
         }
       }
     }
References CppNoddy::Example::source().
vels_from_streamfn_Cartesian() [2/2]
template<typename _Type > void CppNoddy::Utility::vels_from_streamfn_Cartesian (const TwoD_Node_Mesh< _Type > & source, TwoD_Node_Mesh< _Type > & uv)
Definition at line 83 of file Utility.h.
{
       std::cout << "PLAIN MESH version\n";
       std::size_t Nx(source.get_nnodes().first);
       std::size_t Ny(source.get_nnodes().second);
       double dx(source.coord(1,1).first - source.coord(0,0).first);
       double dy(source.coord(1,1).second - source.coord(0,0).second);
       // differentiate the streamfunction to get the velocity field
       {
         // west internal nodes
         std::size_t i(0);
         for(std::size_t j = 1; j < Ny - 1; ++j) {
           uv(i, j, 0) = (source(i, j + 1, 0) - source(i, j - 1, 0)) / (2 * dy);
           uv(i, j, 1) = -(-source(i + 2, j, 0) + 4. * source(i + 1, j, 0) - 3. * source(i, j, 0)) / (2 * dx);
         }
       }
       {
         // east internal nodes
         std::size_t i(Nx - 1);
         for(std::size_t j = 1; j < Ny - 1; ++j) {
           uv(i, j, 0) = (source(i, j + 1, 0) - source(i, j - 1, 0)) / (2 * dy);
           uv(i, j, 1) = -(source(i - 2, j, 0) - 4. * source(i - 1, j, 0) + 3. * source(i, j, 0)) / (2 * dx);
         }
       }
       {
         // south internal nodes
         std::size_t j(0);
         for(std::size_t i = 1; i < Nx - 1; ++i) {
           uv(i, j, 0) = (-source(i, j + 2, 0) + 4. *  source(i, j + 1, 0) - 3. * source(i, j, 0)) / (2 * dy);
           uv(i, j, 1) = -(source(i + 1, j, 0) - source(i - 1, j, 0)) / (2 * dx);
         }
       }
       {
         // north internal nodes
         std::size_t j(Ny - 1);
         for(std::size_t i = 1; i < Nx - 1; ++i) {
           uv(i, j, 0) = (source(i, j - 2, 0) - 4. *  source(i, j - 1, 0) + 3. * source(i, j, 0)) / (2 * dy);
           uv(i, j, 1) = -(source(i + 1, j, 0) - source(i - 1, j, 0)) / (2 * dx);
         }
       }
       {
         // corner nodes
         {
           // sw
           std::size_t i(0);
           std::size_t j(0);
           uv(i, j, 0) = (-source(i, j + 2, 0) + 4. *  source(i, j + 1, 0) - 3. * source(i, j, 0)) / (2 * dy);
           uv(i, j, 1) = -(-source(i + 2, j, 0) + 4. * source(i + 1, j, 0) - 3. * source(i, j, 0)) / (2 * dx);
         }
         {
           // nw
           std::size_t i(0);
           std::size_t j(Ny - 1);
           uv(i, j, 0) = (source(i, j - 2, 0) - 4. *  source(i, j - 1, 0) + 3. * source(i, j, 0)) / (2 * dy);
           uv(i, j, 1) = -(-source(i + 2, j, 0) + 4. * source(i + 1, j, 0) - 3. * source(i, j, 0)) / (2 * dx);
         }
         {
           // ne
           std::size_t i(Nx - 1);
           std::size_t j(Ny - 1);
           uv(i, j, 0) = (source(i, j - 2, 0) - 4. *  source(i, j - 1, 0) + 3. * source(i, j, 0)) / (2 * dy);
           uv(i, j, 1) = -(source(i - 2, j, 0) - 4. * source(i - 1, j, 0) + 3. * source(i, j, 0)) / (2 * dx);
         }
         {
           // se
           std::size_t i(Nx - 1);
           std::size_t j(0);
           uv(i, j, 0) = (-source(i, j + 2, 0) + 4. *  source(i, j + 1, 0) - 3. * source(i, j, 0)) / (2 * dy);
           uv(i, j, 1) = -(source(i - 2, j, 0) - 4. * source(i - 1, j, 0) + 3. * source(i, j, 0)) / (2 * dx);
         }
       }
       {
         // interior nodes
         for(std::size_t i = 1; i < Nx - 1; ++i) {
           for(std::size_t j = 1; j < Ny - 1; ++j) {
             uv(i, j, 0) = (source(i, j + 1, 0) - source(i, j - 1, 0)) / (2 * dy);
             uv(i, j, 1) = -(source(i + 1, j, 0) - source(i - 1, j, 0)) / (2 * dx);
           }
         }
       }
     }
References CppNoddy::Example::source().
© 2012
R.E. Hewitt