/// \file FortranLAPACK.h Some interface definitions for calling external fortran
/// routines in LAPACK

#ifndef FORTRANLAPACK_H
#define FORTRANLAPACK_H

#ifdef LAPACK

#include <cfortran.h>

/// The LAPACK LU solver for a DOUBLE DENSE matrix
/// Fortran interface : SUBROUTINE DGESV(N,NRHS,A,LDA,IPIV,B,LDB,INFO )
PROTOCCALLSFSUB8(DGESV, dgesv, INT, INT, DOUBLEV, INT, INTV, DOUBLEV, INT, PINT)
#define LAPACK_DGESV(N,NRHS,A,LDA,IPIV,B,LDB,INFO) CCALLSFSUB8(DGESV,dgesv,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT,N,NRHS,A,LDA,IPIV,B,LDB,INFO)

/// The LAPACK LU solver for a COMPLEX DENSE matrix
/// Fortran interface : SUBROUTINE ZGESV(N,NRHS,A,LDA,IPIV,B,LDB,INFO )
PROTOCCALLSFSUB8(ZGESV, zgesv, INT, INT, DOUBLEV, INT, INTV, DOUBLEV, INT, PINT)
#define LAPACK_ZGESV(N,NRHS,A,LDA,IPIV,B,LDB,INFO) CCALLSFSUB8(ZGESV,zgesv,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT,N,NRHS,A,LDA,IPIV,B,LDB,INFO)

/// The LAPACK LU solver for a DOUBLE BANDED matrix
/// Fortran interface : SUBROUTINE DGBSV(N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO)
PROTOCCALLSFSUB10(DGBSV, dgbsv, INT, INT, INT, INT, DOUBLEV, INT, INTV, DOUBLEV, INT, PINT)
#define LAPACK_DGBSV(N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO) CCALLSFSUB10(DGBSV,dgbsv,INT,INT,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT,N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO)

/// The LAPACK solve for an already LU decomposed DOUBLE BANDED matrix problem
/// Fortran interface : SUBROUTINE DGBTRS(TRANS,N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO )
PROTOCCALLSFSUB11(DGBTRS, dgbtrs, STRING, INT, INT, INT, INT, DOUBLEV, INT, INTV, DOUBLEV, INT, PINT)
#define LAPACK_DGBTRS(TRANS,N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO) CCALLSFSUB11(DGBTRS,dgbtrs,STRING,INT,INT,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT,TRANS,N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO)

/// The LAPACK LU solver for a COMPLEX BANDED matrix
/// Fortran interface : SUBROUTINE ZGBSV(N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO)
PROTOCCALLSFSUB10(ZGBSV, zgbsv, INT, INT, INT, INT, DOUBLEV, INT, INTV, DOUBLEV, INT, PINT)
#define LAPACK_ZGBSV(N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO) CCALLSFSUB10(ZGBSV,zgbsv,INT,INT,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT,N,KL,KU,NRHS,AB,LDAB,IPIV,B,LDB,INFO)

/// The LAPACK DOUBLE GENERALISED eigenvalue solver
/// Fortran interface : SUBROUTINE DGGEV(JOBVL,JOBVR,N,A,LDA,B,LDB,ALPHAR,ALPHAI,BETA,VL,LDVL,VR,LDVR,WORK,LWORK,INFO)
PROTOCCALLSFSUB17(DGGEV, dggev, STRING, STRING, INT, DOUBLEV, INT, DOUBLEV, INT, DOUBLEV, DOUBLEV, DOUBLEV, DOUBLEV, INT, DOUBLEV, INT, DOUBLEV, INT, PINT)
#define LAPACK_DGGEV(JOBVL,JOBVR,N,A,LDA,B,LDB,ALPHAR,ALPHAI,BETA,VL,LDVL,VR,LDVR,WORK,LWORK,INFO) CCALLSFSUB17(DGGEV,dggev,STRING,STRING,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,DOUBLEV,DOUBLEV,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,INT,PINT,JOBVL,JOBVR,N,A,LDA,B,LDB,ALPHAR,ALPHAI,BETA,VL,LDVL,VR,LDVR,WORK,LWORK,INFO)

/// The LAPACK COMPLEX GENERALISED eigenvalue solver
/// Fortran interface : SUBROUTINE ZGGEV(JOBVL,JOBVR,N,A,LDA,B,LDB,ALPHA,BETA,VL,LDVL,VR,LDVR,WORK,LWORK,RWORK,INFO)
PROTOCCALLSFSUB17(ZGGEV, zggev, STRING, STRING, INT, DOUBLEV, INT, DOUBLEV, INT, DOUBLEV, DOUBLEV, DOUBLEV, INT, DOUBLEV, INT, DOUBLEV, INT, DOUBLEV, PINT)
///                               jobvl  jobvr    n      a     lda   b      ldb    alpha    beta     vl     ldvl   vr     ldvr   work   lwork  rwork  info
#define LAPACK_ZGGEV(JOBVL,JOBVR,N,A,LDA,B,LDB,ALPHA,BETA,VL,LDVL,VR,LDVR,WORK,LWORK,RWORK,INFO) CCALLSFSUB17(ZGGEV,zggev,STRING,STRING,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,DOUBLEV,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,PINT,JOBVL,JOBVR,N,A,LDA,B,LDB,ALPHA,BETA,VL,LDVL,VR,LDVR,WORK,LWORK,RWORK,INFO)

#endif //LAPACK

#endif //FORTRANLAPACK_H
