/// \file FortranARPACK.h Some interface definitions for calling external fortran
/// routines in ARPACK

#ifndef FORTRANARPACK_H
#define FORTRANARPACK_H

#ifdef ARPACK

#include <cfortran.h>

/// The ARPACK double banded interface
/// Fortran interface : SUBROUTINE DNBAND(DR,DI,Z,LDZ,SIGMAR,SIGMAI,N,AB,MB,LDA,RFAC,CFAC,KL,WHICH,NEV,RESID,NCV,V,LDV,IPARAM,INFO)
PROTOCCALLSFSUB21( DNBAND, dnband, DOUBLEV, DOUBLEV, DOUBLEV, INT, DOUBLE, DOUBLE, INT, DOUBLEV, DOUBLEV, INT, DOUBLEV, DOUBLEV, INT, STRING, INT, DOUBLEV, INT, DOUBLEV, INT, INTV, INT )
///                                   DR,     DI,      Z,     LDZ, SIGMAR, SIGMAI,  N,     AB,       MB,   LDA,  RFAC,     CFAC,  KL,   WHICH, NEV, RESID,  NCV,    V,    LDV,IPARAM,INFO
#define ARPACK_DNBAND(DR,DI,Z,LDZ,SIGMAR,SIGMAI,N,AB,MB,LDA,RFAC,CFAC,KL,WHICH,NEV,RESID,NCV,V,LDV,IPARAM,INFO) CCALLSFSUB21(DNBAND,dnband,DOUBLEV,DOUBLEV,DOUBLEV,INT,DOUBLE,DOUBLE,INT,DOUBLEV,DOUBLEV,INT,DOUBLEV,DOUBLEV,INT,STRING,INT,DOUBLEV,INT,DOUBLEV,INT,INTV,INT,DR,DI,Z,LDZ,SIGMAR,SIGMAI,N,AB,MB,LDA,RFAC,CFAC,KL,WHICH,NEV,RESID,NCV,V,LDV,IPARAM,INFO)

/// The ARPACK complex banded interface
/// Fortran interface : SUBROUTINE ZNBAND(D,Z,LDZ,SIGMA,N,AB,MB,LDA,FAC,KL,WHICH,NEV,RESID,NCV,V,LDV,IPARAM,INFO )
PROTOCCALLSFSUB18( ZNBAND, znband, DOUBLEV, DOUBLEV, INT, DOUBLEV, INT, DOUBLEV, DOUBLEV, INT, DOUBLEV, INT, STRING, INT, DOUBLEV, INT, DOUBLEV, INT, INTV, INT )
///                                   D,       Z,    LDZ,  SIGMA,   N,     AB,      MB,   LDA,   FAC,    KL,  WHICH, NEV,  RESID,  NCV,    V,    LDV,IPARAM,INFO )
#define ARPACK_ZNBAND(D,Z,LDZ,SIGMA,N,AB,MB,LDA,FAC,KL,WHICH,NEV,RESID,NCV,V,LDV,IPARAM,INFO) CCALLSFSUB18(ZNBAND,znband,DOUBLEV,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,DOUBLEV,INT,DOUBLEV,INT,STRING,INT,DOUBLEV,INT,DOUBLEV,INT,INTV,INT,D,Z,LDZ,SIGMA,N,AB,MB,LDA,FAC,KL,WHICH,NEV,RESID,NCV,V,LDV,IPARAM,INFO)


#endif //ARPACK

#endif //FORTRANARPACK_H
