/// \file FortranBLAS.h Some interface definitions for calling external fortran
/// routines from BLAS

#ifndef FORTRANBLAS_H
#define FORTRANBLAS_H

//#ifdef LAPACK

#include <cfortran.h>

/// The BLAS DOUBLE dot-product
/// Fortran interface : FUNCTION DDOT(N,X,INCX,Y,INCY)
//PROTOCCALLSFFUN5( DOUBLE, DDOT, ddot, INT, DOUBLEV, INT, DOUBLEV, INT )
//#define BLAS_DDOT(N,X,INCX,Y,INCY) CCALLSFFUN5(DDOT,ddot,INT,DOUBLEV,INT,DOUBLEV,INT,N,X,INCX,Y,INCY)

/// The BLAS DOUBLE matrix multiplier
/// Fortran interface : SUBROUTINE DGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
PROTOCCALLSFSUB13( DGEMM, dgemm, STRING, STRING, INT, INT, INT, DOUBLE, DOUBLEV, INT, DOUBLEV, INT, DOUBLE, DOUBLEV, INT )
#define BLAS_DGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC) CCALLSFSUB13(DGEMM,dgemm,STRING,STRING,INT,INT,INT,DOUBLE,DOUBLEV,INT,DOUBLEV,INT,DOUBLE,DOUBLEV,INT,TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)

//#endif //LAPACK

#endif //FORTRANBLAS_H
