CppNoddy: Tests/Arclength/ArcCircleVector.cpp File Reference
ArcCircleVector.cpp File Reference
Tests
#include <cassert>
#include <Newton_bundle.h>
Classes
class CppNoddy::Example::Arc_problem
Define the residual for arc-length continuation of a circle.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Functions
int main ()
Detailed Description
A simple arc-length continuation solving the vector equation
where is a parameter. The solution is obtained by Newton iteration combined with arclength continuation with the parameter .
Definition in file ArcCircleVector.cpp.
Function Documentation
main()
int main ()
Definition at line 37 of file ArcCircleVector.cpp.
 {
   cout << "\n";
   cout << "=== ARC: cont of x^2 + p^2 = 1.0, y = sin(x) ========\n";
   cout << "\n";
   // initial guess
   DenseVector<double> x( 2, 0.0 );
   x[ 0 ] = 0.4;
   x[ 1 ] = 0.4;
   // Instantiate the problem
   Example::Arc_problem residual;
   // initialise the parameter
   residual.p = 0.9;
   // A Newton object
   Newton<double> newton( &residual );
   newton.set_monitor_det( true );
   newton.init_arc( x, &residual.p, 0.05, 0.1 );
   double tol( 1.e-7 );
   bool failed = false;
   for ( int i = 0; i < 400; ++i )
   {
     try
     {
       try
       {
         newton.arclength_solve( x );
       }
       catch ( const std::runtime_error &error )
       {
         cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
         return 1;
       }
     }
     catch ( const ExceptionBifurcation &bifn )
     {
       cout << " Bifurcation detected near x = " << x[ 0 ]
            << " p = " << residual.p << "\n\n";
     }
     if ( abs( pow( x[ 0 ], 2 )
               + pow( residual.p, 2 ) - 1.0 ) > tol )
     {
       failed = true;
       cout << " Error = " << pow( x[ 0 ], 2 )
            + pow( residual.p, 2 ) - 1.0 << "\n";
     }
   }
   if ( failed )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::Example::failed, CppNoddy::ArcLength_base< _Type >::init_arc(), and CppNoddy::Newton< _Type >::set_monitor_det().
© 2012
R.E. Hewitt