CppNoddy: Tests/Arclength/ArcCircle.cpp File Reference
ArcCircle.cpp File Reference
Tests
A simple arc-length continuation solving the equation.
#include <cassert>
#include <Newton_bundle.h>
Classes
class CppNoddy::Example::Arc_problem
Define the residual for arc-length continuation of a circle.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Functions
int main ()
Detailed Description
A simple arc-length continuation solving the equation.
where is a parameter. The solution is obtained by Newton iteration combined with (pseudo) arclength continuation with the parameter . For a (slightly) more serious example see the FalknerSkan_arc.cpp example.
Definition in file ArcCircle.cpp.
Function Documentation
main()
int main ()
Definition at line 39 of file ArcCircle.cpp.
{
  cout << "\n";
  cout << "=== ARC: continuation of x^2 + p^2 = 2.0 ============\n";
  cout << "\n";
  // Instantiate the problem
  Example::Arc_problem residual_problem;
  residual_problem.p = 1.0;
  const double tol = 1.e-10;
  // Scalar Newton iteration problem
  Newton<double> newton( &residual_problem, 8, tol );
  newton.set_monitor_det( true );
  // initial guess
  DenseVector<double> state( 1, 1.1 );
  // initialise a state for arc length cont.
  newton.init_arc( state, &residual_problem.p, 0.001, 0.1 );
  bool failed = false;
  for ( int i = 0; i < 100; ++i )
  {
    try
    {
      try
      {
        newton.arclength_solve( state );
      }
      catch ( const std::runtime_error &error )
      {
        cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
        return 1;
      }
    }
    catch ( const ExceptionBifurcation &bifn )
    {
      cout << " Bifurcation detected near x = " << state[ 0 ] << " p = " << residual_problem.p << "\n\n";
    }
    if ( abs( pow( state[ 0 ], 2 ) + pow( residual_problem.p, 2 ) - 2.0 ) > tol )
    {
      failed = true;
      cout << " Error = " << pow( state[ 0 ], 2 ) + pow( residual_problem.p, 2 ) - 2.0 << "\n";
    }
  }
  if ( failed )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::ArcLength_base< _Type >::init_arc(), CppNoddy::Example::Arc_problem::p, and CppNoddy::Newton< _Type >::set_monitor_det().
© 2012
R.E. Hewitt