CppNoddy: Tests/Arclength/ArcShootFalknerSkan.cpp File Reference
ArcShootFalknerSkan.cpp File Reference
Tests
Arc-length continue the Falkner-Skan equation.
#include <cassert>
#include <IVP_bundle.h>
#include <Newton_bundle.h>
Classes
class CppNoddy::Example::FS_eqn
Define the Falkner-Skan equation.
class CppNoddy::Example::FS_residual
Define a residual function using the boundary conditions for the Blasius profile.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Functions
int main ()
Detailed Description
Arc-length continue the Falkner-Skan equation.
for varying values of the Hartree parameter – around the well known limit point. The boundary conditions are and . We start from the Blasius solution, then arc-length continue to find the limit point at .
Using Runge-Kutta to solve a BVP is not a great method, but here it's used to demo the arc-length continuation for scalar problems.
Definition in file ArcShootFalknerSkan.cpp.
Function Documentation
main()
int main ()
Definition at line 85 of file ArcShootFalknerSkan.cpp.
{
  cout << "\n";
  cout << "=== ARC: arc-length continuation of the FS equation =\n";
  cout << "\n";
  // the residual function to be satisfied
  Example::FS_residual problem;
  // initial conditions
  problem.eqn -> beta = -0.11;
  DenseVector<double> stress( 1, 0.4 );
  // Scalar Newton iteration problem
  Newton<double> newton( &problem );
  newton.set_monitor_det( true );
  // initialise a state for arc length continuation
  newton.init_arc( stress, &problem.eqn -> beta, -0.01, 0.1 );
  // output for the data
  std::string dirname("./DATA");
  mkdir( dirname.c_str(), S_IRWXU );
  TrackerFile my_file( "./DATA/FSarc_path.dat" );
  my_file.push_ptr( &problem.eqn -> beta, "Hartree parameter" );
  my_file.push_ptr( &stress, "Shear stress at the wall" );
  my_file.header();
  // seek out the limit point in an ad hoc way
  double approx_limit_point = 0.0;
  do
  {
    double last_beta = problem.eqn -> beta;
    try
    {
      try
      {
        newton.arclength_solve( stress );
        //cout << problem.eqn -> beta << " " << stress[0] << "\n";
      }
      catch ( const std::runtime_error &error )
      {
        cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
        return 1;
      }
    }
    catch ( const ExceptionBifurcation &bifn )
    {
      cout << " Bifurcation detected between beta = " << last_beta
           << " and beta = " << problem.eqn -> beta << "\n";
      cout << " Continuing further.\n";
      newton.set_monitor_det( false );
      approx_limit_point = 0.5 * ( problem.eqn -> beta + last_beta );
    }
    my_file.update();
  }
  while ( problem.eqn -> beta  < -0.1 );
  if ( abs( approx_limit_point + 0.1988 ) > 0.0005 )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::Example::FS_residual::eqn, CppNoddy::TrackerFile::header(), CppNoddy::ArcLength_base< _Type >::init_arc(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::Newton< _Type >::set_monitor_det(), and CppNoddy::TrackerFile::update().
© 2012
R.E. Hewitt