CppNoddy: Tests/Arclength/ArcTranscritFold.cpp File Reference
ArcTranscritFold.cpp File Reference
Tests
Solve the nonlinear scalar residual problem.
#include <cassert>
#include <Newton_bundle.h>
Classes
class CppNoddy::Example::Arc_problem
Define the residual for arc-length continuation of a circle.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Functions
int main ()
Detailed Description
Solve the nonlinear scalar residual problem.
by arc-length continuation from the starting solution . There is a limit point and a transcritical bifurcation on the computed branch of solutions, both of which should be flagged through an exception being raised. The Example will fail if two bifurcations are not found.
Definition in file ArcTranscritFold.cpp.
Function Documentation
main()
int main ()
Definition at line 43 of file ArcTranscritFold.cpp.
{
  cout << "\n";
  cout << "=== ARC: Scalar continuation and bifn detection =====\n";
  cout << "\n";
  // Instantiate the problem
  Example::Arc_problem residual_problem;
  residual_problem.p = 0.0;
  residual_problem.eps = 0.0;
  const double tol = 1.e-10;
  // Scalar Newton iteration problem
  Newton<double> newton( &residual_problem, 8, tol );
  newton.set_monitor_det( true );
  // initial guess
  DenseVector<double> state( 1, 0.1 );
  // initialise a state for arc length cont.
  newton.init_arc( state, &residual_problem.p, 0.01, 0.5 );
  // output for the data
  std::string dirname("./DATA");
  mkdir( dirname.c_str(), S_IRWXU );
  TrackerFile my_file( "./DATA/Trans_Fold.dat" );
  my_file.push_ptr( &residual_problem.p, "parameter" );
  my_file.push_ptr( &state, "system state" );
  my_file.header();
  my_file.precision( 8 );
  unsigned n_bif( 0 );
  for ( int i = 0; i < 100; ++i )
  {
    try
    {
      try
      {
        newton.arclength_solve( state );
      }
      catch (const std::runtime_error &error )
      {
        cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
        return 1;
      }
    }
    catch (const ExceptionBifurcation &bifn )
    {
      cout << " Bifurcation detected near x = " << state[0] <<
           " p = " << residual_problem.p << "\n\n";
      ++n_bif;
    }
    my_file.update();
  }
  if ( n_bif != 2 )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::Example::Arc_problem::eps, CppNoddy::TrackerFile::header(), CppNoddy::ArcLength_base< _Type >::init_arc(), CppNoddy::Example::Arc_problem::p, CppNoddy::TrackerFile::precision(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::Newton< _Type >::set_monitor_det(), and CppNoddy::TrackerFile::update().
© 2012
R.E. Hewitt