CppNoddy: Tests/BVP/BermanShooting.cpp File Reference
BermanShooting.cpp File Reference
Tests
#include <IVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::Berman_equation
Define the Berman equation by inheriting Equation base class.
class CppNoddy::Example::Berman_residual
Define a residual function using the boundary conditions for the Berman equation.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Functions
int main ()
Detailed Description
Solving the fourth-order Berman (porous channel) similarity equation
where and is a pressure constant and is the Reynolds number based on the channel half-height and the wall suction. The boundary conditions are that and . This BVP is solved via Runge-Kutta and (vector) Newton iteration. This similarity form is an exact reduction of the Navier-Stokes equations.
Solving a BVP by converting it to an IVP like this is generally not a smart move!
Definition in file BermanShooting.cpp.
Function Documentation
main()
int main ()
Definition at line 100 of file BermanShooting.cpp.
 {
   cout << "\n";
   cout << "=== BVP_Shoot: vector Newton solution of Berman eqn =\n";
   cout << "\n";
   Example::Berman_residual problem;
   // instantiate a Vector Newton class for the Biharmonic
   Newton<double> Berman( &problem );
   DenseVector<double> guess( 2, 0.0 );
   guess[ 0 ] = -2.0;
   guess[ 1 ] = 1.0;
   try
   {
     Berman.iterate( guess );
   }
   catch ( const std::runtime_error &error )
   {
     cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
     return 1;
   }
   // output the data
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   TrackerFile my_file( "./DATA/Berman.dat" );
   my_file.push_ptr( &( problem.ode -> get_mesh() ) );
   my_file.update();
   // check against the known pressure constant K for Re=1.
   if ( std::abs( guess[ 1 ] - 0.70457 ) > 1.e-5 )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout.precision( 14 );
     cout << guess[ 0 ] << " " << guess[ 1 ] << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::Newton< _Type >::iterate(), CppNoddy::TrackerFile::push_ptr(), and CppNoddy::TrackerFile::update().
© 2012
R.E. Hewitt