CppNoddy: Tests/BVP/BVPBerman.cpp File Reference
BVPBerman.cpp File Reference
#include <BVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::Berman_equation
Define the Berman equation by inheriting Equation base class.
class CppNoddy::Example::Berman_left_BC
class CppNoddy::Example::Berman_right_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { f, fd, fdd, fddd }
Functions
int main ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
f
fd
fdd
fddd
Definition at line 15 of file BVPBerman.cpp.
 {f, fd, fdd, fddd };
Function Documentation
main()
int main ()
Definition at line 79 of file BVPBerman.cpp.
 {
   cout << "\n";
   cout << "=== BVP: finite-difference solution of Berman eqn ===\n";
   cout << "\n";
   Example::Berman_equation problem;
   Example::Berman_left_BC BC_left;
   Example::Berman_right_BC BC_right;
   // set the Reynolds number
   problem.Re = 1.0;
   // Reynolds number step
   double delta_Re = 0.1;
   // domain is -1 to 1
   double left = -1.0;
   double right = 1.0;
   // number of nodal points
   int N = 1401;
   // mesh
   DenseVector<double> nodes( Utility::uniform_node_vector( left, right, N ) );
   // Example tolerance
   const double tol = 1.e-4;
   // pass it to the ode
   ODE_BVP<double> ode( &problem, nodes, &BC_left, &BC_right );
   // our initial guess
   for ( int i = 0; i < N; ++i )
   {
     double y = ode.solution().coord( i );
     // set f(y)
     ode.solution()( i, f ) = 1.5 * ( y - y * y * y / 3 );
     // set f'(y)
     ode.solution()( i, fd ) = 1.5 * ( 1 - y * y );
     // set f''(y)
     ode.solution()( i, fdd ) = -3 * y;
     // set f''(y)
     ode.solution()( i, fddd ) = -3;
   }
   // zero-order continuation in Re
   do
   {
     // solve the problem using 2nd order finite-difference
     try
     {
       try
       {
         ode.solve2();
       }
       catch ( const std::runtime_error& error )
       {
         cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
         return 1;
       }
     }
     catch ( const ExceptionBifurcation& bifn )
     {
       cout << " Bifurcation detected between Re = " << problem.Re - delta_Re
            << " and Re = " << problem.Re << "\n";
       cout << " Continuing further.\n";
     }
     problem.Re += delta_Re;
   }
   while ( problem.Re < 10.0 + tol );
   // compare against the Shoot_Berman data at Re = 10
   // data to be compared is f''(y) at y = -1
   if ( std::abs( 5.99898 - ode.solution()( 0, fdd ) ) > tol )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << std::abs( 5.99898 - ode.solution()( 0, fdd ) ) << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References f, fd, fdd, fddd, CppNoddy::ODE_BVP< _Type, _Xtype >::solution(), CppNoddy::ODE_BVP< _Type, _Xtype >::solve2(), and CppNoddy::Utility::uniform_node_vector().
© 2012
R.E. Hewitt