CppNoddy: Tests/BVP/BVPKarmanArclength.cpp File Reference
BVPKarmanArclength.cpp File Reference
Tests
Arc-length continuation of the Karman rotating-disk equations for the flow above an infinite rotating disk:
#include <BVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::Karman_equations
Define the Karman equations.
class CppNoddy::Example::Karman_left_BC
Define the boundary conditions.
class CppNoddy::Example::Karman_right_BC
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Enumerations
enum {
U , Ud , V , W ,
Wd
}
Functions
int main ()
Variables
double CppNoddy::Example::s
relative rotation rate
Detailed Description
Arc-length continuation of the Karman rotating-disk equations for the flow above an infinite rotating disk:
with boundary conditions , and , . The class constructs and solves the global matrix problem using 2nd-order finite differences and employs arc-length continuation to obtain the first three solution branches in the neighbourhood of . The validation of the results is based upon the approximate location of the second limit point.
Definition in file BVPKarmanArclength.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
U
Ud
V
W
Wd
Definition at line 23 of file BVPKarmanArclength.cpp.
{U, Ud, V, W, Wd};
Function Documentation
main()
int main ()
Definition at line 92 of file BVPKarmanArclength.cpp.
{
  cout << "\n";
  cout << "=== BVP: Arc-length continuation of the Karman eqns =\n";
  cout << "\n";
  Example::Karman_equations problem;
  Example::Karman_left_BC BC_left;
  Example::Karman_right_BC BC_right;
  // Boundary layer is from 0 to 20
  double left = 0.0;
  //need a large domain for the higher branch modes
  double right = 150.0;
  Example::s = 1.0;
  // number of nodal points
  unsigned N = 2001;
  // use a non-uniform mesh
  DenseVector<double> nodes = Utility::power_node_vector( left, right, N, 1.2 );
  ODE_BVP<double> ode( &problem, nodes, &BC_left, &BC_right );
  // initial state is rigid-body rotation
  for ( unsigned i = 0; i < N; ++i )
  {
    ode.solution()( i, W ) = Example::s;
  }
  // output to check the adapted mesh
  std::string dirname("./DATA");
  mkdir( dirname.c_str(), S_IRWXU );
  TrackerFile my_file( "./DATA/BVP_Karman_arc.dat", 8 );
  my_file.push_ptr( &Example::s, "s" );
  my_file.push_ptr( &ode.solution()( N - 1, V ), "V_inf" );
  // initialise the arc-length routine
  double ds( -0.02 );
  ode.init_arc( &Example::s, ds, 0.01 );
  ode.rescale_theta() = true;
  ode.desired_arc_proportion() = 0.25;
  my_file.update();
  double last_approx_lp( 0.0 );
  // take 101 arc-length steps
  for ( int i = 0; i < 101; ++i )
  {
    try
    {
      ds = ode.arclength_solve( ds );
      cout << Example::s << " " << ode.solution()( N-1, V ) << "\n";
    }
    catch (const ExceptionBifurcation &error )
    {
      cout << " Bifurcation detected near p = " << Example::s << "\n";
      last_approx_lp = Example::s;
      break;
    }
    my_file.update();
  }
  if ( std::abs( last_approx_lp + 0.1605 ) > 1.e-3 )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    cout << " Difference = " << abs( last_approx_lp + 0.1605 ) << "\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::ODE_BVP< _Type, _Xtype >::arclength_solve(), CppNoddy::ArcLength_base< _Type >::desired_arc_proportion(), CppNoddy::ODE_BVP< _Type, _Xtype >::init_arc(), CppNoddy::Utility::power_node_vector(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::ArcLength_base< _Type >::rescale_theta(), CppNoddy::ODE_BVP< _Type, _Xtype >::solution(), CppNoddy::TrackerFile::update(), V, and W.
© 2012
R.E. Hewitt