CppNoddy: Tests/BVP/BVPKarmanJacobian.cpp File Reference
BVPKarmanJacobian.cpp File Reference
Tests
#include <BVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::Karman_equations
Define the Karman equations.
class CppNoddy::Example::Karman_left_BC
Define the boundary conditions.
class CppNoddy::Example::Karman_right_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum {
U, Ud, V, W,
Wd
}
Functions
int main ()
Detailed Description
Solving the Karman rotating-disk equations for the flow above an infinite rotating disk by applying a user-provided Jacobian
with boundary conditions , and , . The class constructs and solves the global matrix problem using 2nd-order finite differences.
Definition in file BVPKarmanJacobian.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
U
Ud
V
W
Wd
Definition at line 19 of file BVPKarmanJacobian.cpp.
 { U, Ud, V, W, Wd };
Function Documentation
main()
int main ()
Definition at line 99 of file BVPKarmanJacobian.cpp.
 {
   cout << "\n";
   cout << "=== BVP: Karman equations with analytic Jacobian ====\n";
   cout << "\n";
   Example::Karman_equations problem;
   Example::Karman_left_BC BC_left;
   Example::Karman_right_BC BC_right;
   // domain for the ODE problem
   double left = 0.0;
   double right = 20.0;
   // number of nodal points
   int N = 801;
   // mesh
   DenseVector<double> nodes( Utility::power_node_vector( left, right, N, 1.2 ) );
   // pass it to the ode
   ODE_BVP<double> ode( &problem, nodes, &BC_left, &BC_right );
   // set the solution to the initial guess
   for ( int i = 0; i < N; ++i )
   {
     double y = ode.solution().coord( i );
     ode.solution()( i, U ) = 0.0;
     ode.solution()( i, Ud ) = 0.0;
     ode.solution()( i, V ) = 0.0;
     ode.solution()( i, W ) = exp( -y );
     ode.solution()( i, Wd ) = -exp( -y );
   }
   try
   {
     ode.solve2();
   }
   catch ( const std::runtime_error &error )
   {
     cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
     return 1;
   }
   const double tol( 1.e-4 );
   // check the BL transpiration vs the known solution
   if ( abs( ode.solution()( N - 1, V ) + 0.88447 ) > tol )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << " Difference = " << abs( ode.solution()( N - 1, V ) + 0.88447 ) << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::Utility::power_node_vector(), CppNoddy::ODE_BVP< _Type, _Xtype >::solution(), CppNoddy::ODE_BVP< _Type, _Xtype >::solve2(), U, Ud, V, W, and Wd.
© 2012
R.E. Hewitt