CppNoddy: Tests/BVP/BVPTroesch.cpp File Reference
BVPTroesch.cpp File Reference
#include <BVP_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::Troesch_equation< _Type, _Xtype >
Define the harmonic equation by inheriting the Equation base class.
class CppNoddy::Example::Troesch_left_BC< _Type >
class CppNoddy::Example::Troesch_right_BC< _Type >
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { f, fd }
Functions
int main ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
f
fd
Definition at line 13 of file BVPTroesch.cpp.
 {f, fd };
Function Documentation
main()
int main ()
Definition at line 75 of file BVPTroesch.cpp.
 {
   cout << "\n";
   cout << "=== BVP: finite-difference solution of Troesch eqn ==\n";
   cout << "\n";
   Example::Troesch_equation<double, double> problem;
   Example::Troesch_left_BC <double> BC_left;
   Example::Troesch_right_BC<double> BC_right;
   double left =  0.0;
   double right = 1.0;
   // number of nodal points
   unsigned N = 151;
   // a real mesh -- along real axis
   DenseVector<double> nodes( Utility::uniform_node_vector( left, right, N ) );
   // Example tolerance
   const double tol = 1.e-4;
   // a real ODE BVP
   problem.c = 5.0;
   ODE_BVP<double> ode( &problem, nodes, &BC_left, &BC_right );
   // our initial guess
   for ( unsigned i = 0; i < N; ++i )
   {
     double y = ode.solution().coord( i );
     // set f(y)
     ode.solution()( i, f ) = y;
     // set f'(y)
     ode.solution()( i, fd ) = 1;
   }
   // solve the problem using 2nd order finite-difference
   try
   {
     ode.solve2();
   }
   catch (const std::runtime_error &error )
   {
     cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
     return 1;
   }
   // find deviation from y=0.5 solution obtianed from: http://www2.imperial.ac.uk/~jcash/BVP_software/readme.php
   const double diff = std::abs( ode.solution().get_interpolated_vars(0.5)[f] - 0.55437396E-01 );
   // validation test
   if ( diff > tol )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << "Real problem error " << diff << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References f, fd, CppNoddy::ODE_BVP< _Type, _Xtype >::solution(), CppNoddy::ODE_BVP< _Type, _Xtype >::solve2(), and CppNoddy::Utility::uniform_node_vector().
© 2012
R.E. Hewitt