CppNoddy: CppNoddy::Example::OS_bvp_equation Class Reference
CppNoddy::Example::OS_bvp_equation Class Reference
Define the OSE for the local refinement procedure.
Public Member Functions
OS_bvp_equation ()
The OS LOCAL problem is a nonlinear 5th order complex BVP because the eigenvalue is added to the 4th order equation.
void residual_fn (const DenseVector< D_complex > &z, DenseVector< D_complex > &g) const
The OS equation.
void matrix0 (const DenseVector< D_complex > &z, DenseMatrix< D_complex > &m) const
matrix to multiply the BVP coordinate
OS_bvp_equation ()
The OS local problem is a nonlinear 5th order complex BVP.
void residual_fn (const DenseVector< D_complex > &z, DenseVector< D_complex > &g) const
The OS equation.
void matrix0 (const DenseVector< D_complex > &z, DenseMatrix< D_complex > &m) const
matrix to multiply the BVP coordinate
Public Member Functions inherited from CppNoddy::Equation_1matrix< D_complex >
Equation_1matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_1matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< D_complex > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< D_complex > & matrix0 () const
Return a handle to the matrix.
virtual void get_jacobian_of_matrix0_mult_vector (const DenseVector< D_complex > &state, const DenseVector< D_complex > &vec, DenseMatrix< D_complex > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Residual_with_coords< _Type, _Xtype >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
_Xtype & coord (const unsigned &i)
General handle access to the coordinates.
const _Xtype & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< _Type >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Residual object for the current set of state variables.
const DenseVector< _Type > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< _Type > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
_Type & delta ()
const _Type & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< _Type > &state, DenseVector< _Type > &f) const
A blank virtual residual function method.
Additional Inherited Members
virtual void matrix0 (const DenseVector< D_complex > &x, DenseMatrix< D_complex > &m) const
Define the matrix in terms of the current state vector.
Protected Member Functions inherited from CppNoddy::Residual< _Type >
virtual void jacobian (const DenseVector< _Type > &state, DenseMatrix< _Type > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual_with_coords< _Type, _Xtype >
std::vector< _Xtype > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< _Type >
DenseMatrix< _Type > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< _Type > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< _Type > LAST_STATE
The last state vector.
_Type DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Define the OSE for the local refinement procedure.
Definition at line 83 of file EVPOrrSommerfeldEasy_lapack.cpp.
Constructor & Destructor Documentation
OS_bvp_equation() [1/2]
CppNoddy::Example::OS_bvp_equation::OS_bvp_equation () inline
The OS LOCAL problem is a nonlinear 5th order complex BVP because the eigenvalue is added to the 4th order equation.
Definition at line 88 of file EVPOrrSommerfeldEasy_lapack.cpp.
: Equation_1matrix<D_complex>(5) {}
OS_bvp_equation() [2/2]
CppNoddy::Example::OS_bvp_equation::OS_bvp_equation () inline
The OS local problem is a nonlinear 5th order complex BVP.
Definition at line 89 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
: Equation_1matrix<D_complex>(5) {}
Member Function Documentation
matrix0() [1/2]
void CppNoddy::Example::OS_bvp_equation::matrix0 (const DenseVector< D_complex > & z, DenseMatrix< D_complex > & m) const inline virtual
matrix to multiply the BVP coordinate
Reimplemented from CppNoddy::Equation_1matrix< D_complex >.
Definition at line 104 of file EVPOrrSommerfeldEasy_lapack.cpp.
      {
        Utils_Fill::fill_identity(m);
      }
References Utils_Fill::fill_identity(), and m.
matrix0() [2/2]
void CppNoddy::Example::OS_bvp_equation::matrix0 (const DenseVector< D_complex > & z, DenseMatrix< D_complex > & m) const inline virtual
matrix to multiply the BVP coordinate
Reimplemented from CppNoddy::Equation_1matrix< D_complex >.
Definition at line 105 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        Utils_Fill::fill_identity(m);
      }
References Utils_Fill::fill_identity(), and m.
residual_fn() [1/2]
void CppNoddy::Example::OS_bvp_equation::residual_fn (const DenseVector< D_complex > & z, DenseVector< D_complex > & g) const inline
The OS equation.
Definition at line 91 of file EVPOrrSommerfeldEasy_lapack.cpp.
      {
        // define the equation as 5 1st order equations
        g[ phi ] = z[ phid ];
        g[ phid ] = z[ psi ] + alpha * alpha * z[ phi ];
        g[ psi ] = z[ psid ];
        g[ psid ] = alpha * alpha * z[ psi ]
                    + D_complex( 0.0, 1.0 ) * alpha * Re * ( U( coord(0) ) * z[ psi ] - Udd( coord(0) ) * z[ phi ] )
                    - D_complex( 0.0, 1.0 ) * alpha * Re * z[ eval ] * z[ psi ];
        g[ eval ] = 0.0;
      }
References CppNoddy::Example::alpha, CppNoddy::Residual_with_coords< _Type, _Xtype >::coord(), eval, CppNoddy::Example::g(), phi, phid, psi, psid, CppNoddy::Example::Re, U, CppNoddy::Example::Udd(), and CppNoddy::Example::z().
residual_fn() [2/2]
void CppNoddy::Example::OS_bvp_equation::residual_fn (const DenseVector< D_complex > & z, DenseVector< D_complex > & g) const inline
The OS equation.
Definition at line 92 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        // define the equation as 5 1st order equations
        g[ phi ] = z[ phid ];
        g[ phid ] = z[ psi ] + alpha * alpha * z[ phi ];
        g[ psi ] = z[ psid ];
        g[ psid ] = alpha * alpha * z[ psi ]
                    + D_complex( 0.0, 1.0 ) * alpha * Re * ( U( coord(0) ) * z[ psi ] - Udd( coord(0) ) * z[ phi ] )
                    - D_complex( 0.0, 1.0 ) * alpha * Re * z[ eval ] * z[ psi ];
        g[ eval ] = 0.0;
      }
References CppNoddy::Example::alpha, CppNoddy::Residual_with_coords< _Type, _Xtype >::coord(), eval, CppNoddy::Example::g(), phi, phid, psi, psid, CppNoddy::Example::Re, U, CppNoddy::Example::Udd(), and CppNoddy::Example::z().
The documentation for this class was generated from the following files:
Tests/EVP/EVPOrrSommerfeldEasy_lapack.cpp
Tests/EVP/EVPOrrSommerfeldNeutralCurve_lapack.cpp
© 2012
R.E. Hewitt