CppNoddy: CppNoddy::Example::Nlin_adv_equation Class Reference
CppNoddy::Example::Nlin_adv_equation Class Reference
Public Member Functions
Nlin_adv_equation ()
The problem is 2nd order and real.
void residual_fn (const DenseVector< double > &z, DenseVector< double > &f) const
Define a nonlinear advection diffusion problem.
void matrix0 (const DenseVector< double > &z, DenseMatrix< double > &m) const
Define the derivative terms by providing the mass matrix – identity in this case.
void get_jacobian_of_matrix0_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
void matrix1 (const DenseVector< double > &z, DenseMatrix< double > &m) const
Define the unsteady terms by providing the mass matrix.
void get_jacobian_of_matrix1_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Equation_2matrix< double >
Equation_2matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_2matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix1 () const
Return a handle to the matrix member data.
Public Member Functions inherited from CppNoddy::Equation_1matrix< double, double >
Equation_1matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_1matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix0 () const
Return a handle to the matrix.
Public Member Functions inherited from CppNoddy::Residual_with_coords< double, double >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
double & coord (const unsigned &i)
General handle access to the coordinates.
const double & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< double >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Residual object for the current set of state variables.
const DenseVector< double > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< double > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
double & delta ()
const double & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
Additional Inherited Members
Protected Member Functions inherited from CppNoddy::Residual< double >
virtual void jacobian (const DenseVector< double > &state, DenseMatrix< double > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual_with_coords< double, double >
std::vector< double > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< double >
DenseMatrix< double > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< double > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< double > LAST_STATE
The last state vector.
double DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Definition at line 38 of file IBVPNonlinearAdvDiffusion.cpp.
Constructor & Destructor Documentation
Nlin_adv_equation()
CppNoddy::Example::Nlin_adv_equation::Nlin_adv_equation () inline
The problem is 2nd order and real.
Definition at line 43 of file IBVPNonlinearAdvDiffusion.cpp.
 : Equation_2matrix<double> ( 2 ) {}
Member Function Documentation
get_jacobian_of_matrix0_mult_vector()
void CppNoddy::Example::Nlin_adv_equation::get_jacobian_of_matrix0_mult_vector (const DenseVector< double > & state, const DenseVector< double > & vec, DenseMatrix< double > & h) const inline virtual
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
The user should overload this if concerned about performance of the solver. If not overloaded, the default is to finite difference the Jacobian-of-the-matrix.
Parameters
state The current state variables – used for clarity when overloaded by the user instead of expecting the user to access the member data.
vec The vector that will be multiplied by the Jacobian-of-the-matrix
h The resulting 2D matrix
constant mass matrix, so we'll overlload this as empty to speed things up
Reimplemented from CppNoddy::Equation_1matrix< double, double >.
Definition at line 59 of file IBVPNonlinearAdvDiffusion.cpp.
       {
         /// constant mass matrix, so we'll overlload this as empty to speed things up
       }
get_jacobian_of_matrix1_mult_vector()
void CppNoddy::Example::Nlin_adv_equation::get_jacobian_of_matrix1_mult_vector (const DenseVector< double > & state, const DenseVector< double > & vec, DenseMatrix< double > & h) const inline virtual
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
The user should overload this if concerned about performance of the solver. If not overloaded, the default is to finite difference the Jacobian-of-the-matrix.
Parameters
state The current state variables – used for clarity when overloaded by the user instead of expecting the user to access the member data.
vec The vector that will be multiplied by the Jacobian-of-the-matrix
h The resulting 2D matrix
Reimplemented from CppNoddy::Equation_2matrix< double >.
Definition at line 70 of file IBVPNonlinearAdvDiffusion.cpp.
       {
         h( 1, U ) = - Re * vec[ 0 ];
       }
References h, CppNoddy::Example::Re, and CppNoddy::Example::U().
matrix0()
void CppNoddy::Example::Nlin_adv_equation::matrix0 (const DenseVector< double > & z, DenseMatrix< double > & m) const inline virtual
Define the derivative terms by providing the mass matrix – identity in this case.
Reimplemented from CppNoddy::Equation_1matrix< double, double >.
Definition at line 54 of file IBVPNonlinearAdvDiffusion.cpp.
       {
         m(0,0)=1;m(1,1)=1;
       }
References m.
matrix1()
void CppNoddy::Example::Nlin_adv_equation::matrix1 (const DenseVector< double > & z, DenseMatrix< double > & m) const inline virtual
Define the unsteady terms by providing the mass matrix.
Reimplemented from CppNoddy::Equation_2matrix< double >.
Definition at line 65 of file IBVPNonlinearAdvDiffusion.cpp.
       {
         m( 1, 0 ) = - Re * z[ U ];
       }
References m, CppNoddy::Example::Re, CppNoddy::Example::U(), and CppNoddy::Example::z().
residual_fn()
void CppNoddy::Example::Nlin_adv_equation::residual_fn (const DenseVector< double > & z, DenseVector< double > & f) const inline virtual
Define a nonlinear advection diffusion problem.
Reimplemented from CppNoddy::Residual< double >.
Definition at line 46 of file IBVPNonlinearAdvDiffusion.cpp.
       {
         // The system
         f[ U ] = z[ Ud ];
         f[ Ud ] = source( coord(0), coord(1) );
       }
References CppNoddy::Residual_with_coords< double, double >::coord(), f, CppNoddy::Example::source(), CppNoddy::Example::U(), Ud, and CppNoddy::Example::z().
The documentation for this class was generated from the following file:
Tests/IBVP/IBVPNonlinearAdvDiffusion.cpp
© 2012
R.E. Hewitt