CppNoddy: CppNoddy::Example::NlinAdv Class Reference
CppNoddy::Example::NlinAdv Class Reference
Define the system.
Public Member Functions
NlinAdv ()
One dimemsional inviscid Burgers problem.
void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
Define the vector flux.
double max_charac_speed (const DenseVector< double > &q) const
Bound the shock speed.
std::vector< bool > edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t) const
Define the edge boundary conditions.
NlinAdv ()
Two dimemsional scalar linear advection problem.
void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
Bound the wave speed.
NlinAdv ()
void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
Bound the wave speed.
std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
edge conditions
NlinAdv ()
One dimemsional inviscid Burgers problem.
void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
Define the vector flux.
void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
Bound the wave speed.
std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
Define the edge boundary conditions.
NlinAdv ()
One dimemsional inviscid Burgers problem.
void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
Bound the wave speed.
std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
Define the edge boundary conditions.
Public Member Functions inherited from CppNoddy::OneD_Hyperbolic_System
OneD_Hyperbolic_System (const unsigned &order)
virtual ~OneD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function.
virtual void Jac_flux_fn (const double &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the flux function.
virtual double max_charac_speed (const DenseVector< double > &q) const
A virtual method that is used to bound the shock speed and must be implemented by the user.
virtual bool_vec edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t=0.0) const
Define the edge boundary conditions.
virtual void source_fn (const double &x, const DenseVector< double > &q, const DenseVector< double > &slope, DenseVector< double > &r) const
unsigned get_order ()
Public Member Functions inherited from CppNoddy::TwoD_Hyperbolic_System
TwoD_Hyperbolic_System (const unsigned &order)
virtual ~TwoD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
virtual void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
virtual void Jac_flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the x-flux function.
virtual void Jac_flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the y-flux function.
virtual void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
A virtual method that is used to bound the characteristic speed in both directions.
virtual std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
Define the edge boundary conditions.
virtual void edge_slopes (const int &face_index, const DenseVector< double > &x, DenseVector< double > &sigma_n) const
Define the edge boundary condition slopes.
virtual void source_fn (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &r) const
unsigned get_order ()
Additional Inherited Members
Protected Attributes inherited from CppNoddy::OneD_Hyperbolic_System
const std::size_t ORDER_OF_SYSTEM
The order of the system of equations.
Protected Attributes inherited from CppNoddy::TwoD_Hyperbolic_System
const unsigned ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
Define the system.
Definition at line 17 of file HYPNonlinearAdvection.cpp.
Constructor & Destructor Documentation
NlinAdv() [1/5]
CppNoddy::Example::NlinAdv::NlinAdv () inline
One dimemsional inviscid Burgers problem.
Definition at line 23 of file HYPNonlinearAdvection.cpp.
                : OneD_Hyperbolic_System( 1 )
      {}
NlinAdv() [2/5]
CppNoddy::Example::NlinAdv::NlinAdv () inline
Two dimemsional scalar linear advection problem.
Definition at line 23 of file HYP2DLinearAdvectionXY.cpp.
                : TwoD_Hyperbolic_System( 1 )
      {}
NlinAdv() [3/5]
CppNoddy::Example::NlinAdv::NlinAdv () inline
Definition at line 22 of file HYP2DNonlinearAdvectionX.cpp.
                : TwoD_Hyperbolic_System( 1 )
      {}
NlinAdv() [4/5]
CppNoddy::Example::NlinAdv::NlinAdv () inline
One dimemsional inviscid Burgers problem.
Definition at line 22 of file HYP2DNonlinearAdvectionXY.cpp.
                : TwoD_Hyperbolic_System( 1 )
      {}
NlinAdv() [5/5]
CppNoddy::Example::NlinAdv::NlinAdv () inline
One dimemsional inviscid Burgers problem.
Definition at line 23 of file HYP2DNonlinearAdvectionY.cpp.
                : TwoD_Hyperbolic_System( 1 )
      {}
Member Function Documentation
edge_values() [1/4]
std::vector< bool > CppNoddy::Example::NlinAdv::edge_values (const int & face_index, const DenseVector< double > & x, DenseVector< double > & q) const inline virtual
edge conditions
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 44 of file HYP2DNonlinearAdvectionX.cpp.
      {
        std::vector<bool> inflow( q.size(), false );
        // x doesn't matter since the conditions are fixed
        if ( face_index == 1 )
        {
          q[ 0 ] = 0.0;
          inflow[ 0 ] = true;
        }
        if ( face_index == 3 )
        {
          q[ 0 ] = 0.0;
          inflow[ 0 ] = true;
        }
        return inflow;
      }
References CppNoddy::DenseVector< _Type >::size().
edge_values() [2/4]
std::vector< bool > CppNoddy::Example::NlinAdv::edge_values (const int & face_index, const DenseVector< double > & x, DenseVector< double > & q) const inline virtual
Define the edge boundary conditions.
Parameters
face_index An index for the face: 0,1,2,3 for S,E,N,W on the TwoD_TVDLF_Mesh
x The global position vector
q Specify the unknowns specified along the face
Returns
A vector that defines which components have been set as inflow
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 44 of file HYP2DNonlinearAdvectionXY.cpp.
      {
        std::vector<bool> inflow( q.size(), true );
        q[ 0 ] = 0;
        return inflow;
      }
References CppNoddy::DenseVector< _Type >::size().
edge_values() [3/4]
std::vector< bool > CppNoddy::Example::NlinAdv::edge_values (const int & face_index, const DenseVector< double > & x, DenseVector< double > & q) const inline virtual
Define the edge boundary conditions.
Parameters
face_index An index for the face: 0,1,2,3 for S,E,N,W on the TwoD_TVDLF_Mesh
x The global position vector
q Specify the unknowns specified along the face
Returns
A vector that defines which components have been set as inflow
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 45 of file HYP2DNonlinearAdvectionY.cpp.
      {
        std::vector<bool> inflow( q.size(), false );
        // x doesn't matter since the conditions are fixed
        if ( face_index == 1 )
        {
          q[ 0 ] = 0.0;
          inflow[ 0 ] = true;
        }
        if ( face_index == 3 )
        {
          q[ 0 ] = 0.0;
          inflow[ 0 ] = true;
        }
        return inflow;
      }
References CppNoddy::DenseVector< _Type >::size().
edge_values() [4/4]
std::vector< bool > CppNoddy::Example::NlinAdv::edge_values (const int face_index, const double & x, DenseVector< double > & q, const double & t) const inline virtual
Define the edge boundary conditions.
Parameters
face_index An index for the face: -1=left +1=right for OneD_TVDLF_Mesh
x The position vector along the face
q The unknowns specified along the face
t A time for unsteady edge conditions
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 40 of file HYPNonlinearAdvection.cpp.
      {
        std::vector<bool> inflow( q.size(), false );
        // x doesn't matter since the conditions are fixed
        if ( face_index == -1 )
        {
          q[ 0 ] = 0.0;
          inflow[ 0 ] = true;
        }
        if ( face_index == 1 )
        {
          q[ 0 ] = 0.0;
          inflow[ 0 ] = true;
        }
        return inflow;
      }
References CppNoddy::DenseVector< _Type >::size().
flux_fn()
void CppNoddy::Example::NlinAdv::flux_fn (const double & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
Define the vector flux.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 27 of file HYPNonlinearAdvection.cpp.
      {
        f[ 0 ] = q[ 0 ] * q[ 0 ] / 2;
      }
References f.
flux_fn_x() [1/4]
void CppNoddy::Example::NlinAdv::flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the x-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 26 of file HYP2DLinearAdvectionXY.cpp.
      {
        f[ 0 ] = q[ 0 ] / sqrt( 2. );
      }
References f.
flux_fn_x() [2/4]
void CppNoddy::Example::NlinAdv::flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the x-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 25 of file HYP2DNonlinearAdvectionX.cpp.
      {
        f[ 0 ] = q[ 0 ] * q[ 0 ] / 2;
      }
References f.
flux_fn_x() [3/4]
void CppNoddy::Example::NlinAdv::flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the x-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 31 of file HYP2DNonlinearAdvectionXY.cpp.
      {
        f[ 0 ] = sqrt( 2. ) * q[ 0 ] * q[ 0 ] / 2;
      }
References f.
flux_fn_x() [4/4]
void CppNoddy::Example::NlinAdv::flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the x-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 26 of file HYP2DNonlinearAdvectionY.cpp.
      {
        f[ 0 ] = 0;
      }
References f.
flux_fn_y() [1/4]
void CppNoddy::Example::NlinAdv::flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the y-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 31 of file HYP2DLinearAdvectionXY.cpp.
      {
        f[ 0 ] = q[ 0 ] / sqrt( 2. );
      }
References f.
flux_fn_y() [2/4]
void CppNoddy::Example::NlinAdv::flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the y-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 30 of file HYP2DNonlinearAdvectionX.cpp.
      {
        f[ 0 ] = 0;
      }
References f.
flux_fn_y() [3/4]
void CppNoddy::Example::NlinAdv::flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
Define the vector flux.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 26 of file HYP2DNonlinearAdvectionXY.cpp.
      {
        f[ 0 ] = sqrt( 2. ) * q[ 0 ] * q[ 0 ] / 2;
      }
References f.
flux_fn_y() [4/4]
void CppNoddy::Example::NlinAdv::flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the y-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 31 of file HYP2DNonlinearAdvectionY.cpp.
      {
        f[ 0 ] = q[ 0 ] * q[ 0 ] / 2;
      }
References f.
max_charac_speed() [1/5]
double CppNoddy::Example::NlinAdv::max_charac_speed (const DenseVector< double > & q) const inline virtual
Bound the shock speed.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 33 of file HYPNonlinearAdvection.cpp.
      {
        // maximum shock speed
        return std::abs( q[ 0 ] );
      }
max_charac_speed() [2/5]
void CppNoddy::Example::NlinAdv::max_charac_speed (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & c) const inline virtual
Bound the wave speed.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 37 of file HYP2DLinearAdvectionXY.cpp.
      {
        // maximum wave speed
        c[ 0 ] = c[ 1 ] = 1.0;
      }
max_charac_speed() [3/5]
void CppNoddy::Example::NlinAdv::max_charac_speed (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & c) const inline virtual
Bound the wave speed.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 36 of file HYP2DNonlinearAdvectionX.cpp.
      {
        // maximum wave speed
        c[ 0 ] = std::abs( q[ 0 ] );
        c[ 1 ] = std::abs( q[ 0 ] );
      }
max_charac_speed() [4/5]
void CppNoddy::Example::NlinAdv::max_charac_speed (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & c) const inline virtual
Bound the wave speed.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 37 of file HYP2DNonlinearAdvectionXY.cpp.
      {
        // maximum wave speed
        c[ 0 ] = c[ 1 ] = std::abs( q[ 0 ] );
      }
max_charac_speed() [5/5]
void CppNoddy::Example::NlinAdv::max_charac_speed (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & c) const inline virtual
Bound the wave speed.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 38 of file HYP2DNonlinearAdvectionY.cpp.
      {
        // maximum wave speed
        c[ 0 ] = c[ 1 ] = std::abs( q[ 0 ] );
      }
The documentation for this class was generated from the following files:
Tests/HYP_1D/HYPNonlinearAdvection.cpp
Tests/HYP_2D/HYP2DLinearAdvectionXY.cpp
Tests/HYP_2D/HYP2DNonlinearAdvectionX.cpp
Tests/HYP_2D/HYP2DNonlinearAdvectionXY.cpp
Tests/HYP_2D/HYP2DNonlinearAdvectionY.cpp
© 2012
R.E. Hewitt