CppNoddy: CppNoddy::TwoD_Hyperbolic_System Class Reference
CppNoddy::TwoD_Hyperbolic_System Class Reference
A class to represent a two-dimensional hyperbolic system of equations.
#include <TwoD_Hyperbolic_System.h>
Public Member Functions
TwoD_Hyperbolic_System (const unsigned &order)
virtual ~TwoD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
virtual void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
virtual void Jac_flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the x-flux function.
virtual void Jac_flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the y-flux function.
virtual void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
A virtual method that is used to bound the characteristic speed in both directions.
virtual std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
Define the edge boundary conditions.
virtual void edge_slopes (const int &face_index, const DenseVector< double > &x, DenseVector< double > &sigma_n) const
Define the edge boundary condition slopes.
virtual void source_fn (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &r) const
unsigned get_order ()
Protected Attributes
const unsigned ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
A class to represent a two-dimensional hyperbolic system of equations.
Definition at line 12 of file TwoD_Hyperbolic_System.h.
Constructor & Destructor Documentation
TwoD_Hyperbolic_System()
CppNoddy::TwoD_Hyperbolic_System::TwoD_Hyperbolic_System (const unsigned & order) inline explicit
Parameters
order The order of the hyperbolic system
Definition at line 17 of file TwoD_Hyperbolic_System.h.
                                                            : ORDER_OF_SYSTEM(order)
     {}
~TwoD_Hyperbolic_System()
virtual CppNoddy::TwoD_Hyperbolic_System::~TwoD_Hyperbolic_System () inline virtual
An empty destructor, virtual since we have virtual methods.
Definition at line 21 of file TwoD_Hyperbolic_System.h.
     {}
Member Function Documentation
edge_slopes()
virtual void CppNoddy::TwoD_Hyperbolic_System::edge_slopes (const int & face_index, const DenseVector< double > & x, DenseVector< double > & sigma_n) const inline virtual
Define the edge boundary condition slopes.
These default to zero unless otherwise over-ridden.
Parameters
face_index An index for the face: 0,1,2,3 for S,E,N,W on the TwoD_TVDLF_Mesh
x The global position vector
sigma_n Specify the slope normal to the face
Definition at line 124 of file TwoD_Hyperbolic_System.h.
{
     }
edge_values()
virtual std::vector<bool> CppNoddy::TwoD_Hyperbolic_System::edge_values (const int & face_index, const DenseVector< double > & x, DenseVector< double > & q) const inline virtual
Define the edge boundary conditions.
Parameters
face_index An index for the face: 0,1,2,3 for S,E,N,W on the TwoD_TVDLF_Mesh
x The global position vector
q Specify the unknowns specified along the face
Returns
A vector that defines which components have been set as inflow
Reimplemented in CppNoddy::Example::Shallow_2d_source.
Definition at line 114 of file TwoD_Hyperbolic_System.h.
{
       return std::vector<bool>(ORDER_OF_SYSTEM, false);
     }
References ORDER_OF_SYSTEM.
flux_fn_x()
virtual void CppNoddy::TwoD_Hyperbolic_System::flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the x-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented in CppNoddy::Example::Shallow_2d_source, and CppNoddy::Example::Shallow_2d_rad.
Definition at line 28 of file TwoD_Hyperbolic_System.h.
{
       std::string problem;
       problem = "The Hyperbolic_Conservative_System::flux_fn_x method has not been implemented.\n";
       problem += "You have to implement this method to define the system.\n";
       throw ExceptionRuntime(problem);
     }
Referenced by Jac_flux_fn_x().
flux_fn_y()
virtual void CppNoddy::TwoD_Hyperbolic_System::flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the y-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented in CppNoddy::Example::Shallow_2d_source, and CppNoddy::Example::Shallow_2d_rad.
Definition at line 39 of file TwoD_Hyperbolic_System.h.
{
       std::string problem;
       problem = "The Hyperbolic_Conservative_System::flux_fn_y method has not been implemented.\n";
       problem += "You have to implement this method to define the system.\n";
       throw ExceptionRuntime(problem);
     }
Referenced by Jac_flux_fn_y().
get_order()
unsigned CppNoddy::TwoD_Hyperbolic_System::get_order () inline
Definition at line 130 of file TwoD_Hyperbolic_System.h.
{
       return ORDER_OF_SYSTEM;
     }
References ORDER_OF_SYSTEM.
Jac_flux_fn_x()
virtual void CppNoddy::TwoD_Hyperbolic_System::Jac_flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseMatrix< double > & J) const inline virtual
A virtual function function to define the Jacobian of the x-flux function.
The default method uses first-order finite differencing to compute the Jacobian if not otherwise specified by the user.
Parameters
x The vector position
q The unknowns
J The Jacobian of the flux function
cheap & nasty differencing
Reimplemented in CppNoddy::Example::Shallow_2d_source, and CppNoddy::Example::Shallow_2d_rad.
Definition at line 53 of file TwoD_Hyperbolic_System.h.
{
       /// cheap & nasty differencing
       const double delta(1.e-8);
       DenseVector<double> state(q);
       DenseVector<double> temp1(ORDER_OF_SYSTEM, 0.0);
       DenseVector<double> temp2(ORDER_OF_SYSTEM, 0.0);
       flux_fn_x(x, state, temp1);
       // default is to FD the Jacobian
       for(std::size_t i = 0; i < ORDER_OF_SYSTEM; ++i) {
         state[ i ] += delta;
         flux_fn_x(x, state, temp2);
         state[ i ] -= delta;
         J.set_col(i, (temp2 - temp1) / delta);
       }
     }
References flux_fn_x(), ORDER_OF_SYSTEM, and CppNoddy::DenseMatrix< _Type >::set_col().
Jac_flux_fn_y()
virtual void CppNoddy::TwoD_Hyperbolic_System::Jac_flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseMatrix< double > & J) const inline virtual
A virtual function function to define the Jacobian of the y-flux function.
The default method uses first-order finite differencing to compute the Jacobian if not otherwise specified by the user.
Parameters
x The vector position
q The unknowns
J The Jacobian of the flux function
cheap & nasty differencing
Reimplemented in CppNoddy::Example::Shallow_2d_source, and CppNoddy::Example::Shallow_2d_rad.
Definition at line 76 of file TwoD_Hyperbolic_System.h.
{
       /// cheap & nasty differencing
       const double delta(1.e-8);
       DenseVector<double> state(q);
       DenseVector<double> temp1(ORDER_OF_SYSTEM, 0.0);
       DenseVector<double> temp2(ORDER_OF_SYSTEM, 0.0);
       flux_fn_y(x, state, temp1);
       // default is to FD the Jacobian
       for(std::size_t i = 0; i < ORDER_OF_SYSTEM; ++i) {
         state[ i ] += delta;
         flux_fn_y(x, state, temp2);
         state[ i ] -= delta;
         J.set_col(i, (temp2 - temp1) / delta);
       }
     }
References flux_fn_y(), ORDER_OF_SYSTEM, and CppNoddy::DenseMatrix< _Type >::set_col().
max_charac_speed()
virtual void CppNoddy::TwoD_Hyperbolic_System::max_charac_speed (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & c) const inline virtual
A virtual method that is used to bound the characteristic speed in both directions.
It determines the time step in order that the CFL constraint holds. It is sometimes required to specify a speed that is a function of position and to even specify the two-directional speeds. eg. your mesh may actually be w.r.t. a polar coordinate system in which the physical mesh size grows linearly with radius, so one of the speeds should be scaled accordingly.
Parameters
x The global coordinate
q The unknowns
c The speed
Reimplemented in CppNoddy::Example::Shallow_2d_source, and CppNoddy::Example::Shallow_2d_rad.
Definition at line 101 of file TwoD_Hyperbolic_System.h.
{
       std::string problem;
       problem = "The Hyperbolic_Conservative_System::max_charac_speed method has not\n";
       problem += "been implemented. You have to implement this method to define the system.\n";
       throw ExceptionRuntime(problem);
     }
source_fn()
virtual void CppNoddy::TwoD_Hyperbolic_System::source_fn (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & r) const inline virtual
Reimplemented in CppNoddy::Example::Shallow_2d_source.
Definition at line 127 of file TwoD_Hyperbolic_System.h.
{
     }
Member Data Documentation
ORDER_OF_SYSTEM
const unsigned CppNoddy::TwoD_Hyperbolic_System::ORDER_OF_SYSTEM protected
The order of the system of equations.
Definition at line 137 of file TwoD_Hyperbolic_System.h.
Referenced by edge_values(), get_order(), Jac_flux_fn_x(), and Jac_flux_fn_y().
The documentation for this class was generated from the following file:
include/TwoD_Hyperbolic_System.h
© 2012
R.E. Hewitt