CppNoddy: CppNoddy::TwoD_Node_Mesh< _Type > Class Template Reference
CppNoddy::TwoD_Node_Mesh< _Type > Class Template Reference
A two dimensional mesh utility object.
#include <TwoD_Node_Mesh.h>
Public Member Functions
TwoD_Node_Mesh ()
TwoD_Node_Mesh (const DenseVector< double > &x_nodes, const DenseVector< double > &y_nodes, const std::size_t nvars)
ctor
TwoD_Node_Mesh (const double left, const double right, const double bottom, const double top, const std::size_t nx, const std::size_t ny, const std::size_t nvars)
ctor
TwoD_Node_Mesh (std::string filename, const std::size_t nx, const std::size_t ny, const std::size_t nv)
virtual ~TwoD_Node_Mesh ()
dtor
DenseVector< _Type > operator() (const std::size_t nodex, const std::size_t nodey)
Access operator for a nodal point that returns a vector.
_Type & operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var)
Access operator for a nodal point/variable in the mesh.
const _Type & operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) const
Const access operator for a nodal point/variable in the mesh.
std::pair< double, double > coord (const std::size_t nodex, const std::size_t nodey) const
Access the nodal position - as a pair.
double & xcoord (const std::size_t nodex)
Access the x-nodal (first index) position.
double & ycoord (const std::size_t nodey)
Access the y-nodal (second index) position.
void set_nodes_vars (const std::size_t nodex, const std::size_t nodey, const DenseVector< _Type > &U)
Set the variables stored at A SPECIFIED node.
DenseVector< _Type > get_nodes_vars (const std::size_t nodex, const std::size_t nodey) const
Get the variables stored at A SPECIFIED node – equivalent to mesh(nodex,nodey).
OneD_Node_Mesh< _Type > get_xsection_at_xnode (const std::size_t nodex) const
Get a cross section of the 2D mesh at a specified (constant) x node.
OneD_Node_Mesh< _Type > get_xsection_at_ynode (const std::size_t nodey) const
Get a cross section of the 2D mesh at a specified (constant) y node.
OneD_Node_Mesh< _Type > get_xsection_at_x1 (const double x) const
Get a cross section of the 2D mesh at a specified (constant) x node.
void assign (const _Type elt)
Assign an element to all entries in the mesh.
std::pair< std::size_t, std::size_t > get_nnodes () const
Get the number of nodes in the two directions of the 2D mesh.
std::size_t get_nvars () const
Get the number of variables that are stored at each node.
const DenseVector< double > & xnodes () const
Access the vector of x-nodal positions.
const DenseVector< double > & ynodes () const
Access the vector of y-nodal positions.
DenseMatrix< _Type > get_var_as_matrix (std::size_t var) const
Return a matrix corresponding to each nodal point in the mesh Each matrix element will contain a specified variable number.
void remesh1 (const DenseVector< double > &newX, const DenseVector< double > &newY)
Interpolate this mesh data (bilinearly) into a new mesh with nodal points defined in the argument list.
void dump () const
A simple method for dumping data to std::cout.
void dump (std::string filename) const
A simple method for dumping data to a file.
void dump_var (std::string filename, const unsigned var) const
A simple method for dumping a single variable to a file with no nodal information.
void read (std::string filename, const bool reset=false)
A simple method for reading data from a file.
void dump_gnu (std::string filename) const
A simple method for dumping data to a file for gnuplot surface plotting.
void normalise (const std::size_t &var)
Normalise all data in the mesh based on one variable.
void scale (const _Type &value)
Calls the vector "scale" method for the whole mesh data.
void normalise_real_part (const std::size_t &var)
Normalise the mesh such that the real part of variable 'var' has a real part of unity, and is then the largest real part across the whole mesh.
double max_abs_real_part (unsigned var)
Find the maximum stored absolute value in the mesh for a given variable – no interpolation is used.
double max_abs (unsigned var)
Find the maximum stored absolute value in the mesh for a given variable – no interpolation is used.
DenseVector< _Type > get_interpolated_vars (const double &x, const double &y)
Get a bilinearly interpolated value at a specified point.
void normalise (const std::size_t &var)
void normalise (const std::size_t &var)
double max_abs_real_part (unsigned var)
double max_abs_real_part (unsigned var)
void dump_gnu (std::string filename) const
void dump_gnu (std::string filename) const
void read (std::string filename, bool reset)
void read (std::string filename, bool reset)
Protected Attributes
std::size_t m_nx
std::size_t m_ny
std::size_t m_nv
DenseVector< double > m_X
DenseVector< double > m_Y
DenseVector< _Type > m_vars
Detailed Description
template<typename _Type>
class CppNoddy::TwoD_Node_Mesh< _Type >
A two dimensional mesh utility object.
Definition at line 19 of file TwoD_Node_Mesh.h.
Constructor & Destructor Documentation
TwoD_Node_Mesh() [1/4]
template<typename _Type > CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh () inline
Definition at line 22 of file TwoD_Node_Mesh.h.
     {}
TwoD_Node_Mesh() [2/4]
template<typename _Type > CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh (const DenseVector< double > & x_nodes, const DenseVector< double > & y_nodes, const std::size_t nvars) inline
ctor
Definition at line 26 of file TwoD_Node_Mesh.h.
                                           :
       m_nx(x_nodes.size()), m_ny(y_nodes.size()), m_nv(nvars), m_X(x_nodes), m_Y(y_nodes) {
       // we'll store the data as ( x, y, v ) ->  x * ny * nv + y * nv + v
       m_vars = DenseVector<_Type>(m_nx * m_ny * m_nv, 0.0);
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_nv, CppNoddy::TwoD_Node_Mesh< _Type >::m_nx, CppNoddy::TwoD_Node_Mesh< _Type >::m_ny, and CppNoddy::TwoD_Node_Mesh< _Type >::m_vars.
TwoD_Node_Mesh() [3/4]
template<typename _Type > CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh (const double left, const double right, const double bottom, const double top, const std::size_t nx, const std::size_t ny, const std::size_t nvars) inline
ctor
Definition at line 34 of file TwoD_Node_Mesh.h.
                                                                                   :
       m_nx(nx), m_ny(ny), m_nv(nvars) {
       {
         m_X.reserve(m_nx);
         const double delta = (right - left) / (m_nx - 1);
         for(std::size_t i = 0; i < m_nx; ++i) {
           m_X.push_back(left + delta * i);
         }
       }
       {
         m_Y.reserve(m_ny);
         const double delta = (top - bottom) / (m_ny - 1);
         for(std::size_t i = 0; i < m_ny; ++i) {
           m_Y.push_back(bottom + delta * i);
         }
       }
       // we'll store the data as ( x, y, v ) ->  x * ny * nv + y * nv + v
       m_vars = DenseVector<_Type>(m_nx * m_ny * m_nv, 0.0);
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_nv, CppNoddy::TwoD_Node_Mesh< _Type >::m_nx, CppNoddy::TwoD_Node_Mesh< _Type >::m_ny, CppNoddy::TwoD_Node_Mesh< _Type >::m_vars, CppNoddy::TwoD_Node_Mesh< _Type >::m_X, CppNoddy::TwoD_Node_Mesh< _Type >::m_Y, CppNoddy::DenseVector< _Type >::push_back(), and CppNoddy::DenseVector< _Type >::reserve().
TwoD_Node_Mesh() [4/4]
template<typename _Type > CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh (std::string filename, const std::size_t nx, const std::size_t ny, const std::size_t nv) inline
Definition at line 56 of file TwoD_Node_Mesh.h.
                                                                                                     :
       m_nx(nx), m_ny(ny), m_nv(nv) {
       // need storage for the coordinates
       m_X = DenseVector<double>(nx, 0.0);
       m_Y = DenseVector<double>(ny, 0.0);
       // we'll store the data as ( x, y, v ) ->  x * ny * nv + y * nv + v
       m_vars = DenseVector<_Type>(nx * ny * nv, 0.0);
       // now read the mesh from the given filename
       read(filename, true);
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_vars, CppNoddy::TwoD_Node_Mesh< _Type >::m_X, CppNoddy::TwoD_Node_Mesh< _Type >::m_Y, and CppNoddy::TwoD_Node_Mesh< _Type >::read().
~TwoD_Node_Mesh()
template<typename _Type > virtual CppNoddy::TwoD_Node_Mesh< _Type >::~TwoD_Node_Mesh () inline virtual
dtor
Definition at line 68 of file TwoD_Node_Mesh.h.
     {}
Member Function Documentation
assign()
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::assign (const _Type elt)
Assign an element to all entries in the mesh.
Parameters
elt The element to be assigned to the mesh
Definition at line 52 of file TwoD_Node_Mesh.cpp.
{
     m_vars.assign(m_nx * m_ny * m_nv, elt);
   }
coord()
template<typename _Type > std::pair< double, double > CppNoddy::TwoD_Node_Mesh< _Type >::coord (const std::size_t nodex, const std::size_t nodey) const inline
Access the nodal position - as a pair.
Parameters
nodex The x nodal position to return
nodey The y nodal position to return
Returns
The spatial position of this node as a pair
Definition at line 369 of file TwoD_Node_Mesh.h.
{
 #ifdef PARANOID
     if(nodex > m_nx - 1 || nodey > m_ny - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.coord method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nx, nodex, m_ny, nodey);
     }
 #endif
     std::pair< double, double > pos;
     pos.first = m_X[ nodex ];
     pos.second = m_Y[ nodey ];
     return pos;
   }
Referenced by main().
dump() [1/2]
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::dump
A simple method for dumping data to std::cout.
Definition at line 318 of file TwoD_Node_Mesh.cpp.
{
     for(std::size_t var = 0; var < m_nv; ++var) {
       std::cout << "Variable : " << var << "\n";
       std::cout << " x = ";
       for(std::size_t i = 0; i < m_nx; ++i) {
         std::cout << m_X[ i ] << ", ";
       }
       std::cout << "\n";
       for(std::size_t j = 0; j < m_ny; ++j) {
         std::cout << " y = " << m_Y[ j ] << "\n";
         for(std::size_t i = 0; i < m_nx; ++i) {
           std::cout << m_vars[(i * m_ny + j) * m_nv + var ] << ", ";
         }
         std::cout << "\n";
       }
     }
   }
dump() [2/2]
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::dump (std::string filename) const
A simple method for dumping data to a file.
Parameters
filename The filename to write the data to (will overwrite)
Definition at line 455 of file TwoD_Node_Mesh.cpp.
{
     std::ofstream dump;
     dump.open(filename.c_str());
     dump.precision(15);
     dump.setf(std::ios::showpoint);
     dump.setf(std::ios::showpos);
     dump.setf(std::ios::scientific);
     //dump << m_nx << " " << m_ny << " " << m_nv << "\n";
     dump.precision(9);
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         dump << m_X[ i ] << " " << m_Y[ j ] << " ";
         for(std::size_t var = 0; var < m_nv; ++var) {
           dump << m_vars[(i * m_ny + j) * m_nv + var ] << " ";
         }
         dump << "\n";
       }
     }
   }
dump_gnu() [1/3]
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::dump_gnu (std::string filename) const
A simple method for dumping data to a file for gnuplot surface plotting.
Parameters
filename The filename to write the data to (will overwrite)
Referenced by main().
dump_gnu() [2/3]
void CppNoddy::TwoD_Node_Mesh< double >::dump_gnu (std::string filename) const
Definition at line 395 of file TwoD_Node_Mesh.cpp.
{
     std::ofstream dump;
     dump.open(filename.c_str());
     dump.precision(15);
     dump.setf(std::ios::showpoint);
     dump.setf(std::ios::showpos);
     dump.setf(std::ios::scientific);
     //
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         dump << m_X[ i ] << " " << m_Y[ j ] << " ";
         for(std::size_t var = 0; var < m_nv; ++var) {
           dump << m_vars[(i * m_ny + j) * m_nv + var ] << " ";
         }
         dump << "\n";
       }
       dump << "\n";
     }
     dump.close();
   }
dump_gnu() [3/3]
void CppNoddy::TwoD_Node_Mesh< D_complex >::dump_gnu (std::string filename) const
Definition at line 417 of file TwoD_Node_Mesh.cpp.
{
     std::ofstream dump;
     dump.open(filename.c_str());
     dump.precision(15);
     dump.setf(std::ios::showpoint);
     dump.setf(std::ios::showpos);
     dump.setf(std::ios::scientific);
     //
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         dump << m_X[ i ] << " " << m_Y[ j ] << " ";
         for(std::size_t var = 0; var < m_nv; ++var) {
           dump << real(m_vars[(i * m_ny + j) * m_nv + var ]) << " ";
           dump << imag(m_vars[(i * m_ny + j) * m_nv + var ]) << " ";
         }
         dump << "\n";
       }
       dump << "\n";
     }
     dump.close();
   }
References CppNoddy::Utility::imag(), and CppNoddy::Utility::real().
dump_var()
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::dump_var (std::string filename, const unsigned var) const
A simple method for dumping a single variable to a file with no nodal information.
Parameters
filename The filename to write the data to (will overwrite)
var The index of the variable to be dumped to output
Definition at line 440 of file TwoD_Node_Mesh.cpp.
{
     std::ofstream dump;
     dump.open(filename.c_str());
     dump.precision(15);
     dump.setf(std::ios::showpoint);
     dump.setf(std::ios::showpos);
     dump.setf(std::ios::scientific);
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         dump << m_vars[(i * m_ny + j) * m_nv + var ] << "\n";
       }
     }
   }
get_interpolated_vars()
template<typename _Type > DenseVector<_Type> CppNoddy::TwoD_Node_Mesh< _Type >::get_interpolated_vars (const double & x, const double & y) inline
Get a bilinearly interpolated value at a specified point.
Parameters
x x-coordinate in the 2D mesh
y y-coordinate in the 2D mesh
Returns
A vector of bilinearly interpolated values
Definition at line 255 of file TwoD_Node_Mesh.h.
{
       const double tol(1.e-10);
       // check start and end
       if((x < m_X[0] - tol) || (x > m_X[m_nx-1] + tol)) {
         std::string problem;
         problem = " The TwoD_Node_Mesh.get_interpolated_vars method has been called with \n";
         problem += " an x coordinate that lies outside the mesh. \n";
         throw ExceptionRuntime(problem);
       }
       // check start and end
       if((y < m_Y[0] - tol) || (y > m_Y[m_ny-1] + tol)) {
         std::string problem;
         problem = " The TwoD_Node_Mesh.get_interpolated_vars method has been called with \n";
         problem += " a y coordinate that lies outside the mesh. \n";
         throw ExceptionRuntime(problem);
       }
       int bottom_j(-1);
       for(unsigned j = 0; j < m_ny-1; ++j) {
         if((y >= m_Y[j] - tol) && (y <= m_Y[j+1] + tol)) {
           bottom_j = j;
         }
         //if ( abs(y-Y[j]) < tol )
         //{
         //bottom_j = j;
         //}
         //if ( abs(y-m_Y[j+1]) < tol )
         //{
         //bottom_j = j+1;
         //}
       }
       //std::cout << y << " " << m_Y[bottom_j] << " " << m_Y[bottom_j+1] << "\n";
       if(bottom_j == -1) {
         std::string problem;
         problem = " The TwoD_Node_Mesh.get_interpolated_vars method is broken.\n";
         throw ExceptionRuntime(problem);
       }
       //
       OneD_Node_Mesh<_Type> bottom_row = get_xsection_at_ynode(bottom_j);
       OneD_Node_Mesh<_Type> top_row = get_xsection_at_ynode(bottom_j+1);
       const double y1 = m_Y[ bottom_j ];
       const double y2 = m_Y[ bottom_j+1 ];
       DenseVector<_Type> result = top_row.get_interpolated_vars(x)*(y-y1)/(y2-y1)
                                   + bottom_row.get_interpolated_vars(x)*(y2-y)/(y2-y1);
       //std::cout << "x,y,interp: " << x << " " << y << " " << result[0] << "\n";
       return result;
     }
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_interpolated_vars(), CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_ynode(), CppNoddy::TwoD_Node_Mesh< _Type >::m_nx, CppNoddy::TwoD_Node_Mesh< _Type >::m_ny, CppNoddy::TwoD_Node_Mesh< _Type >::m_X, and CppNoddy::TwoD_Node_Mesh< _Type >::m_Y.
get_nnodes()
template<typename _Type > std::pair< std::size_t, std::size_t > CppNoddy::TwoD_Node_Mesh< _Type >::get_nnodes
Get the number of nodes in the two directions of the 2D mesh.
Returns
A pair consisting of the number of nodes in the 2 directions
Definition at line 57 of file TwoD_Node_Mesh.cpp.
{
     std::pair< std::size_t, std::size_t > nodes;
     nodes.first = m_nx;
     nodes.second = m_ny;
     return nodes;
   }
Referenced by CppNoddy::FT::idft_with_ishift().
get_nodes_vars()
template<typename _Type > DenseVector< _Type > CppNoddy::TwoD_Node_Mesh< _Type >::get_nodes_vars (const std::size_t nodex, const std::size_t nodey) const
Get the variables stored at A SPECIFIED node – equivalent to mesh(nodex,nodey).
Parameters
nodex The x nodal index to be returned
nodey The y nodal index to be returned
Returns
The vector of VARIABLES stored at this nodal point
Definition at line 37 of file TwoD_Node_Mesh.cpp.
{
 #ifdef PARANOID
     if(nodex > m_nx - 1 || nodey > m_ny - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.get_nodes_vars method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nx, nodex, m_ny, nodey);
     }
 #endif
     // construct a vector with m_nv elements starting from a pointer
     DenseVector<_Type> nodes_vars(m_nv, &m_vars[(nodex * m_ny + nodey) * m_nv ]);
     return nodes_vars;
   }
get_nvars()
template<typename _Type > std::size_t CppNoddy::TwoD_Node_Mesh< _Type >::get_nvars
Get the number of variables that are stored at each node.
Returns
The number of variables that have data stored at each nodal point
Definition at line 65 of file TwoD_Node_Mesh.cpp.
{
     return m_nv;
   }
Referenced by CppNoddy::FT::idft_with_ishift().
get_var_as_matrix()
template<typename _Type > DenseMatrix< _Type > CppNoddy::TwoD_Node_Mesh< _Type >::get_var_as_matrix (std::size_t var) const
Return a matrix corresponding to each nodal point in the mesh Each matrix element will contain a specified variable number.
Parameters
var The variable number to be accessed
Returns
A dense matrix of the specified variable
Definition at line 80 of file TwoD_Node_Mesh.cpp.
{
 #ifdef PARANOID
     if(var > m_nv - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.get_var_as_matrix method is trying to use a \n";
       problem += " variable index bigger than the number of variables in the mesh. \n";
       throw ExceptionRange(problem, m_nv, var);
     }
 #endif
     DenseMatrix<_Type> temp(m_nx, m_ny, 0.0);
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         temp(i, j) = m_vars[(i * m_ny + j) * m_nv + var ];
       }
     }
     return temp;
   }
Referenced by main().
get_xsection_at_x1()
template<typename _Type > OneD_Node_Mesh<_Type> CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1 (const double x) const inline
Get a cross section of the 2D mesh at a specified (constant) x node.
Parameters
nodex The x nodal index at which the cross section is to be taken
Returns
A 1D nodal mesh
Definition at line 135 of file TwoD_Node_Mesh.h.
{
       unsigned I(0);
       OneD_Node_Mesh<_Type> xsection(m_Y, m_nv);
       for(unsigned i = 0; i<m_nx-1; ++i) {
         if((m_X[i]< x) && (m_X[i+1]>x)) {
           I=i;
         }
       }
       double dx_ratio((x-m_X[I])/(m_X[I+1]-m_X[I]));
       for(unsigned j = 0; j<m_ny; ++j) {
         for(unsigned var = 0; var<m_nv; ++var) {
           xsection(j,var) = this->operator()(I,j,var)+(this->operator()(I+1,j,var)-this->operator()(I,j,var))*dx_ratio;
         }
       }
       return xsection;
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_nv, CppNoddy::TwoD_Node_Mesh< _Type >::m_nx, CppNoddy::TwoD_Node_Mesh< _Type >::m_ny, CppNoddy::TwoD_Node_Mesh< _Type >::m_X, CppNoddy::TwoD_Node_Mesh< _Type >::m_Y, and CppNoddy::TwoD_Node_Mesh< _Type >::operator()().
get_xsection_at_xnode()
template<typename _Type > OneD_Node_Mesh< _Type > CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_xnode (const std::size_t nodex) const
Get a cross section of the 2D mesh at a specified (constant) x node.
Parameters
nodex The x nodal index at which the cross section is to be taken
Returns
A 1D nodal mesh
Definition at line 299 of file TwoD_Node_Mesh.cpp.
{
     OneD_Node_Mesh<_Type> xsection(m_Y, m_nv);
     for(std::size_t nodey = 0; nodey < m_ny; ++nodey) {
       xsection.set_nodes_vars(nodey, this -> get_nodes_vars(nodex, nodey));
     }
     return xsection;
   }
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::set_nodes_vars().
get_xsection_at_ynode()
template<typename _Type > OneD_Node_Mesh< _Type > CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_ynode (const std::size_t nodey) const
Get a cross section of the 2D mesh at a specified (constant) y node.
Parameters
nodey The y nodal index at which the cross section is to be taken
Returns
A 1D nodal mesh
Definition at line 308 of file TwoD_Node_Mesh.cpp.
{
     OneD_Node_Mesh<_Type> xsection(m_X, m_nv);
     for(std::size_t nodex = 0; nodex < m_nx; ++nodex) {
       xsection.set_nodes_vars(nodex, this -> get_nodes_vars(nodex, nodey));
     }
     return xsection;
   }
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::set_nodes_vars().
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_interpolated_vars(), and CppNoddy::FT::idft_with_ishift().
max_abs()
template<typename _Type > double CppNoddy::TwoD_Node_Mesh< _Type >::max_abs (unsigned var) inline
Find the maximum stored absolute value in the mesh for a given variable – no interpolation is used.
Parameters
var The variable index whose maximum is being asked for
Returns
The value of the maximum (abs value)
Definition at line 237 of file TwoD_Node_Mesh.h.
{
       double max(0.0);
       // step through the nodes
       for(unsigned nodex = 0; nodex < m_X.size(); ++nodex) {
         for(unsigned nodey = 0; nodey < m_Y.size(); ++nodey) {
           if(std::abs(m_vars[(nodex * m_ny + nodey) * m_nv + var ]) > max) {
             max = std::abs(m_vars[(nodex * m_ny + nodey) * m_nv + var ]);
           }
         }
       }
       return max;
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_nv, CppNoddy::TwoD_Node_Mesh< _Type >::m_ny, CppNoddy::TwoD_Node_Mesh< _Type >::m_vars, CppNoddy::TwoD_Node_Mesh< _Type >::m_X, CppNoddy::TwoD_Node_Mesh< _Type >::m_Y, and CppNoddy::DenseVector< _Type >::size().
Referenced by main().
max_abs_real_part() [1/3]
template<typename _Type > double CppNoddy::TwoD_Node_Mesh< _Type >::max_abs_real_part (unsigned var)
Find the maximum stored absolute value in the mesh for a given variable – no interpolation is used.
Parameters
var The variable index whose maximum is being asked for
Returns
The value of the maximum (abs value)
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::normalise_real_part().
max_abs_real_part() [2/3]
double CppNoddy::TwoD_Node_Mesh< D_complex >::max_abs_real_part (unsigned var)
Definition at line 368 of file TwoD_Node_Mesh.cpp.
{
     double max(0.0);
     // step through the nodes
     for(unsigned nodex = 0; nodex < m_X.size(); ++nodex) {
       for(unsigned nodey = 0; nodey < m_Y.size(); ++nodey) {
         if(std::abs(m_vars[(nodex * m_ny + nodey) * m_nv + var ].real()) > max) {
           max = std::abs(m_vars[(nodex * m_ny + nodey) * m_nv + var ].real());
         }
       }
     }
     return max;
   }
References CppNoddy::Utility::real().
max_abs_real_part() [3/3]
double CppNoddy::TwoD_Node_Mesh< double >::max_abs_real_part (unsigned var)
Definition at line 382 of file TwoD_Node_Mesh.cpp.
{
 #ifdef PARANOID
     // check start & end
     std::string problem;
     problem = " The TwoD_Node_Mesh.max_abs_real_part method has been called for \n";
     problem += " a mesh with element type of double (rather than D_complex).";
     throw ExceptionRuntime(problem);
 #endif
     // just call the max_abs
     return max_abs(var);
   }
normalise() [1/3]
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::normalise (const std::size_t & var)
Normalise all data in the mesh based on one variable.
Parameters
var This var will have its peak (absolute) value as +/-unity following the normalisation. All other variables will also be rescaled by the same amount.
normalise() [2/3]
void CppNoddy::TwoD_Node_Mesh< double >::normalise (const std::size_t & var)
Definition at line 339 of file TwoD_Node_Mesh.cpp.
{
     double maxval(max_abs(var));
     m_vars.scale(1./maxval);
   }
normalise() [3/3]
void CppNoddy::TwoD_Node_Mesh< D_complex >::normalise (const std::size_t & var)
Definition at line 345 of file TwoD_Node_Mesh.cpp.
{
     //std::cout << "[DEBUG] asked to normalise a complex mesh\n";
     unsigned max_nx(0);
     unsigned max_ny(0);
     double max(0.0);
     // step through the nodes
     for(unsigned nodex = 0; nodex < m_X.size(); ++nodex) {
       for(unsigned nodey = 0; nodey < m_Y.size(); ++nodey) {
         if(std::abs(m_vars[(nodex * m_ny + nodey) * m_nv + var ]) > max) {
           max = std::abs(m_vars[(nodex * m_ny + nodey) * m_nv + var ]);
           max_nx = nodex;
           max_ny = nodey;
         }
       }
     }
     D_complex factor(m_vars[(max_nx * m_ny + max_ny) * m_nv + var ]);
     //std::cout << "[DEBUG] MAX |variable| had complex value of " << factor << "\n";
     m_vars.scale(1./factor);
   }
normalise_real_part()
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::normalise_real_part (const std::size_t & var) inline
Normalise the mesh such that the real part of variable 'var' has a real part of unity, and is then the largest real part across the whole mesh.
Parameters
var The variable to be normalised
Definition at line 224 of file TwoD_Node_Mesh.h.
{
       double maxval(max_abs_real_part(var));
       m_vars.scale(1./maxval);
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_vars, and CppNoddy::TwoD_Node_Mesh< _Type >::max_abs_real_part().
operator()() [1/3]
template<typename _Type > DenseVector< _Type > CppNoddy::TwoD_Node_Mesh< _Type >::operator() (const std::size_t nodex, const std::size_t nodey) inline
Access operator for a nodal point that returns a vector.
Parameters
nodex The nodal index value in the first direction
nodey The nodal index value in the second direction
Returns
The vector of variables stored at the node
Definition at line 317 of file TwoD_Node_Mesh.h.
{
 #ifdef PARANOID
     if(nodex > m_nx - 1 || nodey > m_ny - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.operator() method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nx, nodex, m_ny, nodey);
     }
 #endif
     return get_nodes_vars(nodex, nodey);
   }
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1().
operator()() [2/3]
template<typename _Type > _Type & CppNoddy::TwoD_Node_Mesh< _Type >::operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) inline
Access operator for a nodal point/variable in the mesh.
Parameters
nodex The nodal index value in the first direction
nodey The nodal index value in the second direction
var The variable index to be accessed
Definition at line 331 of file TwoD_Node_Mesh.h.
{
 #ifdef PARANOID
     if(nodex > m_nx - 1 || nodey > m_ny - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.operator() method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nx, nodex, m_ny, nodey);
     }
     if(var > m_nv - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.operator() method is trying to \n";
       problem += " access a variable index that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nv, var);
     }
 #endif
     return m_vars[(nodex * m_ny + nodey) * m_nv + var ];
   }
operator()() [3/3]
template<typename _Type > const _Type & CppNoddy::TwoD_Node_Mesh< _Type >::operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) const inline
Const access operator for a nodal point/variable in the mesh.
Parameters
nodex The nodal index value in the first direction
nodey The nodal index value in the second direction
var The variable index to be accessed
Definition at line 350 of file TwoD_Node_Mesh.h.
{
 #ifdef PARANOID
     if(nodex > m_nx - 1 || nodey > m_ny - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.operator() method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nx, nodex, m_ny, nodey);
     }
     if(var > m_nv - 1) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.operator() method is trying to \n";
       problem += " access a variable index that is not in the mesh. \n";
       throw ExceptionRange(problem, m_nv, var);
     }
 #endif
     return m_vars[(nodex * m_ny + nodey) * m_nv + var ];
   }
read() [1/3]
void CppNoddy::TwoD_Node_Mesh< double >::read (std::string filename, bool reset)
Definition at line 476 of file TwoD_Node_Mesh.cpp.
{
     std::ifstream dump;
     dump.open(filename.c_str());
     if(dump.good() != true) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.read method is trying to read a \n";
       problem += " file (" + filename + ") that doesn't exist.\n";
       throw ExceptionRuntime(problem);
     }
     dump.precision(15);
     dump.setf(std::ios::showpoint);
     dump.setf(std::ios::showpos);
     dump.setf(std::ios::scientific);
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         double x, y;
         dump >> x;
         dump >> y;
         for(std::size_t var = 0; var < m_nv; ++var) {
           double value;
           dump >> value;
           m_vars[(i * m_ny + j) * m_nv + var ] = value;
         }
         if(reset != true) {
           // if not reseting the mesh we should check the node positions
           if((std::fabs(x - m_X[ i ]) > 1.e-6) || (std::fabs(y - m_Y[ j ]) > 1.e-6)) {
             std::cout << " Read x = " << x << " Expected x = " << m_X[ i ] << "; Read y = " << y << " Expected y = " << m_Y[ j ] << " \n";
             std::cout << " Absolute differences are " << fabs(x - m_X[i]) << " and " << fabs(y - m_Y[j]) << "\n";
             std::string problem;
             problem = " The TwoD_Node_Mesh.read method is trying to read a \n";
             problem += " file whose nodal points are in a different position. \n";
             throw ExceptionRuntime(problem);
           }
         } else {
           m_X[ i ] = x;
           m_Y[ j ] = y;
         }
       }
     }
   }
read() [2/3]
void CppNoddy::TwoD_Node_Mesh< D_complex >::read (std::string filename, bool reset)
Definition at line 519 of file TwoD_Node_Mesh.cpp.
{
     std::ifstream dump;
     dump.open(filename.c_str());
     dump.precision(15);
     dump.setf(std::ios::showpoint);
     dump.setf(std::ios::showpos);
     dump.setf(std::ios::scientific);
     //
     // 18/06/2017: switched i and j below for consistency with double
     //
     for(std::size_t i = 0; i < m_nx; ++i) {
       for(std::size_t j = 0; j < m_ny; ++j) {
         double x, y;
         dump >> x;
         dump >> y;
         for(std::size_t var = 0; var < m_nv; ++var) {
           double value_r, value_i;
           dump >> value_r;
           dump >> value_i;
           m_vars[(i * m_ny + j) * m_nv + var ] = D_complex(value_r, value_i);
         }
         if(reset != true) {
           // if not reseting the mesh we should check the node positions
           if((std::fabs(x - m_X[ i ]) > 1.e-6) || (std::fabs(y - m_Y[ j ]) > 1.e-6)) {
             std::cout << " Read x = " << x << " Expected x = " << m_X[ i ] << "; Read y = " << y << " Expected y = " << m_Y[ j ] << " \n";
             std::cout << " Absolute differences are " << fabs(x - m_X[i]) << " and " << fabs(y - m_Y[j]) << "\n";
             std::string problem;
             problem = " The TwoD_Node_Mesh.read method is trying to read a \n";
             problem += " file whose nodal points are in a different position. \n";
             throw ExceptionRuntime(problem);
           }
         } else {
           m_X[ i ] = x;
           m_Y[ j ] = y;
         }
       }
     }
   }
read() [3/3]
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::read (std::string filename, const bool reset = false)
A simple method for reading data from a file.
Parameters
filename The filename to write the data to (will overwrite)
reset Will reset the nodal positions using those from the file
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
remesh1()
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::remesh1 (const DenseVector< double > & newX, const DenseVector< double > & newY)
Interpolate this mesh data (bilinearly) into a new mesh with nodal points defined in the argument list.
Not written to be efficient, so you probably don't want to do any repeated calls with this method.
Parameters
newX The x-nodal coordinates to be used in the new mesh.
newY The y-nodal coordinates to be used in the new mesh.
Definition at line 99 of file TwoD_Node_Mesh.cpp.
{
 #ifdef PARANOID
     // check start & end
     if(std::abs(m_X[ 0 ] - newX[ 0 ]) > 1.e-10 ||
         std::abs(m_X[ m_X.size() - 1 ] - newX[ newX.size() - 1 ]) > 1.e-10) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.remesh1 method has been called with \n";
       problem += " a passed X coordinate vector that has different start and/or \n";
       problem += " end points from the instantiated object. \n";
       throw ExceptionRuntime(problem);
     }
     // check monotonic node positions
     for(std::size_t i = 0; i < newX.size() - 1; ++i) {
       if(newX[ i ] >= newX[ i + 1 ]) {
         std::string problem;
         problem = " The TwoD_Node_Mesh.remesh1 method has been passed \n";
         problem += " a non-monotonic X coordinate vector. \n";
         problem += Utility::stringify(newX[ i ], 6) + " vs. " + Utility::stringify(newX[ i + 1 ], 6);
         throw ExceptionRuntime(problem);
       }
     }
     // check start and end
     if(std::abs(m_Y[ 0 ] - newY[ 0 ]) > 1.e-10 ||
         std::abs(m_Y[ m_Y.size() - 1 ] - newY[ newY.size() - 1 ]) > 1.e-10) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.remesh1 method has been called with \n";
       problem += " a passed Y coordinate vector that has different start and/or \n";
       problem += " end points from the instantiated object. \n";
       throw ExceptionRuntime(problem);
     }
     // check monotonic node positions
     for(std::size_t i = 0; i < newY.size() - 1; ++i) {
       if(newY[ i ] >= newY[ i + 1 ]) {
         std::string problem;
         problem = " The TwoD_Node_Mesh.remesh1 method has been passed \n";
         problem += " a non-monotonic Y coordinate vector. \n";
         problem += Utility::stringify(newY[ i ], 6) + " vs. " + Utility::stringify(newY[ i + 1 ], 6);
         throw ExceptionRuntime(problem);
       }
     }
 #endif
     // new variables storage
     DenseVector<_Type> newvars(newX.size() * newY.size() * m_nv, 0.0);
     // left boundary
     {
       std::size_t xnode(0);
       // bottom left corner copy
       for(unsigned var = 0; var < m_nv; ++var) {
         newvars[(xnode * newY.size() + 0) * m_nv + var ] = get_nodes_vars(0, 0)[ var ];
       }
       for(std::size_t ynode = 1; ynode < newY.size() - 1; ++ynode) {
         std::size_t left_i(0);    // bracketing index
         std::size_t below_j(0);   // bracketing index
         double deltaY(0.0);
         // loop through the source mesh and find the bracket-nodes
         for(std::size_t j = 0; j < m_Y.size() - 1; ++j) {
           if((m_Y[ j ] <= newY[ ynode ]) && (newY[ ynode ] < m_Y[ j + 1 ])) {
             below_j = j;
             deltaY = newY[ ynode ] - m_Y[ j ];
           }
         }
         DenseVector<_Type> dvarsdY = (get_nodes_vars(left_i, below_j + 1) - get_nodes_vars(left_i, below_j))
                                      / (coord(left_i, below_j + 1).second - coord(left_i, below_j).second);
         DenseVector<_Type> interpolated_vars = get_nodes_vars(left_i, below_j) + dvarsdY * deltaY;
         for(unsigned var = 0; var < m_nv; ++var) {
           newvars[(xnode * newY.size() + ynode) * m_nv + var ] = interpolated_vars[ var ];
         }
       }
       // top left corner copy
       for(unsigned var = 0; var < m_nv; ++var) {
         newvars[(xnode * newY.size() + newY.size() - 1) * m_nv + var ] = get_nodes_vars(0, m_ny - 1)[ var ];
       }
     }
     // right boundary
     {
       std::size_t xnode(newX.size() - 1);
       // bottom right corner copy
       for(unsigned var = 0; var < m_nv; ++var) {
         newvars[(xnode * newY.size() + 0) * m_nv + var ] = get_nodes_vars(m_nx - 1, 0)[ var ];
       }
       for(std::size_t ynode = 1; ynode < newY.size() - 1; ++ynode) {
         std::size_t left_i(m_X.size() - 1);    // bracketing index
         std::size_t below_j(0);   // bracketing index
         double deltaY(0.0);
         // loop through the source mesh and find the bracket-nodes
         for(std::size_t j = 0; j < m_Y.size() - 1; ++j) {
           if((m_Y[ j ] <= newY[ ynode ]) && (newY[ ynode ] < m_Y[ j + 1 ])) {
             below_j = j;
             deltaY = newY[ ynode ] - m_Y[ j ];
           }
         }
         DenseVector<_Type> dvarsdY = (get_nodes_vars(left_i, below_j + 1) - get_nodes_vars(left_i, below_j))
                                      / (coord(left_i, below_j + 1).second - coord(left_i, below_j).second);
         DenseVector<_Type> interpolated_vars = get_nodes_vars(left_i, below_j) + dvarsdY * deltaY;
         for(unsigned var = 0; var < m_nv; ++var) {
           newvars[(xnode * newY.size() + ynode) * m_nv + var ] = interpolated_vars[ var ];
         }
       }
       // bottom right corner copy
       for(unsigned var = 0; var < m_nv; ++var) {
         newvars[(xnode * newY.size() + newY.size() - 1) * m_nv + var ] = get_nodes_vars(m_nx - 1, m_ny - 1)[ var ];
       }
     }
     // bottom boundary
     {
       std::size_t ynode(0);
       for(std::size_t xnode = 1; xnode < newX.size() - 1; ++xnode) {
         std::size_t left_i(0);    // bracketing index
         std::size_t below_j(0);   // bracketing index
         double deltaX(0.0);
         // loop through the source mesh and find the bracket-nodes
         for(std::size_t i = 0; i < m_X.size() - 1; ++i) {
           if((m_X[ i ] <= newX[ xnode ]) && (newX[ xnode ] < m_X[ i + 1 ])) {
             left_i = i;
             deltaX = newX[ xnode ] - m_X[ i ];
           }
         }
         DenseVector<_Type> dvarsdX = (get_nodes_vars(left_i + 1, below_j) - get_nodes_vars(left_i, below_j))
                                      / (coord(left_i + 1, below_j).first - coord(left_i, below_j).first);
         DenseVector<_Type> interpolated_vars = get_nodes_vars(left_i, below_j) + dvarsdX * deltaX;
         for(unsigned var = 0; var < m_nv; ++var) {
           newvars[(xnode * newY.size() + ynode) * m_nv + var ] = interpolated_vars[ var ];
         }
       }
     }
     // top boundary
     {
       std::size_t ynode(newY.size() - 1);
       for(std::size_t xnode = 1; xnode < newX.size() - 1; ++xnode) {
         std::size_t left_i(0);    // bracketing index
         std::size_t below_j(m_Y.size() - 1);   // bracketing index
         double deltaX(0.0);
         // loop through the source mesh and find the bracket-nodes
         for(std::size_t i = 0; i < m_X.size() - 1; ++i) {
           if((m_X[ i ] <= newX[ xnode ]) && (newX[ xnode ] < m_X[ i + 1 ])) {
             left_i = i;
             deltaX = newX[ xnode ] - m_X[ i ];
           }
         }
         DenseVector<_Type> dvarsdX = (get_nodes_vars(left_i + 1, below_j) - get_nodes_vars(left_i, below_j))
                                      / (coord(left_i + 1, below_j).first - coord(left_i, below_j).first);
         DenseVector<_Type> interpolated_vars = get_nodes_vars(left_i, below_j) + dvarsdX * deltaX;
         for(unsigned var = 0; var < m_nv; ++var) {
           newvars[(xnode * newY.size() + ynode) * m_nv + var ] = interpolated_vars[ var ];
         }
       }
     }
     // loop thru interior nodes of the destination mesh one node at a time
     for(std::size_t xnode = 1; xnode < newX.size() - 1; ++xnode) {
       for(std::size_t ynode = 1; ynode < newY.size() - 1; ++ynode) {
         std::size_t left_i(0);    // bracketing index
         std::size_t below_j(0);   // bracketing index
         // loop through the source mesh and find the bracket-nodes
         for(std::size_t i = 0; i < m_X.size() - 1; ++i) {
           if((m_X[ i ] <= newX[ xnode ]) && (newX[ xnode ] < m_X[ i + 1 ])) {
             left_i = i;
           }
         }
         // loop through the source mesh and find the bracket-nodes
         for(std::size_t j = 0; j < m_Y.size() - 1; ++j) {
           if((m_Y[ j ] <= newY[ ynode ]) && (newY[ ynode ] < m_Y[ j + 1 ])) {
             below_j = j;
           }
         }
         DenseVector<_Type> dvarsdX = (get_nodes_vars(left_i + 1, below_j) - get_nodes_vars(left_i, below_j))
                                      / (coord(left_i + 1, below_j).first - coord(left_i, below_j).first);
         DenseVector<_Type> dvarsdY = (get_nodes_vars(left_i, below_j + 1) - get_nodes_vars(left_i, below_j))
                                      / (coord(left_i, below_j + 1).second - coord(left_i, below_j).second);
         DenseVector<_Type> interpolated_vars_bottom =
           (get_nodes_vars(left_i, below_j) * (coord(left_i + 1, below_j).first - newX[ xnode ])
            + get_nodes_vars(left_i + 1, below_j) * (newX[ xnode ] - coord(left_i, below_j).first)) /
           (coord(left_i + 1, below_j).first - coord(left_i, below_j).first);
         DenseVector<_Type> interpolated_vars_top =
           (get_nodes_vars(left_i, below_j + 1) * (coord(left_i + 1, below_j + 1).first - newX[ xnode ])
            + get_nodes_vars(left_i + 1, below_j + 1) * (newX[ xnode ] - coord(left_i, below_j + 1).first)) /
           (coord(left_i + 1, below_j + 1).first - coord(left_i, below_j + 1).first);
         DenseVector<_Type> interpolated_vars =
           (interpolated_vars_bottom * (coord(left_i, below_j + 1).second - newY[ ynode ])
            +  interpolated_vars_top * (newY[ ynode ] - coord(left_i, below_j).second)) /
           (coord(left_i, below_j + 1).second - coord(left_i, below_j).second);
         for(unsigned var = 0; var < m_nv; ++var) {
           newvars[(xnode * newY.size() + ynode) * m_nv + var ] = interpolated_vars[ var ];
         }
       }
     }
     // finally replace the old nodes with the new ones
     m_X = newX;
     m_Y = newY;
     m_nx = newX.size();
     m_ny = newY.size();
     m_vars = newvars;
   }
References CppNoddy::DenseVector< _Type >::size(), and CppNoddy::Utility::stringify().
Referenced by main().
scale()
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::scale (const _Type & value) inline
Calls the vector "scale" method for the whole mesh data.
Parameters
value The value to be used in the scale operation
Definition at line 216 of file TwoD_Node_Mesh.h.
{
       m_vars.scale(value);
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_vars.
set_nodes_vars()
template<typename _Type > void CppNoddy::TwoD_Node_Mesh< _Type >::set_nodes_vars (const std::size_t nodex, const std::size_t nodey, const DenseVector< _Type > & U)
Set the variables stored at A SPECIFIED node.
Parameters
nodex The x nodal index to be set
nodey The y nodal index to be set
U The vector of VARIABLES to be written to this nodal point
Definition at line 20 of file TwoD_Node_Mesh.cpp.
{
 #ifdef PARANOID
     if(U.size() > m_nv) {
       std::string problem;
       problem = " The TwoD_Node_Mesh.set_nodes_vars method is trying to use a \n";
       problem += " vector that has more entries than variables stored in the mesh. \n";
       throw ExceptionRuntime(problem);
     }
 #endif
     // assign contents of U to the member data
     std::size_t offset((nodex * m_ny + nodey) * m_nv);
     for(std::size_t var = 0; var < m_nv; ++var) {
       m_vars[ offset++ ] = U[ var ];
     }
   }
References U.
Referenced by CppNoddy::FT::dft_with_shift(), and CppNoddy::FT::idft_with_ishift().
xcoord()
template<typename _Type > double& CppNoddy::TwoD_Node_Mesh< _Type >::xcoord (const std::size_t nodex) inline
Access the x-nodal (first index) position.
Parameters
nodex The x nodal index
Returns
The x-coordinate of the node
Definition at line 98 of file TwoD_Node_Mesh.h.
{
       return m_X[nodex];
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_X.
Referenced by CppNoddy::FT::dft_with_shift(), and CppNoddy::FT::idft_with_ishift().
xnodes()
template<typename _Type > const DenseVector< double > & CppNoddy::TwoD_Node_Mesh< _Type >::xnodes
Access the vector of x-nodal positions.
Returns
A vector of the nodal positions for this mesh
Definition at line 70 of file TwoD_Node_Mesh.cpp.
{
     return m_X;
   }
Referenced by CppNoddy::FT::idft_with_ishift().
ycoord()
template<typename _Type > double& CppNoddy::TwoD_Node_Mesh< _Type >::ycoord (const std::size_t nodey) inline
Access the y-nodal (second index) position.
Parameters
nodex The y nodal index
Returns
The y-coordinate of the node
Definition at line 105 of file TwoD_Node_Mesh.h.
{
       return m_Y[nodey];
     }
References CppNoddy::TwoD_Node_Mesh< _Type >::m_Y.
ynodes()
template<typename _Type > const DenseVector< double > & CppNoddy::TwoD_Node_Mesh< _Type >::ynodes
Access the vector of y-nodal positions.
Returns
A vector of the nodal positions for this mesh
Definition at line 75 of file TwoD_Node_Mesh.cpp.
{
     return m_Y;
   }
Referenced by CppNoddy::FT::idft_with_ishift().
Member Data Documentation
m_nv
template<typename _Type > std::size_t CppNoddy::TwoD_Node_Mesh< _Type >::m_nv protected
Definition at line 306 of file TwoD_Node_Mesh.h.
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1(), CppNoddy::TwoD_Node_Mesh< _Type >::max_abs(), and CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
m_nx
template<typename _Type > std::size_t CppNoddy::TwoD_Node_Mesh< _Type >::m_nx protected
Definition at line 306 of file TwoD_Node_Mesh.h.
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_interpolated_vars(), CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1(), and CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
m_ny
template<typename _Type > std::size_t CppNoddy::TwoD_Node_Mesh< _Type >::m_ny protected
Definition at line 306 of file TwoD_Node_Mesh.h.
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_interpolated_vars(), CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1(), CppNoddy::TwoD_Node_Mesh< _Type >::max_abs(), and CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
m_vars
template<typename _Type > DenseVector<_Type> CppNoddy::TwoD_Node_Mesh< _Type >::m_vars protected
Definition at line 312 of file TwoD_Node_Mesh.h.
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::max_abs(), CppNoddy::TwoD_Node_Mesh< _Type >::normalise_real_part(), CppNoddy::TwoD_Node_Mesh< _Type >::scale(), and CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
m_X
template<typename _Type > DenseVector<double> CppNoddy::TwoD_Node_Mesh< _Type >::m_X protected
Definition at line 308 of file TwoD_Node_Mesh.h.
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_interpolated_vars(), CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1(), CppNoddy::TwoD_Node_Mesh< _Type >::max_abs(), CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh(), and CppNoddy::TwoD_Node_Mesh< _Type >::xcoord().
m_Y
template<typename _Type > DenseVector<double> CppNoddy::TwoD_Node_Mesh< _Type >::m_Y protected
Definition at line 310 of file TwoD_Node_Mesh.h.
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::get_interpolated_vars(), CppNoddy::TwoD_Node_Mesh< _Type >::get_xsection_at_x1(), CppNoddy::TwoD_Node_Mesh< _Type >::max_abs(), CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh(), and CppNoddy::TwoD_Node_Mesh< _Type >::ycoord().
The documentation for this class was generated from the following files:
include/TwoD_Node_Mesh.h
src/TwoD_Node_Mesh.cpp
© 2012
R.E. Hewitt