CppNoddy: Example::My_Mesh< _Type > Class Template Reference
Example::My_Mesh< _Type > Class Template Reference
Public Member Functions
My_Mesh (double left, double right, double bottom, double top, std::size_t nz, std::size_t ny, std::size_t nv)
double FnComp_X (const double &x) const
Mapping function that provides a computational X coordinate from a physical coordinate.
double FnComp_Xd (const double &x) const
Mapping function that provides the first derivative of the computational m_X coordinate as a function of the physical coordinate.
double FnComp_Xdd (const double &x) const
Mapping function that provides the second derivative of the computational X coordinate as a function of the physical coordinate.
double FnComp_Y (const double &y) const
Mapping function that provides the computational Y coordinate as a function of the physical coordinate.
double FnComp_Yd (const double &y) const
Mapping function that provides the first derivative of the computational Y coordinate as a function of the physical coordinate.
double FnComp_Ydd (const double &y) const
Mapping function that provides the second derivative of the computational Y coordinate as a function of the physical coordinate.
My_Mesh (double left, double right, double bottom, double top, std::size_t nz, std::size_t ny, std::size_t nv)
double FnComp_X (const double &x) const
Mapping function that provides a computational X coordinate from a physical coordinate.
double FnComp_Xd (const double &x) const
Mapping function that provides the first derivative of the computational m_X coordinate as a function of the physical coordinate.
double FnComp_Xdd (const double &x) const
Mapping function that provides the second derivative of the computational X coordinate as a function of the physical coordinate.
double FnComp_Y (const double &y) const
Mapping function that provides the computational Y coordinate as a function of the physical coordinate.
double FnComp_Yd (const double &y) const
Mapping function that provides the first derivative of the computational Y coordinate as a function of the physical coordinate.
double FnComp_Ydd (const double &y) const
Mapping function that provides the second derivative of the computational Y coordinate as a function of the physical coordinate.
Public Member Functions inherited from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >
virtual double FnComp_X (const double &zeta) const
Mapping function that provides a computational X coordinate from a physical coordinate.
virtual double FnComp_Xd (const double &zeta) const
Mapping function that provides the first derivative of the computational m_X coordinate as a function of the physical coordinate.
virtual double FnComp_Xdd (const double &zeta) const
Mapping function that provides the second derivative of the computational X coordinate as a function of the physical coordinate.
virtual double FnComp_Y (const double &eta) const
Mapping function that provides the computational Y coordinate as a function of the physical coordinate.
virtual double FnComp_Yd (const double &eta) const
Mapping function that provides the first derivative of the computational Y coordinate as a function of the physical coordinate.
virtual double FnComp_Ydd (const double &eta) const
Mapping function that provides the second derivative of the computational Y coordinate as a function of the physical coordinate.
TwoD_Mapped_Node_Mesh ()
TwoD_Mapped_Node_Mesh (const double left, const double right, const double bottom, const double top, const std::size_t nx, const std::size_t ny, const std::size_t nvars)
ctor of a blank mesh
TwoD_Mapped_Node_Mesh (std::string filename, const std::size_t nx, const std::size_t ny, const std::size_t nv)
void init_mapping ()
Sometimes a useful mapping is painful to invert analytically.
std::pair< double, double > get_comp_step_sizes () const
virtual ~TwoD_Mapped_Node_Mesh ()
dtor
DenseVector< _Type > operator() (const std::size_t nodex, const std::size_t nodey)
Access operator for a nodal point that returns a vector.
_Type & operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var)
Access operator for a nodal point/variable in the mesh.
const _Type & operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) const
Const access operator for a nodal point/variable in the mesh.
std::pair< double, double > coord (const std::size_t nodex, const std::size_t nodey) const
Access the physical nodal position - as a pair.
void set_nodes_vars (const std::size_t nodex, const std::size_t nodey, const DenseVector< _Type > &U)
Set the variables stored at A SPECIFIED node.
DenseVector< _Type > get_nodes_vars (const std::size_t nodex, const std::size_t nodey) const
Get the variables stored at A SPECIFIED node – equivalent to mesh(nodex,nodey).
std::pair< std::size_t, std::size_t > get_nnodes () const
Get the number of nodes in the two directions of the 2D mesh.
std::size_t get_nvars () const
Get the number of variables that are stored at each node.
DenseVector< double > & xnodes ()
Access the vector of x-nodal positions.
DenseVector< double > & ynodes ()
Access the vector of y-nodal positions.
OneD_Node_Mesh< _Type > get_xsection_at_xnode (const std::size_t nodex) const
Get a cross section of the 2D mesh at a specified (constant) x node.
OneD_Node_Mesh< _Type > get_xsection_at_ynode (const std::size_t nodey) const
Get a cross section of the 2D mesh at a specified (constant) y node.
void read (std::string filename, const bool reset=false)
A simple method for reading data from a file.
void dump_gnu (std::string filename) const
A simple method for dumping data to a file for gnuplot surface plotting.
void normalise (const std::size_t &var)
Normalise all data in the mesh based on one variable.
void scale (const _Type &value)
Rescale all values stored in the mapped mesh by a scalar.
double max (unsigned var)
Find the maximum stored absolute value in the mesh for a given variable – no interpolation is used.
DenseVector< _Type > get_interpolated_vars (const double &x, const double &y)
Get a bilinearly interpolated value at a specified point.
void normalise (const std::size_t &var)
void normalise (const std::size_t &var)
void read (std::string filename, bool reset)
void read (std::string filename, bool reset)
void dump_gnu (std::string filename) const
void dump_gnu (std::string filename) const
Additional Inherited Members
Protected Attributes inherited from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >
double m_left
double m_right
double m_bottom
double m_top
std::size_t m_nx
std::size_t m_ny
std::size_t m_nv
DenseVector< double > m_compX
DenseVector< double > m_compY
DenseVector< double > m_X
DenseVector< double > m_Y
DenseVector< _Type > m_vars
Detailed Description
template<typename _Type>
class Example::My_Mesh< _Type >
Definition at line 63 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
Constructor & Destructor Documentation
My_Mesh() [1/2]
template<typename _Type > Example::My_Mesh< _Type >::My_Mesh (double left, double right, double bottom, double top, std::size_t nz, std::size_t ny, std::size_t nv) inline
Definition at line 66 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
                                                                                                              : TwoD_Mapped_Node_Mesh<_Type>( left, right, bottom, top, nz, ny, nv )
    {
      // mesh stretching parameters
       BX = 10.0;
       BY = 10.0;
       CX = 0.2;
       CY = 0.8;
       this -> init_mapping();
    }
References CppNoddy::TwoD_Mapped_Node_Mesh< _Type >::init_mapping().
My_Mesh() [2/2]
template<typename _Type > Example::My_Mesh< _Type >::My_Mesh (double left, double right, double bottom, double top, std::size_t nz, std::size_t ny, std::size_t nv) inline
Definition at line 66 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
                                                                                                              : TwoD_Mapped_Node_Mesh<_Type>( left, right, bottom, top, nz, ny, nv )
    {
      // mesh stretching parameters
       BX = 10.0;
       BY = 10.0;
       CX = 0.2;
       CY = 0.8;
       this -> init_mapping();
    }
References CppNoddy::TwoD_Mapped_Node_Mesh< _Type >::init_mapping().
Member Function Documentation
FnComp_X() [1/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_X (const double & zeta) const inline virtual
Mapping function that provides a computational X coordinate from a physical coordinate.
Parameters
zeta The physical coordinate
Returns
The corresponding computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 78 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
    {
      return x;
    }
FnComp_X() [2/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_X (const double & zeta) const inline virtual
Mapping function that provides a computational X coordinate from a physical coordinate.
Parameters
zeta The physical coordinate
Returns
The corresponding computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 78 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
    {
      return x;
    }
FnComp_Xd() [1/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Xd (const double & zeta) const inline virtual
Mapping function that provides the first derivative of the computational m_X coordinate as a function of the physical coordinate.
Parameters
zeta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 82 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
    {
      return 1.0;
    }
Referenced by main().
FnComp_Xd() [2/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Xd (const double & zeta) const inline virtual
Mapping function that provides the first derivative of the computational m_X coordinate as a function of the physical coordinate.
Parameters
zeta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 82 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
    {
      return 1.0;
    }
FnComp_Xdd() [1/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Xdd (const double & zeta) const inline virtual
Mapping function that provides the second derivative of the computational X coordinate as a function of the physical coordinate.
Parameters
zeta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 86 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
    {
      return 0.0;
    }
Referenced by main().
FnComp_Xdd() [2/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Xdd (const double & zeta) const inline virtual
Mapping function that provides the second derivative of the computational X coordinate as a function of the physical coordinate.
Parameters
zeta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 86 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
    {
      return 0.0;
    }
FnComp_Y() [1/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Y (const double & eta) const inline virtual
Mapping function that provides the computational Y coordinate as a function of the physical coordinate.
Parameters
eta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 91 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
    {
      return y;
    }
FnComp_Y() [2/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Y (const double & eta) const inline virtual
Mapping function that provides the computational Y coordinate as a function of the physical coordinate.
Parameters
eta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 91 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
    {
      return y;
    }
FnComp_Yd() [1/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Yd (const double & eta) const inline virtual
Mapping function that provides the first derivative of the computational Y coordinate as a function of the physical coordinate.
Parameters
eta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 95 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
    {
      return 1.0;
    }
Referenced by main().
FnComp_Yd() [2/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Yd (const double & eta) const inline virtual
Mapping function that provides the first derivative of the computational Y coordinate as a function of the physical coordinate.
Parameters
eta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 95 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
    {
      return 1.0;
    }
FnComp_Ydd() [1/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Ydd (const double & eta) const inline virtual
Mapping function that provides the second derivative of the computational Y coordinate as a function of the physical coordinate.
Parameters
eta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 99 of file EVP2DOrrSommerfeld_slepcz_mumps.cpp.
    {
      return 0.0;
    }
Referenced by main().
FnComp_Ydd() [2/2]
template<typename _Type > double Example::My_Mesh< _Type >::FnComp_Ydd (const double & eta) const inline virtual
Mapping function that provides the second derivative of the computational Y coordinate as a function of the physical coordinate.
Parameters
eta The physical coordinate
Returns
The corresponding derivative of the computational coordinate
Reimplemented from CppNoddy::TwoD_Mapped_Node_Mesh< _Type >.
Definition at line 99 of file EVP2DOrrSommerfeld_slepcz_superludist.cpp.
    {
      return 0.0;
    }
The documentation for this class was generated from the following files:
Tests/EVP/EVP2DOrrSommerfeld_slepcz_mumps.cpp
Tests/EVP/EVP2DOrrSommerfeld_slepcz_superludist.cpp
© 2012
R.E. Hewitt