CppNoddy: CppNoddy::BandedMatrix< _Type > Class Template Reference
CppNoddy::BandedMatrix< _Type > Class Template Reference
A matrix class that constructs a BANDED matrix.
#include <BandedMatrix.h>
Public Types
typedef DenseVector< _Type >::elt_iter elt_iter
Public Member Functions
BandedMatrix ()
Empty constructor .. should we stop this?
void blank ()
BandedMatrix (const std::size_t &rows, const std::size_t &offdiag, const _Type &fill)
Noddy Banded Matrix constructor.
BandedMatrix (const BandedMatrix &source)
Copy constructor.
BandedMatrix & operator= (const BandedMatrix &source)
Assignment operator.
const _Type & operator() (const std::size_t &row, const std::size_t &col) const
Access operator.
_Type & operator() (const std::size_t &row, const std::size_t &col)
Access operator.
const _Type & get (const std::size_t &row, const std::size_t &col) const
Access operator.
_Type & set (const std::size_t &row, const std::size_t &col)
Access operator.
std::size_t nrows () const
Get the number of rows.
std::size_t ncols () const
Get the number of columns.
std::size_t nelts () const
Get the number of elements.
void scale (const _Type &mult)
Scale all entries in the matrix by a scalar.
void transpose ()
Transpose the matrix.
double one_norm () const
double two_norm () const
double inf_norm () const
double frob_norm () const
DenseVector< _Type > multiply (const DenseVector< _Type > &X) const
Right multiply the matrix by a DENSE vector.
void dump () const
Output the matrix contents to std::cout.
void assign (_Type elt)
Assign a value the matrix so that it has the same geometry, but zero entries in all locations including those reserved for pivotting.
std::size_t noffdiag () const
Get the number of off-diagonal elements where the total INPUT band width is 2*noffdiag+1 since the band structure is symmetric.
void row_swap (const std::size_t &row1, const std::size_t &row2)
Exchange rows in the matrix.
double * base ()
Allow direct access to the vector m_storage.
elt_iter get_elt_iter (std::size_t row, std::size_t col)
double * base ()
double * base ()
Public Member Functions inherited from CppNoddy::Sequential_Matrix_base< _Type >
Sequential_Matrix_base ()
An empty constructor.
virtual ~Sequential_Matrix_base ()
virtual const _Type & operator() (const std::size_t &row, const std::size_t &col) const =0
virtual _Type & operator() (const std::size_t &row, const std::size_t &col)=0
virtual const _Type & get (const std::size_t &row, const std::size_t &col) const =0
virtual _Type & set (const std::size_t &row, const std::size_t &col)=0
virtual std::size_t nrows () const =0
virtual std::size_t ncols () const =0
virtual std::size_t nelts () const =0
virtual void scale (const _Type &mult)=0
virtual void dump () const =0
Public Attributes
DenseVector< _Type > m_storage
A contiguous vector.
std::size_t m_N
The number of rows/cols in the matrix.
std::size_t m_L
Max number of (INPUT) bands above OR below the main diagonal.
Detailed Description
template<typename _Type>
class CppNoddy::BandedMatrix< _Type >
A matrix class that constructs a BANDED matrix.
Definition at line 16 of file BandedMatrix.h.
Member Typedef Documentation
elt_iter
template<typename _Type > typedef DenseVector<_Type>::elt_iter CppNoddy::BandedMatrix< _Type >::elt_iter
Definition at line 20 of file BandedMatrix.h.
Constructor & Destructor Documentation
BandedMatrix() [1/3]
template<typename _Type > CppNoddy::BandedMatrix< _Type >::BandedMatrix () inline
Empty constructor .. should we stop this?
Definition at line 23 of file BandedMatrix.h.
    {}
BandedMatrix() [2/3]
template<typename _Type > CppNoddy::BandedMatrix< _Type >::BandedMatrix (const std::size_t & rows, const std::size_t & offdiag, const _Type & fill)
Noddy Banded Matrix constructor.
Parameters
rows The number of rows in the matrix.
offdiag The maximum number of bands above OR below the diagonal. The total number stored will be 3 * offdiag + 1; i.e. assumes the number of offdiagonal elts is the same both above and below, and we must an extra 'offdiag' because of fill-in during pivotting.
fill The initial value to be placed in each element of the banded matrix.
Definition at line 16 of file BandedMatrix.cpp.
                                                       :
    Sequential_Matrix_base<_Type>(),
    m_N(rows),
    m_L(upper_offdiag_bands) {
    // we'll assume that the upper & lower offdiags are of equal size.
    // logical m_storage is the main diagonal + upper offdiagonal + lower offdiagonal
    // = 2 * m_L + 1.
    // However, allowing for row interchanging during pivotting leads to additional
    // padding of m_L, to make a total of 3*m_L+1.
    m_storage = DenseVector<_Type>(m_N * (3 * m_L + 1), 0.0);
  }
References CppNoddy::BandedMatrix< _Type >::m_L, CppNoddy::BandedMatrix< _Type >::m_N, and CppNoddy::BandedMatrix< _Type >::m_storage.
BandedMatrix() [3/3]
template<typename _Type > CppNoddy::BandedMatrix< _Type >::BandedMatrix (const BandedMatrix< _Type > & source)
Copy constructor.
Parameters
source The source object to be copied
Definition at line 31 of file BandedMatrix.cpp.
                                                                     :
    Sequential_Matrix_base<_Type>() {
    *this = source;
  }
Member Function Documentation
assign()
template<typename _Type > void CppNoddy::BandedMatrix< _Type >::assign (_Type elt) inline
Assign a value the matrix so that it has the same geometry, but zero entries in all locations including those reserved for pivotting.
Parameters
elt The value to be assigned to all entries
Definition at line 106 of file BandedMatrix.h.
{
      m_storage.assign(m_storage.size(), elt);
    }
References CppNoddy::BandedMatrix< _Type >::m_storage.
Referenced by CppNoddy::PDE_IBVP< _Type >::assemble_matrix_problem().
base() [1/3]
template<typename _Type > double * CppNoddy::BandedMatrix< _Type >::base ()
Allow direct access to the vector m_storage.
Dangerous, but used for passing to LAPACK.
base() [2/3]
double * CppNoddy::BandedMatrix< double >::base ()
Definition at line 160 of file BandedMatrix.cpp.
{
    return &(m_storage[0]);
  }
base() [3/3]
double * CppNoddy::BandedMatrix< std::complex< double > >::base ()
Definition at line 165 of file BandedMatrix.cpp.
{
    //return &( m_storage[0].real() );
    return &reinterpret_cast<double(&)[2]>(m_storage[0])[0];
  }
blank()
template<typename _Type > void CppNoddy::BandedMatrix< _Type >::blank () inline
Definition at line 26 of file BandedMatrix.h.
                 {
      m_storage = DenseVector<_Type>(m_N * (3 * m_L + 1), 0.0);
    }
References CppNoddy::BandedMatrix< _Type >::m_L, CppNoddy::BandedMatrix< _Type >::m_N, and CppNoddy::BandedMatrix< _Type >::m_storage.
dump()
template<typename _Type > void CppNoddy::BandedMatrix< _Type >::dump virtual
Output the matrix contents to std::cout.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 137 of file BandedMatrix.cpp.
{
    std::cout << "BANDED mtx size = " << nrows() << " x " << ncols()
              << " with INPUT no. of bands = " << 2 * m_L + 1
              << " and total bands STORED (for pivotting) = " << 3 * m_L + 1 << "\n";
    std::cout.precision(4);
    std::cout << "- start matrix \n";
    for(std::size_t i = 0; i < nrows(); ++i) {
      std::cout << " row " << i << " =  ";
      for(std::size_t j = 0; j < nrows(); ++j) {
        if(i == j)
          std::cout << "*";
        if(((int) j < (int) i - (int) m_L) || ((int) j > (int) i + (int)(2*m_L))) {
          std::cout << 0 << ", ";
        } else {
          std::cout << operator()(i, j) << ", ";
        }
      }
      std::cout << "\n";
    }
    std::cout << "- end matrix \n";
  }
frob_norm()
template<typename _Type > double CppNoddy::BandedMatrix< _Type >::frob_norm
Returns
The sum of the two_norm of all rows
Definition at line 126 of file BandedMatrix.cpp.
{
    double sum(0.0);
    for(unsigned row = 0; row < m_N; ++row) {
      // copy the row into a temp vector
      DenseVector<_Type> temp(3 * m_L + 1, &m_storage[ row * (3 * m_L + 1) ]);
      sum += temp.two_norm();
    }
    return sum;
  }
References CppNoddy::DenseVector< _Type >::two_norm().
get()
template<typename _Type > const _Type & CppNoddy::BandedMatrix< _Type >::get (const std::size_t & row, const std::size_t & col) const inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 205 of file BandedMatrix.h.
{
    return operator()(row, col);
  }
get_elt_iter()
template<typename _Type > elt_iter CppNoddy::BandedMatrix< _Type >::get_elt_iter (std::size_t row, std::size_t col) inline
Definition at line 127 of file BandedMatrix.h.
{
      return m_storage.begin() + m_L * (3 * col + 2) + row;
    }
References CppNoddy::BandedMatrix< _Type >::m_L, and CppNoddy::BandedMatrix< _Type >::m_storage.
Referenced by CppNoddy::PDE_IBVP< _Type >::assemble_matrix_problem().
inf_norm()
template<typename _Type > double CppNoddy::BandedMatrix< _Type >::inf_norm
Returns
The maximum inf_norm of all rows
Definition at line 114 of file BandedMatrix.cpp.
{
    double max(0.0);
    for(unsigned row = 0; row < m_N; ++row) {
      // copy the row into a temp vector
      DenseVector<_Type> temp(3 * m_L + 1, &m_storage[ row * (3 * m_L + 1) ]);
      max = std::max(max, temp.inf_norm());
    }
    return max;
  }
References CppNoddy::DenseVector< _Type >::inf_norm().
multiply()
template<typename _Type > DenseVector< _Type > CppNoddy::BandedMatrix< _Type >::multiply (const DenseVector< _Type > & X) const
Right multiply the matrix by a DENSE vector.
Parameters
X The DENSE vector to multiply by
Returns
A DENSE vector of length ncols() produced from the multiplication
Definition at line 58 of file BandedMatrix.cpp.
{
    std::string problem;
    problem = " The multiply method of the BandedMatrix class has \n";
    problem += " not been implemented. \n";
    throw ExceptionRuntime(problem);
    return m_storage; // dummy return
  }
ncols()
template<typename _Type > std::size_t CppNoddy::BandedMatrix< _Type >::ncols inline virtual
Get the number of columns.
Returns
The number of columns in the matrix
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 222 of file BandedMatrix.h.
{
    return m_N;
  }
nelts()
template<typename _Type > std::size_t CppNoddy::BandedMatrix< _Type >::nelts virtual
Get the number of elements.
Returns
The number of elements
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 47 of file BandedMatrix.cpp.
{
    return m_storage.size();
  }
noffdiag()
template<typename _Type > std::size_t CppNoddy::BandedMatrix< _Type >::noffdiag inline
Get the number of off-diagonal elements where the total INPUT band width is 2*noffdiag+1 since the band structure is symmetric.
Returns
The number of upper or lower offdiagonal bands; NOTE: the number of offdiagonals STORED will typically be three times this to allow for pivotting
Definition at line 227 of file BandedMatrix.h.
{
    return m_L;
  }
Referenced by CppNoddy::PDE_IBVP< _Type >::assemble_matrix_problem(), and main().
nrows()
template<typename _Type > std::size_t CppNoddy::BandedMatrix< _Type >::nrows inline virtual
Get the number of rows.
Returns
The number of rows in the matrix
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 217 of file BandedMatrix.h.
{
    return m_N;
  }
one_norm()
template<typename _Type > double CppNoddy::BandedMatrix< _Type >::one_norm
Returns
The maximum one_norm of all rows
Definition at line 90 of file BandedMatrix.cpp.
{
    double max(0.0);
    for(unsigned row = 0; row < m_N; ++row) {
      // copy the row into a temp vector
      DenseVector<_Type> temp(3 * m_L + 1, &m_storage[ row * (3 * m_L + 1) ]);
      max = std::max(max, temp.one_norm());
    }
    return max;
  }
References CppNoddy::DenseVector< _Type >::one_norm().
operator()() [1/2]
template<typename _Type > _Type & CppNoddy::BandedMatrix< _Type >::operator() (const std::size_t & row, const std::size_t & col) inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 175 of file BandedMatrix.h.
{
#ifdef PARANOID
    // if outside the m_Nxm_N matrix
    if((row >= m_N) || (row < 0) || (col >= m_N) || (col < 0)) {
      std::string problem;
      problem = " The operator() of BandedMatrix has been called \n";
      problem += " with a (row, col) index that is outside \n";
      problem += " the square m_Nxm_N matrix.\n";
      throw ExceptionRange(problem, m_N, m_N, row, col);
    }
    // check if the subscripts are out of the band
    if(!((col + m_L >= row) && (col <= 2*m_L + row))) {
      std::string problem;
      problem = " The operator() of BandedMatrix has been called \n";
      problem += " with a (row, col) index that is outside \n";
      problem += " the band structure.\n";
      std::cout << " m_L = " << m_L << "\n";
      std::cout << " row = " << row << "\n";
      std::cout << " col = " << col << "\n";
      throw ExceptionRange(problem, m_N, m_L, row, col);
    }
#endif
    // MOSTLY WE PUSH BANDED MATRICES TO LAPACK - so we'll keep column major
    // internal storage ... a la Fortran
    // return m_storage[ col * ( 3 * m_L + 1 ) + ( row - col ) + 2 * m_L ];
    // or equiv.
    return m_storage[ m_L * (3 * col + 2) + row ];
  }
operator()() [2/2]
template<typename _Type > const _Type & CppNoddy::BandedMatrix< _Type >::operator() (const std::size_t & row, const std::size_t & col) const inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 147 of file BandedMatrix.h.
{
#ifdef PARANOID
    // if outside the m_Nxm_N matrix
    if((row >= m_N) || (row < 0) || (col >= m_N) || (col < 0)) {
      std::string problem;
      problem = " The const operator() of BandedMatrix has been called \n";
      problem += " with a (row, col) index that is outside \n";
      problem += " the square m_Nxm_N matrix.\n";
      throw ExceptionGeom(problem, m_N, m_N, row, col);
    }
    // check if the subscripts are out of the band
    if(!((col + m_L >= row) && (col <= 2*m_L + row))) {
      std::string problem;
      problem = " The const operator() of BandedMatrix has been called \n";
      problem += " with a (row, col) index that is outside \n";
      problem += " the band structure. Bandwidth and offset from\n";
      problem += " the diagonal information follows.\n";
      throw ExceptionGeom(problem, m_L, col - row);
    }
#endif
    // MOSTLY WE PUSH BANDED MATRICES TO LAPACK - so we'll keep column major
    // internal storage ... a la Fortran
    // return m_storage[ col * ( 3 * m_L + 1 ) + ( row - col ) + 2 * m_L ];
    // or equiv.
    return m_storage[ m_L * (3 * col + 2) + row ];
  }
operator=()
template<typename _Type > BandedMatrix< _Type > & CppNoddy::BandedMatrix< _Type >::operator= (const BandedMatrix< _Type > & source) inline
Assignment operator.
Parameters
source The source object for the assignment
Returns
The newly assigned object
Definition at line 37 of file BandedMatrix.cpp.
{
    if(this == &source)
      return * this;
    m_storage = source.m_storage;
    m_N = source.m_N;
    m_L = source.m_L;
    return *this;
  }
row_swap()
template<typename _Type > void CppNoddy::BandedMatrix< _Type >::row_swap (const std::size_t & row1, const std::size_t & row2)
Exchange rows in the matrix.
Parameters
row1 First row to be swapped
row2 Second row to be swapped
Todo:
MAKE ME PRIVATE OR ELSE!
Definition at line 79 of file BandedMatrix.cpp.
{
    // WE MUST HAVE row2 > row1 & row1 must have no elements left of the diagonal!
    // only of any use to native Gaussian elimination solver
    /// \todo MAKE ME PRIVATE OR ELSE!
    for(std::size_t col = row1; col <= std::min(row1 + 2 * m_L, m_N - 1); ++col) {
      std::swap(operator()(row1, col), operator()(row2, col));
    }
  }
scale()
template<typename _Type > void CppNoddy::BandedMatrix< _Type >::scale (const _Type & mult) virtual
Scale all entries in the matrix by a scalar.
Parameters
mult The scalar multiplier
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 52 of file BandedMatrix.cpp.
{
    m_storage *= mult;
  }
set()
template<typename _Type > _Type & CppNoddy::BandedMatrix< _Type >::set (const std::size_t & row, const std::size_t & col) inline virtual
Access operator.
Implements CppNoddy::Sequential_Matrix_base< _Type >.
Definition at line 211 of file BandedMatrix.h.
{
    return operator()(row, col);
  }
transpose()
template<typename _Type > void CppNoddy::BandedMatrix< _Type >::transpose
Transpose the matrix.
Definition at line 68 of file BandedMatrix.cpp.
{
    for(std::size_t row = 0; row < m_N; ++row) {
      for(std::size_t col = std::max(0, int(row) - int(m_L)); col < row; ++col) {
        // swap elements
        std::swap(operator()(row, col), operator()(col, row));
      }
    }
  }
two_norm()
template<typename _Type > double CppNoddy::BandedMatrix< _Type >::two_norm
Returns
The maximum two_norm of all rows
Definition at line 102 of file BandedMatrix.cpp.
{
    double max(0.0);
    for(unsigned row = 0; row < m_N; ++row) {
      // copy the row into a temp vector
      DenseVector<_Type> temp(3 * m_L + 1, &m_storage[ row * (3 * m_L + 1) ]);
      max = std::max(max, temp.two_norm());
    }
    return max;
  }
References CppNoddy::DenseVector< _Type >::two_norm().
Member Data Documentation
m_L
template<typename _Type > std::size_t CppNoddy::BandedMatrix< _Type >::m_L
Max number of (INPUT) bands above OR below the main diagonal.
Definition at line 138 of file BandedMatrix.h.
Referenced by CppNoddy::BandedMatrix< _Type >::BandedMatrix(), CppNoddy::BandedMatrix< _Type >::blank(), and CppNoddy::BandedMatrix< _Type >::get_elt_iter().
m_N
template<typename _Type > std::size_t CppNoddy::BandedMatrix< _Type >::m_N
The number of rows/cols in the matrix.
Definition at line 136 of file BandedMatrix.h.
Referenced by CppNoddy::BandedMatrix< _Type >::BandedMatrix(), and CppNoddy::BandedMatrix< _Type >::blank().
m_storage
template<typename _Type > DenseVector<_Type> CppNoddy::BandedMatrix< _Type >::m_storage
A contiguous vector.
Definition at line 134 of file BandedMatrix.h.
Referenced by CppNoddy::BandedMatrix< _Type >::assign(), CppNoddy::BandedMatrix< _Type >::BandedMatrix(), CppNoddy::BandedMatrix< _Type >::blank(), and CppNoddy::BandedMatrix< _Type >::get_elt_iter().
The documentation for this class was generated from the following files:
include/BandedMatrix.h
src/BandedMatrix.cpp
© 2012
R.E. Hewitt