CppNoddy: CppNoddy::Example::Shallow_2d_source Class Reference
CppNoddy::Example::Shallow_2d_source Class Reference
Define the system.
Public Member Functions
Shallow_2d_source ()
One dimemsional constant coefft acoustic problem.
void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
Define the vector flux.
void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
void Jac_flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the x-flux function.
void Jac_flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the y-flux function.
void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
Bound the wave speed.
std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
edge conditions
void source_fn (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &r) const
Public Member Functions inherited from CppNoddy::TwoD_Hyperbolic_System
TwoD_Hyperbolic_System (const unsigned &order)
virtual ~TwoD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the x-derivative.
virtual void flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function for the y-derivative.
virtual void Jac_flux_fn_x (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the x-flux function.
virtual void Jac_flux_fn_y (const DenseVector< double > &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the y-flux function.
virtual void max_charac_speed (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &c) const
A virtual method that is used to bound the characteristic speed in both directions.
virtual std::vector< bool > edge_values (const int &face_index, const DenseVector< double > &x, DenseVector< double > &q) const
Define the edge boundary conditions.
virtual void edge_slopes (const int &face_index, const DenseVector< double > &x, DenseVector< double > &sigma_n) const
Define the edge boundary condition slopes.
virtual void source_fn (const DenseVector< double > &x, const DenseVector< double > &q, DenseVector< double > &r) const
unsigned get_order ()
Additional Inherited Members
Protected Attributes inherited from CppNoddy::TwoD_Hyperbolic_System
const unsigned ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
Define the system.
Definition at line 39 of file HYP2DShallowSource.cpp.
Constructor & Destructor Documentation
Shallow_2d_source()
CppNoddy::Example::Shallow_2d_source::Shallow_2d_source () inline
One dimemsional constant coefft acoustic problem.
Definition at line 45 of file HYP2DShallowSource.cpp.
                          : TwoD_Hyperbolic_System( 3 )
      {}
Member Function Documentation
edge_values()
std::vector< bool > CppNoddy::Example::Shallow_2d_source::edge_values (const int & face_index, const DenseVector< double > & x, DenseVector< double > & q) const inline virtual
edge conditions
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 102 of file HYP2DShallowSource.cpp.
      {
        std::vector<bool> comps( q.size(), false );
        switch ( face_index )
        {
        case 1:
          q[ h ] = 0.33;
          comps[ h ] = true;
          break;
        case 3:
          q[ hu ] = 0.18;
          comps[ hu ] = true;
          break;
        }
        return comps;
      }
References h, hu, and CppNoddy::DenseVector< _Type >::size().
flux_fn_x()
void CppNoddy::Example::Shallow_2d_source::flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
Define the vector flux.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 49 of file HYP2DShallowSource.cpp.
      {
        f[ h ] = q[ hu ];
        f[ hu ] = q[ hu ] * q[ hu ] / q[ h ] + g * q[ h ] * q[ h ] / 2;
        f[ hv ] = q[ hu ] * q[ hv ] / q[ h ];
      }
References f, CppNoddy::Example::g(), h, hu, and hv.
flux_fn_y()
void CppNoddy::Example::Shallow_2d_source::flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function for the y-derivative.
Parameters
x The vector position
q The unknowns
f The flux function
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 56 of file HYP2DShallowSource.cpp.
      {
        f[ h ] = q[ hv ];
        f[ hu ] = q[ hu ] * q[ hv ] / q[ h ];
        f[ hv ] = q[ hv ] * q[ hv ] / q[ h ] + g * q[ h ] * q[ h ] / 2;
      }
References f, CppNoddy::Example::g(), h, hu, and hv.
Jac_flux_fn_x()
void CppNoddy::Example::Shallow_2d_source::Jac_flux_fn_x (const DenseVector< double > & x, const DenseVector< double > & q, DenseMatrix< double > & J) const inline virtual
A virtual function function to define the Jacobian of the x-flux function.
The default method uses first-order finite differencing to compute the Jacobian if not otherwise specified by the user.
Parameters
x The vector position
q The unknowns
J The Jacobian of the flux function
cheap & nasty differencing
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 64 of file HYP2DShallowSource.cpp.
      {
        J( 0, hu ) = 1;
        //
        J( 1, h  ) = - q[ hu ] * q[ hu ] / ( q[ h ] * q[ h ] ) + g * q[ h ];
        J( 1, hu ) = 2 * q[ hu ] / q[ h ];
        //
        J( 2, h  ) = - q[ hu ] * q[ hv ] / ( q[ h ] * q[ h ] );
        J( 2, hu ) = q[ hv ] / q[ h ];
        J( 2, hv ) = q[ hu ] / q[ h ];
      }
References CppNoddy::Example::g(), h, hu, and hv.
Jac_flux_fn_y()
void CppNoddy::Example::Shallow_2d_source::Jac_flux_fn_y (const DenseVector< double > & x, const DenseVector< double > & q, DenseMatrix< double > & J) const inline virtual
A virtual function function to define the Jacobian of the y-flux function.
The default method uses first-order finite differencing to compute the Jacobian if not otherwise specified by the user.
Parameters
x The vector position
q The unknowns
J The Jacobian of the flux function
cheap & nasty differencing
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 76 of file HYP2DShallowSource.cpp.
      {
        J( 0, hv ) = 1;
        //
        J( 1, h  ) = - q[ hu ] * q[ hv ] / ( q[ h ] * q[ h ] );
        J( 1, hu ) = q[ hv ] / q[ h ];
        J( 1, hv ) = q[ hu ] / q[ h ];
        //
        J( 2, h  ) = - q[ hv ] * q[ hv ] / ( q[ h ] * q[ h ] ) + g * q[ h ];
        J( 2, hv ) = 2 * q[ hv ] / q[ h ];
      }
References CppNoddy::Example::g(), h, hu, and hv.
max_charac_speed()
void CppNoddy::Example::Shallow_2d_source::max_charac_speed (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & c) const inline virtual
Bound the wave speed.
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 89 of file HYP2DShallowSource.cpp.
      {
        // wave speed
        double cc = sqrt( g * q[ h ] );
        // flow speed
        double U = q[ hu ] / q[ h ];
        double V = q[ hv ] / q[ h ];
        // maximum shock speed
        c[ 0 ] = std::max( std::abs( U + cc ), std::abs( U - cc ) );
        c[ 1 ] = std::max( std::abs( V + cc ), std::abs( V - cc ) );
      }
References CppNoddy::Example::g(), h, hu, hv, U, and V.
source_fn()
void CppNoddy::Example::Shallow_2d_source::source_fn (const DenseVector< double > & x, const DenseVector< double > & q, DenseVector< double > & r) const inline virtual
Reimplemented from CppNoddy::TwoD_Hyperbolic_System.
Definition at line 119 of file HYP2DShallowSource.cpp.
      {
        const double delta( 1.e-6 );
        r[ h ] = 0.0;
        r[ hu ] = - g * q[ h ] * ( z( x[0] + delta, x[1] ) - z( x[0], x[1] ) ) / delta;
        r[ hv ] = - g * q[ h ] * ( z( x[0], x[1] + delta ) - z( x[0], x[1] ) ) / delta;
      }
References CppNoddy::Example::delta(), CppNoddy::Example::g(), h, hu, hv, and CppNoddy::Example::z().
The documentation for this class was generated from the following file:
Tests/HYP_2D/HYP2DShallowSource.cpp
© 2012
R.E. Hewitt