CppNoddy: CppNoddy::Example::Nonidentity_equation< _Type, _Xtype > Class Template Reference
CppNoddy::Example::Nonidentity_equation< _Type, _Xtype > Class Template Reference
Define the harmonic equation by inheriting the Equation base class.
Public Member Functions
Nonidentity_equation ()
The harmonic equation is a 2nd order ODE.
void residual_fn (const DenseVector< _Type > &z, DenseVector< _Type > &g) const
The Berman equation.
void matrix0 (const DenseVector< _Type > &z, DenseMatrix< _Type > &m) const
Define the matrix in terms of the current state vector.
Public Member Functions inherited from CppNoddy::Equation_1matrix< _Type, _Xtype >
Equation_1matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_1matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< _Type > & matrix0 () const
Return a handle to the matrix.
virtual void get_jacobian_of_matrix0_mult_vector (const DenseVector< _Type > &state, const DenseVector< _Type > &vec, DenseMatrix< _Type > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Residual_with_coords< _Type, _Xtype >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
_Xtype & coord (const unsigned &i)
General handle access to the coordinates.
const _Xtype & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< _Type >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Residual object for the current set of state variables.
const DenseVector< _Type > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< _Type > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
_Type & delta ()
const _Type & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< _Type > &state, DenseVector< _Type > &f) const
A blank virtual residual function method.
Public Attributes
double gamma
Additional Inherited Members
virtual void matrix0 (const DenseVector< _Type > &x, DenseMatrix< _Type > &m) const
Define the matrix in terms of the current state vector.
Protected Member Functions inherited from CppNoddy::Residual< _Type >
virtual void jacobian (const DenseVector< _Type > &state, DenseMatrix< _Type > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual_with_coords< _Type, _Xtype >
std::vector< _Xtype > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< _Type >
DenseMatrix< _Type > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< _Type > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< _Type > LAST_STATE
The last state vector.
_Type DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
template<typename _Type, typename _Xtype>
class CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >
Define the harmonic equation by inheriting the Equation base class.
Definition at line 24 of file BVPNonIdentityMatrix0.cpp.
Constructor & Destructor Documentation
Nonidentity_equation()
template<typename _Type , typename _Xtype > CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >::Nonidentity_equation () inline
The harmonic equation is a 2nd order ODE.
Definition at line 31 of file BVPNonIdentityMatrix0.cpp.
: Equation_1matrix<_Type, _Xtype>(2) {}
Member Function Documentation
matrix0()
template<typename _Type , typename _Xtype > void CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >::matrix0 (const DenseVector< _Type > & x, DenseMatrix< _Type > & m) const inline virtual
Define the matrix in terms of the current state vector.
Parameters
x The current state vector.
m The matrix.
Reimplemented from CppNoddy::Equation_1matrix< _Type, _Xtype >.
Definition at line 41 of file BVPNonIdentityMatrix0.cpp.
      {
        m( 0, 0 ) = 1.0;
        m( 1, 1 ) = z[f];
      }
References f, m, and CppNoddy::Example::z().
residual_fn()
template<typename _Type , typename _Xtype > void CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >::residual_fn (const DenseVector< _Type > & z, DenseVector< _Type > & g) const inline virtual
The Berman equation.
Reimplemented from CppNoddy::Residual< _Type >.
Definition at line 34 of file BVPNonIdentityMatrix0.cpp.
      {
        const double y( this -> coord(0) );
        g[ f ] = z[ fd ];
        g[ fd ] = 1 + gamma*y - z[ fd ]*z[ fd ];
      }
References CppNoddy::Residual_with_coords< _Type, _Xtype >::coord(), f, fd, CppNoddy::Example::g(), CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >::gamma, and CppNoddy::Example::z().
Member Data Documentation
gamma
template<typename _Type , typename _Xtype > double CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >::gamma
Definition at line 28 of file BVPNonIdentityMatrix0.cpp.
Referenced by main(), and CppNoddy::Example::Nonidentity_equation< _Type, _Xtype >::residual_fn().
The documentation for this class was generated from the following file:
Tests/BVP/BVPNonIdentityMatrix0.cpp
© 2012
R.E. Hewitt