CppNoddy: CppNoddy::DenseVector< _Type > Class Template Reference
CppNoddy::DenseVector< _Type > Class Template Reference
An DenseVector class – a dense vector object.
#include <DenseVector.h>
Public Types
typedef std::vector< _Type >::iterator elt_iter
typedef std::vector< _Type >::const_iterator elt_citer
typedef std::vector< _Type >::reverse_iterator elt_riter
typedef std::vector< _Type >::const_reverse_iterator elt_criter
Public Member Functions
DenseVector ()
Constructor for a non-filled vector, to be filled by the user.
DenseVector (const std::size_t &size, const _Type &fill)
Constructor with specified fill-in initialization.
DenseVector (const std::size_t &size, const _Type *p)
Construct a Noddy vector from a contiguous set of real data.
template<typename _sourceType >
DenseVector (const DenseVector< _sourceType > &source)
A templated implicitly converting copy constructor.
DenseVector & operator= (const DenseVector &source)
Copy assignment.
~DenseVector ()
elt_iter begin ()
Pass through to the storage container.
elt_riter rbegin ()
Pass through to the storage container.
elt_citer begin () const
Pass through to the storage container.
elt_criter rbegin () const
Pass through to the storage container.
elt_iter end ()
Pass through to the storage container.
elt_citer end () const
Pass through to the storage container.
elt_riter rend ()
Pass through to the storage container.
elt_criter rend () const
Pass through to the storage container.
DenseVector< _Type > operator+ (const DenseVector< _Type > &x) const
Operator overloading for addition.
DenseVector< _Type > operator+ () const
Overloading for +.
DenseVector< _Type > operator- (const DenseVector< _Type > &x) const
Operator overloading for subtraction.
DenseVector< _Type > operator- () const
Overloading for -.
DenseVector< _Type > operator* (const _Type &m) const
Operator overloading for scalar multiplication.
DenseVector< _Type > operator/ (const _Type &m) const
Operaotr overloading for scalar division.
const _Type & operator[] (const std::size_t &i) const
Overloading of the [] operator.
_Type & operator[] (const std::size_t &i)
Overloading of the [] operator.
DenseVector< _Type > & operator*= (const _Type &m)
Overloading *= for scalar multiplication.
DenseVector< _Type > & operator/= (const _Type &m)
Overloading /= for scalar multiplication.
DenseVector< _Type > & operator-= (const DenseVector< _Type > &x)
Overloading the -= operator.
DenseVector< _Type > & operator+= (const DenseVector< _Type > &x)
Overloading the += operator.
void push_back (const _Type &fill)
A pass-thru definition of push_back.
void resize (const std::size_t &length)
A pass-thru definition of resize.
void assign (const std::size_t n, const _Type elem)
A pass-thru definition of assign.
void clear ()
A pass-thru definition of clear.
double one_norm () const
l1-norm.
double two_norm () const
l2-norm.
double inf_norm () const
Infinity norm.
void scale (const _Type &scale)
Scale each element of the vector, equivalent to *=.
void add (const DenseVector< _Type > &x)
Add a vector, element wise, equivalent to +=.
void sub (const DenseVector< _Type > &x)
Subtract a vector, element wise, equivalent to -=.
std::size_t size () const
A pass-thru definition to get the size of the vector.
std::size_t nelts () const
Get the number of elements in the vector Since the vector is dense, the number of elements is the size.
void reserve (const std::size_t &n)
Reserve space for the vector.
void swap (const std::size_t &i, const std::size_t &j)
Swap elements i and j.
void dump () const
Dump to std::cout.
void dump_file (std::string filename, int precision=10) const
Dump the contents to a file, each element on a separate line.
DenseVector (const DenseVector< double > &source)
DenseVector (const DenseVector< std::complex< double > > &source)
void dump_file (std::string filename, int precision) const
void dump_file (std::string filename, int precision) const
Friends
class BandedMatrix< _Type >
Detailed Description
template<typename _Type>
class CppNoddy::DenseVector< _Type >
An DenseVector class – a dense vector object.
This is templated but intended ONLY for double or std::complex<double>. We just encapsulate the STL vector container and pass through a few simple iterators whilst adding appropriate operator overloading and norms.
Definition at line 34 of file DenseVector.h.
Member Typedef Documentation
elt_citer
template<typename _Type > typedef std::vector<_Type>::const_iterator CppNoddy::DenseVector< _Type >::elt_citer
Definition at line 38 of file DenseVector.h.
elt_criter
template<typename _Type > typedef std::vector<_Type>::const_reverse_iterator CppNoddy::DenseVector< _Type >::elt_criter
Definition at line 40 of file DenseVector.h.
elt_iter
template<typename _Type > typedef std::vector<_Type>::iterator CppNoddy::DenseVector< _Type >::elt_iter
Definition at line 37 of file DenseVector.h.
elt_riter
template<typename _Type > typedef std::vector<_Type>::reverse_iterator CppNoddy::DenseVector< _Type >::elt_riter
Definition at line 39 of file DenseVector.h.
Constructor & Destructor Documentation
DenseVector() [1/6]
template<typename _Type > CppNoddy::DenseVector< _Type >::DenseVector
Constructor for a non-filled vector, to be filled by the user.
Definition at line 17 of file DenseVector.cpp.
  {}
DenseVector() [2/6]
template<typename _Type > CppNoddy::DenseVector< _Type >::DenseVector (const std::size_t & size, const _Type & fill)
Constructor with specified fill-in initialization.
Parameters
fill Data to be initialised to each entry
size The size of the vector to be instantiated
Definition at line 28 of file DenseVector.cpp.
                                                     : m_vec(size, fill)
  {}
DenseVector() [3/6]
template<typename _Type > CppNoddy::DenseVector< _Type >::DenseVector (const std::size_t & size, const _Type * p)
Construct a Noddy vector from a contiguous set of real data.
This will be nasty if you pass the wrong pointer, but is useful in interfacing with external libraries
Parameters
size The number of elements in the vector.
p A pointer to the start of the data.
Definition at line 21 of file DenseVector.cpp.
{
    m_vec.reserve(size);
    // assign the array contents to the vector
    m_vec.assign(p, p + size);
  }
References p.
DenseVector() [4/6]
template<typename _Type > template<typename _sourceType > CppNoddy::DenseVector< _Type >::DenseVector (const DenseVector< _sourceType > & source) inline
A templated implicitly converting copy constructor.
Note this is specialised for double to double and std::complex<double> to std::complex<double> copy construction.
Parameters
source The DenseVector to be used in the initialising.
Definition at line 62 of file DenseVector.h.
{
      // size the current vector
      m_vec.resize(source.size());
      elt_iter p_local(m_vec.begin());
      for(typename DenseVector<_sourceType>::elt_citer
          p_from = source.begin();
          p_from != source.end();
          ++p_from, ++p_local) {
        *p_local = *p_from;
      }
    }
~DenseVector()
template<typename _Type > CppNoddy::DenseVector< _Type >::~DenseVector inline
Definition at line 268 of file DenseVector.h.
  {}
DenseVector() [5/6]
CppNoddy::DenseVector< double >::DenseVector (const DenseVector< double > & source) inline
Definition at line 274 of file DenseVector.h.
{
    m_vec = source.m_vec;
  }
DenseVector() [6/6]
CppNoddy::DenseVector< std::complex< double > >::DenseVector (const DenseVector< std::complex< double > > & source) inline
Definition at line 280 of file DenseVector.h.
{
    m_vec = source.m_vec;
  }
Member Function Documentation
add()
template<typename _Type > void CppNoddy::DenseVector< _Type >::add (const DenseVector< _Type > & x)
Add a vector, element wise, equivalent to +=.
Parameters
x The vector to be added to this object.
Definition at line 38 of file DenseVector.cpp.
{
    operator+=(x);
  }
assign()
template<typename _Type > void CppNoddy::DenseVector< _Type >::assign (const std::size_t n, const _Type elem) inline
A pass-thru definition of assign.
Parameters
n The number of elements to assign
elem The element copy to be used in the assign
Definition at line 190 of file DenseVector.h.
{
      m_vec.assign(n, elem);
    }
begin() [1/2]
template<typename _Type > elt_iter CppNoddy::DenseVector< _Type >::begin () inline
Pass through to the storage container.
Definition at line 82 of file DenseVector.h.
                     {
      return m_vec.begin();
    }
Referenced by CppNoddy::Utility::dot(), main(), CppNoddy::DenseVector< _Type >::operator+=(), and CppNoddy::DenseVector< _Type >::operator-=().
begin() [2/2]
template<typename _Type > elt_citer CppNoddy::DenseVector< _Type >::begin () const inline
Pass through to the storage container.
Definition at line 92 of file DenseVector.h.
{
      return m_vec.begin();
    }
clear()
template<typename _Type > void CppNoddy::DenseVector< _Type >::clear inline
A pass-thru definition of clear.
Definition at line 320 of file DenseVector.h.
{
    m_vec.clear();
  }
dump()
template<typename _Type > void CppNoddy::DenseVector< _Type >::dump
Dump to std::cout.
Definition at line 64 of file DenseVector.cpp.
{
    std::cout << "size = " << size() << "\n";
    for(std::size_t i = 0; i < size(); ++i) {
      std::cout << m_vec[ i ] << ", ";
    }
    std::cout << "\n";
  }
Referenced by main().
dump_file() [1/3]
void CppNoddy::DenseVector< double >::dump_file (std::string filename, int precision) const
Definition at line 74 of file DenseVector.cpp.
{
    std::ofstream dump;
    dump.open(filename.c_str());
    dump.precision(precision);
    dump.setf(std::ios::showpoint);
    dump.setf(std::ios::showpos);
    dump.setf(std::ios::scientific);
    for(std::size_t i = 0; i < m_vec.size(); ++i) {
      dump << i << " " << m_vec[ i ] << "\n";
    }
  }
dump_file() [2/3]
void CppNoddy::DenseVector< std::complex< double > >::dump_file (std::string filename, int precision) const
Definition at line 87 of file DenseVector.cpp.
{
    std::ofstream dump;
    dump.open(filename.c_str());
    dump.precision(precision);
    dump.setf(std::ios::showpoint);
    dump.setf(std::ios::showpos);
    dump.setf(std::ios::scientific);
    for(std::size_t i = 0; i < m_vec.size(); ++i) {
      dump << i << " " << m_vec[ i ].real() << " " << m_vec[ i ].imag()  << "\n";
    }
  }
dump_file() [3/3]
template<typename _Type > void CppNoddy::DenseVector< _Type >::dump_file (std::string filename, int precision = 10) const
Dump the contents to a file, each element on a separate line.
Parameters
filename The name of the file to write to
precision Precision of the output strings
end() [1/2]
template<typename _Type > elt_iter CppNoddy::DenseVector< _Type >::end () inline
Pass through to the storage container.
Definition at line 102 of file DenseVector.h.
                   {
      return m_vec.end();
    }
Referenced by CppNoddy::Utility::dot(), and main().
end() [2/2]
template<typename _Type > elt_citer CppNoddy::DenseVector< _Type >::end () const inline
Pass through to the storage container.
Definition at line 107 of file DenseVector.h.
{
      return m_vec.end();
    }
inf_norm()
template<typename _Type > double CppNoddy::DenseVector< _Type >::inf_norm
Infinity norm.
Returns
The maximum (abs) element in the vector.
Definition at line 59 of file DenseVector.cpp.
{
    return std::abs(*max_element(begin(), end(), abs_predicate<_Type>()));
  }
Referenced by CppNoddy::ODE_BVP< _Type, _Xtype >::adapt(), CppNoddy::ODE_BVP< _Type, _Xtype >::arclength_solve(), CppNoddy::Newton< _Type >::arclength_solve(), CppNoddy::reversed_BL< _Type >::bidirectional_step2(), CppNoddy::BandedMatrix< _Type >::inf_norm(), main(), CppNoddy::PDE_double_IBVP< _Type >::step2(), CppNoddy::PDE_IBVP< _Type >::step2(), and CppNoddy::reversed_BL< _Type >::step2().
nelts()
template<typename _Type > std::size_t CppNoddy::DenseVector< _Type >::nelts inline
Get the number of elements in the vector Since the vector is dense, the number of elements is the size.
Returns
The number of elements in the vector.
Definition at line 335 of file DenseVector.h.
{
    return m_vec.size();
  }
Referenced by main().
one_norm()
template<typename _Type > double CppNoddy::DenseVector< _Type >::one_norm
l1-norm.
Returns
The square-root of the sum of the squares.
Definition at line 49 of file DenseVector.cpp.
{
    return accumulate(begin(), end(), 0.0, absAdd_functor<_Type>());
  }
Referenced by main(), and CppNoddy::BandedMatrix< _Type >::one_norm().
operator*()
template<typename _Type > DenseVector< _Type > CppNoddy::DenseVector< _Type >::operator* (const _Type & m) const inline
Operator overloading for scalar multiplication.
Parameters
m The scalar multiplier
Returns
The 'this' vector scaled by the constant 'm'
Definition at line 345 of file DenseVector.h.
{
    DenseVector<_Type> temp(*this);
    temp *= m;
    return temp;
  }
References m.
operator*=()
template<typename _Type > DenseVector< _Type > & CppNoddy::DenseVector< _Type >::operator*= (const _Type & m) inline
Overloading *= for scalar multiplication.
Parameters
m The scalar multiplier
Returns
A reference to the 'this' vector multiplied by the scalar
Definition at line 352 of file DenseVector.h.
{
    // run thru m_vec from begin to end, transforming into
    // m_vec container starting from begin using functor
    std::transform(m_vec.begin(), m_vec.end(), m_vec.begin(), scale_functor<_Type, _Type>(m));
    return *this;
  }
References m.
operator+() [1/2]
template<typename _Type > DenseVector< _Type > CppNoddy::DenseVector< _Type >::operator+ inline
Overloading for +.
Returns
+this
Definition at line 325 of file DenseVector.h.
{
    return * this;
  }
operator+() [2/2]
template<typename _Type > DenseVector< _Type > CppNoddy::DenseVector< _Type >::operator+ (const DenseVector< _Type > & x) const inline
Operator overloading for addition.
Parameters
x The dense vector to be added
Returns
The sum of 'this' and x
Definition at line 425 of file DenseVector.h.
{
#ifdef PARANOID
    if(x.size() != size()) {
      std::string problem;
      problem = " The DenseVector.operator+ method is trying to use \n";
      problem += " two vectors of unequal length \n";
      throw ExceptionGeom(problem, size(), x.size());
    }
#endif
    DenseVector<_Type> temp(*this);
    temp += x;
    return temp;
  }
References CppNoddy::DenseVector< _Type >::size().
operator+=()
template<typename _Type > DenseVector< _Type > & CppNoddy::DenseVector< _Type >::operator+= (const DenseVector< _Type > & x) inline
Overloading the += operator.
Parameters
x A dense vector that will be added to 'this'
Returns
A reference to the 'this' vector after addition by x
Definition at line 389 of file DenseVector.h.
{
#ifdef PARANOID
    if(x.size() != size()) {
      std::string problem;
      problem = " The DenseVector.operator+= method is trying to use \n";
      problem += " two vectors of unequal length \n";
      throw ExceptionGeom(problem, size(), x.size());
    }
#endif
    std::transform(m_vec.begin(), m_vec.end(), x.begin(), m_vec.begin(), std::plus<_Type>());
    return *this;
  }
References CppNoddy::DenseVector< _Type >::begin(), and CppNoddy::DenseVector< _Type >::size().
operator-() [1/2]
template<typename _Type > DenseVector< _Type > CppNoddy::DenseVector< _Type >::operator- inline
Overloading for -.
Returns
-this
Definition at line 418 of file DenseVector.h.
{
    DenseVector<_Type> temp(*this);
    temp *= -1;
    return temp;
  }
operator-() [2/2]
template<typename _Type > DenseVector< _Type > CppNoddy::DenseVector< _Type >::operator- (const DenseVector< _Type > & x) const inline
Operator overloading for subtraction.
Parameters
x The dense vector to be subtracted from 'this'
Returns
The subtraction of x from 'this'
Definition at line 403 of file DenseVector.h.
{
#ifdef PARANOID
    if(x.size() != size()) {
      std::string problem;
      problem = " The DenseVector.operator- method is trying to use \n";
      problem += " two vectors of unequal length \n";
      throw ExceptionGeom(problem, size(), x.size());
    }
#endif
    DenseVector<_Type> temp(*this);
    temp -= x;
    return temp;
  }
References CppNoddy::DenseVector< _Type >::size().
operator-=()
template<typename _Type > DenseVector< _Type > & CppNoddy::DenseVector< _Type >::operator-= (const DenseVector< _Type > & x) inline
Overloading the -= operator.
Parameters
x A dense vector that will be subtracted from 'this'
Returns
A reference to the 'this' vector after subtraction by x
Definition at line 375 of file DenseVector.h.
{
#ifdef PARANOID
    if(x.size() != size()) {
      std::string problem;
      problem = " The DenseVector.operator-= method is trying to use \n";
      problem += " two vectors of unequal length \n";
      throw ExceptionGeom(problem, size(), x.size());
    }
#endif
    std::transform(m_vec.begin(), m_vec.end(), x.begin(), m_vec.begin(), std::minus<_Type>());
    return *this;
  }
References CppNoddy::DenseVector< _Type >::begin(), and CppNoddy::DenseVector< _Type >::size().
operator/()
template<typename _Type > DenseVector< _Type > CppNoddy::DenseVector< _Type >::operator/ (const _Type & m) const inline
Operaotr overloading for scalar division.
Parameters
m The scalar divisor
Returns
The 'this' vector divided by the constant 'm'
Definition at line 360 of file DenseVector.h.
{
    DenseVector<_Type> temp(*this);
    temp *= (1. / m);
    return temp;
  }
References m.
operator/=()
template<typename _Type > DenseVector< _Type > & CppNoddy::DenseVector< _Type >::operator/= (const _Type & m) inline
Overloading /= for scalar multiplication.
Parameters
m The scalar divisor
Returns
A reference to the 'this' vector divided by the scalar
Definition at line 367 of file DenseVector.h.
{
    // run thru m_vecfrom begin to end, transforming into
    // m_vec container starting from begin using functor
    std::transform(m_vec.begin(), m_vec.end(), m_vec.begin(), scale_functor<_Type, _Type>(1.0 / m));
    return *this;
  }
References m.
operator=()
template<typename _Type > DenseVector< _Type > & CppNoddy::DenseVector< _Type >::operator= (const DenseVector< _Type > & source) inline
Copy assignment.
Parameters
source Object to copy
Returns
The new object
Definition at line 440 of file DenseVector.h.
{
    if(this == &source)
      return *this;
    m_vec = source.m_vec;
    return *this;
  }
operator[]() [1/2]
template<typename _Type > _Type & CppNoddy::DenseVector< _Type >::operator[] (const std::size_t & i) inline
Overloading of the [] operator.
Parameters
i The index of the element to be accessed
Returns
The element stored at index i (read/write)
Definition at line 285 of file DenseVector.h.
{
#ifdef PARANOID
    if((i < 0) || (i >= size())) {
      std::string problem;
      problem = " The DenseVector.operator[] method has a range error. \n";
      throw ExceptionRange(problem, size(), i);
    }
#endif
    return m_vec[ i ];
  }
operator[]() [2/2]
template<typename _Type > const _Type & CppNoddy::DenseVector< _Type >::operator[] (const std::size_t & i) const inline
Overloading of the [] operator.
Parameters
i The index of the element to be accessed
Returns
The element stored at index i (read only)
Definition at line 297 of file DenseVector.h.
{
#ifdef PARANOID
    if((i < 0) || (i >= size())) {
      std::string problem;
      problem = " The DenseVector.operator[] method has a range error. \n";
      throw ExceptionRange(problem, size(), i);
    }
#endif
    return m_vec[ i ];
  }
push_back()
template<typename _Type > void CppNoddy::DenseVector< _Type >::push_back (const _Type & fill) inline
A pass-thru definition of push_back.
Parameters
fill The data element to be pushed into the vector
Definition at line 310 of file DenseVector.h.
{
    m_vec.push_back(fill);
  }
Referenced by CppNoddy::ODE_BVP< _Type, _Xtype >::adapt(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::find_roots1(), CppNoddy::FnQuadrature::Gauss(), CppNoddy::OneD_TVDLF_Mesh::get_face_pos_vector(), CppNoddy::OneD_TVDLF_Mesh::get_mid_node_vector(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_nodes_vars(), CppNoddy::DenseLinearEigenSystem< _Type >::get_tagged_eigenvalues(), CppNoddy::LinearEigenSystem_base::get_tagged_eigenvalues(), main(), CppNoddy::TwoD_TVDLF_Mesh::maxmod(), CppNoddy::TwoD_TVDLF_Mesh::minmod(), CppNoddy::ODE_IVP< _Type >::shoot45(), CppNoddy::ODE_IVP< double >::store_every(), CppNoddy::Utility::three_uniform_node_vector(), CppNoddy::Utility::two_uniform_node_vector(), and CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
rbegin() [1/2]
template<typename _Type > elt_riter CppNoddy::DenseVector< _Type >::rbegin () inline
Pass through to the storage container.
Definition at line 87 of file DenseVector.h.
                       {
      return m_vec.rbegin();
    }
rbegin() [2/2]
template<typename _Type > elt_criter CppNoddy::DenseVector< _Type >::rbegin () const inline
Pass through to the storage container.
Definition at line 97 of file DenseVector.h.
{
      return m_vec.rbegin();
    }
rend() [1/2]
template<typename _Type > elt_riter CppNoddy::DenseVector< _Type >::rend () inline
Pass through to the storage container.
Definition at line 112 of file DenseVector.h.
                     {
      return m_vec.rend();
    }
rend() [2/2]
template<typename _Type > elt_criter CppNoddy::DenseVector< _Type >::rend () const inline
Pass through to the storage container.
Definition at line 117 of file DenseVector.h.
{
      return m_vec.rend();
    }
reserve()
template<typename _Type > void CppNoddy::DenseVector< _Type >::reserve (const std::size_t & n) inline
Reserve space for the vector.
Parameters
n The number of elements to reserve space for
Definition at line 340 of file DenseVector.h.
{
    m_vec.reserve(n);
  }
Referenced by CppNoddy::TwoD_Node_Mesh< _Type >::TwoD_Node_Mesh().
resize()
template<typename _Type > void CppNoddy::DenseVector< _Type >::resize (const std::size_t & length) inline
A pass-thru definition of resize.
Parameters
length The target length after resizing
Definition at line 315 of file DenseVector.h.
{
    m_vec.resize(length);
  }
scale()
template<typename _Type > void CppNoddy::DenseVector< _Type >::scale (const _Type & scale)
Scale each element of the vector, equivalent to *=.
Parameters
scale The value to scale each element by.
Definition at line 33 of file DenseVector.cpp.
{
    operator*=(m);
  }
References m.
Referenced by CppNoddy::FnQuadrature::Gauss().
size()
template<typename _Type > std::size_t CppNoddy::DenseVector< _Type >::size inline
A pass-thru definition to get the size of the vector.
Since the vector is dense, the number of elements is the size.
Returns
The number of elements in the vector.
Definition at line 330 of file DenseVector.h.
{
    return m_vec.size();
  }
Referenced by CppNoddy::ODE_EVP< _Type >::add_tagged_to_mesh(), CppNoddy::ArcLength_base< _Type >::arclength_residual(), CppNoddy::Utility::dot(), CppNoddy::Example::Shallow_2d_source::edge_values(), CppNoddy::Example::Acoustic_1d_ref::edge_values(), CppNoddy::Example::NlinAdv::edge_values(), Utils_Fill::fill(), CppNoddy::FnQuadrature::Gauss(), CppNoddy::OneD_TVDLF_Mesh::get_slope(), CppNoddy::OneD_TVDLF_Mesh::get_soln(), CppNoddy::Utility::imag(), CppNoddy::Newton< _Type >::iterate(), CppNoddy::ArcLength_base< _Type >::Jac_arclength_residual(), main(), CppNoddy::TwoD_Node_Mesh< _Type >::max_abs(), CppNoddy::ODE_EVP< _Type >::ODE_EVP(), CppNoddy::OneD_TVDLF_Mesh::OneD_TVDLF_Mesh(), CppNoddy::DenseVector< _Type >::operator+(), CppNoddy::DenseVector< _Type >::operator+=(), CppNoddy::DenseVector< _Type >::operator-(), CppNoddy::DenseVector< _Type >::operator-=(), CppNoddy::Utility::real(), CppNoddy::TwoD_Node_Mesh< _Type >::remesh1(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::set_vars_from_vector(), CppNoddy::ODE_IVP< _Type >::shoot45(), CppNoddy::OneD_Node_Mesh< double >::squared_integral2(), CppNoddy::FnQuadrature::sub_Gauss(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_all(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_disc(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_left(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_lower(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_right(), CppNoddy::LinearEigenSystem_base::tag_eigenvalues_upper(), CppNoddy::FnQuadrature::trapezium(), CppNoddy::TwoD_TVDLF_Mesh::TwoD_TVDLF_Mesh(), and CppNoddy::ArcLength_base< _Type >::update_theta().
sub()
template<typename _Type > void CppNoddy::DenseVector< _Type >::sub (const DenseVector< _Type > & x)
Subtract a vector, element wise, equivalent to -=.
Parameters
x The vector to be subtracted from this object.
Definition at line 44 of file DenseVector.cpp.
{
    operator-=(x);
  }
Referenced by main().
swap()
template<typename _Type > void CppNoddy::DenseVector< _Type >::swap (const std::size_t & i, const std::size_t & j)
Swap elements i and j.
Parameters
i The index of the element to swap.
j The index of the other element to swap.
Definition at line 100 of file DenseVector.cpp.
{
#ifdef PARANOID
    if((i >= size()) || (j >= size())) {
      std::string problem;
      problem = " The DenseVector.swap method is trying to access \n";
      problem += " outside the max/min number of elements. \n";
      if(i > size())
        throw ExceptionRange(problem, size(), i);
      if(j > size())
        throw ExceptionRange(problem, size(), j);
    }
#endif
    std::swap<_Type>(m_vec[ i ], m_vec[ j ]);
  }
two_norm()
template<typename _Type > double CppNoddy::DenseVector< _Type >::two_norm
l2-norm.
No attention paid to possible overflow for large vectors.
Returns
The square-root of the sum of the squares.
Definition at line 54 of file DenseVector.cpp.
{
    return std::sqrt(accumulate(begin(), end(), 0.0, absSquareAdd_functor<_Type>()));
  }
Referenced by CppNoddy::BandedMatrix< _Type >::frob_norm(), main(), and CppNoddy::BandedMatrix< _Type >::two_norm().
Friends And Related Function Documentation
BandedMatrix< _Type >
template<typename _Type > friend class BandedMatrix< _Type > friend
Definition at line 249 of file DenseVector.h.
The documentation for this class was generated from the following files:
include/DenseVector.h
src/DenseVector.cpp
© 2012
R.E. Hewitt