CppNoddy: CppNoddy::LinearEigenSystem_base Class Reference
CppNoddy::LinearEigenSystem_base Class Reference
A linear Nth-order generalised eigensystem base class.
#include <LinearEigenSystem_base.h>
Public Member Functions
LinearEigenSystem_base ()
Constructor for a linear system object.
virtual ~LinearEigenSystem_base ()
Destructor for a linear system object.
virtual void eigensolve ()
Solve the matrix linear eigensystem.
void set_calc_eigenvectors (bool flag)
Compute the eigenvectors in any eigenvalue computation.
void set_shift (const D_complex &z)
Set the shift value to be used in tagging.
D_complex get_shift () const
Get the shift value associated with this class (used for tagging) and eigenvalue tagging.
virtual void tag_eigenvalues_right (const int &val)
Tag those eigenvalues that are to the right of a specified shft point.
virtual void tag_eigenvalues_left (const int &val)
Tag those eigenvalues that are to the left of a specified point.
virtual void tag_eigenvalues_upper (const int &val)
Tag those eigenvalues that are in the upper half-plane above a specified point.
virtual void tag_eigenvalues_lower (const int &val)
Tag those eigenvalues that are in the lower half-plane below a specified point.
virtual void tag_eigenvalues_disc (const int &val, const double &radius)
Tag those eigenvalues that are within a disc centred at a point in the complex plane.
virtual void tag_eigenvalues_all ()
Tag all the eigenvalues returned from the ARPACK routine.
virtual void clear_all_tags ()
virtual DenseVector< D_complex > get_tagged_eigenvalues () const
Get the the tagged eigenvalues.
virtual DenseMatrix< D_complex > get_tagged_eigenvectors () const
Get the the tagged eigenvectors.
Protected Types
typedef std::set< unsigned, std::less< unsigned > >::iterator iter
typedef std::set< unsigned, std::less< unsigned > >::const_iterator citer
Protected Attributes
DenseVector< D_complex > m_all_eigenvalues
storage for eigenvectors and eigenvalues
DenseMatrix< D_complex > m_all_eigenvectors
std::set< unsigned, std::less< unsigned > > m_tagged_indices
a set of tagged eigenvalue indices
D_complex m_shift
The complex shift value.
bool m_calc_eigenvectors
calculate the eigenvectors in any eigenvalue computation
Detailed Description
A linear Nth-order generalised eigensystem base class.
Here we can construct a linear eigenproblem in the form
for matrices and . The eigenvalues and eigenvectors can be tagged and retrieved as required.
Definition at line 18 of file LinearEigenSystem_base.h.
Member Typedef Documentation
citer
typedef std::set< unsigned, std::less<unsigned> >::const_iterator CppNoddy::LinearEigenSystem_base::citer protected
Definition at line 25 of file LinearEigenSystem_base.h.
iter
typedef std::set< unsigned, std::less<unsigned> >::iterator CppNoddy::LinearEigenSystem_base::iter protected
Definition at line 23 of file LinearEigenSystem_base.h.
Constructor & Destructor Documentation
LinearEigenSystem_base()
CppNoddy::LinearEigenSystem_base::LinearEigenSystem_base ()
Constructor for a linear system object.
Definition at line 14 of file LinearEigenSystem_base.cpp.
                                                  :
     m_shift(D_complex(0., 0.)),
     m_calc_eigenvectors(true) {
   }
~LinearEigenSystem_base()
CppNoddy::LinearEigenSystem_base::~LinearEigenSystem_base () virtual
Destructor for a linear system object.
Definition at line 20 of file LinearEigenSystem_base.cpp.
   {}
Member Function Documentation
clear_all_tags()
virtual void CppNoddy::LinearEigenSystem_base::clear_all_tags () inline virtual
Definition at line 79 of file LinearEigenSystem_base.h.
{
       m_tagged_indices.clear();
     }
References m_tagged_indices.
eigensolve()
void CppNoddy::LinearEigenSystem_base::eigensolve () virtual
Solve the matrix linear eigensystem.
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 34 of file LinearEigenSystem_base.cpp.
{
     std::string problem;
     problem = "The LinearEigenSystem_base::eigensolve method has been called\n";
     problem += "but the method has not been implemented ... this should be \n";
     problem += "implemented in the sub-class.";
     throw ExceptionExternal(problem);
   }
get_shift()
std::complex< double > CppNoddy::LinearEigenSystem_base::get_shift () const
Get the shift value associated with this class (used for tagging) and eigenvalue tagging.
Definition at line 29 of file LinearEigenSystem_base.cpp.
{
     return m_shift;
   }
References m_shift.
get_tagged_eigenvalues()
DenseVector< D_complex > CppNoddy::LinearEigenSystem_base::get_tagged_eigenvalues () const virtual
Get the the tagged eigenvalues.
All of the tagged eigenvalues are returned in a complex vector, with no ordering guaranteed.
Returns
The tagged eigenvalues as a complex vector
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 48 of file LinearEigenSystem_base.cpp.
{
     if(m_tagged_indices.size() == 0) {
       std::string problem;
       problem = "In LinearEigenSystem_base.get_tagged_eigenvalues() : there are\n";
       problem += "no eigenvalues that have been tagged. This set is empty.\n";
       throw ExceptionRuntime(problem);
     }
     // storage for the eigenvalues
     DenseVector<D_complex> evals;
     // loop through the tagged set
     for(iter p = m_tagged_indices.begin(); p != m_tagged_indices.end(); ++p) {
       // get the index of the relevant eigenvalue from the set
       std::size_t j = *p;
       std::cout << " number " << j << " is a tagged ev.\n";
       // work out the complex eigenvalue associated with this index
       // and add it to the vector
       evals.push_back(m_all_eigenvalues[ j ]);
     }
     // return the complex vector of eigenvalues
     return evals;
   }
References m_all_eigenvalues, m_tagged_indices, p, and CppNoddy::DenseVector< _Type >::push_back().
get_tagged_eigenvectors()
DenseMatrix< D_complex > CppNoddy::LinearEigenSystem_base::get_tagged_eigenvectors () const virtual
Get the the tagged eigenvectors.
All of the eigenvectors associated with the tagged eigenvalues are returned, with the i-th eigenvector corresponding to the i-th eigenvalue as returned by the get_tagged_eigenvalues method. The i-th eigenvector is returned in row i of the complex dense matrix.
Returns
The tagged eigenvectors as a complex matrix
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 71 of file LinearEigenSystem_base.cpp.
{
     if(m_tagged_indices.size() == 0) {
       std::string problem;
       problem = "In LinearEigenSystem_base.get_tagged_eigenvectors() : there are\n";
       problem += "no eigenvalues that have been tagged. This set is empty.\n";
       throw ExceptionRuntime(problem);
     }
     // number of degrees of freedom in each eigenvector
     std::size_t n = m_all_eigenvectors[0].size();
     // eigenvector storage : size() eigenvectors each of length n
     DenseMatrix<D_complex> evecs(m_tagged_indices.size(), n, 0.0);
     std::size_t row = 0;
     // loop through the tagged set
     for(iter p = m_tagged_indices.begin(); p != m_tagged_indices.end(); ++p) {
       // get the index of the relevant eigenvalue from the set
       std::size_t j = *p;
       // put the eigenvector in the matrix
       evecs[ row ] = m_all_eigenvectors[ j ];
       // next row/eigenvector
       ++row;
     }
     return evecs;
   }
References m_all_eigenvectors, m_tagged_indices, and p.
set_calc_eigenvectors()
void CppNoddy::LinearEigenSystem_base::set_calc_eigenvectors (bool flag)
Compute the eigenvectors in any eigenvalue computation.
Parameters
flag The boolean value to set.
Definition at line 43 of file LinearEigenSystem_base.cpp.
{
     m_calc_eigenvectors = flag;
   }
References m_calc_eigenvectors.
Referenced by main().
set_shift()
void CppNoddy::LinearEigenSystem_base::set_shift (const D_complex & z)
Set the shift value to be used in tagging.
Parameters
z The shift value to be used
Definition at line 24 of file LinearEigenSystem_base.cpp.
{
     m_shift = z;
   }
References m_shift, and CppNoddy::Example::z().
Referenced by CppNoddy::HST::Rayleigh< _Type >::global_evp(), and main().
tag_eigenvalues_all()
void CppNoddy::LinearEigenSystem_base::tag_eigenvalues_all () virtual
Tag all the eigenvalues returned from the ARPACK routine.
Definition at line 98 of file LinearEigenSystem_base.cpp.
{
     for(unsigned i = 0; i < m_all_eigenvalues.size(); ++i) {
       m_tagged_indices.insert(m_tagged_indices.end(), i);
     }
     std::cout << "** I have tagged " << m_all_eigenvalues.size() << " eigenvalues.\n";
   }
References m_all_eigenvalues, m_tagged_indices, and CppNoddy::DenseVector< _Type >::size().
tag_eigenvalues_disc()
void CppNoddy::LinearEigenSystem_base::tag_eigenvalues_disc (const int & val, const double & radius) virtual
Tag those eigenvalues that are within a disc centred at a point in the complex plane.
Parameters
val Tags are added or removed for val +ve or -ve
radius The radius of the disc to be considered
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 106 of file LinearEigenSystem_base.cpp.
{
     // loop through all the eigenvalues
     for(std::size_t i = 0; i < m_all_eigenvalues.size(); ++i) {
       // if the eigenvalue is in the disc centred at shift then include it
       if(std::abs(m_all_eigenvalues[ i ] - m_shift) < radius) {
         if(val > 0) {
           // add it to our set of tagged eigenvalues
           m_tagged_indices.insert(m_tagged_indices.end(), i);
         } else {
           // remove it from the set if it exists
           m_tagged_indices.erase(i);
         }
       }
     }
   }
References m_all_eigenvalues, m_shift, m_tagged_indices, and CppNoddy::DenseVector< _Type >::size().
tag_eigenvalues_left()
void CppNoddy::LinearEigenSystem_base::tag_eigenvalues_left (const int & val) virtual
Tag those eigenvalues that are to the left of a specified point.
Parameters
val Tags are added or removed for val +ve or -ve
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 140 of file LinearEigenSystem_base.cpp.
{
     // loop through all the eigenvalues
     for(std::size_t i = 0; i < m_all_eigenvalues.size(); ++i) {
       // if the eigenvalue is in the disc centred at m_shift then include it
       if((m_all_eigenvalues[ i ] - m_shift).real() < 0.0) {
         if(val > 0) {
           // add it to our set of tagged eigenvalues
           m_tagged_indices.insert(m_tagged_indices.end(), i);
         } else {
           // remove it from the set if it exists
           m_tagged_indices.erase(i);
         }
       }
     }
   }
References m_all_eigenvalues, m_shift, m_tagged_indices, CppNoddy::Utility::real(), and CppNoddy::DenseVector< _Type >::size().
tag_eigenvalues_lower()
void CppNoddy::LinearEigenSystem_base::tag_eigenvalues_lower (const int & val) virtual
Tag those eigenvalues that are in the lower half-plane below a specified point.
Parameters
val Tags are added or removed for val +ve or -ve
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 173 of file LinearEigenSystem_base.cpp.
{
     // loop through all the eigenvalues
     for(std::size_t i = 0; i < m_all_eigenvalues.size(); ++i) {
       // if the eigenvalue is in the disc centred at m_shift then include it
       if((m_all_eigenvalues[ i ] - m_shift).imag() < 0.0) {
         if(val > 0) {
           // add it to our set of tagged eigenvalues
           m_tagged_indices.insert(m_tagged_indices.end(), i);
         } else {
           // remove it from the set if it exists
           m_tagged_indices.erase(i);
         }
       }
     }
   }
References CppNoddy::Utility::imag(), m_all_eigenvalues, m_shift, m_tagged_indices, and CppNoddy::DenseVector< _Type >::size().
tag_eigenvalues_right()
void CppNoddy::LinearEigenSystem_base::tag_eigenvalues_right (const int & val) virtual
Tag those eigenvalues that are to the right of a specified shft point.
Parameters
val Tags are added or removed for val +ve or -ve
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 123 of file LinearEigenSystem_base.cpp.
{
     // loop through all the eigenvalues
     for(std::size_t i = 0; i < m_all_eigenvalues.size(); ++i) {
       // if the eigenvalue is in the disc centred at m_shift then include it
       if((m_all_eigenvalues[ i ] - m_shift).real() > 0.0) {
         if(val > 0) {
           // add it to our set of tagged eigenvalues
           m_tagged_indices.insert(m_tagged_indices.end(), i);
         } else {
           // remove it from the set if it exists
           m_tagged_indices.erase(i);
         }
       }
     }
   }
References m_all_eigenvalues, m_shift, m_tagged_indices, CppNoddy::Utility::real(), and CppNoddy::DenseVector< _Type >::size().
tag_eigenvalues_upper()
void CppNoddy::LinearEigenSystem_base::tag_eigenvalues_upper (const int & val) virtual
Tag those eigenvalues that are in the upper half-plane above a specified point.
Parameters
val Tags are added or removed for val +ve or -ve
Reimplemented in CppNoddy::DenseLinearEigenSystem< _Type >.
Definition at line 157 of file LinearEigenSystem_base.cpp.
{
     // loop through all the eigenvalues
     for(std::size_t i = 0; i < m_all_eigenvalues.size(); ++i) {
       // if the eigenvalue is in the disc centred at m_shift then include it
       if((m_all_eigenvalues[ i ] - m_shift).imag() > 0.0) {
         if(val > 0) {
           // add it to our set of tagged eigenvalues
           m_tagged_indices.insert(m_tagged_indices.end(), i);
         } else {
           // remove it from the set if it exists
           m_tagged_indices.erase(i);
         }
       }
     }
   }
References CppNoddy::Utility::imag(), m_all_eigenvalues, m_shift, m_tagged_indices, and CppNoddy::DenseVector< _Type >::size().
Member Data Documentation
m_all_eigenvalues
DenseVector<D_complex> CppNoddy::LinearEigenSystem_base::m_all_eigenvalues protected
storage for eigenvectors and eigenvalues
Definition at line 98 of file LinearEigenSystem_base.h.
Referenced by get_tagged_eigenvalues(), tag_eigenvalues_all(), tag_eigenvalues_disc(), tag_eigenvalues_left(), tag_eigenvalues_lower(), tag_eigenvalues_right(), and tag_eigenvalues_upper().
m_all_eigenvectors
DenseMatrix<D_complex> CppNoddy::LinearEigenSystem_base::m_all_eigenvectors protected
Definition at line 99 of file LinearEigenSystem_base.h.
Referenced by get_tagged_eigenvectors().
m_calc_eigenvectors
bool CppNoddy::LinearEigenSystem_base::m_calc_eigenvectors protected
calculate the eigenvectors in any eigenvalue computation
Definition at line 109 of file LinearEigenSystem_base.h.
Referenced by set_calc_eigenvectors().
m_shift
D_complex CppNoddy::LinearEigenSystem_base::m_shift protected
The complex shift value.
Definition at line 106 of file LinearEigenSystem_base.h.
Referenced by get_shift(), set_shift(), tag_eigenvalues_disc(), tag_eigenvalues_left(), tag_eigenvalues_lower(), tag_eigenvalues_right(), and tag_eigenvalues_upper().
m_tagged_indices
std::set< unsigned, std::less<unsigned> > CppNoddy::LinearEigenSystem_base::m_tagged_indices protected
a set of tagged eigenvalue indices
Definition at line 103 of file LinearEigenSystem_base.h.
Referenced by clear_all_tags(), get_tagged_eigenvalues(), get_tagged_eigenvectors(), tag_eigenvalues_all(), tag_eigenvalues_disc(), tag_eigenvalues_left(), tag_eigenvalues_lower(), tag_eigenvalues_right(), and tag_eigenvalues_upper().
The documentation for this class was generated from the following files:
include/LinearEigenSystem_base.h
src/LinearEigenSystem_base.cpp
© 2012
R.E. Hewitt