CppNoddy: CppNoddy::Example::Neutral_residual Class Reference
CppNoddy::Example::Neutral_residual Class Reference
Public Member Functions
Neutral_residual (const unsigned &initial_N)
~Neutral_residual ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &f) const
A blank virtual residual function method.
Public Member Functions inherited from CppNoddy::Residual< double >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Residual object for the current set of state variables.
const DenseVector< double > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< double > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
double & delta ()
const double & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< double > &state, DenseVector< double > &f) const
A blank virtual residual function method.
Public Attributes
ODE_BVP< D_complex > * ode_local
OS_bvp_equation * bvp
OS_bvp_left_BC * BC_left
OS_bvp_right_BC * BC_right
Additional Inherited Members
Protected Member Functions inherited from CppNoddy::Residual< double >
virtual void jacobian (const DenseVector< double > &state, DenseMatrix< double > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual< double >
DenseMatrix< double > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< double > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< double > LAST_STATE
The last state vector.
double DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Definition at line 155 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
Constructor & Destructor Documentation
Neutral_residual()
CppNoddy::Example::Neutral_residual::Neutral_residual (const unsigned & initial_N) inline
Definition at line 160 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
                                                    : Residual<double>( 1 )
      {
        // instantiate the object by doing a rough QZ pass of the eigenvalues
        OS_evp_equation evp;
        // instantiate the BCs
        OS_evp_both_BC BC_both;
        // domain is -1 to 1
        double left = -1.0;
        double right = 1.0;
        // number of nodal points
        int N = initial_N;
        // mesh
        DenseVector<double> nodes( Utility::uniform_node_vector( left, right, N ) );
        // pass it to the ode
        ODE_EVP<D_complex> ode_global( &evp, nodes, &BC_both, &BC_both );
        try
        {
          // solve the global eigenvalue problem for growth rate
          ode_global.eigensolve();
        }
        catch (const std::runtime_error &error )
        {
          std::cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
          assert(false);
        }
        // get the eigenvalues near the origin
        ode_global.p_eigensystem() -> tag_eigenvalues_disc( + 1, 0.6 );
        // make a mesh of each tagged eigenmode in the ODE_EVP class
        ode_global.add_tagged_to_mesh();
        DenseVector<D_complex> lambdas = ode_global.p_eigensystem() -> get_tagged_eigenvalues();
        // instantiate the nonlinear BVP formulation
        bvp = new OS_bvp_equation;
        BC_left = new OS_bvp_left_BC;
        BC_right = new OS_bvp_right_BC;
        // pass it to the ode BVP solver
        ode_local = new ODE_BVP<D_complex>( bvp, nodes, BC_left, BC_right );
        ode_local -> set_monitor_det( false );
        // use our not-great initial guess from QZ code to start the solver off
        // here we just use the first (0) tagged eigenvalue
        ode_local -> solution() = ode_global.get_mesh( 0 );
        // interpolate onto a finer mesh
        ode_local -> solution().remesh1( Utility::uniform_node_vector( left, right, 201 ) );
        ode_local -> set_monitor_det( false );
        ode_local -> solve2();
        // adaptively refine the mesh
        for ( int i = 0; i < MAX_REFINE; ++i )
        {
          ode_local -> adapt( 1.e-2 );
          ode_local -> solve2();
          std::cout << "Adapted to " << ode_local -> solution().get_nnodes() << " nodes \n";
        }
      }
References CppNoddy::ODE_EVP< _Type >::add_tagged_to_mesh(), BC_left, BC_right, bvp, CppNoddy::ODE_EVP< _Type >::eigensolve(), CppNoddy::ODE_EVP< _Type >::get_mesh(), CppNoddy::Example::MAX_REFINE(), ode_local, CppNoddy::ODE_EVP< _Type >::p_eigensystem(), and CppNoddy::Utility::uniform_node_vector().
~Neutral_residual()
CppNoddy::Example::Neutral_residual::~Neutral_residual () inline
Definition at line 214 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        delete bvp;
        delete BC_left;
        delete BC_right;
        delete ode_local;
      }
References BC_left, BC_right, bvp, and ode_local.
Member Function Documentation
residual_fn()
void CppNoddy::Example::Neutral_residual::residual_fn (const DenseVector< double > & state, DenseVector< double > & f) const inline virtual
A blank virtual residual function method.
Parameters
state The unknown variable.
f The residual function f(x).
Reimplemented from CppNoddy::Residual< double >.
Definition at line 222 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        Example::Re = z[ 0 ];
        // solve the nonlinear BVP
        ode_local -> solve2();
        // return the residual
        f[ 0 ] = ode_local -> solution()( 0, eval ).imag();
        wave_speed = ode_local -> solution()( 0, eval ).real();
      }
References eval, f, ode_local, CppNoddy::Example::Re, CppNoddy::Example::wave_speed, and CppNoddy::Example::z().
Member Data Documentation
BC_left
OS_bvp_left_BC* CppNoddy::Example::Neutral_residual::BC_left
Definition at line 234 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
Referenced by Neutral_residual(), and ~Neutral_residual().
BC_right
OS_bvp_right_BC* CppNoddy::Example::Neutral_residual::BC_right
Definition at line 235 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
Referenced by Neutral_residual(), and ~Neutral_residual().
bvp
OS_bvp_equation* CppNoddy::Example::Neutral_residual::bvp
Definition at line 233 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
Referenced by Neutral_residual(), and ~Neutral_residual().
ode_local
ODE_BVP<D_complex>* CppNoddy::Example::Neutral_residual::ode_local
Definition at line 232 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
Referenced by Neutral_residual(), residual_fn(), and ~Neutral_residual().
The documentation for this class was generated from the following file:
Tests/EVP/EVPOrrSommerfeldNeutralCurve_lapack.cpp
© 2012
R.E. Hewitt