CppNoddy: CppNoddy::Example::Acoustic_1d_ref Class Reference
CppNoddy::Example::Acoustic_1d_ref Class Reference
Define the system.
Public Member Functions
Acoustic_1d_ref ()
One dimemsional constant coefft acoustic problem.
void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
Define the vector flux.
double max_charac_speed (const DenseVector< double > &q) const
Bound the shock speed.
std::vector< bool > edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t) const
edge conditions
Public Member Functions inherited from CppNoddy::OneD_Hyperbolic_System
OneD_Hyperbolic_System (const unsigned &order)
virtual ~OneD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function.
virtual void Jac_flux_fn (const double &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the flux function.
virtual double max_charac_speed (const DenseVector< double > &q) const
A virtual method that is used to bound the shock speed and must be implemented by the user.
virtual bool_vec edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t=0.0) const
Define the edge boundary conditions.
virtual void source_fn (const double &x, const DenseVector< double > &q, const DenseVector< double > &slope, DenseVector< double > &r) const
unsigned get_order ()
Additional Inherited Members
Protected Attributes inherited from CppNoddy::OneD_Hyperbolic_System
const std::size_t ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
Define the system.
Definition at line 25 of file HYPAcousticReflection.cpp.
Constructor & Destructor Documentation
Acoustic_1d_ref()
CppNoddy::Example::Acoustic_1d_ref::Acoustic_1d_ref () inline
One dimemsional constant coefft acoustic problem.
Definition at line 31 of file HYPAcousticReflection.cpp.
                        : OneD_Hyperbolic_System( 2 )
      {}
Member Function Documentation
edge_values()
std::vector< bool > CppNoddy::Example::Acoustic_1d_ref::edge_values (const int face_index, const double & x, DenseVector< double > & q, const double & t) const inline virtual
edge conditions
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 51 of file HYPAcousticReflection.cpp.
      {
        // reflection condition
        std::vector<bool> inflow( q.size(), false );
        q[ u ] = 0.0;
        inflow[ u ] = true;
        return inflow;
      }
References CppNoddy::DenseVector< _Type >::size(), and u.
flux_fn()
void CppNoddy::Example::Acoustic_1d_ref::flux_fn (const double & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
Define the vector flux.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 35 of file HYPAcousticReflection.cpp.
      {
        f[ p ] = K * q[ u ];
        f[ u ] = q[ p ] / rho;
      }
References f, CppNoddy::Example::K(), p, rho, and u.
max_charac_speed()
double CppNoddy::Example::Acoustic_1d_ref::max_charac_speed (const DenseVector< double > & q) const inline virtual
Bound the shock speed.
Reimplemented from CppNoddy::OneD_Hyperbolic_System.
Definition at line 42 of file HYPAcousticReflection.cpp.
      {
        // sound speeds
        double c = sqrt( K / rho );
        // maximum shock speed
        return c;
      }
References CppNoddy::Example::K(), and rho.
The documentation for this class was generated from the following file:
Tests/HYP_1D/HYPAcousticReflection.cpp
© 2012
R.E. Hewitt