CppNoddy: CppNoddy::FortranData Class Reference
CppNoddy::FortranData Class Reference
A little (legacy) utility class for passing CppNoddy containers to Fortran library routines.
#include <FortranData.h>
Public Member Functions
FortranData (std::size_t size)
Make an empty FortranData object that is not constructed from a CppNoddy container.
FortranData (DenseMatrix< double > &matrix, bool transpose=true, int padding=0)
Make a FortranData object from a double dense matrix (with potential) for padding the data to avoid cache contention.
FortranData (DenseMatrix< D_complex > &matrix, bool transpose=true, int padding=0)
Make a FortranData object from a complex dense matrix (with potential) for padding the data to avoid cache contention.
FortranData (BandedMatrix< double > &matrix, bool transpose=true)
FortranData (BandedMatrix< D_complex > &matrix, bool transpose=true)
FortranData (DenseVector< D_complex > &vector)
~FortranData ()
double * base ()
Get the pointer to the first element.
double & operator[] (const std::size_t &i)
Get the reference to the first element.
std::size_t size () const
Find the number of stored elements.
DenseMatrix< double > to_dense_matrix (std::size_t rows, std::size_t cols)
Convert the data to a double dense format.
void dump ()
Dump the data to standard out.
Detailed Description
A little (legacy) utility class for passing CppNoddy containers to Fortran library routines.
Definition at line 13 of file FortranData.h.
Constructor & Destructor Documentation
FortranData() [1/6]
CppNoddy::FortranData::FortranData (std::size_t size) inline explicit
Make an empty FortranData object that is not constructed from a CppNoddy container.
Definition at line 19 of file FortranData.h.
{
      p_DATA = new DenseVector<double>(size, 0.0);
    }
References size().
FortranData() [2/6]
CppNoddy::FortranData::FortranData (DenseMatrix< double > & matrix, bool transpose = true, int padding = 0) inline
Make a FortranData object from a double dense matrix (with potential) for padding the data to avoid cache contention.
The transpose flag defaults to true in order to return data in column-major format.
Parameters
matrix A double dense matrix to convert to Lapack/Fortran format
transpose Transpose the matrix to be in column major format
padding The number of additional elements to pad the matrix
Definition at line 29 of file FortranData.h.
{
      p_DATA = new DenseVector<double>;
      if(transpose) {
        matrix.transpose();
      }
      matrix.matrix_to_vector(*p_DATA, padding);
    }
References CppNoddy::DenseMatrix< _Type >::matrix_to_vector(), and CppNoddy::DenseMatrix< _Type >::transpose().
FortranData() [3/6]
CppNoddy::FortranData::FortranData (DenseMatrix< D_complex > & matrix, bool transpose = true, int padding = 0) inline
Make a FortranData object from a complex dense matrix (with potential) for padding the data to avoid cache contention.
The transpose flag defaults to true in order to return data in column-major format.
Parameters
matrix A complex dense matrix to convert to Lapack/Fortran format
transpose Transpose the matrix to be in column major format
padding The number of additional elements to pad the matrix
Definition at line 43 of file FortranData.h.
{
      p_DATA = new DenseVector<double>;
      if(transpose) {
        matrix.transpose();
      }
      matrix.matrix_to_vector(*p_DATA, padding);
    }
References CppNoddy::DenseMatrix< _Type >::matrix_to_vector(), and CppNoddy::DenseMatrix< _Type >::transpose().
FortranData() [4/6]
CppNoddy::FortranData::FortranData (BandedMatrix< double > & matrix, bool transpose = true) inline
Definition at line 51 of file FortranData.h.
{
      std::string problem;
      problem = "The default storage format for a banded matrix is now\n";
      problem += "a contiguous column-major vector. You should not need to \n";
      problem += "the FortranData method anymore.\n";
      throw ExceptionRuntime(problem);
    }
FortranData() [5/6]
CppNoddy::FortranData::FortranData (BandedMatrix< D_complex > & matrix, bool transpose = true) inline
Definition at line 59 of file FortranData.h.
{
      std::string problem;
      problem = "The default storage format for a banded matrix is now\n";
      problem += "a contiguous column-major vector. You should not need to \n";
      problem += "the FortranData method anymore.\n";
      throw ExceptionRuntime(problem);
    }
FortranData() [6/6]
CppNoddy::FortranData::FortranData (DenseVector< D_complex > & vector) inline
Definition at line 67 of file FortranData.h.
{
      std::string problem;
      problem = "This method is not required. Just use the base address of \n";
      problem += "the first element and treat it as a vector of doubles.\n";
      throw ExceptionRuntime(problem);
    }
~FortranData()
CppNoddy::FortranData::~FortranData () inline
Definition at line 74 of file FortranData.h.
                   {
      delete p_DATA;
    }
Member Function Documentation
base()
double * CppNoddy::FortranData::base () inline
Get the pointer to the first element.
Returns
The pointer to the base address.
Definition at line 80 of file FortranData.h.
                   {
      return & (p_DATA -> operator[](0));
    }
References operator[]().
Referenced by CppNoddy::Utility::multiply().
dump()
void CppNoddy::FortranData::dump () inline
Dump the data to standard out.
Definition at line 106 of file FortranData.h.
                {
      p_DATA -> dump();
    }
References dump().
Referenced by dump().
operator[]()
double & CppNoddy::FortranData::operator[] (const std::size_t & i) inline
Get the reference to the first element.
Returns
The the i-th element in the vector
Definition at line 86 of file FortranData.h.
{
      return p_DATA -> operator[](i);
    }
References operator[]().
Referenced by base(), and operator[]().
size()
std::size_t CppNoddy::FortranData::size () const inline
Find the number of stored elements.
Returns
The number of elements.
Definition at line 92 of file FortranData.h.
{
      return p_DATA -> size();
    }
References size().
Referenced by FortranData(), and size().
to_dense_matrix()
DenseMatrix< double > CppNoddy::FortranData::to_dense_matrix (std::size_t rows, std::size_t cols) inline
Convert the data to a double dense format.
Parameters
rows The number of required rows
cols The number of required columns
Returns
The DenseMatrix<double> of the data
Definition at line 100 of file FortranData.h.
{
      DenseMatrix<double> matrix(rows, cols, &(p_DATA->operator[](0)));
      return matrix;
    }
Referenced by CppNoddy::Utility::multiply().
The documentation for this class was generated from the following file:
include/FortranData.h
© 2012
R.E. Hewitt