CppNoddy: CppNoddy::Example::diffusion_double Class Reference
CppNoddy::Example::diffusion_double Class Reference
Public Member Functions
diffusion_double ()
The problem is 2nd order and real.
void residual_fn (const DenseVector< double > &z, DenseVector< double > &f) const
Define a nonlinear advection diffusion problem.
void jacobian (const DenseVector< double > &z, DenseMatrix< double > &jac) const
Provide the exact Jacobian rather than using finite-differences.
void matrix0 (const DenseVector< double > &z, DenseMatrix< double > &m) const
Define the matrix in terms of the current state vector.
void matrix1 (const DenseVector< double > &z, DenseMatrix< double > &m) const
Define the unsteady terms by providing the mass matrix.
void matrix2 (const DenseVector< double > &z, DenseMatrix< double > &m) const
Define the matrix for the current state vector.
void get_jacobian_of_matrix0_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
void get_jacobian_of_matrix1_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
void get_jacobian_of_matrix2_mult_vector (const DenseVector< double > &state, const DenseVector< double > &vec, DenseMatrix< double > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Equation_3matrix< double >
Equation_3matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_3matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix2 () const
Return a handle to the matrix member data.
Public Member Functions inherited from CppNoddy::Equation_2matrix< double, double >
Equation_2matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_2matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix1 () const
Return a handle to the matrix member data.
Public Member Functions inherited from CppNoddy::Equation_1matrix< double, double >
Equation_1matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_1matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< double > & matrix0 () const
Return a handle to the matrix.
Public Member Functions inherited from CppNoddy::Residual_with_coords< double, double >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
double & coord (const unsigned &i)
General handle access to the coordinates.
const double & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< double >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Residual object for the current set of state variables.
const DenseVector< double > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< double > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
double & delta ()
const double & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
Additional Inherited Members
Protected Attributes inherited from CppNoddy::Residual_with_coords< double, double >
std::vector< double > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< double >
DenseMatrix< double > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< double > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< double > LAST_STATE
The last state vector.
double DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Definition at line 31 of file IBVPLinear.cpp.
Constructor & Destructor Documentation
diffusion_double()
CppNoddy::Example::diffusion_double::diffusion_double () inline
The problem is 2nd order and real.
Definition at line 35 of file IBVPLinear.cpp.
 : Equation_3matrix<double> ( 2 ) {}
Member Function Documentation
get_jacobian_of_matrix0_mult_vector()
void CppNoddy::Example::diffusion_double::get_jacobian_of_matrix0_mult_vector (const DenseVector< double > & state, const DenseVector< double > & vec, DenseMatrix< double > & h) const inline virtual
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
The user should overload this if concerned about performance of the solver. If not overloaded, the default is to finite difference the Jacobian-of-the-matrix.
Parameters
state The current state variables – used for clarity when overloaded by the user instead of expecting the user to access the member data.
vec The vector that will be multiplied by the Jacobian-of-the-matrix
h The resulting 2D matrix
Reimplemented from CppNoddy::Equation_1matrix< double, double >.
Definition at line 70 of file IBVPLinear.cpp.
       {
         // constant matrix
       }
get_jacobian_of_matrix1_mult_vector()
void CppNoddy::Example::diffusion_double::get_jacobian_of_matrix1_mult_vector (const DenseVector< double > & state, const DenseVector< double > & vec, DenseMatrix< double > & h) const inline virtual
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
The user should overload this if concerned about performance of the solver. If not overloaded, the default is to finite difference the Jacobian-of-the-matrix.
Parameters
state The current state variables – used for clarity when overloaded by the user instead of expecting the user to access the member data.
vec The vector that will be multiplied by the Jacobian-of-the-matrix
h The resulting 2D matrix
Reimplemented from CppNoddy::Equation_2matrix< double, double >.
Definition at line 74 of file IBVPLinear.cpp.
       {
         // constant matrix
       }
get_jacobian_of_matrix2_mult_vector()
void CppNoddy::Example::diffusion_double::get_jacobian_of_matrix2_mult_vector (const DenseVector< double > & state, const DenseVector< double > & vec, DenseMatrix< double > & h) const inline virtual
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
The user should overload this if concerned about performance of the solver. If not overloaded, the default is to finite difference the Jacobian-of-the-matrix.
Parameters
state The current state variables – used for clarity when overloaded by the user instead of expecting the user to access the member data.
vec The vector that will be multiplied by the Jacobian-of-the-matrix
h The resulting 2D matrix
Reimplemented from CppNoddy::Equation_3matrix< double >.
Definition at line 78 of file IBVPLinear.cpp.
       {
         // constant matrix
       }
jacobian()
void CppNoddy::Example::diffusion_double::jacobian (const DenseVector< double > & z, DenseMatrix< double > & jac) const inline virtual
Provide the exact Jacobian rather than using finite-differences.
Reimplemented from CppNoddy::Residual< double >.
Definition at line 46 of file IBVPLinear.cpp.
       {
         jac( 0, Ud ) = 1.0;
       }
References Ud.
matrix0()
void CppNoddy::Example::diffusion_double::matrix0 (const DenseVector< double > & x, DenseMatrix< double > & m) const inline virtual
Define the matrix in terms of the current state vector.
Parameters
x The current state vector.
m The matrix.
Reimplemented from CppNoddy::Equation_1matrix< double, double >.
Definition at line 51 of file IBVPLinear.cpp.
       {
         Utils_Fill::fill_identity(m);
       }
References Utils_Fill::fill_identity(), and m.
matrix1()
void CppNoddy::Example::diffusion_double::matrix1 (const DenseVector< double > & z, DenseMatrix< double > & m) const inline virtual
Define the unsteady terms by providing the mass matrix.
Reimplemented from CppNoddy::Equation_2matrix< double, double >.
Definition at line 57 of file IBVPLinear.cpp.
       {
         // eqn 1 variable 0
         m( 1, 0 ) = -1.0;
       }
References m.
matrix2()
void CppNoddy::Example::diffusion_double::matrix2 (const DenseVector< double > & state, DenseMatrix< double > & m) const inline virtual
Define the matrix for the current state vector.
Parameters
state The current state vector.
m The matrix.
Reimplemented from CppNoddy::Equation_3matrix< double >.
Definition at line 63 of file IBVPLinear.cpp.
       {
         // eqn 1 variable 0
         m( 1, 0 ) = -1.0;
       }
References m.
residual_fn()
void CppNoddy::Example::diffusion_double::residual_fn (const DenseVector< double > & z, DenseVector< double > & f) const inline virtual
Define a nonlinear advection diffusion problem.
Reimplemented from CppNoddy::Residual< double >.
Definition at line 38 of file IBVPLinear.cpp.
       {
         // The system
         f[ U ] = z[ Ud ];
         f[ Ud ] = source( coord(2), coord(0), coord(1) );
       }
References CppNoddy::Residual_with_coords< double, double >::coord(), f, CppNoddy::Example::source(), CppNoddy::Example::U(), Ud, and CppNoddy::Example::z().
The documentation for this class was generated from the following file:
Tests/double_IBVP/IBVPLinear.cpp
© 2012
R.E. Hewitt