CppNoddy: CppNoddy::Example::OS_evp_equation Class Reference
CppNoddy::Example::OS_evp_equation Class Reference
Define the OS equation for the global QZ EVP.
Public Member Functions
OS_evp_equation ()
The OS equation is a 4th order complex ODE.
void residual_fn (const DenseVector< D_complex > &z, DenseVector< D_complex > &g) const
The OS equation.
void matrix0 (const DenseVector< D_complex > &z, DenseMatrix< D_complex > &m) const
matrix to multiply the BVP coordinate
void matrix1 (const DenseVector< D_complex > &z, DenseMatrix< D_complex > &m) const
Define the unsteady terms by providing the mass matrix Here we define the eigenvalue contribution to the g[ psid ] equation.
OS_evp_equation ()
The OS equation is a 4th order complex ODE.
void residual_fn (const DenseVector< D_complex > &z, DenseVector< D_complex > &g) const
The OS equation.
void matrix0 (const DenseVector< D_complex > &z, DenseMatrix< D_complex > &m) const
matrix to multiply the BVP coordinate
void matrix1 (const DenseVector< D_complex > &z, DenseMatrix< D_complex > &m) const
Define the unsteady terms by providing the mass matrix Here we define the eigenvalue contribution to the g[ psid ] equation.
Public Member Functions inherited from CppNoddy::Equation_2matrix< D_complex >
Equation_2matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_2matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< D_complex > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< D_complex > & matrix1 () const
Return a handle to the matrix member data.
virtual void get_jacobian_of_matrix1_mult_vector (const DenseVector< D_complex > &state, const DenseVector< D_complex > &vec, DenseMatrix< D_complex > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Equation_1matrix< _Type, _Xtype >
Equation_1matrix (const unsigned &order)
Constructor for equation class.
virtual ~Equation_1matrix ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Equation object for the current set of state variables.
const DenseMatrix< _Type > & matrix0 () const
Return a handle to the matrix.
virtual void get_jacobian_of_matrix0_mult_vector (const DenseVector< _Type > &state, const DenseVector< _Type > &vec, DenseMatrix< _Type > &h) const
Return the product of the Jacobian-of-the-matrix and a vector 'vec' when the equation has a given 'state'.
Public Member Functions inherited from CppNoddy::Residual_with_coords< _Type, _Xtype >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
_Xtype & coord (const unsigned &i)
General handle access to the coordinates.
const _Xtype & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< _Type >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Residual object for the current set of state variables.
const DenseVector< _Type > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< _Type > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
_Type & delta ()
const _Type & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< _Type > &state, DenseVector< _Type > &f) const
A blank virtual residual function method.
Additional Inherited Members
virtual void matrix1 (const DenseVector< D_complex > &state, DenseMatrix< D_complex > &m) const
Define the matrix in terms of the current state vector.
Protected Member Functions inherited from CppNoddy::Equation_1matrix< _Type, _Xtype >
virtual void matrix0 (const DenseVector< _Type > &x, DenseMatrix< _Type > &m) const
Define the matrix in terms of the current state vector.
Protected Member Functions inherited from CppNoddy::Residual< _Type >
virtual void jacobian (const DenseVector< _Type > &state, DenseMatrix< _Type > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual_with_coords< _Type, _Xtype >
std::vector< _Xtype > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< _Type >
DenseMatrix< _Type > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< _Type > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< _Type > LAST_STATE
The last state vector.
_Type DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Define the OS equation for the global QZ EVP.
Definition at line 47 of file EVPOrrSommerfeldEasy_lapack.cpp.
Constructor & Destructor Documentation
OS_evp_equation() [1/2]
CppNoddy::Example::OS_evp_equation::OS_evp_equation () inline
The OS equation is a 4th order complex ODE.
Definition at line 51 of file EVPOrrSommerfeldEasy_lapack.cpp.
: Equation_2matrix<D_complex>(4) {}
OS_evp_equation() [2/2]
CppNoddy::Example::OS_evp_equation::OS_evp_equation () inline
The OS equation is a 4th order complex ODE.
Definition at line 53 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
: Equation_2matrix<D_complex>(4) {}
Member Function Documentation
matrix0() [1/2]
void CppNoddy::Example::OS_evp_equation::matrix0 (const DenseVector< D_complex > & z, DenseMatrix< D_complex > & m) const inline
matrix to multiply the BVP coordinate
Definition at line 65 of file EVPOrrSommerfeldEasy_lapack.cpp.
      {
        Utils_Fill::fill_identity(m);
      }
References Utils_Fill::fill_identity(), and m.
matrix0() [2/2]
void CppNoddy::Example::OS_evp_equation::matrix0 (const DenseVector< D_complex > & z, DenseMatrix< D_complex > & m) const inline
matrix to multiply the BVP coordinate
Definition at line 67 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        Utils_Fill::fill_identity(m);
      }
References Utils_Fill::fill_identity(), and m.
matrix1() [1/2]
void CppNoddy::Example::OS_evp_equation::matrix1 (const DenseVector< D_complex > & z, DenseMatrix< D_complex > & m) const inline virtual
Define the unsteady terms by providing the mass matrix Here we define the eigenvalue contribution to the g[ psid ] equation.
D_complex(0.0, 1.0) * alpha * Re * c * z[ psi ]
Reimplemented from CppNoddy::Equation_2matrix< D_complex >.
Definition at line 73 of file EVPOrrSommerfeldEasy_lapack.cpp.
      {
        // the eigenvalue is in equation 3, and multiplies unknown 2
        m( 3, 2 ) = D_complex( 0.0, 1.0 ) * alpha * Re;
      }
References CppNoddy::Example::alpha, m, and CppNoddy::Example::Re.
matrix1() [2/2]
void CppNoddy::Example::OS_evp_equation::matrix1 (const DenseVector< D_complex > & z, DenseMatrix< D_complex > & m) const inline virtual
Define the unsteady terms by providing the mass matrix Here we define the eigenvalue contribution to the g[ psid ] equation.
D_complex(0.0, 1.0) * alpha * Re * c * z[ psi ]
Reimplemented from CppNoddy::Equation_2matrix< D_complex >.
Definition at line 75 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        // the eigenvalue is in equation 3, and multiplies unknown 2
        m( 3, 2 ) = D_complex( 0.0, 1.0 ) * alpha * Re;
      }
References CppNoddy::Example::alpha, m, and CppNoddy::Example::Re.
residual_fn() [1/2]
void CppNoddy::Example::OS_evp_equation::residual_fn (const DenseVector< D_complex > & z, DenseVector< D_complex > & g) const inline
The OS equation.
Definition at line 54 of file EVPOrrSommerfeldEasy_lapack.cpp.
      {
        // define the equation as 4 1st order equations
        g[ phi ] = z[ phid ];
        g[ phid ] = z[ psi ] + alpha * alpha * z[ phi ];
        g[ psi ] = z[ psid ];
        g[ psid ] = alpha * alpha * z[ psi ]
                    + D_complex( 0.0, 1.0 ) * alpha * Re * ( U( coord(0) ) * z[ psi ] - Udd( coord(0) ) * z[ phi ] );
      }
References CppNoddy::Example::alpha, CppNoddy::Residual_with_coords< _Type, _Xtype >::coord(), CppNoddy::Example::g(), phi, phid, psi, psid, CppNoddy::Example::Re, U, CppNoddy::Example::Udd(), and CppNoddy::Example::z().
residual_fn() [2/2]
void CppNoddy::Example::OS_evp_equation::residual_fn (const DenseVector< D_complex > & z, DenseVector< D_complex > & g) const inline
The OS equation.
Definition at line 56 of file EVPOrrSommerfeldNeutralCurve_lapack.cpp.
      {
        // define the equation as four 1st order equations
        g[ phi ] = z[ phid ];
        g[ phid ] = z[ psi ] + alpha * alpha * z[ phi ];
        g[ psi ] = z[ psid ];
        g[ psid ] = alpha * alpha * z[ psi ]
                    + D_complex( 0.0, 1.0 ) * alpha * Re * ( U( coord(0) ) * z[ psi ] - Udd( coord(0) ) * z[ phi ] );
      }
References CppNoddy::Example::alpha, CppNoddy::Residual_with_coords< _Type, _Xtype >::coord(), CppNoddy::Example::g(), phi, phid, psi, psid, CppNoddy::Example::Re, U, CppNoddy::Example::Udd(), and CppNoddy::Example::z().
The documentation for this class was generated from the following files:
Tests/EVP/EVPOrrSommerfeldEasy_lapack.cpp
Tests/EVP/EVPOrrSommerfeldNeutralCurve_lapack.cpp
© 2012
R.E. Hewitt