CppNoddy: CppNoddy::OneD_Hyperbolic_System Class Reference
CppNoddy::OneD_Hyperbolic_System Class Reference
A class to represent a one dimensional hyperbolic system of equations.
#include <OneD_Hyperbolic_System.h>
Public Member Functions
OneD_Hyperbolic_System (const unsigned &order)
virtual ~OneD_Hyperbolic_System ()
An empty destructor, virtual since we have virtual methods.
virtual void flux_fn (const double &x, const DenseVector< double > &q, DenseVector< double > &f) const
A virtual flux function.
virtual void Jac_flux_fn (const double &x, const DenseVector< double > &q, DenseMatrix< double > &J) const
A virtual function function to define the Jacobian of the flux function.
virtual double max_charac_speed (const DenseVector< double > &q) const
A virtual method that is used to bound the shock speed and must be implemented by the user.
virtual bool_vec edge_values (const int face_index, const double &x, DenseVector< double > &q, const double &t=0.0) const
Define the edge boundary conditions.
virtual void source_fn (const double &x, const DenseVector< double > &q, const DenseVector< double > &slope, DenseVector< double > &r) const
unsigned get_order ()
Protected Attributes
const std::size_t ORDER_OF_SYSTEM
The order of the system of equations.
Detailed Description
A class to represent a one dimensional hyperbolic system of equations.
Definition at line 13 of file OneD_Hyperbolic_System.h.
Constructor & Destructor Documentation
OneD_Hyperbolic_System()
CppNoddy::OneD_Hyperbolic_System::OneD_Hyperbolic_System (const unsigned & order) inline explicit
Parameters
order The order of the hyperbolic system
Definition at line 20 of file OneD_Hyperbolic_System.h.
                                                           : ORDER_OF_SYSTEM(order) {
    }
~OneD_Hyperbolic_System()
virtual CppNoddy::OneD_Hyperbolic_System::~OneD_Hyperbolic_System () inline virtual
An empty destructor, virtual since we have virtual methods.
Definition at line 24 of file OneD_Hyperbolic_System.h.
    {}
Member Function Documentation
edge_values()
virtual bool_vec CppNoddy::OneD_Hyperbolic_System::edge_values (const int face_index, const double & x, DenseVector< double > & q, const double & t = 0.0) const inline virtual
Define the edge boundary conditions.
Parameters
face_index An index for the face: -1=left +1=right for OneD_TVDLF_Mesh
x The position vector along the face
q The unknowns specified along the face
t A time for unsteady edge conditions
Reimplemented in CppNoddy::Example::Acoustic_1d_ref, and CppNoddy::Example::NlinAdv.
Definition at line 78 of file OneD_Hyperbolic_System.h.
{
      return std::vector<bool>(ORDER_OF_SYSTEM, false);
    }
References ORDER_OF_SYSTEM.
flux_fn()
virtual void CppNoddy::OneD_Hyperbolic_System::flux_fn (const double & x, const DenseVector< double > & q, DenseVector< double > & f) const inline virtual
A virtual flux function.
Parameters
x The spatial coordinate
q The unknowns
f The flux function
Reimplemented in CppNoddy::Example::Acoustic_1d, CppNoddy::Example::Acoustic_1d_ref, CppNoddy::Example::NlinAdv, CppNoddy::Example::Shallow_1d_rad, and CppNoddy::Example::Euler_1d.
Definition at line 31 of file OneD_Hyperbolic_System.h.
{
      std::string problem;
      problem = "The Hyperbolic_Conservative_System::flux_fn method has not been implemented.\n";
      problem += "You have to implement this method to define the system.\n";
      throw ExceptionRuntime(problem);
    }
Referenced by Jac_flux_fn().
get_order()
unsigned CppNoddy::OneD_Hyperbolic_System::get_order () inline
Definition at line 85 of file OneD_Hyperbolic_System.h.
{
      return ORDER_OF_SYSTEM;
    }
References ORDER_OF_SYSTEM.
Jac_flux_fn()
virtual void CppNoddy::OneD_Hyperbolic_System::Jac_flux_fn (const double & x, const DenseVector< double > & q, DenseMatrix< double > & J) const inline virtual
A virtual function function to define the Jacobian of the flux function.
The default method uses first-order finite differencing to compute the Jacobian if not otherwise specified by the user.
Parameters
x The position
q The unknowns
J The Jacobian of the flux function
first order differencing is the default unless overloaded
Definition at line 45 of file OneD_Hyperbolic_System.h.
{
      /// first order differencing is the default unless overloaded
      double delta(1.e-8);
      DenseVector<double> state(q);
      DenseVector<double> temp1(ORDER_OF_SYSTEM, 0.0);
      DenseVector<double> temp2(ORDER_OF_SYSTEM, 0.0);
      flux_fn(x, q, temp1);
      // default is to FD the Jacobian
      for(std::size_t i = 0; i < ORDER_OF_SYSTEM; ++i) {
        state[ i ] += delta;
        flux_fn(x, state, temp2);
        state[ i ] -= delta;
        J.set_col(i, (temp2 - temp1) / delta);
      }
    }
References flux_fn(), ORDER_OF_SYSTEM, and CppNoddy::DenseMatrix< _Type >::set_col().
max_charac_speed()
virtual double CppNoddy::OneD_Hyperbolic_System::max_charac_speed (const DenseVector< double > & q) const inline virtual
A virtual method that is used to bound the shock speed and must be implemented by the user.
Parameters
q The unknowns
Returns
A bound on the maximum wave speed
Reimplemented in CppNoddy::Example::Acoustic_1d, CppNoddy::Example::Acoustic_1d_ref, CppNoddy::Example::NlinAdv, CppNoddy::Example::Shallow_1d_rad, and CppNoddy::Example::Euler_1d.
Definition at line 65 of file OneD_Hyperbolic_System.h.
{
      std::string problem;
      problem = "The Hyperbolic_Conservative_System::max_shock_speed method has not\n";
      problem += "been implemented. You have to implement this method to define the system.\n";
      throw ExceptionRuntime(problem);
    }
source_fn()
virtual void CppNoddy::OneD_Hyperbolic_System::source_fn (const double & x, const DenseVector< double > & q, const DenseVector< double > & slope, DenseVector< double > & r) const inline virtual
Reimplemented in CppNoddy::Example::Shallow_1d_rad.
Definition at line 82 of file OneD_Hyperbolic_System.h.
{
    }
Member Data Documentation
ORDER_OF_SYSTEM
const std::size_t CppNoddy::OneD_Hyperbolic_System::ORDER_OF_SYSTEM protected
The order of the system of equations.
Definition at line 92 of file OneD_Hyperbolic_System.h.
Referenced by edge_values(), get_order(), and Jac_flux_fn().
The documentation for this class was generated from the following file:
include/OneD_Hyperbolic_System.h
© 2012
R.E. Hewitt