CppNoddy: CppNoddy::OneD_TVDLF_Elt Class Reference
CppNoddy::OneD_TVDLF_Elt Class Reference
A Linear Element class.
#include <OneD_TVDLF_Elt.h>
Public Member Functions
OneD_TVDLF_Elt (double a, double b, OneD_Hyperbolic_System *ptr, bool flag=false, int index=0)
Construct a linear element.
~OneD_TVDLF_Elt ()
An empty destructor.
void add_contribution (OneD_TVDLF_Elt *ptr, const DenseVector< double > &s_range, int index)
Allow the connection of this element to another element.
void clear_contributions ()
Clear the record of contributions to this element.
DenseVector< double > contributed_Q ()
Find the integral contributions to this black/red element from the contributed red/black element.
void contributed_flux_in_left (const double &dt, DenseVector< double > &flux_in_left, const double &current_time)
Compute the flux into this element through the left face over a given time step.
void contributed_flux_out_right (const double &dt, DenseVector< double > &flux_out_right, const double &current_time)
Compute the flux out of this element through the right face over a given time step.
double get_s (double x) const
Convert a global coordinate into a local coordinate within this element If the global coordinate is outside the element, then we throw an exception.
double get_x (double s) const
Get the global position of the local coordinate.
double get_dx () const
Get the size of the element.
bool get_external_flag () const
Get the external flag.
void set_external_flag (bool flag)
Set the external flag.
int get_external_face_i () const
Get the exterior boundary number.
void set_external_face_i (int i)
Set the local coordinate of the external face.
DenseVector< double > get_Q (double s) const
Get the value of the 'concentration' stored in this element.
DenseVector< double > get_int_Q (const double s0, const double s1)
Get the integral of Q over a sub-element.
void set_Q_mid (const DenseVector< double > value)
Set the value of the 'concentration' stored in this element.
void set_slope (const DenseVector< double > value)
The concentration is approximated by a linear function in each element.
DenseVector< double > get_slope () const
The concentration is approximated by a linear function in each element.
DenseVector< double > get_flux_fn (const double s) const
Get the flux function evaluated for the concentration value stored in this elt.
DenseMatrix< double > get_Jac_flux_fn (const double s) const
Get the Jacobian of the flux function evaluated for the concentration value stored in this elt.
DenseVector< double > get_source_fn (const double s) const
Get the value of the source function term in this element at a given local coordinate.
double get_max_dt () const
Get the maximum allowable time step for this element by using information about the size of the element and the maximum wave speed set in the conservative system.
Public Attributes
OneD_Hyperbolic_System * system_ptr
Detailed Description
A Linear Element class.
Definition at line 15 of file OneD_TVDLF_Elt.h.
Constructor & Destructor Documentation
OneD_TVDLF_Elt()
CppNoddy::OneD_TVDLF_Elt::OneD_TVDLF_Elt (double a, double b, OneD_Hyperbolic_System * ptr, bool flag = false, int index = 0)
Construct a linear element.
Parameters
a The left hand edge
b The right hand edge
ptr A pointer to the hyperbolic system for this element
flag A boolean indicator to specify an elt with an external face
index Index of the external face if flag=true
Definition at line 13 of file OneD_TVDLF_Elt.cpp.
{
 #ifdef DEBUG
     std::cout << "DEBUG: Constructing a OneD_TVDLF_Elt object between "
               << a << " and " << b << "\n";
 #endif
     system_ptr = ptr;
     LEFT = a;
     RIGHT = b;
     EXTERNAL = flag;
     EXTERNAL_FACE_I = index;
     SLOPE = DenseVector<double>(system_ptr -> get_order(), 0.0);
     Q = DenseVector<double>(system_ptr -> get_order(), 0.0);
   }
References system_ptr.
~OneD_TVDLF_Elt()
CppNoddy::OneD_TVDLF_Elt::~OneD_TVDLF_Elt ()
An empty destructor.
Definition at line 29 of file OneD_TVDLF_Elt.cpp.
   {}
Member Function Documentation
add_contribution()
void CppNoddy::OneD_TVDLF_Elt::add_contribution (OneD_TVDLF_Elt * ptr, const DenseVector< double > & s_range, int index)
Allow the connection of this element to another element.
Parameters
ptr A pointer to another element of the same type
s_range A vector range of local coordinates (s_min,s_max) in this 1D case.
index An index to indicate which face of the current elt this contribution is associated with for flux computations -1=left, +1=right, 0=none
Definition at line 32 of file OneD_TVDLF_Elt.cpp.
{
     contribution cont;
     cont.elt_ptr = ptr;
     cont.s = s_range;
     cont.face_index = index;
     // push the contribution data into a list
     CONT_LIST.push_back(cont);
   }
clear_contributions()
void CppNoddy::OneD_TVDLF_Elt::clear_contributions () inline
Clear the record of contributions to this element.
Definition at line 46 of file OneD_TVDLF_Elt.h.
{
       CONT_LIST.clear();
     }
contributed_flux_in_left()
void CppNoddy::OneD_TVDLF_Elt::contributed_flux_in_left (const double & dt, DenseVector< double > & flux_in_left, const double & current_time)
Compute the flux into this element through the left face over a given time step.
Parameters
dt The time step to compute the flux over
flux_in_left A vector to return the flux components in
current_time The current mesh time level
Definition at line 54 of file OneD_TVDLF_Elt.cpp.
{
     std::list< contribution >::iterator c = CONT_LIST.begin();
     // loop over all contributing elements
     while(c != CONT_LIST.end()) {
       // find contributions to the left face
       if(c -> face_index == -1) {
         // which local coord in the contributing elt?
         const double s = c -> s[ 0 ];
         DenseVector<double> q_half_step(c -> elt_ptr -> get_Q(s));
         // add half step correction
         q_half_step += (c -> elt_ptr -> get_source_fn(s)
                         - c -> elt_ptr -> get_Jac_flux_fn(s).multiply(c -> elt_ptr -> SLOPE))
                        * 0.5 * dt;
         //DenseVector<double> x( 1, 0.0 ); x[ 0 ] = c -> elt_ptr -> get_x( s );
         double x(c -> elt_ptr -> get_x(s));
         // evaluate the flux at this Q value
         c -> elt_ptr -> system_ptr -> flux_fn(x, q_half_step, flux_in_left);
       }
       ++c;
     }
     // treat the user specified external faces separately
     if(EXTERNAL) {
       // we are in an external elt
       c = CONT_LIST.begin();
       while(c != CONT_LIST.end()) {
         // external faces are external for the current elt *and* its contributions
         if(c -> elt_ptr -> get_external_flag()) {
           if(EXTERNAL_FACE_I < 0) {
             // LH boundary
             DenseVector<double> q_left(c -> elt_ptr -> get_Q(-1.0));
             // convert x at boundary to a vector
             //DenseVector<double> x_left( 1, 0.0 ); x_left[ 0 ] = c -> elt_ptr -> get_x( -1.0 );
             double x_left(c -> elt_ptr -> get_x(-1.0));
             DenseVector<double> q_left_half_step(q_left);
             //compute flux at the half time step
             q_left_half_step += (c -> elt_ptr -> get_source_fn(-1.0)
                                  - c -> elt_ptr -> get_Jac_flux_fn(-1.0).multiply(c -> elt_ptr -> SLOPE))
                                 * 0.5 * dt;
             // get the edge values
             system_ptr -> edge_values(-1, x_left, q_left_half_step, current_time + 0.5*dt);
             // get the flux
             system_ptr -> flux_fn(x_left, q_left_half_step, flux_in_left);
           }
         }
         ++c;
       }
     }
   }
References get_external_flag(), get_Jac_flux_fn(), get_Q(), get_source_fn(), get_x(), CppNoddy::DenseMatrix< _Type >::multiply(), CppNoddy::Example::s, and system_ptr.
contributed_flux_out_right()
void CppNoddy::OneD_TVDLF_Elt::contributed_flux_out_right (const double & dt, DenseVector< double > & flux_out_right, const double & current_time)
Compute the flux out of this element through the right face over a given time step.
Parameters
dt The time step to compute the flux over
flux_out_right A vector to return the flux components in
current_time The current mesh time level
Definition at line 103 of file OneD_TVDLF_Elt.cpp.
{
     std::list< contribution >::iterator c = CONT_LIST.begin();
     // loop over all contributing elements
     while(c != CONT_LIST.end()) {
       // find contributions to the right face
       if(c -> face_index == 1) {
         // which local coord in the contributing elt?
         const double s = c -> s[ 1 ];
         DenseVector<double> q_half_step(c -> elt_ptr -> get_Q(s));
         // add half step correction
         q_half_step += (c -> elt_ptr -> get_source_fn(s)
                         - c -> elt_ptr -> get_Jac_flux_fn(s).multiply(c -> elt_ptr -> SLOPE))
                        * 0.5 * dt;
         //DenseVector<double> x( 1, 0.0 ); x[ 0 ] = c -> elt_ptr -> get_x( s );
         double x(c -> elt_ptr -> get_x(s));
         // evaluate the flux at this Q value
         c -> elt_ptr -> system_ptr -> flux_fn(x, q_half_step, flux_out_right);
       }
       ++c;
     }
     // treat the user specified external faces separately
     if(EXTERNAL) {
       // we are in an external elt
       c = CONT_LIST.begin();
       while(c != CONT_LIST.end()) {
         // external faces are external for the current elt *and* its contributions
         if(c -> elt_ptr -> get_external_flag()) {
           if(EXTERNAL_FACE_I > 0) {
             // RH boundary
             DenseVector<double> q_right(c -> elt_ptr -> get_Q(1.0));
             // convert x at boundary to a vector
             //DenseVector<double> x_right( 1, 0.0 ); x_right[ 0 ] = c -> elt_ptr -> get_x( 1.0 );
             double x_right(c -> elt_ptr -> get_x(1.0));
             DenseVector<double> q_right_half_step(q_right);
             // compute flux at the half time step
             q_right_half_step += (c -> elt_ptr -> get_source_fn(1.0)
                                   - c -> elt_ptr -> get_Jac_flux_fn(1.0).multiply(c -> elt_ptr -> SLOPE))
                                  * 0.5 * dt;
             // get the edge values
             system_ptr -> edge_values(1, x_right, q_right_half_step, current_time + 0.5*dt);
             // get the flux
             system_ptr -> flux_fn(x_right, q_right_half_step, flux_out_right);
           }
         }
         ++c;
       }
     }
   }
References get_external_flag(), get_Jac_flux_fn(), get_Q(), get_source_fn(), get_x(), CppNoddy::DenseMatrix< _Type >::multiply(), CppNoddy::Example::s, and system_ptr.
contributed_Q()
DenseVector< double > CppNoddy::OneD_TVDLF_Elt::contributed_Q ()
Find the integral contributions to this black/red element from the contributed red/black element.
Returns
The integrated value of all components
Definition at line 41 of file OneD_TVDLF_Elt.cpp.
{
     std::list< contribution >::iterator c = CONT_LIST.begin();
     // start with zero
     DenseVector<double> sum(system_ptr -> get_order(), 0.0);
     // loop over contributions
     while(c != CONT_LIST.end()) {
       // get integral of each
       sum += c -> elt_ptr -> get_int_Q(c -> s[0], c -> s[1]);
       ++c;
     }
     return sum;
   }
References get_int_Q(), CppNoddy::Example::s, and system_ptr.
get_dx()
double CppNoddy::OneD_TVDLF_Elt::get_dx () const inline
Get the size of the element.
Returns
The separation of the left and right faces
Definition at line 181 of file OneD_TVDLF_Elt.h.
{
     return RIGHT - LEFT;
   }
Referenced by get_int_Q(), get_max_dt(), and get_x().
get_external_face_i()
int CppNoddy::OneD_TVDLF_Elt::get_external_face_i () const inline
Get the exterior boundary number.
Returns
An integer boundary indicator +1 for right, -1 for left.
Definition at line 193 of file OneD_TVDLF_Elt.h.
{
     return EXTERNAL_FACE_I;
   }
get_external_flag()
bool CppNoddy::OneD_TVDLF_Elt::get_external_flag () const inline
Get the external flag.
Returns
The value of the flag (true if this is an elt with an external face)
Definition at line 189 of file OneD_TVDLF_Elt.h.
{
     return EXTERNAL;
   }
Referenced by contributed_flux_in_left(), and contributed_flux_out_right().
get_flux_fn()
DenseVector< double > CppNoddy::OneD_TVDLF_Elt::get_flux_fn (const double s) const
Get the flux function evaluated for the concentration value stored in this elt.
Parameters
s The local coordinate at which to evaluate
Returns
The flux function vector
Definition at line 152 of file OneD_TVDLF_Elt.cpp.
{
     DenseVector<double> f(system_ptr -> get_order(), 0.0);
     double x(get_x(s));
     system_ptr -> flux_fn(x, get_Q(s), f);
     return f;
   }
References f, get_Q(), get_x(), CppNoddy::Example::s, and system_ptr.
get_int_Q()
DenseVector< double > CppNoddy::OneD_TVDLF_Elt::get_int_Q (const double s0, const double s1) inline
Get the integral of Q over a sub-element.
Parameters
s0 The left local coordinate
s1 The right local coordinate
Returns
The integral of the concentration over the local range
Definition at line 201 of file OneD_TVDLF_Elt.h.
{
     // linear elt so integral is 0.5 * dx * ( f(s0) + f(s1) )
     return (get_Q(s0) + get_Q(s1)) * 0.5 * ((s1 - s0) * get_dx() / 2);
   }
References get_dx(), and get_Q().
Referenced by contributed_Q().
get_Jac_flux_fn()
DenseMatrix< double > CppNoddy::OneD_TVDLF_Elt::get_Jac_flux_fn (const double s) const
Get the Jacobian of the flux function evaluated for the concentration value stored in this elt.
Parameters
s The local coordinate at which to evaluate
Returns
The Jacobian matrix
Definition at line 159 of file OneD_TVDLF_Elt.cpp.
{
     DenseMatrix<double> J(system_ptr -> get_order(), system_ptr -> get_order(), 0.0);
     double x(get_x(s));
     system_ptr -> Jac_flux_fn(x, get_Q(s), J);
     return J;
   }
References get_Q(), get_x(), CppNoddy::Example::s, and system_ptr.
Referenced by contributed_flux_in_left(), and contributed_flux_out_right().
get_max_dt()
double CppNoddy::OneD_TVDLF_Elt::get_max_dt () const
Get the maximum allowable time step for this element by using information about the size of the element and the maximum wave speed set in the conservative system.
The time step is guranteed to satisfy the CFL < 0.5 constraint.
Returns
The maximum time step.
Definition at line 173 of file OneD_TVDLF_Elt.cpp.
{
     // left face & right face speeds
     return get_dx() / std::max(std::abs(system_ptr -> max_charac_speed(get_Q(-1.0))),
                                std::abs(system_ptr -> max_charac_speed(get_Q(1.0))));
   }
References get_dx(), get_Q(), and system_ptr.
get_Q()
DenseVector< double > CppNoddy::OneD_TVDLF_Elt::get_Q (double s) const inline
Get the value of the 'concentration' stored in this element.
Parameters
s The local coordinate in the elt at which Q is requested
Returns
The concentration value of the elt for each component
Definition at line 197 of file OneD_TVDLF_Elt.h.
{
     return Q + SLOPE * s * (RIGHT - LEFT) / 2;
   }
References CppNoddy::Example::s.
Referenced by contributed_flux_in_left(), contributed_flux_out_right(), get_flux_fn(), get_int_Q(), get_Jac_flux_fn(), get_max_dt(), and get_source_fn().
get_s()
double CppNoddy::OneD_TVDLF_Elt::get_s (double x) const inline
Convert a global coordinate into a local coordinate within this element If the global coordinate is outside the element, then we throw an exception.
Parameters
x The global coordinate to convert
Definition at line 72 of file OneD_TVDLF_Elt.h.
{
 #ifdef PARANOID
       if((x < LEFT) || (x > RIGHT)) {
         std::string problem;
         problem = " The OneD_TVDLF_Elt::get_s method has been called for an element \n";
         problem += " whose range does not bracket the given global coordinate.\n";
         throw ExceptionRuntime(problem);
       }
 #endif
       return -1.0 + 2 * (x - LEFT) / (RIGHT - LEFT);
     }
get_slope()
DenseVector< double > CppNoddy::OneD_TVDLF_Elt::get_slope () const inline
The concentration is approximated by a linear function in each element.
The slope of this function is got through this method.
Returns
The value of the 'slope' member data
Definition at line 222 of file OneD_TVDLF_Elt.h.
{
     return SLOPE;
   }
Referenced by get_source_fn().
get_source_fn()
DenseVector< double > CppNoddy::OneD_TVDLF_Elt::get_source_fn (const double s) const
Get the value of the source function term in this element at a given local coordinate.
Parameters
s The local coordinate to evaluate at
Definition at line 166 of file OneD_TVDLF_Elt.cpp.
{
     DenseVector<double> r(system_ptr -> get_order(), 0.0);
     double x(get_x(s));
     system_ptr -> source_fn(x, get_Q(s), get_slope(), r);
     return r;
   }
References get_Q(), get_slope(), get_x(), CppNoddy::Example::s, CppNoddy::Example::source_fn(), and system_ptr.
Referenced by contributed_flux_in_left(), and contributed_flux_out_right().
get_x()
double CppNoddy::OneD_TVDLF_Elt::get_x (double s) const inline
Get the global position of the local coordinate.
Parameters
s The local coordinate
Returns
The global position
Definition at line 185 of file OneD_TVDLF_Elt.h.
{
     return (LEFT + RIGHT + s * get_dx()) / 2;
   }
References get_dx(), and CppNoddy::Example::s.
Referenced by contributed_flux_in_left(), contributed_flux_out_right(), get_flux_fn(), get_Jac_flux_fn(), and get_source_fn().
set_external_face_i()
void CppNoddy::OneD_TVDLF_Elt::set_external_face_i (int i) inline
Set the local coordinate of the external face.
Only one face can be external.
Parameters
i The index of the external face -1=left, +1=right
Definition at line 210 of file OneD_TVDLF_Elt.h.
{
     EXTERNAL_FACE_I = i;
   }
set_external_flag()
void CppNoddy::OneD_TVDLF_Elt::set_external_flag (bool flag) inline
Set the external flag.
Parameters
flag is the value to set
Definition at line 206 of file OneD_TVDLF_Elt.h.
{
     EXTERNAL = flag;
   }
set_Q_mid()
void CppNoddy::OneD_TVDLF_Elt::set_Q_mid (const DenseVector< double > value) inline
Set the value of the 'concentration' stored in this element.
To second order, this is the value of the concentration at the mid-point of the element.
Parameters
value The value to be assigned to the concentration member data Q
Definition at line 214 of file OneD_TVDLF_Elt.h.
{
     Q = value;
   }
set_slope()
void CppNoddy::OneD_TVDLF_Elt::set_slope (const DenseVector< double > value) inline
The concentration is approximated by a linear function in each element.
The slope of this function is set through this method.
Parameters
value The value to be assigned to the member data 'slope'
Definition at line 218 of file OneD_TVDLF_Elt.h.
{
     SLOPE = value;
   }
Member Data Documentation
system_ptr
OneD_Hyperbolic_System* CppNoddy::OneD_TVDLF_Elt::system_ptr
Definition at line 165 of file OneD_TVDLF_Elt.h.
Referenced by contributed_flux_in_left(), contributed_flux_out_right(), contributed_Q(), get_flux_fn(), get_Jac_flux_fn(), get_max_dt(), get_source_fn(), and OneD_TVDLF_Elt().
The documentation for this class was generated from the following files:
include/OneD_TVDLF_Elt.h
src/OneD_TVDLF_Elt.cpp
© 2012
R.E. Hewitt