CppNoddy: CppNoddy::Example::Karman_left_BC Class Reference
CppNoddy::Example::Karman_left_BC Class Reference
Define the boundary conditions.
Public Member Functions
Karman_left_BC ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &B) const
A blank virtual residual function method.
Karman_left_BC ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &B) const
A blank virtual residual function method.
Karman_left_BC ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &B) const
A blank virtual residual function method.
Karman_left_BC ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &B) const
A blank virtual residual function method.
Karman_left_BC ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &b) const
A blank virtual residual function method.
Public Member Functions inherited from CppNoddy::Residual< double >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< double > &state)
Update the Residual object for the current set of state variables.
const DenseVector< double > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< double > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
double & delta ()
const double & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< double > &state, DenseVector< double > &f) const
A blank virtual residual function method.
Public Member Functions inherited from CppNoddy::Residual_with_coords< double >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
double & coord (const unsigned &i)
General handle access to the coordinates.
const double & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< _Type >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Residual object for the current set of state variables.
const DenseVector< _Type > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< _Type > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
_Type & delta ()
const _Type & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< _Type > &state, DenseVector< _Type > &f) const
A blank virtual residual function method.
Additional Inherited Members
Protected Member Functions inherited from CppNoddy::Residual< double >
virtual void jacobian (const DenseVector< double > &state, DenseMatrix< double > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Member Functions inherited from CppNoddy::Residual< _Type >
virtual void jacobian (const DenseVector< _Type > &state, DenseMatrix< _Type > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual< double >
DenseMatrix< double > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< double > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< double > LAST_STATE
The last state vector.
double DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Protected Attributes inherited from CppNoddy::Residual_with_coords< double >
std::vector< double > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< _Type >
DenseMatrix< _Type > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< _Type > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< _Type > LAST_STATE
The last state vector.
_Type DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Define the boundary conditions.
Definition at line 53 of file BVPKarman.cpp.
Constructor & Destructor Documentation
Karman_left_BC() [1/5]
CppNoddy::Example::Karman_left_BC::Karman_left_BC () inline
Definition at line 57 of file BVPKarman.cpp.
: Residual<double> (3, 5) {}
Karman_left_BC() [2/5]
CppNoddy::Example::Karman_left_BC::Karman_left_BC () inline
Definition at line 55 of file BVPKarmanAdaptive.cpp.
: Residual<double> (3, 5) {}
Karman_left_BC() [3/5]
CppNoddy::Example::Karman_left_BC::Karman_left_BC () inline
Definition at line 63 of file BVPKarmanArclength.cpp.
: Residual<double> (3, 5) {}
Karman_left_BC() [4/5]
CppNoddy::Example::Karman_left_BC::Karman_left_BC () inline
Definition at line 69 of file BVPKarmanJacobian.cpp.
: Residual<double> (3, 5) {}
Karman_left_BC() [5/5]
CppNoddy::Example::Karman_left_BC::Karman_left_BC () inline
Definition at line 87 of file IBVPKarman.cpp.
: Residual_with_coords<double> (3, 5, 1) {}
Member Function Documentation
residual_fn() [1/5]
void CppNoddy::Example::Karman_left_BC::residual_fn (const DenseVector< double > & state, DenseVector< double > & f) const inline virtual
A blank virtual residual function method.
Parameters
state The unknown variable.
f The residual function f(x).
Reimplemented from CppNoddy::Residual< double >.
Definition at line 59 of file BVPKarman.cpp.
      {
        B[ 0 ] = z[ U ];
        B[ 1 ] = z[ V ];
        B[ 2 ] = z[ W ] - 1.0;
      }
References U, V, W, and CppNoddy::Example::z().
residual_fn() [2/5]
void CppNoddy::Example::Karman_left_BC::residual_fn (const DenseVector< double > & state, DenseVector< double > & f) const inline virtual
A blank virtual residual function method.
Parameters
state The unknown variable.
f The residual function f(x).
Reimplemented from CppNoddy::Residual< double >.
Definition at line 57 of file BVPKarmanAdaptive.cpp.
      {
        B[ 0 ] = z[ U ];
        B[ 1 ] = z[ V ];
        B[ 2 ] = z[ W ] - 1.0;
      }
References U, V, W, and CppNoddy::Example::z().
residual_fn() [3/5]
void CppNoddy::Example::Karman_left_BC::residual_fn (const DenseVector< double > & state, DenseVector< double > & f) const inline virtual
A blank virtual residual function method.
Parameters
state The unknown variable.
f The residual function f(x).
Reimplemented from CppNoddy::Residual< double >.
Definition at line 65 of file BVPKarmanArclength.cpp.
      {
        B[ 0 ] = z[ U ];
        B[ 1 ] = z[ V ];
        B[ 2 ] = z[ W ] - 1.0;
      }
References U, V, W, and CppNoddy::Example::z().
residual_fn() [4/5]
void CppNoddy::Example::Karman_left_BC::residual_fn (const DenseVector< double > & state, DenseVector< double > & f) const inline virtual
A blank virtual residual function method.
Parameters
state The unknown variable.
f The residual function f(x).
Reimplemented from CppNoddy::Residual< double >.
Definition at line 71 of file BVPKarmanJacobian.cpp.
      {
        B[ 0 ] = z[ U ];
        B[ 1 ] = z[ V ];
        B[ 2 ] = z[ W ] - 1.0;
      }
References U, V, W, and CppNoddy::Example::z().
residual_fn() [5/5]
void CppNoddy::Example::Karman_left_BC::residual_fn (const DenseVector< double > & state, DenseVector< double > & f) const inline virtual
A blank virtual residual function method.
Parameters
state The unknown variable.
f The residual function f(x).
Reimplemented from CppNoddy::Residual< double >.
Definition at line 89 of file IBVPKarman.cpp.
      {
        // get the time level for unsteady boundary condition
        const double t = coord( 0 );
        const double W_bc = Example::W_disk + ( Example::W_inf - Example::W_disk ) * std::exp( - 2 * t * t );
        b[ 0 ] = z[ U ];
        b[ 1 ] = z[ V ];
        b[ 2 ] = z[ W ] - W_bc;
      }
References CppNoddy::Residual_with_coords< double >::coord(), U, V, W, CppNoddy::Example::W_disk(), CppNoddy::Example::W_inf(), and CppNoddy::Example::z().
The documentation for this class was generated from the following files:
Tests/BVP/BVPKarman.cpp
Tests/BVP/BVPKarmanAdaptive.cpp
Tests/BVP/BVPKarmanArclength.cpp
Tests/BVP/BVPKarmanJacobian.cpp
Tests/IBVP/IBVPKarman.cpp
© 2012
R.E. Hewitt