CppNoddy: CppNoddy::Example::BC_upper Class Reference
CppNoddy::Example::BC_upper Class Reference
Public Member Functions
BC_upper ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &b) const
BC_upper ()
void residual_fn (const DenseVector< double > &z, DenseVector< double > &b) const
Public Member Functions inherited from CppNoddy::Residual_with_coords< double >
Residual_with_coords (const unsigned &order, const unsigned &ncoords)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual_with_coords (const unsigned &order, const unsigned &nvars, const unsigned &ncoords)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual_with_coords ()
An empty destructor.
double & coord (const unsigned &i)
General handle access to the coordinates.
const double & coord (const unsigned &i) const
General handle access to the coordinates.
Public Member Functions inherited from CppNoddy::Residual< _Type >
Residual (const unsigned &order)
Constructor for a 'square' residual object that is, N residuals for N unknowns.
Residual (const unsigned &order, const unsigned &nvars)
Constructor for a 'non-square' residual object that is, there are less residual constraints than unknowns.
virtual ~Residual ()
An empty destructor, virtual since we have virtual methods.
void update (const DenseVector< _Type > &state)
Update the Residual object for the current set of state variables.
const DenseVector< _Type > & residual () const
Return a handle to the residuals corresponding to the last update state.
const DenseMatrix< _Type > & jacobian () const
Retrun a handle to the Jacobian of the residual corresponding to the last update state.
_Type & delta ()
const _Type & delta () const
unsigned get_order () const
Get the order of the residual vector.
unsigned get_number_of_vars () const
Get the number of variables that this residual condition is defined for.
virtual void residual_fn (const DenseVector< _Type > &state, DenseVector< _Type > &f) const
A blank virtual residual function method.
Additional Inherited Members
Protected Member Functions inherited from CppNoddy::Residual< _Type >
virtual void jacobian (const DenseVector< _Type > &state, DenseMatrix< _Type > &jac) const
Because the residual evaluation at the current state is assumed to have already been done by the 'update' method, this routine is protected.
Protected Attributes inherited from CppNoddy::Residual_with_coords< double >
std::vector< double > coords
The coordinates stored for this residual.
Protected Attributes inherited from CppNoddy::Residual< _Type >
DenseMatrix< _Type > JAC_AT_LAST_STATE
Jacobian for the last state vector.
DenseVector< _Type > FN_AT_LAST_STATE
Residual for the last state vector.
DenseVector< _Type > LAST_STATE
The last state vector.
_Type DELTA
A default step for FD computation of the Jacobian.
unsigned ORDER_OF_SYSTEM
The order of the system of equations.
unsigned NUMBER_OF_VARS
The number of elements in the state vector.
Detailed Description
Definition at line 103 of file IBVPNonlinearFast.cpp.
Constructor & Destructor Documentation
BC_upper() [1/2]
CppNoddy::Example::BC_upper::BC_upper () inline
Definition at line 107 of file IBVPNonlinearFast.cpp.
: Residual_with_coords<double> (1, 2, 2) {}
BC_upper() [2/2]
CppNoddy::Example::BC_upper::BC_upper () inline
Definition at line 84 of file IBVPNonlinearSlower.cpp.
: Residual_with_coords<double> (1, 2, 2) {}
Member Function Documentation
residual_fn() [1/2]
void CppNoddy::Example::BC_upper::residual_fn (const DenseVector< double > & z, DenseVector< double > & b) const inline
Definition at line 109 of file IBVPNonlinearFast.cpp.
      {
        const double x = coord( 0 );
        const double t = coord( 1 );
        b[ 0 ] = z[ U ] - t * std::exp( - x );
      }
References CppNoddy::Residual_with_coords< double >::coord(), U, and CppNoddy::Example::z().
residual_fn() [2/2]
void CppNoddy::Example::BC_upper::residual_fn (const DenseVector< double > & z, DenseVector< double > & b) const inline
Definition at line 86 of file IBVPNonlinearSlower.cpp.
      {
        const double x = coord( 0 );
        const double t = coord( 1 );
        b[ 0 ] = z[ U ] - t * std::exp( - x );
      }
References CppNoddy::Residual_with_coords< double >::coord(), U, and CppNoddy::Example::z().
The documentation for this class was generated from the following files:
Tests/double_IBVP/IBVPNonlinearFast.cpp
Tests/double_IBVP/IBVPNonlinearSlower.cpp
© 2012
R.E. Hewitt