CppNoddy: Tests/EVP/EVPHarmonicEasy_lapack.cpp File Reference
EVPHarmonicEasy_lapack.cpp File Reference
Tests
#include <EVP_bundle.h>
#include <Utility.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::harmonic_equation
Define the harmonic equation by inheriting the Equation base class.
class CppNoddy::Example::harmonic_both_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { f, fd }
Functions
int main ()
Detailed Description
Solves the harmonic equation
as an eigenvalue problem for over the unit domain with homogeneous boundary conditions for , returning the smallest eigenvalue. This is the 'easy' approach, using the ODE_EVP class which is constructed from an Equation_with_mass object, with Residual objects for the boundary conditions. The solver then only needs a pointer to the eigenvalue variable.
Definition in file EVPHarmonicEasy_lapack.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
f
fd
Definition at line 18 of file EVPHarmonicEasy_lapack.cpp.
 {f, fd };
Function Documentation
main()
int main ()
Definition at line 72 of file EVPHarmonicEasy_lapack.cpp.
 {
   cout << "\n";
   cout << "=== EVP: The harmonic equation done the easy way ====\n";
   cout << "\n";
   // test pass/fail
   bool failed( true );
   Example::harmonic_equation problem;
   Example::harmonic_both_BC BC_both;
   // domain is 0 to 1
   double left = 0.0;
   double right = 1.0;
   // number of nodal points
   int N = 256;
   // EV is pi^2 so we'll guess = 10 + 0i
   D_complex guess( 10.0, 0.0 );
   // pass/fail tolerance
   const double tol = 1.e-3;
   cout << " Solving the system using LAPACK:\n";
   // set up the ode eigenproblem
   ODE_EVP<double> ode_lapack( &problem, Utility::uniform_node_vector( left, right, N ), &BC_both, &BC_both );
   ode_lapack.p_eigensystem() -> set_calc_eigenvectors( true );
   ode_lapack.p_eigensystem() -> set_shift( guess );
   try
   {
     // solve the global eigenvalue
     ode_lapack.eigensolve();
   }
   catch (const std::runtime_error &error )
   {
     cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
     return 1;
   }
   // get the eigenvalues in a disk of radius 1 about the guess
   ode_lapack.p_eigensystem() -> tag_eigenvalues_disc( + 1, 1. );
   // get the tagged eigenvalue(s) -- hopefully only 1
   DenseVector<D_complex> lapack_lambdas = ode_lapack.p_eigensystem() -> get_tagged_eigenvalues();
   if ( abs( lapack_lambdas[ 0 ].real() - M_PI * M_PI ) < tol )
   {
     failed = false;
     cout << "  LAPACK solver works.\n";
   }
   if ( failed )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     return 1;
   }
   cout << "\033[1;32;48m  * PASSED \033[0m\n";
   return 0;
 }
References CppNoddy::ODE_EVP< _Type >::eigensolve(), CppNoddy::Example::failed, CppNoddy::ODE_EVP< _Type >::p_eigensystem(), CppNoddy::Utility::real(), and CppNoddy::Utility::uniform_node_vector().
© 2012
R.E. Hewitt