CppNoddy: Tests/EVP/EVPRayleigh_lapack.cpp File Reference
EVPRayleigh_lapack.cpp File Reference
Tests
#include <EVP_bundle.h>
#include <HST.h>
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Functions
D_complex CppNoddy::Example::U (const D_complex &y)
D_complex CppNoddy::Example::Udd (const D_complex &y)
int main ()
Variables
OneD_Node_Mesh< D_complex, D_complex > CppNoddy::Example::baseflow
Detailed Description
Solves the Rayleigh problem for values that satisfy :
subject to ; it determines the critical wavenumber such that for . The test compares the critical wavenumber with the predicted value of .
Definition in file EVPRayleigh_lapack.cpp.
Function Documentation
main()
int main ()
Definition at line 38 of file EVPRayleigh_lapack.cpp.
 {
   cout << "\n";
   cout << "=== EVP: Rayleigh modes, Tollmien's example =========\n";
   cout << "\n";
   Example::alpha = 0.8;    // the wavenumber
   double tol = 1.e-5;      // tolerance for the test
   double left = 0.0;       // from y = 0
   double right = 2 * M_PI; // to y= 2*pi
   unsigned N( 801 );
   // a real distribution of nodes
   DenseVector<double> r_nodes( Utility::power_node_vector( left, right, N, 1.0 ) );
   DenseVector<D_complex> c_nodes( r_nodes );
   // make a distribution of nodes in the complex plane
   for ( unsigned i = 0; i < N; ++i )
   {
     D_complex y( r_nodes[ i ] );
     c_nodes[ i ] -= .2 * D_complex( 0.0, 1.0 ) * y * std::exp( - y );
   }
   // make a base flow on the complex distribution of nodes
   OneD_Node_Mesh<D_complex, D_complex> base( c_nodes, 2 );
   for ( unsigned i = 0; i < c_nodes.size(); ++i )
   {
     D_complex y = c_nodes[ i ];
     base( i, 0 ) = Example::U( y );
     base( i, 1 ) = Example::Udd( y );
   }
   // make the Rayleigh EVP, with 'CHANNEL' boundary conditions
   HST::Rayleigh<D_complex> my_ray( base, Example::alpha, "CHANNEL" );
   // do a global solve
   my_ray.global_evp();
   unsigned i_ev = 0;
   for ( unsigned i = 0; i < my_ray.eigenvalues().size(); ++i )
   {
     if ( my_ray.eigenvalues()[ i ].imag() > 0.05 )
     {
       // there should be only one
       i_ev = i;
     }
   }
   my_ray.iterate_to_neutral( i_ev );
   if ( std::abs( my_ray.alpha() - .5*sqrt( 3. ) ) < tol )
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
   cout << "\033[1;31;48m  * FAILED \033[0m\n";
   cout << "    Final error in critical wavenumber = " << std::abs( my_ray.alpha() - .5*sqrt( 3. ) ) << "\n";
   return 1;
 }
References CppNoddy::Example::alpha, CppNoddy::HST::Rayleigh< _Type >::alpha(), CppNoddy::HST::Rayleigh< _Type >::eigenvalues(), CppNoddy::HST::Rayleigh< _Type >::global_evp(), CppNoddy::HST::Rayleigh< _Type >::iterate_to_neutral(), CppNoddy::Utility::power_node_vector(), CppNoddy::DenseVector< _Type >::size(), CppNoddy::Example::U(), and CppNoddy::Example::Udd().
© 2012
R.E. Hewitt