CppNoddy: Tests/Generic/ExceptionChecks.cpp File Reference
ExceptionChecks.cpp File Reference
Tests
We do some obviously dumb things to induce a handful of common failures.
#include <Newton_bundle.h>
#include <DenseLinearSystem.h>
Classes
class CppNoddy::Example::Cube_root_problem
The problem to be solved, here z^3 -1 in complex form.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Functions
int main ()
Detailed Description
We do some obviously dumb things to induce a handful of common failures.
The failures should result in exceptions being thrown, which should be caught. The test is passed if the required number of exceptions are successfully caught.
Definition in file ExceptionChecks.cpp.
Function Documentation
main()
int main ()
Definition at line 39 of file ExceptionChecks.cpp.
{
  cout << "\n";
  cout << "=== Exception checks: testing forced failures =======\n";
  cout << "\n";
  int exceptions_caught( 0 );
  int tests( 0 );
  {
    ++tests;
    // set up noddy singular 2x2 problem
    DenseMatrix<double> A( 2, 2, 0.0 );
    DenseVector<double> B( 2, 0.0 );
    A( 0, 0 ) = 1.;
    A( 0, 1 ) = 2.;
    A( 1, 0 ) = 2.; // row 1 = 2 * row 0 -- so singular
    A( 1, 1 ) = 4.;
    B[ 0 ] = 5.;
    B[ 1 ] = 11.;
    DenseLinearSystem<double> system( &A, &B, "native" );
    // singular matrix should be caught in the native solver
    try
    {
      system.solve();
    }
    catch ( const std::exception & e )
    {
      ++exceptions_caught;
      cout << "  Caught a runtime exception in the native linear solver \n\n";
    }
  }
  {
    // too many potential geometry errors to test ... just the add method here
#ifdef PARANOID
    ++tests;
    // geometry checkes are only made under PARANOID flags
    DenseMatrix<double> C( 3, 3, 1.0 );
    DenseMatrix<double> D( 2, 2, 1.0 );
    try
    {
      C.add( D );
    }
    catch ( std::exception & e )
    {
      ++exceptions_caught;
      cout << "  Caught a geometry exception when adding two matrices. \n\n";
    }
#endif
  }
  {
    ++tests;
    // set the tolerance & max iteration number too low
    Example::Cube_root_problem problem;
    Newton<D_complex> newton( &problem, 8, 1.e-12 );
    D_complex half( 0.5, 0.5 );
    DenseVector<D_complex> guess( 1, half );
    try
    {
      newton.iterate( guess );
    }
    catch ( std::exception & e )
    {
      ++exceptions_caught;
      cout << "  Caught an iteration exception in a scalar Newton problem. \n\n";
    }
  }
  if ( tests != exceptions_caught )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    cout << tests << " checks were run but only " << exceptions_caught
         << " exceptions were caught!\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::DenseMatrix< _Type >::add(), CppNoddy::Newton< _Type >::iterate(), and CppNoddy::DenseLinearSystem< _Type >::solve().
© 2012
R.E. Hewitt