CppNoddy: Tests/HYP_2D/HYP2DRadialDamBreak.cpp File Reference
HYP2DRadialDamBreak.cpp File Reference
#include <TwoD_HYP_bundle.h>
Classes
class CppNoddy::Example::Shallow_2d_rad
Define the system.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { h, hu, hv }
Functions
double CppNoddy::Example::g (1.0)
gravitational acceleration
double CppNoddy::Example::A (1.0)
initial hump amplitude
void CppNoddy::Example::Q_init (const double &x, const double &y, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
h
hu
hv
Definition at line 10 of file HYP2DRadialDamBreak.cpp.
 { h, hu, hv };
Function Documentation
main()
int main ()
Definition at line 97 of file HYP2DRadialDamBreak.cpp.
 {
   cout << "\n";
   cout << "=== Hyperbolic: 2D radial dam-break in Cartesians ===\n";
   cout << "\n";
   // define the domain/mesh
   const double west = -1;
   const double east = 1;
   const double south = -1;
   const double north = 1;
   const unsigned N = 151;
   DenseVector<double> faces_x = Utility::power_node_vector( west, east, N, 1.0 );
   DenseVector<double> faces_y = Utility::power_node_vector( south, north, N, 1.0 );
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   std::string filename_stub( "./DATA/HYP_2D_rad_dam" );
   Example::Shallow_2d_rad conservative_problem;
   TwoD_TVDLF_Mesh Shallow_2d_mesh( faces_x, faces_y, &conservative_problem, Example::Q_init );
   Shallow_2d_mesh.set_limiter( 0 );
   int file_counter( 1 );
   const double t_end = 0.5;
   DenseVector<double> x1( 2, 0.0 );
   x1[0] = 0.4;
   x1[1] = 0.1;
   DenseVector<double> x2( 2, 0.0 );
   x2[0] = 0.1;
   x2[1] = 0.4;
   do
   {
     Shallow_2d_mesh.update( 0.49, std::abs( Shallow_2d_mesh.get_time() - t_end ) );
     Shallow_2d_mesh.dump_gnu( filename_stub + Utility::stringify( file_counter ) + "_gnu.dat" );
     file_counter += 1;
   }
   while ( Shallow_2d_mesh.get_time() < t_end );
   double h_clawpack( 1.13466 );
   double theta = M_PI / 4;
   DenseVector<double> x( 2, 0.0 );
   x[ 0 ] = 0.5 * cos( theta );
   x[ 1 ] = 0.5 * sin( theta );
   double h_diag = Shallow_2d_mesh.get_point_values( x )[ h ];
   if ( abs( h_diag - h_clawpack ) > 1.e-3 )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << " deviation from the Clawpack data = " << abs( h_diag - h_clawpack ) << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::TwoD_TVDLF_Mesh::dump_gnu(), CppNoddy::TwoD_TVDLF_Mesh::get_point_values(), CppNoddy::TwoD_TVDLF_Mesh::get_time(), h, CppNoddy::Utility::power_node_vector(), CppNoddy::Example::Q_init(), CppNoddy::TwoD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), and CppNoddy::TwoD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt