CppNoddy: Tests/HYP_2D/HYP2DNonlinearAdvectionXY.cpp File Reference
HYP2DNonlinearAdvectionXY.cpp File Reference
Tests
#include <TwoD_HYP_bundle.h>
Classes
class CppNoddy::Example::NlinAdv
Define the system.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Functions
void CppNoddy::Example::Q_init (const double &x, const double &y, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Detailed Description
Solving the 2D ‘nonlinear advection equation’
using a TVD Lax-Friedrichs scheme for . The initial condition is a sine distribution.
Definition in file HYP2DNonlinearAdvectionXY.cpp.
Function Documentation
main()
int main ()
Definition at line 66 of file HYP2DNonlinearAdvectionXY.cpp.
 {
   cout << "\n";
   cout << "=== Hyperbolic: 2D nonlinear advection at an angle ==\n";
   cout << "\n";
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   std::string filename_stub( "./DATA/HYP_2D_nlin_adv_xy" );
   // define the domain/mesh
   const double west =  -1.0;
   const double east =  1.0;
   const double south =  -1.0;
   const double north = 1.0;
   const unsigned N = 151;
   DenseVector<double> faces_x = Utility::uniform_node_vector( west, east, N );
   DenseVector<double> faces_y = Utility::uniform_node_vector( south, north, N );
   Example::NlinAdv conservative_problem;
   TwoD_TVDLF_Mesh NlinAdv_mesh( faces_x, faces_y, &conservative_problem, Example::Q_init );
   NlinAdv_mesh.set_limiter( 0 );
   double asym( 0.0 );
   unsigned loop_counter( 0 );
   DenseVector<double> x1( 2, 0.0 );
   x1[ 0 ] = 0.75;
   x1[ 1 ] = 0.75;
   DenseVector<double> x2( 2, 0.0 );
   x2[ 0 ] = -0.75;
   x2[ 1 ] = -0.75;
   do
   {
     NlinAdv_mesh.update( 0.49 );
     NlinAdv_mesh.dump_gnu( filename_stub + Utility::stringify( loop_counter ) + "_gnu.dat" );
     asym = std::max( asym, std::abs( NlinAdv_mesh.get_point_values( x1 )[0] + NlinAdv_mesh.get_point_values( x2 )[0] ) );
     ++loop_counter;
   }
   while ( ( NlinAdv_mesh.get_time() < 0.4 ) && ( loop_counter < 1000 ) );
   // problem should be antisymmetric about x = 1/2
   if ( ( asym > 1.e-9 ) || ( loop_counter >= 1000 ) )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << "asymmetry = " << asym << "\n";
     cout << "loop counter = " << loop_counter << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 } // end of main()
References CppNoddy::TwoD_TVDLF_Mesh::dump_gnu(), CppNoddy::TwoD_TVDLF_Mesh::get_point_values(), CppNoddy::TwoD_TVDLF_Mesh::get_time(), CppNoddy::Example::Q_init(), CppNoddy::TwoD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), CppNoddy::Utility::uniform_node_vector(), and CppNoddy::TwoD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt