CppNoddy: Tests/HYP_1D/HYPAcousticReflection.cpp File Reference
HYPAcousticReflection.cpp File Reference
Tests
Solve the constant coefficient linear sound wave problem.
#include <OneD_HYP_bundle.h>
Classes
class CppNoddy::Example::Acoustic_1d_ref
Define the system.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Enumerations
enum { p , u }
Functions
double CppNoddy::Example::K (2.0)
bulk modulus
double CppNoddy::Example::rho (2.0)
higher density
void CppNoddy::Example::Q_init (const double &x, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Detailed Description
Solve the constant coefficient linear sound wave problem.
for a right-propagating square pulse in a medium with constant bulk modulus and density and reflecting boundary conditions at both sides.
Definition in file HYPAcousticReflection.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
p
u
Definition at line 13 of file HYPAcousticReflection.cpp.
{ p, u };
Function Documentation
main()
int main ()
Definition at line 83 of file HYPAcousticReflection.cpp.
{
  cout << "\n";
  cout << "=== Hyperbolic: 1D acoustic wave reflection problem =\n";
  cout << "\n";
  // define the domain/mesh
  const double left =  -3.0;
  const double right = 3.0;
  const unsigned N = 800;
  DenseVector<double> faces_x = Utility::uniform_node_vector( left, right, N );
  // time
  double t = 0;
  double t_end = 6;
  // hyperbolic problem
  Example::Acoustic_1d_ref conservative_problem;
  OneD_TVDLF_Mesh Acoustic_mesh( faces_x, &conservative_problem, Example::Q_init );
  Acoustic_mesh.set_limiter( 1 );
  // output
  double I1 = Acoustic_mesh.integrate()[0];
  int loop_counter( 0 );
  int file_counter( 1 );
  std::string dirname("./DATA");
  mkdir( dirname.c_str(), S_IRWXU );
  std::string filename_stub;
  filename_stub = "./DATA/HYP_acoustic_ref";
  TrackerFile my_file( 5 );
  OneD_Node_Mesh<double> soln = Acoustic_mesh.get_soln();
  my_file.push_ptr( &soln, "mesh" );
  do
  {
    if ( loop_counter % 10 == 0 )
    {
      my_file.set_filename( filename_stub + Utility::stringify( file_counter ) + ".dat" );
      soln = Acoustic_mesh.get_soln();
      my_file.update();
      file_counter += 1;
    }
    // take a step
    t += Acoustic_mesh.update( 0.49, t_end - t );
    ++loop_counter;
  }
  while ( ( t < t_end ) && ( loop_counter < 1100 ) );
  double I2 = Acoustic_mesh.integrate()[0];
  // compute the pressure difference after the pressure pulse
  // has returned to its original position
  soln = Acoustic_mesh.get_soln();
  my_file.update();
  double diff = 0.0;
  for ( std::size_t i = 0; i < soln.get_nnodes(); ++i )
  {
    // get the initial condition
    DenseVector<double> q( 2, 0.0 );
    Example::Q_init( soln.coord( i ), q );
    // difference between initial and final state
    diff = std::max( diff, q[0] - soln( i, 0 ) );
  }
  // check the maximum difference in the reflected pulse & the
  // integral of the pressure over the mesh
  if ( ( diff > 1.e-2 ) || ( std::abs( I1 - I2 ) > 1.e-8 ) )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    cout << "difference in the reflected wave = " << diff << "\n";
    cout << "difference in the integral = " << std::abs( I1 - I2 ) << "\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
} // end of main()
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::coord(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_nnodes(), CppNoddy::OneD_TVDLF_Mesh::get_soln(), CppNoddy::OneD_TVDLF_Mesh::integrate(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::TrackerFile::set_filename(), CppNoddy::OneD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), CppNoddy::Utility::uniform_node_vector(), CppNoddy::TrackerFile::update(), and CppNoddy::OneD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt