CppNoddy: Tests/HYP_1D/HYPRadialDamBreak.cpp File Reference
HYPRadialDamBreak.cpp File Reference
Tests
Solve the shallow water equations in one dimension for an initial column of fluid.
#include <OneD_HYP_bundle.h>
Classes
class CppNoddy::Example::Shallow_1d_rad
Define the system.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Enumerations
enum { h , hu }
Functions
double CppNoddy::Example::g (1.0)
gravitational acceleration
double CppNoddy::Example::A (1.0)
initial hump amplitude
void CppNoddy::Example::Q_init (const double &x, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Detailed Description
Solve the shallow water equations in one dimension for an initial column of fluid.
The result is compared to the same problem solved using Clawpack, evaluated at the single point x=0.5.
Definition in file HYPRadialDamBreak.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
h
hu
Definition at line 13 of file HYPRadialDamBreak.cpp.
{ h, hu };
Function Documentation
main()
int main ()
Todo:
Include a mechanism for avoiding source term computations at the singular point by indicating where edge conditions are specified. For the time being, we'll bodge it by stopping away from x=0.
Definition at line 75 of file HYPRadialDamBreak.cpp.
{
  cout << "\n";
  cout << "=== Hyperbolic: Shallow water radial dam break ======\n";
  cout << "\n";
  // There is a singular source_fn at r=0, so we bodge it here (for now).
  /// \todo Include a mechanism for avoiding source term computations
  /// at the singular point by indicating where edge conditions are specified.
  /// For the time being, we'll bodge it by stopping away from x=0.
  const double left =  1.e-4;
  const double right = 2.5;
  const unsigned N = 2001;
  DenseVector<double> faces_x = Utility::power_node_vector( left, right, N, 1.0 );
  // time
  double t = 0;
  double t_end = 0.5;
  // hyperbolic problem
  Example::Shallow_1d_rad conservative_problem;
  OneD_TVDLF_Mesh Shallow_mesh( faces_x, &conservative_problem, Example::Q_init );
  Shallow_mesh.set_limiter( 0 );
  // output
  int loop_counter( 0 );
  int file_counter( 0 );
  std::string dirname("./DATA");
  mkdir( dirname.c_str(), S_IRWXU );
  std::string filename_stub;
  filename_stub = "./DATA/HYP_shallow_rad";
  TrackerFile my_file( 5 );
  OneD_Node_Mesh<double> soln = Shallow_mesh.get_soln();
  my_file.push_ptr( &soln, "mesh" );
  do
  {
    if ( loop_counter % 50 == 0 )
    {
      my_file.set_filename( filename_stub + Utility::stringify( file_counter ) + ".dat" );
      soln = Shallow_mesh.get_soln();
      my_file.update();
      file_counter += 1;
    }
    t += Shallow_mesh.update( 0.499, t_end - t );
    ++loop_counter;
  }
  while ( ( t < t_end ) && ( loop_counter < 3000 ) );
  // we test the result against the Clawpack computational result
  soln = Shallow_mesh.get_soln();
  double h_clawpack( 1.13466 );
  double h_test( soln.get_interpolated_vars( 0.5 )[ h ] );
  if ( abs( h_test - h_clawpack ) > 1.e-3 )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    cout << " deviation from the Clawpack data = " << abs( h_test - h_clawpack ) << "\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
} // end of main()
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_interpolated_vars(), CppNoddy::OneD_TVDLF_Mesh::get_soln(), h, CppNoddy::Utility::power_node_vector(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::TrackerFile::set_filename(), CppNoddy::OneD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), CppNoddy::TrackerFile::update(), and CppNoddy::OneD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt