CppNoddy: Tests/HYP_1D/HYPSodsShocktube.cpp File Reference
HYPSodsShocktube.cpp File Reference
Tests
#include <OneD_HYP_bundle.h>
Classes
class CppNoddy::Example::Euler_1d
Define the system.
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { rho, m, E }
Functions
double CppNoddy::Example::gamma (1.4)
Adiabatic index – ratio of specific heats.
void CppNoddy::Example::Q_init (const double &x, DenseVector< double > &q)
Set the initial state of the system.
int main ()
Detailed Description
Solving the 1D Euler problem for gas dynamics
where
and . The initial conditions correspond to Sod's problem
for
for .
Definition in file HYPSodsShocktube.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
rho
m
E
Definition at line 18 of file HYPSodsShocktube.cpp.
 { rho, m, E };
Function Documentation
main()
int main ()
Definition at line 83 of file HYPSodsShocktube.cpp.
 {
   cout << "\n";
   cout << "=== Hyperbolic: 1D Euler gasdynamics shocktube  =====\n";
   cout << "\n";
   // define the domain/mesh
   const double left =  0.0;
   const double right = 1.0;
   const unsigned N = 400;
   DenseVector<double> faces_x = Utility::uniform_node_vector( left, right, N );
   double t = 0.0;
   Example::Euler_1d conservative_problem;
   OneD_TVDLF_Mesh Euler_mesh( faces_x, &conservative_problem, Example::Q_init );
   Euler_mesh.set_limiter( 0 );
   double I1 = Euler_mesh.integrate()[0];
   int loop_counter( 0 );
   int file_counter( 0 );
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   std::string filename_stub;
   filename_stub = "./DATA/HYP_shocktube_sod";
   TrackerFile my_file( 10 );
   OneD_Node_Mesh<double> soln = Euler_mesh.get_soln();
   my_file.push_ptr( &soln, "mesh" );
   do
   {
     if ( loop_counter % 10 == 0 )
     {
       my_file.set_filename( filename_stub + Utility::stringify( file_counter ) + ".dat" );
       soln = Euler_mesh.get_soln( );
       my_file.update();
       file_counter += 1;
     }
     t += Euler_mesh.update( 0.499 );
     ++loop_counter;
   }
   while ( ( t < 0.2 ) && ( loop_counter < 1000 ) );
   double I2 = Euler_mesh.integrate()[0];
   // These are clawpack results (to 4dp) with N=400 and minmod for the
   // density of the two density steps ...
   soln = Euler_mesh.get_soln( );
   double E1 = std::abs( soln.get_interpolated_vars( 0.575 )[0] - 0.4264 );
   double E2 = std::abs( soln.get_interpolated_vars( 0.75 )[0] - 0.2656 );
   // check against the clawpack data, and that the mass is conserved.
   if ( ( E1 > 1.e-3 ) || ( E2 > 1.e-3 ) || ( std::abs( I1 - I2 ) > 1.e-8 ) || ( loop_counter >= 1000 ) )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << E1 << " " << E2 << " " << std::abs( I1 - I2 ) << " " << loop_counter << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 } // end of main()
References CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_interpolated_vars(), CppNoddy::OneD_TVDLF_Mesh::get_soln(), CppNoddy::OneD_TVDLF_Mesh::integrate(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::Example::Q_init(), CppNoddy::TrackerFile::set_filename(), CppNoddy::OneD_TVDLF_Mesh::set_limiter(), CppNoddy::Utility::stringify(), CppNoddy::Utility::uniform_node_vector(), CppNoddy::TrackerFile::update(), and CppNoddy::OneD_TVDLF_Mesh::update().
© 2012
R.E. Hewitt