CppNoddy: Tests/IBVP/IBVPKarman.cpp File Reference
IBVPKarman.cpp File Reference
Tests
Solving the unsteady Karman rotating-disk equations for the flow above an infinite rotating disk in a rotating fluid:
#include <IBVP_bundle.h>
Classes
class CppNoddy::Example::Karman_equations
Define the Karman equations.
class CppNoddy::Example::Karman_left_BC
Define the boundary conditions.
class CppNoddy::Example::Karman_right_BC
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Enumerations
enum {
U , Ud , V , W ,
Wd
}
Functions
double CppNoddy::Example::W_inf (0.0)
double CppNoddy::Example::W_disk (1.0)
int main ()
Detailed Description
Solving the unsteady Karman rotating-disk equations for the flow above an infinite rotating disk in a rotating fluid:
with boundary conditions , and , . The initial condition corresponds to rigid rotation of the fluid and boundary at the frequency The class constructs and solves the IBVP using 2nd order finite-differencing in both space and time over a non-uniform spatial mesh. The example shows the case and
and simply checks for convergence to the correct steady state solution.
Definition in file IBVPKarman.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
U
Ud
V
W
Wd
Definition at line 21 of file IBVPKarman.cpp.
{ U, Ud, V, W, Wd };
Function Documentation
main()
int main ()
Definition at line 119 of file IBVPKarman.cpp.
{
  cout << "\n";
  cout << "=== IBVP: The unsteady Karman equations  ============\n";
  cout << "\n";
  // define the system
  Example::Karman_equations problem;
  // define the boundary conditions
  Example::Karman_left_BC BC_left;
  Example::Karman_right_BC BC_right;
  // domain definition
  double left = 0.0;
  double right = 40.0;
  // number of (spatial) nodal points
  unsigned ny = 400;
  // time step
  double dt = 0.005;
  // number of time steps
  unsigned max_steps = ( unsigned ) ( 30.0 / dt );
  // construct our IBVP with more nodes near the boundary
  PDE_IBVP<double> karman( &problem, Utility::power_node_vector( left, right, ny, 2.0 ), &BC_left, &BC_right );
  //
  for ( unsigned i = 0; i < ny; ++i )
  {
    karman.solution()( i, U ) = 0.0;
    karman.solution()( i, Ud ) = 0.0;
    karman.solution()( i, V ) = 0.0;
    karman.solution()( i, W ) = Example::W_inf;
    karman.solution()( i, Wd ) = 0.0;
  }
  // set up output details
  std::string dirname("./DATA");
  mkdir( dirname.c_str(), S_IRWXU );
  TrackerFile metric( "./DATA/IBVP_Karman_metric.dat" );
  metric.push_ptr( &karman.coord(), "time" );
  metric.push_ptr( &karman.solution()( ny - 1, V ), "Ekman suction" );
  metric.header();
  TrackerFile profs( "./DATA/IBVP_Karman_profs.dat" );
  profs.push_ptr( &karman.coord(), "time" );
  profs.push_ptr( &karman.solution(), "solution" );
  profs.header();
  // time step
  for ( unsigned i = 1; i < max_steps; ++i )
  {
    // take a time step
    try
    {
      karman.step2( dt );
    }
    catch (const std::runtime_error &error )
    {
      cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
      return 1;
    }
    metric.update();
  }
  const double tol( 1.e-4 );
  // check the BL transpiration vs the known solution
  if ( abs( karman.solution()( ny - 1, V ) + 0.88447 ) > tol )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    cout << " Difference = " << abs( karman.solution()( ny - 1, V ) + 0.88447 ) << "\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::PDE_IBVP< _Type >::coord(), CppNoddy::TrackerFile::header(), CppNoddy::Utility::power_node_vector(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::PDE_IBVP< _Type >::solution(), CppNoddy::PDE_IBVP< _Type >::step2(), U, Ud, CppNoddy::TrackerFile::update(), V, W, and Wd.
© 2012
R.E. Hewitt