CppNoddy: Tests/double_IBVP/IBVPLinear.cpp File Reference
IBVPLinear.cpp File Reference
Tests
#include <IBVP_double_bundle.h>
#include "../Utils_Fill.h"
Classes
class CppNoddy::Example::diffusion_double
class CppNoddy::Example::dd_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { U, Ud }
Functions
double CppNoddy::Example::source (const double &x, const double &y, const double &t)
int main ()
Detailed Description
Solving the linear equation
subject to and . The solution is computed over a range of for and the maximum deviation away from the exact solution is found. The test fails if this deviation is larger than a set tolerance . The example is solved using the PDE_double_IBVP for problems that are parabolic in 2 coordinates with a BVP in .
Definition in file IBVPLinear.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
U
Ud
Definition at line 18 of file IBVPLinear.cpp.
 { U, Ud };
Function Documentation
main()
int main ()
Definition at line 104 of file IBVPLinear.cpp.
 {
   cout << "\n";
   cout << "=== double_IBVP: linear diffusive problem ===========\n";
   cout << "\n";
   // instantiate the problem
   Example::diffusion_double problem;
   Example::dd_BC BC_bottom;
   Example::dd_BC BC_top;
   // domain definition
   double top = 1.0;
   double bottom = -1.0;
   double left = 0.0;
   double right = 10.0;
   // number of (spatial) nodal points
   unsigned ny = 301;
   unsigned nx = 301;
   // time and time step
   double t_end = 1.0;
   double dt = 0.01;
   // construct our IBVP
   PDE_double_IBVP<double> diffusion( &problem,
                                      Utility::uniform_node_vector( left, right, nx ),
                                      Utility::uniform_node_vector( bottom, top, ny ),
                                      &BC_bottom, &BC_top );
   // initial conditions
   for ( unsigned i = 0; i < nx; ++i )
   {
     for ( unsigned j = 0; j < ny; ++j )
     {
       double y = diffusion.solution().coord( i, j ).second;
       diffusion.solution()( i, j, U ) = ( 1.0 - y * y );
       diffusion.solution()( i, j, Ud ) = - 2 * y ;
     }
   }
   double max_error( 0.0 );
   do
   {
     diffusion.update_previous_solution();
     diffusion.step2( dt );
     for ( unsigned i = 0; i < nx; ++i )
     {
       for ( unsigned j = 0; j < ny; ++j )
       {
         double x = diffusion.solution().coord( i, j ).first;
         double y = diffusion.solution().coord( i, j ).second;
         double exact_u = ( 1 - y * y ) * exp( - x * diffusion.t() );
         max_error = max( max_error, abs( exact_u - diffusion.solution()( i, j, U ) ) );
       }
     }
   }
   while ( diffusion.t() < t_end );
   const double tol( 1.e-4 );
   // check the BL transpiration vs the known solution
   if ( max_error > tol )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << " Difference = " << max_error << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::PDE_double_IBVP< _Type >::solution(), CppNoddy::PDE_double_IBVP< _Type >::step2(), CppNoddy::PDE_double_IBVP< _Type >::t(), U, Ud, CppNoddy::Utility::uniform_node_vector(), and CppNoddy::PDE_double_IBVP< _Type >::update_previous_solution().
© 2012
R.E. Hewitt