CppNoddy: Tests/IBVP/IBVPDiffusion.cpp File Reference
IBVPDiffusion.cpp File Reference
Tests
#include <IBVP_bundle.h>
Classes
class CppNoddy::Example::Diff_equation
class CppNoddy::Example::Diff_both_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { f, fd }
Functions
int main ()
Detailed Description
Solving the heat diffusion equation
subject to and with initial condition . The solution is computed over a range of and the maximum deviation away from the analytical solution is found. The test fails if this deviation is larger than a set tolerance . The analytical solution is the Fourier series:
The series is truncated at the -th term, in such a way that the first neglected term is of magnitude .
Definition in file IBVPDiffusion.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
f
fd
Definition at line 19 of file IBVPDiffusion.cpp.
 { f, fd };
Function Documentation
main()
int main ()
Definition at line 83 of file IBVPDiffusion.cpp.
 {
   cout << "\n";
   cout << "=== IBVP: An unsteady diffusion eqn =================\n";
   cout << "\n";
   // Diffusion equation
   Example::Diff_equation problem;
   // boundary conditions
   Example::Diff_both_BC BC_both;
   // domain definition
   double left = 0.0;
   double right = 1.0;
   // number of (spatial) nodal points
   unsigned ny = 201;
   // time step
   double dt = 0.005;
   // number of time steps
   unsigned max_steps = ( unsigned ) ( 3.0 / dt );
   // test tolerance
   double tol = 1.e-4;
   // construct our IBVP
   PDE_IBVP<double> heat( &problem, Utility::uniform_node_vector( left, right, ny ), &BC_both, &BC_both );
   for ( unsigned i = 0; i < ny; ++i )
   {
     double y = heat.solution().coord( i );
     heat.solution()( i, f ) = y * ( 1 - y );
     heat.solution()( i, fd ) = 1 - 2 * y;
   }
   // maximum difference between numerical and series solution at centre point
   double max_diff( 0.0 );
   // time step
   for ( unsigned i = 1; i < max_steps; ++i )
   {
     // take a time step
     try
     {
       heat.step2( dt );
     }
     catch (const std::runtime_error &error )
     {
       cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
       return 1;
     }
     // evaluate analytical Fourier series solution at y = 0.5
     unsigned mid = ( ny - 1 ) / 2;
     double y = left + mid * ( right - left ) / ( ny - 1 );
     double u( 0.0 );
     int en( -1 );
     double correction( 0.0 );
     do
     {
       en += 2;
       correction = 8 / ( std::pow( en * M_PI, 3 ) )
                    * std::exp( -std::pow( en * M_PI, 2 ) * heat.coord() ) * std::sin( en * M_PI * y );
       u += correction;
     }
     while ( std::abs( correction ) > tol / 10. );
     // examine the difference between the numerical and series solutions
     max_diff = std::max( max_diff, std::abs( u - heat.solution()( mid, f ) ) );
   }
   bool failed = true;
   if ( abs( max_diff ) < tol )
   {
     failed = false;
   }
   if ( failed )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::PDE_IBVP< _Type >::coord(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::coord(), f, CppNoddy::Example::failed, fd, CppNoddy::PDE_IBVP< _Type >::solution(), CppNoddy::PDE_IBVP< _Type >::step2(), u, and CppNoddy::Utility::uniform_node_vector().
© 2012
R.E. Hewitt