CppNoddy: Tests/IBVP/IBVPDiffusionNonlinear.cpp File Reference
IBVPDiffusionNonlinear.cpp File Reference
Tests
#include <IBVP_bundle.h>
Classes
class CppNoddy::Example::Diffusion_equations
class CppNoddy::Example::Diffusion_left_BC
Define the boundary conditions.
class CppNoddy::Example::Diffusion_right_BC
Namespaces
CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
CppNoddy::Example
Enumerations
enum { U, Ud }
Functions
double CppNoddy::Example::A (10.0)
double CppNoddy::Example::sigma (100.0)
int main ()
Detailed Description
Solving the unstead diffusion problem:
with boundary conditions ; where . The initial condition is . The class constructs and solves the IBVP using 2nd order finite-differencing in both space and time over a non-uniform spatial mesh. The output is compared to the exact solution .
Definition in file IBVPDiffusionNonlinear.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
U
Ud
Definition at line 14 of file IBVPDiffusionNonlinear.cpp.
 { U, Ud };
Function Documentation
main()
int main ()
Definition at line 100 of file IBVPDiffusionNonlinear.cpp.
 {
   cout << "\n";
   cout << "=== IBVP: A nonlinear diffusion problem  ============\n";
   cout << "\n";
   // define the system
   Example::Diffusion_equations problem;
   // define the boundary conditions
   Example::Diffusion_left_BC BC_left;
   Example::Diffusion_right_BC BC_right;
   // domain definition
   double left = 0.0;
   double right = 1.0;
   // number of (spatial) nodal points
   unsigned ny = 400;
   // time step
   double dt = 0.005;
   // number of time steps
   unsigned max_steps = ( unsigned ) ( 2.0 / dt );
   // construct our IBVP with more nodes near the boundary
   PDE_IBVP<double> diffusion( &problem, Utility::power_node_vector( left, right, ny, 1.0 ), &BC_left, &BC_right );
   //
   for ( unsigned i = 0; i < ny; ++i )
   {
     double y( diffusion.solution().coord(i) );
     diffusion.solution()( i, U ) = (1+y) + Example::A*sin(M_PI*y);
     diffusion.solution()( i, Ud ) = 1 + Example::A*M_PI*cos(M_PI*y);
   }
   // set up output details
   std::string dirname("./DATA");
   mkdir( dirname.c_str(), S_IRWXU );
   TrackerFile metric( "./DATA/IBVP_diffusion_metric.dat" );
   metric.push_ptr( &diffusion.coord(), "time" );
   metric.push_ptr( &diffusion.solution()( 0, Ud ), "y=0 derivative" );
   metric.header();
   TrackerFile profs( "./DATA/IBVP_diffusion_profs.dat" );
   profs.push_ptr( &diffusion.coord(), "time" );
   profs.push_ptr( &diffusion.solution(), "solution" );
   profs.header();
   Timer timer;
   timer.start();
   //
   double max_error( 0.0 );
   // time step
   for ( unsigned i = 1; i < max_steps; ++i )
   {
     // take a time step
     try
     {
       diffusion.step2( dt );
     }
     catch (const std::runtime_error &error )
     {
       cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
       return 1;
     }
     if ( i % 20 == 0 )
     {
       cout << diffusion.coord() << "\n";
       profs.update();
       profs.newline();
     }
     timer.counter()++;
     metric.update();
     //
     double yy( 0.5 );
     double Uexact = 1 + yy + Example::A*exp(-diffusion.coord())*sin(M_PI*yy);
     double error = diffusion.solution().get_interpolated_vars( 0.5 )[ U ] - Uexact;
     max_error = std::max( std::abs( error ), max_error );
     //
     // std::cout << " ****** " << diffusion.t() << " " << max_error << "\n";
   }
   timer.stop();
   timer.print();
   //
   const double tol( 1.e-4 );
   // check the BL transpiration vs the known solution
   if ( max_error > tol )
   {
     cout << "\033[1;31;48m  * FAILED \033[0m\n";
     cout << " Max difference over time steps = " << max_error << "\n";
     return 1;
   }
   else
   {
     cout << "\033[1;32;48m  * PASSED \033[0m\n";
     return 0;
   }
 }
References CppNoddy::Example::A(), CppNoddy::PDE_IBVP< _Type >::coord(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::coord(), CppNoddy::Timer::counter(), CppNoddy::OneD_Node_Mesh< _Type, _Xtype >::get_interpolated_vars(), CppNoddy::TrackerFile::header(), CppNoddy::TrackerFile::newline(), CppNoddy::Utility::power_node_vector(), CppNoddy::Timer::print(), CppNoddy::TrackerFile::push_ptr(), CppNoddy::PDE_IBVP< _Type >::solution(), CppNoddy::Timer::start(), CppNoddy::PDE_IBVP< _Type >::step2(), CppNoddy::Timer::stop(), U, Ud, and CppNoddy::TrackerFile::update().
© 2012
R.E. Hewitt