CppNoddy: Tests/IVP/IVPHarmonic.cpp File Reference
IVPHarmonic.cpp File Reference
Tests
Integrate the harmonic equation.
#include <IVP_bundle.h>
Classes
class CppNoddy::Example::Harmonic_equation< _Type, _Xtype >
Define the harmonic equation by inheriting the Equation base class.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Functions
int main ()
Detailed Description
Integrate the harmonic equation.
with from to as an IVP, using an adaptive Runge-Kutta-Fehlberg routine.
Definition in file IVPHarmonic.cpp.
Function Documentation
main()
int main ()
Definition at line 42 of file IVPHarmonic.cpp.
{
  Timer timer;
  cout << "\n";
  cout << "=== IVP: solving harmonic equation ==================\n";
  cout << "   Solving between x = 0 to x = 10 \n";
  cout << "\n";
  cout << "   Running shoot45 method - auto step choice \n";
  // set up the problem
  Example::Harmonic_equation problem;
  problem.lambda = 10.0;
  // pass it to the ode
  ODE_IVP<double> ode( &problem, 0.0, 10.0, 1000 );
  // run the checks
  cout.precision( 12 );
  double tol( 1.e-7 );
  DenseVector<double> u_init( 2, 0.0 );
  DenseVector<double> u_final( 2, 0.0 );
  u_init[ 0 ] = 1.0;
  u_init[ 1 ] = 0.0;
  problem.coord(0) = 0.0;
  ode.shoot45( u_init, tol, 0.01 );
  try
  {
    u_final = ode.shoot45( u_init, tol, 0.01 );
  }
  catch (const std::runtime_error &error )
  {
    cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
    return 1;
  }
  timer.counter()++;
  bool failed( false );
  for ( int j = 1; j < 7; j++ )
  {
    // run through a few tolerance choices
    tol = 1. / ( pow( 10., j ) );
    // auto step choice; tolerance; initial step
    u_final = ode.shoot45( u_init, tol, 0.01 );
    // some output
    cout << "\n";
    cout << "    Error relative tol : " << tol << "\n";
    cout << "    Error |num - exact|: "
         << abs( u_final[ 0 ] - cos( sqrt( problem.lambda ) * 10. ) ) << "\n";
    if ( abs( u_final[ 0 ] - cos( sqrt( problem.lambda ) * 10. ) ) > 10. * tol )
    {
      failed = true;
    }
  }
  if ( failed )
  {
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
    return 1;
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
    return 0;
  }
}
References CppNoddy::Residual_with_coords< _Type, _Xtype >::coord(), CppNoddy::Timer::counter(), CppNoddy::Example::Harmonic_equation< _Type, _Xtype >::lambda, and CppNoddy::ODE_IVP< _Type >::shoot45().
© 2012
R.E. Hewitt