CppNoddy: Tests/IVP/IVPLorenz.cpp File Reference
IVPLorenz.cpp File Reference
Tests
Integrate the Lorenz equations.
#include <IVP_bundle.h>
Classes
class CppNoddy::Example::Lorenz_equations
Define the Lorenz equations by inheriting Equation base class.
Namespaces
namespace CppNoddy
A collection of OO numerical routines aimed at simple (typical) applied problems in continuum mechanics.
namespace CppNoddy::Example
Functions
int main ()
Detailed Description
Integrate the Lorenz equations.
forward in time using an adaptive Runge-Kutta-Fehlberg routine. The parameters are chosen to be , , . There is a fixed point solution , which is tested here.
Definition in file IVPLorenz.cpp.
Function Documentation
main()
int main ()
Definition at line 42 of file IVPLorenz.cpp.
{
  cout << "\n";
  cout << "=== IVP: integrating the Lorenz system ==============\n";
  cout << "\n";
  cout << "   Running shoot method - fixed step choice \n";
  DenseVector<double> u( 3, 0.0 ), u_init( 3, 0.0 );
  // initialise
  u_init[ 0 ] = 1.0;
  u_init[ 1 ] = 1.0;
  u_init[ 2 ] = 1.0;
  const int num_of_steps( 5000000 );
  // set up the problem.
  Example::Lorenz_equations problem;
  problem.a = 10.0;
  problem.b = 7.0;
  problem.c = 8.0 / 3.0;
  // Construct an ODE from the problem.
  ODE_IVP<double> ode( &problem, 0.0, 200.0, num_of_steps );
  ode.store_every() = 10;
  const double tol = 1.e-7;
#ifdef TIME
  Timer timer;
  timer.start();
  do
  {
#endif
    try
    {
      u = ode.shoot45( u_init, tol, 0.1 );
    }
    catch (const std::runtime_error &error )
    {
      cout << " \033[1;31;48m  * FAILED THROUGH EXCEPTION BEING RAISED \033[0m\n";
      return 1;
    }
#ifdef TIME
    timer.counter()++;
  }
  while ( timer.get_time() < 5000.0 );
  timer.stop();
  timer.print();
#endif
  cout.precision( 12 );
  if ( abs( u[ 0 ] - 4.0 ) > tol )
  {
    cout << "    Difference = " << abs( u[ 0 ] - 4.0 ) << "\n";
    cout << "\033[1;31;48m  * FAILED \033[0m\n";
  }
  else
  {
    cout << "\033[1;32;48m  * PASSED \033[0m\n";
  }
  ode.get_mesh().dump_gnu("./DATA/test.dat");
}
References CppNoddy::Example::Lorenz_equations::a, CppNoddy::Example::Lorenz_equations::b, CppNoddy::Example::Lorenz_equations::c, CppNoddy::Timer::counter(), CppNoddy::ODE_IVP< _Type >::get_mesh(), CppNoddy::Timer::get_time(), CppNoddy::Timer::print(), CppNoddy::ODE_IVP< _Type >::shoot45(), CppNoddy::Timer::start(), CppNoddy::Timer::stop(), CppNoddy::ODE_IVP< _Type >::store_every(), and u.
© 2012
R.E. Hewitt