CppNoddy: Utils_Fill Namespace Reference
Utils_Fill Namespace Reference
Functions
void time_seed ()
initialise RNG
template<typename _Type >
void fill_identity (CppNoddy::Sequential_Matrix_base< _Type > &A)
Fill diagonal with unit values.
template<typename _Type >
void fill_band (CppNoddy::Sequential_Matrix_base< _Type > &A, const int &offset, const _Type &value)
Fill a diagonal band of a matrix.
template<typename _Type >
void fill (CppNoddy::DenseVector< _Type > &X, const _Type &value)
Set all elements of a DENSE vector.
void fill_random (CppNoddy::SparseVector< double > &V, const unsigned &num_of_elts)
void fill_random (CppNoddy::SparseVector< std::complex< double > > &V, const unsigned &num_of_elts)
void fill_random (CppNoddy::DenseVector< double > &V)
void fill_random (CppNoddy::DenseVector< std::complex< double > > &V)
void fill_random (CppNoddy::DenseMatrix< double > &A)
void fill_random (CppNoddy::BandedMatrix< double > &A)
Function Documentation
fill()
template<typename _Type > void Utils_Fill::fill (CppNoddy::DenseVector< _Type > & X, const _Type & value)
Set all elements of a DENSE vector.
Parameters
X The DENSE vector to be filled
value The value to be placed in each element of the vector
Definition at line 46 of file Utils_Fill.h.
{
     for(std::size_t i = 0; i < X.size(); ++i) {
       X[ i ] = value;
     }
   }
References CppNoddy::DenseVector< _Type >::size().
Referenced by CppNoddy::DenseMatrix< D_complex >::DenseMatrix(), and CppNoddy::DenseVector< D_complex >::push_back().
fill_band()
template<typename _Type > void Utils_Fill::fill_band (CppNoddy::Sequential_Matrix_base< _Type > & A, const int & offset, const _Type & value)
Fill a diagonal band of a matrix.
Parameters
A The matrix to be used
offset The offset of the band from the main diagonal e.g. 0 = main diagional, -1 = first sub-diagonal
value The value to be written to the band elements
Definition at line 34 of file Utils_Fill.h.
{
     for (std::size_t row = 0; row < A.nrows(); ++row) {
       if ((row + offset < A.ncols()) && (row + offset >= 0)) {
         A(row, row + offset) = value;
       }
     }
   }
References CppNoddy::Example::A().
Referenced by main().
fill_identity()
template<typename _Type > void Utils_Fill::fill_identity (CppNoddy::Sequential_Matrix_base< _Type > & A)
Fill diagonal with unit values.
Parameters
A The dense matrix to be filled
Definition at line 22 of file Utils_Fill.h.
{
     for (std::size_t row = 0; row < A.nrows(); ++row) {
       A(row, row) = 1.0;
     }
   }
References CppNoddy::Example::A().
Referenced by main(), CppNoddy::Example::Berman_equation::mass(), CppNoddy::Example::Blasius_equation::mass(), CppNoddy::Example::Troesch_equation< _Type, _Xtype >::matrix0(), CppNoddy::Example::Berman_equation::matrix0(), CppNoddy::Example::Harmonic_equation< _Type, _Xtype >::matrix0(), CppNoddy::Example::harmonic_equation::matrix0(), CppNoddy::Example::Blasius_equation::matrix0(), CppNoddy::Example::Karman_equations::matrix0(), CppNoddy::Example::nonlinear::matrix0(), CppNoddy::Example::diffusion_double::matrix0(), CppNoddy::Example::OS_evp_equation::matrix0(), and CppNoddy::Example::OS_bvp_equation::matrix0().
fill_random() [1/6]
void Utils_Fill::fill_random (CppNoddy::BandedMatrix< double > & A)
Definition at line 103 of file Utils_Fill.h.
{
     for(std::size_t row = 0; row < A.nrows(); ++row) {
       for(std::size_t col = std::max((int)(row - A.noffdiag()), 0);
           (int) col <= std::min((int)(row + A.noffdiag()), (int) A.ncols()); ++col) {
         double x = (double) rand() / ((double) RAND_MAX + (double) 1) ;
         A(row, col) = x;
       }
     }
   }
References CppNoddy::Example::A().
fill_random() [2/6]
void Utils_Fill::fill_random (CppNoddy::DenseMatrix< double > & A)
Definition at line 95 of file Utils_Fill.h.
{
     CppNoddy::DenseVector<double> temp(A.ncols(), 0.0);
     for(std::size_t row = 0; row < A.nrows(); ++row) {
       fill_random(temp);
       A[ row ] = temp;
     }
   }
References CppNoddy::Example::A(), and fill_random().
fill_random() [3/6]
void Utils_Fill::fill_random (CppNoddy::DenseVector< double > & V)
Definition at line 77 of file Utils_Fill.h.
{
     for(unsigned i = 0; i < V.size(); ++i) {
       double x = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       V[ i ] = x;
     }
   }
References V.
fill_random() [4/6]
void Utils_Fill::fill_random (CppNoddy::DenseVector< std::complex< double > > & V)
Definition at line 85 of file Utils_Fill.h.
{
     for(unsigned i = 0; i < V.size(); ++i) {
       double x = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       double y = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       V[ i ] = std::complex<double>(x, y);
     }
   }
References V.
fill_random() [5/6]
void Utils_Fill::fill_random (CppNoddy::SparseVector< double > & V, const unsigned & num_of_elts)
Definition at line 53 of file Utils_Fill.h.
{
     do {
       double index = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       index *= V.size();
       double x = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       V[(unsigned) index ] = x;
     } while(V.nelts() < num_of_elts);
   }
References V.
Referenced by fill_random(), and main().
fill_random() [6/6]
void Utils_Fill::fill_random (CppNoddy::SparseVector< std::complex< double > > & V, const unsigned & num_of_elts)
Definition at line 64 of file Utils_Fill.h.
{
     do {
       double index = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       index *= V.size();
       double x = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       double y = (double) rand() /
         ((double) RAND_MAX + (double) 1) ;
       V[(unsigned) index ] = std::complex<double>(x, y);
     } while(V.nelts() < num_of_elts);
   }
References V.
time_seed()
void Utils_Fill::time_seed ()
initialise RNG
Definition at line 14 of file Utils_Fill.h.
                    {
     srand((unsigned) std::time(0));
   }
Referenced by main().
© 2012
R.E. Hewitt